모듈 import/export 방식 변경 (index.ts)
woowacourse-teams/2024-code-zap pull request #134
Opened 2024-07-24 09:09 UTC by vi-wolhwa

## ⚡️ 관련 이슈
close #133

## 📍주요 변경 사항
### 1. 각 디렉터리에서 `index.ts` 파일을 통해 모듈을 export 한다.
### 2. eslint 외부/내부 모듈 import 사이에 newLine 규칙 추가

2024-07-24 14:04 UTC, Hain-tain reviewed
수고하셨습니다👍 
다만, EOL 빠진 곳이 하나 있어서(components/index.ts) 코멘트 달아두었으니 확인 부탁드립니다.
그리고 우리 style 파일 명을 `컴포넌트명.style.ts` 로 가기로 해서 혹시 괜찮으면 이번에 파일 명도 다 바꿔서 머지하는 건 어떨까요? 어차피 다 변경사항 잡히니까 파일 명 따로 변경하는 것보다 이번에 한 번에 해도 좋을 것 같아요!

2024-07-24 14:04 UTC, Hain-tain commented on frontend/src/components/index.ts
> +export { default as Text }from './Text/Text';
EOL 추가해주세요~!

2024-07-25 00:58 UTC, Jaymyong66 requested changes

2024-07-25 00:58 UTC, Jaymyong66 commented on frontend/src/components/Header/Header.tsx
> +import { Button, Flex, Input, Text } from '..';
요 import문을 @/components로 하면 어떨까요?

2024-07-25 01:56 UTC, Hain-tain approved these changes

2024-07-25 01:56 UTC, Jaymyong66 approved these changes

2024-07-25 01:57 UTC, merged