Logback 구성 및 환경별 설정
woowacourse-teams/2024-code-zap pull request #235
Opened 2024-08-01 04:30 UTC by jminkkk

## ⚡️ 관련 이슈
close #229 

## 📍주요 변경 사항
1. 로그백 설정 및 환경별 구성파일 작성
2. 콘솔 및 파일용 appender 작성

## 🎸 기타
1. 디스커션의 [환경별 로깅 레벨 정하기](https://github.com/woowacourse-teams/2024-code-zap/discussions/200#discussioncomment-10206221)을 참고해주세요.

2024-08-02 04:36 UTC, zangsu submitted a review, later dismissed

2024-08-02 06:32 UTC, kyum-q requested changes
몰리 로그 너무 멋져요 ~!
몰리가 했기에 이렇게 깔끔하게 코드가 작성될 수 있는거에요 굿굿 ~!
몇가지 제안사항 남겨놨으니 확인 부탁드립니다 ~

2024-08-02 06:32 UTC, kyum-q commented on backend/src/main/resources/logback-spring.xml
> +    <!-- Development 환경 로그 설정 -->
⚡주석은 제거하면 좋을 것 같아요
설명을 위해서는 필요한거면 name을 명확하게 하는 건 어떤가요?

2024-08-02 06:32 UTC, kyum-q commented on backend/src/main/resources/logback-spring.xml
> +               datePattern="yyyy-MM-dd"/>
⚡
```suggestion
    <timestamp key="DATE_FORMAT" datePattern="yyyy-MM-dd"/>
```

불필요한 엔터 같아요 !

2024-08-02 06:32 UTC, kyum-q commented on backend/src/main/resources/logger/logback-spring-dev.xml
> +              value="./logs/dev"/>
⚡
```suggestion
    <property name="LOG_FILE_PATH" value="./logs/dev"/>
```

공백 제거해주면 더 좋을 것 같아요 😊

2024-08-02 06:32 UTC, kyum-q commented on backend/src/main/resources/logger/logback-spring-local.xml
> +    <!--        </logger>-->
⚡현재 필요없는 경우 제거해주세요 😊

2024-08-02 06:32 UTC, kyum-q commented on backend/src/main/resources/logback-spring.xml
> +    <springProfile name="default">
아 ! 왜 profile 설정을 default로 했나했더니, 저희 프로젝트에 yml 파일에 profile을 따로 안만들었네요..🤔
혹시 주석을 제거하면 명시성이 떨어질 수 있으니, profile 설정을 yml 파일에 추가하고 name을 적절하게 변경해주면 좋을 것 같아요 !

2024-08-02 06:33 UTC, zeus6768 requested changes
몰리 정말 고생 많았어요. 

의논할 게 있어 코멘트 남겼습니다 👍

2024-08-02 06:33 UTC, zeus6768 commented on backend/src/main/resources/logger/file/error-appender.xml
> +            <maxHistory>180</maxHistory>
회의했던대로 30일로 하는 건가용?

2024-08-02 06:33 UTC, zeus6768 commented on backend/src/main/resources/logger/logback-spring-dev.xml
> +              value="./logs/dev"/>
```suggestion
              value="spring-log"/>
```

현재 서버의 디렉토리가 아래와 같아서 변경하면 좋을 것 같은데, 어떻게 생각하나요?

```shell
dev
├── application-**.yml
├── application-***.yml
├── application-******.yml
├── code-zap-0.0.1-2024-07-**.jar
├── code-zap-0.0.1-2024-07-**.jar
├── code-zap-0.0.1-2024-07-**.jar
├── code-zap-0.0.1-2024-07-**.jar
├── nginx-log
│   ├── access.log
│   └── error.log
└── spring-log    # here
    ├── error-dev-1.log
    ├── error-dev-2.log
    ├── output-dev-1.log
    └── output-dev-2.log

3 directories, 13 files
```

2024-08-02 06:34 UTC, HoeSeong123 submitted a review, later dismissed
남기는 로그의종류가 너무 많아지면 정보를 찾기 힘들 수도 있겠다는 생각이 드네요.
그래도 이 부분은 일단 사용해보고 불편함을 느끼면 그 때 가서 다시 다같이 의논해보기로 하죠!!
고생하셨습니다.

2024-08-02 06:52 UTC, kyum-q reviewed
추가적으로 prod profile도 추가해줬으면 좋겠어요

2024-08-02 06:52 UTC, kyum-q commented on backend/src/main/resources/logback-spring.xml
> +    <springProfile name="dev">
저희 서버 에 prod profile도 있으니 추가해주세요❤️

2024-08-02 07:11 UTC, jminkkk commented on backend/src/main/resources/logger/logback-spring-dev.xml
> +              value="./logs/dev"/>
좋습니다 바로 반영할게요 👍

2024-08-02 08:37 UTC, jminkkk commented on backend/src/main/resources/logger/logback-spring-local.xml
> +    <!--        </logger>-->
해당 주석은 TODO용 주석의 성격이 아니라 남겨두었습니다...!
개발 시 해당 파일에 지정하지 않은 로그 정보가 필요할 경우가 종종 있을수도 있기 때문에요...!
(지금은 막아둬서 확인하지 못합니다.)

그런데 대면 회의를 통해 해당 부분도 전체 지우는 것으로 했기 때문에 전체 제거하겠습니다!

2024-08-02 08:54 UTC, jminkkk commented on backend/src/main/resources/logback-spring.xml
> +    <!-- Development 환경 로그 설정 -->
주석은 제거했습니다 !
다만 springProfile name은 profile 명과 일치해야 하는데 local 프로파일이 없어서 헷갈릴까 작성해두었었습니당..!

2024-08-02 08:56 UTC, jminkkk commented on backend/src/main/resources/logback-spring.xml
> +    <springProfile name="default">
넵넵 ㅎㅎ
local profile 추가하여 분리했습니다!

2024-08-02 14:06 UTC, kyum-q approved these changes

2024-08-03 09:33 UTC, zangsu approved these changes

2024-08-04 02:49 UTC, HoeSeong123 approved these changes

2024-08-05 06:06 UTC, merged