템플릿 CRUD에 태그 및 카테고리 추가, 카테고리 CRUD
woowacourse-teams/2024-code-zap pull request #252
Opened 2024-08-02 08:26 UTC by HoeSeong123

## ⚡️ 관련 이슈
close #191, #250, #251

## 📍주요 변경 사항
1. 템플릿 CRUD에 태그 및 카테고리 정보를 추가하여 처리한다.
2. 카테고리 CRUD 기능 구현
3. 위 기능들에 대한 Swagger 문서 최신화
4. cors 헤더 열람 권한 추가

## 🎸기타
1. null이 아닌 빈 값이 들어오는 경우에 대한 예외처리가 진행되어야 합니다.

2024-08-02 08:28 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
>      }
템플릿을 수정하는 메서드의 경우 리턴값이 따로 없습니다.
그렇다보니 수정을 하고 제대로 수정이 되었는지 결과를 확인하려면 각각의 repository에서 값들을 하나하나 가져와서 확인해야 하는 번거로움이 발생하였습니다.
해결방법 추천 받습니다...

2024-08-03 14:24 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
>      }
양방향 매핑을 해야 하나 고민 또 고민 중... 😭

2024-08-03 14:27 UTC, zangsu commented on backend/src/main/java/codezap/category/dto/request/UpdateCategoryRequest.java
> +public record UpdateCategoryRequest(
`CreateCategoryRequest` 와 완전히 동일한 형식인데요. 
혹여나 나중에 생성 / 수정 기능 중 하나만 request 형식이 변경될 경우를 대비해 요청 DTO 도 분리해 두었습니다. 
그런데, 이게 맞는건지 잘 모르겠네요 🤔

2024-08-03 16:24 UTC, zangsu commented
⚡ `ValidatedSnippetsOrdinalRequest` 에도 group을 추가해 주어야 해요. 
`@Validated` 로 그룹을 명시해서 검증하는 순간 그룹이 없는 검증들이 확인되지 않더라고요!

2024-08-04 15:33 UTC, kyum-q requested changes
초롱 짱수 수고하셨습니다 👍😊 결과물이 굳굳이네요 ~!
확인하면서 몇가지 코멘트 남겨뒀습니다. 그리고 제가 생각하기에는 수정됐으면 바라는 부분은 ⚡표시 해놨습니다. 하지만 이 부분도 제 주장일 뿐이니, 제 주장이 이해가 안되거나 안 고치는 게 나을 것 같다면 함께 이야기해보고 싶어요 🍭

2024-08-04 15:33 UTC, kyum-q commented on backend/src/main/java/codezap/template/domain/TemplateTag.java
> +    }
⚡
해당 클래스를 다른 별도의 파일로 분리하는 것이 더 좋을 것 같습니다.
저는 잘 몰라서 찾아보니, ID가 복합키이기 때문에 이와 같이 복합 키를 표현하는 클래스를 내부 클래스로 선언하신 것 같아요 👍
하지만 저는 inner 클래스로 숨기는 것보다 다른 별도의 파일로 분리하는 것이 좋다고 생각합니다. 그 이유는 다음과 같습니다.

1. 해당 복합키가 TemplateTagId에서만 사용 가능. TemplateTag가 다른 테이블과 연관관계를 맺게 되어 다른 테이블이 TemplateTagId를 필요로 해도 사용할 수 없게 된다.
2. 클래스 내부에 다른 클래스가 정의되므로 코드가 길어지고 복잡하다.
3. 굳이 숨길 이유가 없다.

2024-08-04 15:33 UTC, kyum-q commented on backend/src/main/java/codezap/template/dto/response/FindTagByIdResponse.java
> +public record FindTagByIdResponse(
위에 리뷰와 동일하게 ById는 없어도 될 것 같습니다 😊

2024-08-04 15:33 UTC, kyum-q commented on backend/src/main/java/codezap/template/repository/TemplateTagRepository.java
> +    void deleteAllByTemplateId(Long id);
(이건 몰라서 물어보는 질문 ㅎㅎ)
`deleteAllByTemplateId`만 있어도 될 것 같은데 왜 `deleteAllByTemplate`까지 구현하신건가요?

2024-08-04 15:33 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
>      }
저는 현재 방법이 최선인 것 같아요 ! 당장 양방향 매핑이 필요해보이지 않달까..?
테스트 확인에서는 repository를 하나하나 확인해야하는 번거로움이 존재하지만, 실제 서버에서는 문제가 생길 시 에러가 발생하니까요! 
그래서 개인적으로는 현재 양방향 매핑을 하지 않고 status로 성공 실패 여부를 알게끔 해도 될 것 같습니다. 😊

2024-08-04 15:33 UTC, kyum-q commented on backend/src/main/java/codezap/category/dto/request/UpdateCategoryRequest.java
> +public record UpdateCategoryRequest(
저도 생성하고 수정 request는 구분해 놓는 게 좋을 것 같아요 !

2024-08-04 16:13 UTC, zangsu requested changes
고생 많으셨어요, 초롱!!
몇가지 궁금한 점들 남겨 두었으니 확인 부탁드려요!

2024-08-04 16:13 UTC, zangsu commented on backend/src/main/java/codezap/template/service/TemplateService.java
> +        templateTagRepository.saveAll(createTemplateRequest.tags().stream()
⚡ 오, 템플릿 생성에 사용되는 태그를 존재하는지 찾아보는 대신 매번 새로이 저장하는 것 같네요!
각각의 템플릿이 동일한 이름의 태그를 사용해도 서로 다른 id 를 가진 태그를 가지게 될 것 같은데요. 
이렇게 선택하신 이유가 궁금해요!

2024-08-05 06:42 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +    private void validateDuplicatedCategory(String categoryName) {
별도의 이유는 없었습니다!! 확실히 ㅔublic 메서드 아래에 있는 게 가독성이 더 좋은 것 같네요. 
반영했습니다!

2024-08-05 06:44 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/dto/response/FindCategoryByIdResponse.java
> +public record FindCategoryByIdResponse(
처음에는 `FindallSnippetByTemplateResponse`처럼 뭔가를 통해 찾아온다는 느낌으로 네이밍을 작성해서 이에 대한 통일성을 지키기 위해 `ById`를 사용했었습니다.
그런데 듣고 보니 불필요한 것 같네요!!
피드백 반영했습니다.

2024-08-05 06:55 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +        if (id == 1) {
좋은데요?!
기본 카테고리라는 뜻으로 `DEFAULT_CATEGORY`로 상수화 하였습니다.

2024-08-05 07:00 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/repository/TemplateTagRepository.java
> +    void deleteAllByTemplateId(Long id);
날카로운 리뷰 감사합니다.
`deleteAllByTemplateId`만 남겨두도록 수정했습니다!

2024-08-05 07:06 UTC, HoeSeong123 commented on backend/src/main/java/codezap/global/validation/ValidationGroups.java
> +    public interface SizeCheckGroup {}
다른 검증 어노테이션을 같은 그룹으로 묶는 건 생각해보지 못했네요!!
반영했습니다.

2024-08-05 07:08 UTC, jminkkk approved these changes
안녕하세요 초롱~
구현 잘 해주셨네요 짱!

당장은 크게 수정해야할 부분은 없는 것 같아요!~ 
코멘트 확인해주시고 이슈 생성 해주시면 좋을 것 같슴다!

2024-08-05 07:08 UTC, jminkkk commented on backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
> +        @Size(max = 255, message = "템플릿 이름은 최대 255자까지 입력 가능합니다.", groups = SizeCheckGroup.class)
흠 뭔가 어떤 어노테이션에는 group이 있고 어떤 것은 없고 헷갈리네요 @.@
제가 이해하기로는 특정 어노테이션을 동시에 사용할 경우에 group 지정이 필요한 것 같아요.

이게 되게 서로에게 의존적이고(한개가 사라지면 다른 하나의 group이 의미가 없어짐)
관리하기 까다로운 것 같아서 리팩토링해볼 방법을 이슈로 만들고 같이 고민해보면 좋을 것 같습니당

2024-08-05 07:08 UTC, jminkkk commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +class CategoryServiceTest {
각 레이어의 테스트마다 공통적으로 필요한 코드가 보이는데, 이 부분도 이슈로 만들고 리팩토링해보면 좋을 것 같아요!

2024-08-05 07:18 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/domain/TemplateTag.java
> +public class TemplateTag extends BaseTimeEntity {
`CreatedAt`과 `ModifiedAt`은 쓰일지는 잘 모르겠지만 데이터 무결성 등을 검증할 수 있는 등 다양한 도움을 주는 필드이고, 추가해도 큰 비용이 들지는 않을 것 같아서 넣어둬도 좋을 것 같은데 짱수 생각은 어떤가요?

2024-08-05 07:24 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/domain/TemplateTag.java
> +    @EqualsAndHashCode
식별자 필드가 하나일 때는 자바의 기본 타입을 사용하므로 문제가 없지만, 식별자 필드가 2개 이상이면 별도의 식별자 클래스를 만들고, 이를 구분할 수 없으므로 `equals`와 `hashCode`를 구현해야 합니다.

2024-08-05 07:26 UTC, zangsu commented on backend/src/main/java/codezap/template/domain/TemplateTag.java
> +public class TemplateTag extends BaseTimeEntity {
다시 생각을 해 보니, 우리가 `Template`, `Tag` 가 서로에 대한 의존성이 없네요!
이 경우 `TemplateTag`에서 해당 정보를을 저장하지 않는다면 `Template`의 `Tag`를 변경한다고 하더라도 변경 내역을 트래킹 하기 어려울 수 있겠군요!
이대로 두어도 좋을 것 같습니다!

2024-08-05 07:37 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/service/TemplateService.java
> +        templateTagRepository.saveAll(createTemplateRequest.tags().stream()
수정에서는 적용을 했었는데 생성에는 적용을 안 했네요;;
피드백 반영했습니다!

2024-08-05 08:02 UTC, zangsu commented on backend/src/main/java/codezap/template/domain/TemplateTag.java
> +    @EqualsAndHashCode
오오...감사합니다! 새롭게 하나를 알아가는군요!

2024-08-05 08:05 UTC, zangsu submitted a review, later dismissed
변경사항 확인했습니다!
너무 고생 많았어요, 초롱!!!

2024-08-05 08:07 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
> +        @Size(max = 255, message = "템플릿 이름은 최대 255자까지 입력 가능합니다.", groups = SizeCheckGroup.class)
https://github.com/woowacourse-teams/2024-code-zap/issues/271#issue-2447894402
생성하였습니다.

2024-08-05 08:09 UTC, HoeSeong123 commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +class CategoryServiceTest {
https://github.com/woowacourse-teams/2024-code-zap/issues/273#issue-2447897907

2024-08-05 08:19 UTC, kyum-q approved these changes
수고하셨습니다 초롱 👍🍭🍬🐤

2024-08-05 10:04 UTC, kyum-q submitted a review, later dismissed

2024-08-05 11:57 UTC, zeus6768 requested changes
초롱 작업하느라 고생많았어요~ 코멘트 남겼으니 편하게 의견 나눠봐요!

2024-08-05 11:57 UTC, zeus6768 commented on backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
> +    }
```suggestion
    private static List<FindTagResponse> mapToFindTagByTemplateResponse(List<Tag> tags) {
        return tags.stream()
                .map(FindTagResponse::from)
                .toList();
    }
```

2024-08-05 11:57 UTC, zeus6768 commented on backend/src/main/java/codezap/template/repository/TagRepository.java
> +    Tag findByName(String name);
⚡
```suggestion
    Optional<Tag> findByName(String name);
```

2024-08-05 11:57 UTC, zeus6768 commented on backend/src/main/java/codezap/template/repository/TemplateRepository.java
line 20 또한 변경해주세요. 

As-is
```java
Snippet findByTemplateAndOrdinal(Template template, int ordinal);
```

To-be
```java
Optional<Snippet> findByTemplateAndOrdinal(Template template, int ordinal);
```

2024-08-05 11:57 UTC, zeus6768 commented on backend/src/main/java/codezap/template/service/TemplateService.java
>      public Long create(CreateTemplateRequest createTemplateRequest) {
```suggestion
    public Long createTemplate(CreateTemplateRequest createTemplateRequest) {
```

2024-08-05 11:57 UTC, zeus6768 commented on backend/src/main/java/codezap/template/service/TemplateService.java
> +    }
⚡

`save` 연산을 stream에서 실행하는게 위험해 보입니다. 

대신 `saveAll()` 메서드를 사용해볼까요?

---

[참고자료 | Java SE 8](https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html#StatelessBehaviors)

> Stream pipeline results may be nondeterministic or incorrect if the behavioral parameters to the stream operations are stateful.

> 스트림 연산에 대한 동작 매개변수가 상태 저장 방식인 경우 스트림 파이프라인 결과는 비결정적이거나 부정확할 수 있습니다.

2024-08-05 11:57 UTC, zeus6768 commented on backend/src/main/java/codezap/template/service/TemplateService.java
>                  .forEach(createSnippetRequest -> createSnippet(createSnippetRequest, template));
⚡

forEach 연산을 모두 saveAll로 변경하면 좋겠어요~!

2024-08-05 11:57 UTC, zeus6768 commented on backend/src/main/java/codezap/template/service/TemplateService.java
> +                .forEach(tagRepository::save);
⚡

2024-08-05 11:57 UTC, zeus6768 commented on backend/src/main/java/codezap/template/service/TemplateService.java
> +                .forEach(tag -> templateTagRepository.save(new TemplateTag(template, tag)));
⚡

2024-08-05 11:58 UTC, jminkkk submitted a review, later dismissed
초롱 리뷰 사항 잘 반영된 것 같네요~ 🔥

마지막 코멘트일 것 같아서 여기에 남겨요
초롱도 느끼고 있겠지만 다음 pr에는 pr 단위를 좀 더 쪼개보면 좋을 것 같슴다...ㅎㅎ
수고했어요!!!!!!!!!!!!!!!!

2024-08-05 12:30 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
> +    }
진짜 이상하게 개행이 돼있었네요;;

2024-08-05 12:34 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/repository/TagRepository.java
> +    Tag findByName(String name);
`findBy`는 전부 Optional이어야 하는 건가요??
만약 그렇다면 `fetchById` 처럼 `fetchByName`으로 default 메서드로 사용하는건 어떤가요?

2024-08-05 12:45 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/service/TemplateService.java
> +    }
stream에서 사용된 `save` 연산들은 전부 `saveAll`로 변경하였습니다.
개행 등 괜찮은지 확인 부탁드립니다~~

2024-08-06 04:39 UTC, zangsu approved these changes

2024-08-06 04:40 UTC, kyum-q approved these changes
수고하셨습니다 초롱 ~

2024-08-06 04:41 UTC, jminkkk approved these changes

2024-08-06 04:53 UTC, zeus6768 approved these changes
고생많았어요!

2024-08-06 05:06 UTC, zeus6768 commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +    public static final int DEFAULT_CATEGORY = 1;
변수명 변경은 안 한 이유가 궁금해요~!

2024-08-06 05:11 UTC, merged