[FEAT, DOCS] 이메일 회원가입, 로그인, 로그아웃 구현
woowacourse-teams/2024-code-zap pull request #267
Opened 2024-08-05 06:33 UTC by zeus6768

## ⚡️ 관련 이슈
close #197 #198 #199 

## 📍주요 변경 사항
- 이메일 회원가입
- 이메일 로그인
  - 쿠키를 사용합니다. 
  - 쿠키에 "{email}:{password}"를 Base64 인코딩한 값을 저장합니다. 
- 로그아웃
  - 쿠키를 만료시킵니다. 

## 🎸 추가 작업
- #264
- Domain validation

2024-08-05 09:08 UTC, HoeSeong123 requested changes
고생하셨습니다 제우스!!
몇 가지 간단한 리뷰와 질문사항 남겨두었습니다.

추가로 테스트 코드가 정말 깔끔한 것 같네요!!
추후에 다른 테스트 코드에도 FakeRepository를 적용해보도록 하겠습니다.

2024-08-05 09:08 UTC, HoeSeong123 commented on backend/src/main/java/codezap/member/repository/MemberRepository.java
>  }
궁금한 게 있어서 질문 남깁니다!
`MemberJpaRepository`에는 `save` 메서드가 별도로 구현되어 있지 않은 것 같은데, 프로덕션 코드에서 `save`를 사용할 때 자동으로 `JpaRepository`의 `save`를 사용하는 건가요?

2024-08-05 09:54 UTC, kyum-q requested changes
제우스 수고하셨습니다 😊🍬🍭 코드가 전반적으로 깔끔하네요 !! 
몇가지 부분만 코멘트 남겼습니다. 확인해주세요 😊

2024-08-05 09:54 UTC, kyum-q commented on backend/src/main/java/codezap/member/domain/Member.java
>  @NoArgsConstructor
⚡
```suggestion
@NoArgsConstructor(access = AccessLevel.PROTECTED)
```

@NoArgsConstructor의 기본 접근제어자를 찾아보니 public으로 설정 되어있네요. protected로 접근제어자를 좁히면 더 좋을 것 같습니다.

2024-08-05 09:54 UTC, kyum-q commented on backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
> +public interface MemberJpaRepository extends MemberRepository, JpaRepository<Member, Long> {
MemberJpaRepository 와 MemberRepository  두 개가 있는 이유가 있나요??

2024-08-05 09:54 UTC, kyum-q commented on backend/src/main/java/codezap/member/service/AuthService.java
> +        String password = credentials[1];
⚡ 배열이 2개의 String을 가지고 있음이 명확하지 않을 것 같아요.
email과 password를 배열에서 인덱스 정보로 꺼내기 전에 배열의 크기가 2가 맞는지 체크하는 로직이 있으면 좋을 것 같아요.

2024-08-05 09:54 UTC, kyum-q commented on backend/src/main/java/codezap/member/service/AuthService.java
> +    }
이건 선호도의 문제인데 
`getAuthCookieValue` -> `throwUnauthorized` -> `decodeCredentials` 순서로 메서드가 있으면 좋을 것 같아요.
`getAuthCookieValue`에서 `throwUnauthorized`을 사용하기 때문에 사용하는 메서드와 최대한 가깝게 메서드를 위치시키면 좋을 것 같아요.😊

2024-08-05 09:54 UTC, kyum-q commented on backend/src/main/java/codezap/member/repository/MemberRepository.java
> +    Optional<Member> findByEmail(String email);
⚡ 다른 레파지토리들 처럼 fetchByEmail을 default 메서드로 만들어서 Optional 을 제거하면 더 좋을 것 같아요

2024-08-05 13:24 UTC, zangsu requested changes
간단한 수정사항 하나와 여러개의 의견들 담겨두었어요!

2024-08-05 13:24 UTC, zangsu commented on backend/src/main/java/codezap/member/dto/LoginRequest.java
> +        String email,
```suggestion
        @Schema(
                description = "이메일",
                example = "code@zap.com",
                pattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\n"
        )
        @NotEmpty(message = "이메일이 입력되지 않았습니다.")
        @Size(max = 255, message = "이메일은 255자 이하로 입력해주세요.")
        @Pattern(regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\n")
        //@Email(regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\n")
        String email,
```

`@Schema` 에서 정규 표현식을 명시해 두었으니만큼, `@Pattern` 또는 `@Email` 을 검증에도 사용해 보는 것도 좋을 것 같아요.

2024-08-05 13:24 UTC, zangsu commented on backend/src/main/java/codezap/member/service/AuthService.java
> +        String password = credentials[1];
어쩌면 `decodeCredentials()` 메서드가 일급 컬렉션, 또는 특정 책임을 가지는 객체를 반환해 주는 것도 방법이 될 수 있겠네요!

2024-08-05 13:24 UTC, zangsu commented on backend/src/main/java/codezap/member/repository/MemberRepository.java
> +public interface MemberRepository {
아 이 인터페이스 너무 좋은데요 ⚡

2024-08-05 13:24 UTC, zangsu commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +public class MemberServiceTest {
Fake 객체를 쓰니 `@SpringBootTest` 를 사용하지 않아도 되네요!
너무너무 마음에 듭니다 👍

2024-08-05 13:36 UTC, HoeSeong123 commented
혹시 지금 스웨거에서 회원가입이 되나요?? 제 로컬에서만 안되는지 궁금하네요...

2024-08-05 18:18 UTC, HoeSeong123 requested changes
멤버 정보가 가져와지지가 않아서 계속 확인해봤는데 어노테이션에 옵션들이 설정이 안 되어 있었네요!!

그리고 아래는 뭐 때문인지는 모르겠는데 뭔가 이상한 것 같아서 공유합니다. 확인 부탁드려요!!
요청시에 Header의 Cookie 부분에 다음과 같이 정보가 들어가있습니다.
>token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkByb29tZXNjYXBlLmNvbSIsImlhdCI6MTcxODE3MjUwNiwiZXhwIjoxNzE4MTc2MTA2fQ.Tnj2aX5hU_FlZRhtzcxeDKBanhwQeHzocuaomdpLi1M; Authorization=dGVzdEBlbWFpbC5jb206cGFzc3dvcmQ=

여기서 token을 해석해보면 
>{"alg":"HS256"}{"sub":"admin@roomescape.com","iat":1718172506,"exp":1718176106}f?VQ·.j 

이렇게 나오던데 뭐 때문에 이런건가요??
제 브라우저의 캐시 문제인가요..?

2024-08-05 18:18 UTC, HoeSeong123 commented on backend/src/main/java/codezap/member/configuration/BasicAuthentication.java
> +}
⚡
```suggestion
package codezap.member.configuration;

@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
public @interface BasicAuthentication {
}
```
어노테이션에 이 친구들 붙여줘야 동작하는 것 같은데 확인 부탁드립니다!!

2024-08-06 04:18 UTC, kyum-q commented on backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
> +public interface MemberJpaRepository extends MemberRepository, JpaRepository<Member, Long> {
설명 이제 읽었어용 ㅎㅎ 👍

2024-08-06 04:19 UTC, kyum-q commented on backend/src/main/java/codezap/member/repository/MemberRepository.java
> +    Optional<Member> findByEmail(String email);
이해 완 ~

2024-08-06 05:16 UTC, zeus6768 commented on backend/src/main/java/codezap/member/configuration/AuthWebConfiguration.java
> +}
레벨2에서 리뷰어가 참고하라고 주신 글인데요.

[참고자료](https://www.facebook.com/story.php?story_fbid=3677744105594970&id=100000782515542&anchor_composer=false&paipv=0&eav=AfZcC4ljTPJOJLpgoNERBmnA2rjvL_dUhmlxpEJ_6ot-F1hL15E3XUn0ZFlkl54FftQ&_rdr)

현재 단계에서는 큰 차이가 발생하지 않지만, 프로젝트가 성장할수록 의존성 관리가 어려워지죠. 

그래서 빈 등록이 주는 강력함도 있지만, 안 할 수 있다면 안 하는 편이 더 좋다고 생각합니다.

2024-08-06 05:24 UTC, zeus6768 commented on backend/src/main/java/codezap/member/repository/MemberRepository.java
>  }
MemberJpaRepository > JpaRepository > ListCrudRepository > CrudRepository

```java
@NoRepositoryBean
public interface CrudRepository<T, ID> extends Repository<T, ID> {

	<S extends T> S save(S entity);

        (생략)
```

여기에 구현되어있답니다~

2024-08-06 05:55 UTC, jminkkk requested changes
안녕하세요 제우스!
수고하셨어요 리뷰 남겼으니 같이 얘기해보아요 🔥

2024-08-06 05:55 UTC, jminkkk commented on backend/src/main/java/codezap/member/service/AuthService.java
> +
지금은 쿠키이지만 Authorization Header로 인증 값을 주고 받는다면 서비스 전체가 변경될 것 같아요.
추상화를 시도해보면 어떨까요?

2024-08-06 05:55 UTC, jminkkk commented on backend/src/main/java/codezap/member/configuration/AuthArgumentResolver.java
> +package codezap.member.configuration;
AuthArgumentResolver 의 위치가 /member/configuration 인 것이 조금 모호한 것 같아요
오히려 /member/auth 패키지로 두는 것이 더 찾기 수월할 것 같은데 어떤가요?

2024-08-06 05:55 UTC, jminkkk commented on backend/src/main/java/codezap/member/configuration/AuthWebConfiguration.java
> +package codezap.member.configuration;
⚡️ auth 패키지를 따로 분리하지 않고 member 패키지 아래에 인증 관련 것들을 둔 이유가 있을까용?
member 패키지 아래 파일들이 대부분 인증에 대한 것 같아서용

domain 패키지를 제외한 다른 파일들은 auth로 따로 있는 것이 적절할 것 같다는 생각이 들기도 하네용...

2024-08-06 05:55 UTC, jminkkk commented on backend/src/main/java/codezap/member/controller/MemberController.java
> +public class MemberController implements SpringDocMemberController {
⚡️ 이것도 비슷하게 `AuthController` 가 더 적절할 것 같습니당...
MemberController면 Member에 대한 CRUD 요청이 오고 갈 것 같은데 Auth 관련 로직만 있어서유

어드민 페이지가 생겨서 회원 정보를 조회해야 한다면? 그 친구들이 MemberController에 있는 것이 더 명확하지 않을까요?

2024-08-06 05:55 UTC, jminkkk commented on backend/src/main/java/codezap/member/dto/SignupRequest.java
> +package codezap.member.dto;
⚡️ 현재 dto가 request 만 있어서 /dto에 바로 위치시킨 것 같아요~
그런데 내 정보 조회 등 response body가 필요한 api 들이 다음 스프린트에서 추가될텐데 그때 패키지를 구분하게 되면 변경사항이 매우 많이 잡힐 것 같네용

미리 /dto/request 아래에 두는 것이 어떤가요?

2024-08-06 05:55 UTC, jminkkk commented on backend/src/main/java/codezap/member/dto/MemberDto.java
> +public record MemberDto(
Dto의 역할이 맞는데 뭔가 이름이 매우 불편쓰... 어카죠... 고민해봅시다...

그리고 Member 엔티티를 바로 조회해와도 좋을 것 같아요~ 같이 논의해보아요!!!!!

2024-08-06 05:55 UTC, jminkkk commented on backend/src/main/java/codezap/member/service/MemberService.java
> +public class MemberService {
이 부분도 앞서 리뷰 남긴 것처럼 현재는 AuthService 가 적절한 것 같아요 :)

2024-08-06 06:04 UTC, zeus6768 commented on backend/src/main/java/codezap/member/service/AuthService.java
> +        String password = credentials[1];
> ⚡ 배열이 2개의 String을 가지고 있음이 명확하지 않을 것 같아요. email과 password를 배열에서 인덱스 정보로 꺼내기 전에 배열의 크기가 2가 맞는지 체크하는 로직이 있으면 좋을 것 같아요.

좋은 피드백 고마워요!

배열의 크기를 확인하는 대신, 인코딩 형식이 맞는지 확인하는 로직을 `decodeCredentials` 메서드에 추가했습니다. 

이렇게 하면 배열의 크기가 2가 됨을 보장하면서도, Basic Auth credentials의 표현이 올바른지 동시에 검증할 수 있어요.

2024-08-06 06:33 UTC, zeus6768 commented on backend/src/main/java/codezap/member/service/AuthService.java
> +    }
> 위에서 아래로 프로그램을 읽으면 함수 추상화 수준이 한 번에 한 단계씩 낮아진다.  - 클린 코드

추상화 수준이 높은 메서드를 위로 위치시켰습니다.

2024-08-06 07:01 UTC, zeus6768 commented on backend/src/main/java/codezap/member/service/AuthService.java
> +
좋은 생각이에요 :)

다만 저는 구현체가 하나 뿐인 인터페이스를 만드는 게 좋은 방법이라고 생각하지 않습니다. 그래서 인증 방식이 추가된다면 그때 추상화를 하면 좋겠어요!

2024-08-06 08:56 UTC, merged