하나의 status에 대해 예외 상황이 여러개일 경우, 문서가 덮어씌워지는 에러 해결
woowacourse-teams/2024-code-zap pull request #418
Opened 2024-08-12 15:41 UTC by jminkkk

## ⚡️ 관련 이슈
close #270 

## 📍주요 변경 사항
1. 이전 pr을 통해 하나의 api에 대해 여러 실패 예시를 정의할 수 있었으나,  하나의 status에 대해 예외 상황이 여러개일 경우 가장 먼저 정의된 하나만 적용되는 에러를 해결하였습니다.
2. ApiResponses의 addApiResponse 는 map을 사용하기 때문에 기존 "클라이언트 오류"와 같은 description을 key로 저장하게 되면 다른 에러가 덮어씌워지는 문제가 발생했습니다. 
 따라서 description에 상태 코드를 추가하여 구분하였습니다.

2024-08-13 02:20 UTC, zangsu approved these changes
김홀리몰리 체고 ⚡

2024-08-13 04:47 UTC, kyum-q approved these changes
귯 몰리 👍

2024-08-13 06:02 UTC, zeus6768 requested changes
개선할 부분 리팩토링 해봤으니 확인 바라요~

2024-08-13 06:02 UTC, zeus6768 commented on backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
> +
⚡

```java
@Override
public Operation customize(Operation operation, HandlerMethod handlerMethod) {
    List<ApiErrorResponse> apiErrorResponses = getApiErrorResponses(handlerMethod);
    Map<String, ApiResponse> customResponses = makeApiResponses(apiErrorResponses);
    ApiResponses apiResponses = operation.getResponses();
    apiResponses.putAll(customResponses);
    return operation;
}

private List<ApiErrorResponse> getApiErrorResponses(HandlerMethod handlerMethod) {
    if (handlerMethod.hasMethodAnnotation(ApiErrorResponses.class)) {
        ApiErrorResponse[] responses = handlerMethod.getMethodAnnotation(ApiErrorResponses.class).value();
        return Arrays.stream(responses).toList();
    }
    if (handlerMethod.hasMethodAnnotation(ApiErrorResponse.class)) {
        ApiErrorResponse response = handlerMethod.getMethodAnnotation(ApiErrorResponse.class);
        return List.of(response);
    }
    return List.of();
}

private Map<String, ApiResponse> makeApiResponses(List<ApiErrorResponse> apiErrorResponses) {
    return apiErrorResponses.stream()
            .map(this::makeFailResponse)
            .collect(Collectors.toMap(ApiResponse::getDescription, response -> response));
}
```

열심히 개선해봤어요!!!

1. 힙 오염이 발생할 여지가 있기 때문에 타입 매개변수에는 배열을 대입하는 것은 권장되지 않아요. 

2. stream 파이프라인의 forEach 연산에서 저장을 수행하는 건 예측하지 못한 결과를 발생할 가능성이 있어요. 

---
[힙 오염](https://en.wikipedia.org/wiki/Heap_pollution)

[스트림 | Java SE 8](https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html#StatelessBehaviors)

> Stream pipeline results may be nondeterministic or incorrect if the behavioral parameters to the stream operations are stateful.

> 스트림 연산에 대한 동작 매개변수가 상태 저장 방식인 경우 스트림 파이프라인 결과는 비결정적이거나 부정확할 수 있습니다.

2024-08-13 12:10 UTC, jminkkk commented on backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
> +
기가 막힙니다 🔥

2024-08-14 02:34 UTC, HoeSeong123 submitted a review, later dismissed

2024-08-14 02:36 UTC, zangsu submitted a review, later dismissed
👍

2024-08-14 02:36 UTC, kyum-q submitted a review, later dismissed
GOOD

2024-08-14 02:43 UTC, zeus6768 requested changes

2024-08-14 02:43 UTC, zeus6768 commented on backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
>      }
⚡
```java
        MediaType mediaType = new MediaType();
        ErrorCase[] errorCases = apiErrorResponse.errorCases();
        for (ErrorCase errorCase : errorCases) {
            Example example = makeExample(apiErrorResponse, errorCase);
            mediaType.addExamples(errorCase.description(), example);
        }
        return mediaType;
```

이것까지만 반영해주세요!

2024-08-14 02:46 UTC, jminkkk commented on backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
>      }
제가 놓쳤군요! 감사함당

2024-08-14 02:46 UTC, HoeSeong123 approved these changes

2024-08-14 02:46 UTC, zangsu approved these changes

2024-08-14 02:46 UTC, zeus6768 approved these changes

2024-08-14 02:46 UTC, kyum-q approved these changes

2024-08-14 02:49 UTC, merged