회원 정보 수정, 조회 API 문서 작성
woowacourse-teams/2024-code-zap pull request #419
Opened 2024-08-12 16:03 UTC by jminkkk

## ⚡️ 관련 이슈
close #397

## 📍주요 변경 사항
1. 회원 정보 수정, 조회 API 문서 작성

## 🎸 기타
1. 응답, 요청, 가능한 에러 응답 중 놓친 부분이 있다면 코멘트 부탁드립니다.

2024-08-13 05:10 UTC, kyum-q requested changes
수고하셨습니다 몰리 ~
성공 케이스에 대한 구체화 및 response 도 문서화 해주면 좋을 것 같아서 코멘트 남겼습니다 ~😁

2024-08-13 05:10 UTC, kyum-q commented on backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
> +    @ApiResponse(responseCode = "200", description = "회원 정보 조회 성공")
```suggestion
    @ApiResponse(responseCode = "200", description = "회원 정보 조회 성공",
            content = {@Content(schema = @Schema(implementation = FindMemberResponse.class))})
```

⚡ 성공 케이스일 때 어떤 response가 반환되는지 명시해주세요

2024-08-13 05:10 UTC, kyum-q commented on backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
> +    @ApiResponse(responseCode = "200", description = "회원 정보 수정 성공")
⚡ 성공 케이스일 때 어떤 response가 반환되는지 명시해주세요
```suggestion
    @ApiResponse(responseCode = "200", description = "회원 정보 수정 성공",
          content = {@Content(schema = @Schema(implementation = UpdateMemberProfileResponse.class))})
```

2024-08-13 05:10 UTC, kyum-q commented on backend/src/main/java/codezap/member/dto/response/FindMemberResponse.java
> +        String username
```suggestion
        @Schema(description = "이메일", example = "code@zap.com")
        String email,
        @Schema(description = "사용자명", example = "zappy")
        String username
```
⚡response에도 schema 설정을 해주세요😁

2024-08-13 05:10 UTC, kyum-q commented on backend/src/main/java/codezap/member/dto/response/UpdateMemberProfileResponse.java
> +        String username
```suggestion
        @Schema(description = "이메일", example = "code@zap.com")
        String email,
        @Schema(description = "사용자명", example = "zappy")
        String username
```
⚡response에도 schema 설정을 해주세요😁

2024-08-14 02:31 UTC, kyum-q approved these changes
GOOD❤️🍬🐰

2024-08-14 02:32 UTC, zangsu approved these changes
이전에 비해 문서화가 훨씬 깔끔해졌네요!! 
너무 좋습니다~ 👍

2024-08-14 02:32 UTC, zeus6768 approved these changes
👍

2024-08-14 02:33 UTC, HoeSeong123 approved these changes

2024-08-14 02:35 UTC, merged