flyway 설정 추가
woowacourse-teams/2024-code-zap pull request #430
Opened 2024-08-13 07:54 UTC by jminkkk

## ⚡️ 관련 이슈
close #423

## 📍주요 변경 사항
1. flyway 의존성 추가

## 🎸기타
1. 스키마 체크를 부탁드립니당 (휴먼 에러 발생 가능 폴폴)
2. 앞으로 db 스키마 마이그레이션 시 flyway 문법에 맞춰 파일을 작성해야 합니다

인프라 담당분 application-db.yml에 해당 부분 추가가 필요합니다. 
```
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
```

[달록의 데이터베이스 마이그레이션을 위한 Flyway 적용기](https://hudi.blog/dallog-flyway/#%EC%B2%AB%EB%B2%88%EC%A7%B8-%EB%A7%88%EC%9D%B4%EA%B7%B8%EB%A0%88%EC%9D%B4%EC%85%98-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%9E%91%EC%84%B1)

2024-08-14 02:55 UTC, zeus6768 requested changes

2024-08-14 02:55 UTC, zeus6768 commented on backend/build.gradle
> +    id 'org.flywaydb.flyway' version '8.5.13'
최신버전이 10.17.1 인데 8.5.13 으로 한 이유가 있나요~!

2024-08-14 03:33 UTC, HoeSeong123 submitted a review, later dismissed
고생하셨습니다.
항상 좋은 자료들을 찾아서 공유해주시네요 👍

2024-08-14 04:43 UTC, kyum-q submitted a review, later dismissed

2024-08-17 08:42 UTC, jminkkk commented on backend/build.gradle
> +    id 'org.flywaydb.flyway' version '8.5.13'
+) gradle plugin 사용할 일이 없을 것 같아 제거합니다.

2024-08-17 23:50 UTC, zeus6768 submitted a review, later dismissed
고생했어요 몰리~

궁금한 부분에 코멘트 남겼습니다 ㅎㅎ

2024-08-17 23:50 UTC, zeus6768 commented on backend/src/main/resources/db/migration/V1__init.sql
단순 질문) 지난 코드에서는 Hibernate의 DDL문을 복사 붙여넣기 했다고 했는데요, 변경된 커밋에서도 동일한 방식으로 작업한 건가요?

2024-08-18 08:10 UTC, zangsu submitted a review, later dismissed

2024-08-19 03:26 UTC, kyum-q reviewed
PR 머지 될 때 현재 테이블 구조에 따라 DDL 변경해주면 좋을 것 같아요 😁

2024-08-19 06:54 UTC, kyum-q submitted a review, later dismissed
몰리 수고했엉요, 짱

2024-08-19 14:09 UTC, jminkkk commented on backend/src/main/resources/db/migration/V1__init.sql
Hibernate DDL 을 mysql ddl 로 변경해달라고 했습니다 (with claude)

2024-08-20 05:59 UTC, zeus6768 approved these changes

2024-08-20 05:59 UTC, kyum-q approved these changes

2024-08-20 06:02 UTC, HoeSeong123 approved these changes

2024-08-20 06:05 UTC, zangsu approved these changes

2024-08-20 06:05 UTC, merged