충돌한 테스트 코드 해결 및 equals 재정의
woowacourse-teams/2024-code-zap pull request #459
Opened 2024-08-16 10:36 UTC by kyum-q

## 📍주요 변경사항
- 충돌한 테스트 코드 해결
- equals & hashcode 재정의
  - @EqualsAndHashCode 사용 시 프록시 객체 비교 안 됨
  - 재정의 방법
     - getClass() vs instanceOf 사용 -> getClass() 사용 (intanceOf는 상속한 객체 비교도 true 라서 안됨)
     - getter로 id 가져오기 (프록시 객체일 경우 값이 없을 수 있기 때문에 getter를 이용해 실제 값 가져오기)

2024-08-16 23:52 UTC, zeus6768 approved these changes
켬미 고생했어요~

2024-08-16 23:52 UTC, zeus6768 commented on backend/src/main/java/codezap/auth/configuration/AuthorizationInterceptor.java
> +    public boolean preHandle(final HttpServletRequest request, final HttpServletResponse response, final Object handler
오랜만에 보는 `final` 키워드네요~

일관성을 위해 지우는 건 어떤가요?

2024-08-16 23:52 UTC, zeus6768 commented on backend/src/test/java/codezap/member/domain/MemberTest.java
JUnit의 메서드 대신 일관성 있게 AssertJ의 메서드로 통일하는 건 어떤가요?

2024-08-17 08:19 UTC, zangsu requested changes
컨벤션에 맞지 않는 수정 사항이 있어 RC 남겼는데요, 
해당 부분만 제외하면 대부분의 컨벤션이 맞지 않던 부분들도 너무 잘 수정해 주셨고, 주석 테스트도 꼼꼼하게 살려 주셨네요 🥹
너무 고생 많았어요 켬미!

2024-08-17 08:19 UTC, zangsu commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +    private final MemberRepository memberRepository = new FakeMemberRepository();
필드의 `final` 은 좋아요!
저도 신경써서 일관성 유지해 보겠습니닷 👍

2024-08-17 08:19 UTC, zangsu commented on backend/src/test/java/codezap/fixture/MemberDtoFixture.java
> +                "몰리2",
몰리만 좋아하고 ☹️

2024-08-17 13:01 UTC, jminkkk submitted a review, later dismissed
켬미 수고했어요~ 🔥🔥

2024-08-17 13:01 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +
😭

2024-08-18 03:57 UTC, kyum-q commented on backend/src/main/java/codezap/auth/controller/AuthController.java
> +    ) {
저도 최대한 수동으로 다시 예쁘게 하긴하는데 스타일 파일 손봐야겠네요..🥲😁 일단 수동으로 고칠게용 ~

2024-08-18 04:02 UTC, kyum-q commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +
이 부분에 대해 더 생각해봐요🥲

2024-08-18 06:16 UTC, kyum-q commented on backend/src/test/java/codezap/member/domain/MemberTest.java
좋아요 ~ 
하지만 이번 PR 이 아닌 다음 PR에서 테스트 수정하도록 하겠습니다 😁
(왜냐하면 지금 이 PR 날리고 리펙터링 중이라서 여기서 고치면 코드 충돌이 생길 것 같습니다 ! ㅎㅎ)

2024-08-18 08:11 UTC, zangsu submitted a review, later dismissed
변경 확인 했습니다! 고생하셨어요 켬미~~~ ⚡

2024-08-19 03:58 UTC, HoeSeong123 approved these changes
고생하셨습니다 켬미
다른 분들이 다 해놔서 제가 리뷰를 남길만한 곳이 없네요 ㅎㅎ;;

2024-08-19 04:02 UTC, zeus6768 approved these changes
고생했어요~

2024-08-19 04:02 UTC, zeus6768 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +                    .build();
👍

2024-08-19 04:04 UTC, jminkkk approved these changes

2024-08-19 04:04 UTC, zangsu approved these changes
고생했어요 켬미~ ⚡

2024-08-19 04:05 UTC, merged