템플릿 도메인 서비스 책임 분리
woowacourse-teams/2024-code-zap pull request #477
Opened 2024-08-19 04:14 UTC by kyum-q

> 진짜 싹싹 빌게요 ... 서비스 책임 분리하려면 어쩔 수 없었다...는 핑계는 안할게요...
> 진짜 하루종일 개발 했으니 그래도 봐줘요.. 나도 열심히 하고 싶어서 그랫어요...

## 📍주요 변경사항

### 템플릿 서비스 책임 분리
이 전에는 템플릿 서비스가 가지는 책임이 너무 컸다. 그래서 테스트 코드 작성할 때도 필요하지 않은 다른 서비스들이 엮여서 어려움이 있었음
그래서 템플릿 서비스는 최소한의 기능만 하도록하고, 파사드 서비스를 통해 다른 서비스와의 연관 관계를 주었습니다.

- 기본 서비스 
   - 템플릿 서비스 - TemplateRepository : 템플릿 기본 CRUD (검색 포함) 
   - 소스코드 서비스 - SourceCodeRepository : 소스 코드 기본 CRUD
   - 썸네일 서비스 - ThumbnailRepository : 썸네일 소스 코드 기본 CRUD
   - 카테고리 서비스 - CategoryRepository : 카테고리 소스 코드 기본 CRUD

- 두개 레포 서비스
   -  템플릿태그서비스 - TagRepository/TemplateTagRepository :
 두 가지 레포가 필요한 작업
   - 카테고리템플릿서비스 - CategoryRepository/TemplateRepository : 두 가지 레포가 필요한 작업

- 파사드 서비스
   - MemberTemplateApplicationService : 멤버 작업과 템플릿 작업
   - TagTemplateApplicationService : 태그와 템플릿 작업
   - TemplateApplicationService : 카테고리, 태그, 템플릿 작업

## 🎸 기타

- 분리를 하고 나니 한 번 더 예외 확인을 해야하나 걱정이네요
   - ex.
     - 원래: 검색 시 null 확인을 template에서 확인 다 해버림
     - 지금: 검색 시 null 확인을 facade에서 해주고 넘겨주다보니 templateService에서는 안하는 중, 하지만 추가적으로 해야하나 고민 중 입니다

2024-08-20 02:11 UTC, zeus6768 submitted a review, later dismissed
고생했어요 ⚡

2024-08-20 02:11 UTC, zeus6768 commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +    }
```suggestion
    private void validateCategoryAuthorizeMember(Member member, Category category) {
        Member owner = category.getMember();
        if (!owner.equals(member)) {
            throw new CodeZapException(HttpStatus.UNAUTHORIZED, "해당 카테고리에 대한 권한이 없습니다.");
        }
    }
```

디미터 법칙을 고려해 위와 같이 바꾸는 건 어떨까요?

2024-08-20 02:17 UTC, zangsu approved these changes
고생 정말 많았어요 컴미 ㅋㅋㅋㅋㅋㅋㅋ
코멘트를 몇개 달아두긴 했지만, 사소한 것들이라 우선 Approve 남겨둘게요. 
확인 부탁드립니다!

2024-08-20 02:17 UTC, zangsu commented on backend/src/main/java/codezap/template/service/SourceCodeService.java
> +    public List<SourceCode> getSourceCode(Template template) {
이 친구도 네이밍이 다른 서비스 메서드와 조금 달라 보이네요. 
기존의 메서드들은 `getSourceCodeBy()` 또는 `getSourceCodeByTemplate()` 이 될 것 같은데, 맞나요?

2024-08-20 02:17 UTC, zangsu commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        validateCategoryAuthorizeMember(member, category);
```suggestion
        category.validateAuthorization(member);
```
`Category`가 가지고 있는 `Member` 를 꺼내서 확인하는 대신 `Category` 에게 직접 물어봐도 좋을 것 같아요.

2024-08-20 02:28 UTC, jminkkk requested changes
안녕하세요 켬미 🔥
너무너무너무너무 수고가 많네요. 켬미 덕분에 코드가 많이 개선된 것 같아요 (켬미 짱 ⚡️)

코멘트를 어쩌다보니 많이 남겼는데, 죄송해여,,,, 천천히 확인 부탁드려요 😭

2024-08-20 02:28 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +    private void validateCategoryAuthorizeMember(Member member, Category category) {
⚡️ CategoryService 도 MemberRepository를 의존하고 있어서, CategoryService로 이 메서드의 위치를 이동해도 되지 않을까요?
CategoryService에 validateAuthorizeMember 메서드와 동일한 역할인 것 같아서, CategoryService안에서 기존 메서드를 재사용해도 될 것 같네요!

⚡️ 또 CategoryService에서 최상위 파사드에서 Member를 전해주면 CategoryService는 MemberRepository를 의존하지 않아도 될 것 같아요! (templateRepository도 마찬가지로요!)

2024-08-20 02:28 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/SourceCodeService.java
> +        }
이 메서드를 추출해서 기존 isThumbnailDeleted() 는 메서드의 변수로 빼보면 어떨까요?

2024-08-20 02:28 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/SourceCodeService.java
> +package codezap.template.service;
SourceCode, Thumbnail은 따로 패키지 분리하지 않고 /template 에 있는 이유가 궁금해요!

2024-08-20 03:25 UTC, HoeSeong123 requested changes
고생하셨습니다 켬미!!
TemplateService가 하는 일이 너무 많아서 저도 걱정이 많았는데 정말 깔끔하게 분리하셨네요.
간단한 수정사항 몇 개 남겼습니다 확인 부탁드려요!!

2024-08-20 08:50 UTC, kyum-q commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +    public void validateExistsById(Long id) {
다음은 개선된 한국어 버전입니다:

코멘트를 읽고 생각해봤어요. 하지만 제 생각에는 해당 로직이 비즈니스 로직에 가깝다고 판단됩니다. 그래서 이 로직이 서비스 레이어에 있는 것이 더 적합하다고 생각해요.

만약 그렇다면, fetchByID 메서드도 동일한 논리로 봐야 할 것 같아요. 하지만 다음 부분이 다른 것 같아요 ~ 

validate: 예외처리 로직이 주
fetch: DB에서 값 추출이 주
- DB에 값이 있을 거라고 생각하고 요청을 보내고 반환되는 값이 없으면 예외를 발생

2024-08-20 12:19 UTC, kyum-q commented on backend/src/main/java/codezap/member/service/MemberService.java
> +    public Member getByMemberDto(MemberDto memberDto) {
findAllBy 같은 경우는 파라미터가 많아서 메서드명을 구체화 하지 않았는데 통일성이 없어보이기도 하네요 ~ 모든 메서드를 명확하게 네이밍 하는 방향으로 바꿨습니다.

> +) 그런데 혹시 id 값을 꺼내서 조회하지 않고 MemberDto 를 그대로 파라미터로 넘기는 이유가 있을까요?
큰 이유는 없고 MemberDto를 확인하는 차원에서 ID만 뽑아서 주기보다 Dto 그대로 넘기는 방식을 선택했습니다 ~

2024-08-20 12:20 UTC, kyum-q commented on backend/src/main/java/codezap/tag/service/TemplateTagService.java
> +    private void validateTagId(Long tagId) {
음..! 더 좋은 메서드명이 있으면 좋을 것 같은데 어렵네요~

2024-08-20 12:22 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/SourceCodeService.java
> +    public List<SourceCode> getSourceCode(Template template) {
findSourceCodesTemplate로 변경하였습니다. 

find와 get의 차이점
- find :값이 없을 수 있음 (배열인 경우 비어있을 수, 아닌 경우 optional일 수도)
- get: 값이 무조건 있음 없으면 예외처리

2024-08-20 12:48 UTC, kyum-q commented on backend/src/main/java/codezap/tag/controller/SpringDocTagController.java
> +            @ErrorCase(description = "인증 정보가 없거나 잘못된 경우", exampleMessage = "인증에 실패했습니다."),
오홍 몰리 굿 쟙 ~!

2024-08-20 14:12 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/facade/TagTemplateApplicationService.java
> +
원래 Tag와 관련된 것을 분류하려고 했다가 Tag를 빼면서 의미가 이상해졌네요~

해당 부분은 다음과 같이 변경했습니다.

TagTemplateApplicationService ->  TemplateApplicationService
TemplateApplicationService -> CategoryTemplateApplicationService

2024-08-20 14:16 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/SourceCodeService.java
> +package codezap.template.service;
따로 API가 존재하지 않아서 분리하지 않았습니다 ~

2024-08-20 14:18 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/facade/MemberTemplateApplicationService.java
> +    }
find와 get의 차이점은 다음과 같습니다.

- find :값이 없을 수 있음 (배열인 경우 비어있을 수, 아닌 경우 optional일 수도)
- get: 값이 무조건 있음 없으면 예외처리

2024-08-20 14:22 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +            long memberId,
controller에서 long으로 받는줄 알았는데 제 착각 ~ 모두 Long으로 고쳤습니다 ~

2024-08-21 04:33 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/facade/TagTemplateApplicationService.java
> +    }
분리했습니다 ~ !
네이밍은 FindAllTemplateItemResponse로 변경하였습니다.

2024-08-21 04:34 UTC, kyum-q commented on backend/src/main/java/codezap/tag/service/TemplateTagService.java
> +public class TemplateTagService {
TagTemplateApplicationService 클래스 명이 변경되었습니다 ~!
[변경 관련 리뷰](https://github.com/woowacourse-teams/2024-code-zap/pull/477/#discussion_r1722582566)

2024-08-21 06:22 UTC, zeus6768 approved these changes

2024-08-21 06:29 UTC, jminkkk approved these changes
🔥 켬미야 수고했드아 🔥

2024-08-21 06:51 UTC, HoeSeong123 approved these changes

2024-08-21 06:56 UTC, merged