카테고리 안내 메세지 및 생성 후 자동 선택 기능 추가
woowacourse-teams/2024-code-zap pull request #490
Opened 2024-08-19 11:32 UTC by Hain-tain

### ⚡️ 관련 이슈
- #442 
### 📍 주요 변경 사항
- 카테고리 생성 시, 안내메시지(`Guide`) 뜨도록 추가
- 카테고리 생성 후, 방금 생성한 것 자동 선택되는 기능 추가
- Input 컴포넌트에 placeholderColor 및 inputColor props 생성
  - 이건 템플릿 생성페이지에서 카테고리 Dropdown 에 들어가는 input 색상을 변경하기 위해 뚫었습니다!

2024-08-19 12:33 UTC, Jaymyong66 requested changes

2024-08-19 12:33 UTC, Jaymyong66 commented on frontend/src/components/Input/Input.tsx
> +    const isInputClicked = target.tagName === 'INPUT';
기발한 방법이네요~!

2024-08-19 12:33 UTC, Jaymyong66 commented on frontend/src/components/Input/Input.tsx
> +  };
[요런 이유](https://velog.io/@skawnkk/Dom%EA%B3%BC-VirtualDOM-Dom%EC%A0%91%EA%B7%BC%EC%9D%84-%EC%A7%80%EC%96%91%ED%95%B4%EC%95%BC%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0) 와 [요런 글](https://headwing.tistory.com/53)의 이유로 DOM에 직접 접근 안하는 방식으로 하면 어떨까요?

2024-08-19 12:33 UTC, Jaymyong66 commented on frontend/src/queries/category/useCategoryUploadMutation.ts
> +      handleCurrentCategory(res as Category);
postCategory의 response 타입을 Category로 하면 여기서 타입 단언 안해도 될 것 같아요!

2024-08-19 12:33 UTC, Jaymyong66 commented on frontend/src/queries/category/useCategoryUploadMutation.ts
> +export const useCategoryUploadMutation = (handleCurrentCategory: (newValue: Category) => void) => {
category 폴더의 index.ts에서 useCategoryUploadMutation이 아닌 useCategoryUploa로 export 하고 있는데, 의도한 것이 아니라면 동일한 것으로 고치면 좋을 것 같아요~! 검색에 안잡히네욥

2024-08-19 12:33 UTC, Jaymyong66 commented on frontend/src/components/TemplateEdit/TemplateEdit.tsx
이 아래의 타입들이 너무 장황해서 유지보수하기 힘들 것 같은데, 리팩토링하려면 저 밑에 useInput이나 깊은 곳부터 타입 정리를 해야겠네요. 
이번 PR의 변경사항이 아니니 우선 인지만 하고 리팩토링 하는 것으로 하죠!

-> 보니까 useTemplateEdit 훅을 여기서 실행시키면 props로 이렇게 받지 않아도 되지 않을까 싶네요?!

2024-08-19 12:33 UTC, Jaymyong66 commented on frontend/src/components/TemplateEdit/TemplateEdit.tsx
> +    e.target.value = '';
다음 줄에서 await을 걸지 않는다면 이후 value를 빈 문자열로 만드는 과정이나 다른 부분에서 사이드 이펙트가 발생할 수 있지 않을까요?

2024-08-19 12:33 UTC, Jaymyong66 requested changes
고생하셨습니닷!@ 고민한 흔적이 코드에서 많이 보여서 좋았습니다.

2024-08-19 12:44 UTC, vi-wolhwa submitted a review, later dismissed

2024-08-20 02:36 UTC, Hain-tain commented on frontend/src/components/TemplateEdit/TemplateEdit.tsx
Props 가 장황해진 이유는 `TemplateEditPage`와 `TemplateUploadPage` 둘 다에서 쓰이고 있기 때문입니다.
현재 useTemplateEdit과 useTemplateUpload가 추상화가 잘 되지 않아 현재 변경하기는 어려울 것 같습니다.
추후 리펙토링 해볼게요!! 👍

2024-08-20 02:40 UTC, Hain-tain commented on frontend/src/components/Guide/Guide.style.ts
> +  box-shadow: 1px 2px 8px 1px #00000030;
`GuideContainer` 라는 이름으로 변경하였습니다! 👍

2024-08-20 05:02 UTC, Hain-tain commented on frontend/src/components/TemplateEdit/TemplateEdit.tsx
> +    e.target.value = '';
이건 추후에 리펙토링해볼게요!!

2024-08-20 05:53 UTC, vi-wolhwa approved these changes

2024-08-20 05:54 UTC, Jaymyong66 approved these changes

2024-08-20 05:54 UTC, merged