프론트엔드 CD 복구
woowacourse-teams/2024-code-zap pull request #601
Opened 2024-09-05 06:06 UTC by vi-wolhwa

## ⚡️ 관련 이슈
#581

## 📍주요 변경 사항
- 프론트엔드 CD의 소스코드가 변경 됨(로그 없음)
- 마지막 Merge 시점으로 복구 (#569)

2024-09-05 08:53 UTC, Hain-tain submitted a review, later dismissed
👍

2024-09-05 08:54 UTC, Jaymyong66 requested changes
간단한데 하나만 바꾸면 좋겠네요! 코멘트 확인해주세욥

2024-09-05 08:54 UTC, Jaymyong66 commented on .github/workflows/frontend_cd.yml
> +
이거 아마 위의 환경 파일 권한 설정에서 /.env.*로 처리해서 포함되지 않을까요?!

2024-09-06 01:03 UTC, Hain-tain approved these changes

2024-09-06 01:04 UTC, Jaymyong66 approved these changes
고생했어요~

2024-09-06 01:04 UTC, merged