TemplateTagRepository 테스트
woowacourse-teams/2024-code-zap pull request #621
Opened 2024-09-09 13:30 UTC by zangsu

## ⚡️ 관련 이슈
close #620 

## 📍주요 변경 사항
1. 메서드 이름 및 쿼리를 직접 작성한 메서드에 대해 테스트를 작성

## 🎸기타
1. 테스트에 주요하게 사용되는 변수들을 픽스쳐 대신 지역 변수로 변경

2024-09-10 05:00 UTC, kyum-q requested changes
짱수 수고했어요 ~ 몇가지 코멘트 남겨놨습니다 확인 부탁드려요 ~

2024-09-10 05:30 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +        tagRepository.save(new Tag("tag3"));
`TagRepository` 에는 저장되어 있지만 조회 조건에 포함되지 않는 `Tag` 도 함께 확인을 하고 싶었는데요.
굳이 필요 없는 테스트일까요?

2024-09-10 05:30 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +    @DisplayName("findAllByTemplateTest 조회 성공")
확인했습니다~

2024-09-10 05:31 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +                .hasSize(2);
저는 상관 없습니다!
단순 궁금증인데, size 를 먼저 체크하는 것을 제안하신 이유가 있을까요?

2024-09-11 02:01 UTC, HoeSeong123 requested changes
👍

2024-09-11 02:27 UTC, jminkkk requested changes
안녕하세요 짱수 
테스트 수고하셨습니다 🔥

코멘트 확인 부탁드립니당~!

2024-09-11 02:27 UTC, jminkkk commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +        assertThat(templateTags).isEmpty();
템플릿을 하나 더 두어서 템플릿 식별자가 다른 템플릿 태그는 삭제되지 않음이 코드에서 보였으면 좋겠어요

2024-09-11 02:27 UTC, jminkkk commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +                List.of(tag2.getId(), tag3.getId()), 2);
template 기준으로 개행이 되어있는데, tag 기준으로 개행이 되어있는게 이해하기 더 쉬울 것 같아요~

테스트 목적이 태그에 해당하는 템플릿 아이디 찾기 이기 때문에.. 
```suggestion
        templateTagRepository.save(new TemplateTag(template1, tag1));
        templateTagRepository.save(new TemplateTag(template3, tag1));

        templateTagRepository.save(new TemplateTag(template1, tag2));
        templateTagRepository.save(new TemplateTag(template2, tag2));

        templateTagRepository.save(new TemplateTag(template1, tag3));
        templateTagRepository.save(new TemplateTag(template2, tag3));
                
        //when
        List<Long> allTemplateIdInTagIds = templateTagRepository.findAllTemplateIdInTagIds(
                List.of(tag2.getId(), tag3.getId()), 2);
```
tag 기준으로 개행을 하면 다른 개발자가 확인할 때에도 tag2, tag3 문단의 템플릿 아이디만 확인하면 더 수월하지 않을까요?

2024-09-11 02:27 UTC, jminkkk commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +        templateTagRepository.save(new TemplateTag(template2, tag3));
그리고 `templateTagRepository.save(new TemplateTag(template2, tag3));`가 두개 있네요

2024-09-11 02:27 UTC, jminkkk commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +                .hasSize(2);
`containsExactly(tag1.getId(), tag3.getId()) `통과 -> `hasSize(2); `무조건 통과
`hasSize(2);` 통과 -> `containsExactly(tag1.getId(), tag3.getId())` 무조건 통과 X

여서 같네요~

저도 켬미랑 같은 의견입니닷

2024-09-11 02:27 UTC, jminkkk commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
>      void testFindDistinctByTemplateIn() {
궁금한 게 이 쿼리 메서드에서 `Distinct`가 유효한 조건인가요? (= findAllByTemplateIn 와 다른가요?)

유효하다면, Distinct가 적용된 것을 확인할 수 있도록 테스트 내용을 변경해주세요.
유효하지 않다면 해당 메서드의 쿼리가 잘못 작성되었으니, 메서드를 변경해주세요.

2024-09-11 02:29 UTC, jminkkk reviewed
안녕하세요 짱수 
테스트 수고하셨습니다 🔥

코멘트 확인 부탁드립니당~!

2024-09-11 02:29 UTC, jminkkk commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +                new Template(member, "testTemplate1", "testTemplate1", category));
픽스처를 생성해서 활용해보면 어떨까요?
유효한 인자가 member, category이고 `"testTemplate1", "testTemplate1",` 이 부분은 사용되지 않을 것 같아요.
이 부분만 픽스처로 제거해도 라인 수가 많이 줄어들 것 같아요.

2024-09-11 04:19 UTC, zeus6768 requested changes
짱수 화이팅!!

다른 분들이 리뷰를 꼼꼼히 해주셔서, 저는 조금만 남기고 갑니다!

2024-09-11 04:19 UTC, zeus6768 commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +        tagRepository.save(new Tag("tag3"));
Tag3를 변수로 명시하고 `doesNotContain()` 메서드를 사용하면 좋겠어요~

2024-09-11 04:19 UTC, zeus6768 commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +        Template template3 = templateRepository.save(new Template(member, "title3", "description3", category));
```suggestion
        Template template1 = templateRepository.save(
                new Template(member, "title1", "description1", category));
        Template template2 = templateRepository.save(
                new Template(member, "title2", "description2", category));
        Template template3 = templateRepository.save(
                new Template(member, "title3", "description3", category));
```

위에서 한 것처럼 개행하면 어떨까요?

2024-09-11 05:01 UTC, kyum-q commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +                .hasSize(2);
몰리 의견 그대로 입니다 ~! 몰설굿

2024-09-11 07:57 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +        category = categoryRepository.save(new Category("Category 1", member));
반영 완료 ⭐

2024-09-11 08:19 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
>      void testFindDistinctByTemplateIn() {
아하, `distinct` 가 없이 `findAllByTemplateIn` 으로도 기대한 동작을 하는군요!
메서드 이름을 변경해야겠네요.

다만, 이번 이슈가 테스트 추가 이슈이므로 별도의 이슈를 새로 파고 수정해 두겠습니다.

2024-09-11 08:24 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
>      void testFindDistinctByTemplateIn() {
#635 
이슈로 파 두었어용~

2024-09-11 08:41 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +        templateTagRepository.save(new TemplateTag(template2, tag3));
헉...!

2024-09-11 09:45 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +                            .hasMessageContaining("템플릿이 존재하지 않습니다."),
엣지 케이스에 대한 테스트를 추가했습니다.
그런데, 실제로 존재하지 않는 id 를 가져올 방법이 없는 것 같아 이렇게 테스트에 사용할 변수를 다시 테스트 내부에서 테스트 하고 있습니다.
이런 코드.. 들어가도 될까요? 🤔

2024-09-11 09:47 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +                            templateTagRepository.deleteAllByTemplateId(template.getId() + 1))
여기선 존재하지 않는 id 를 가장 최근에 저장된 객체의 id + 1 로 사용하고 있는데요.
이 방법이 테스트코드에 한해서는 가능한 방법이지만, 모호하게도 느껴지는 것 같아요.

실제론 DB 동작에 따라 없는 id가 아닐 수 있다던지...

이런 코드는 또 어떻게 생각하시나요..?

2024-09-11 10:23 UTC, kyum-q requested changes
짱수 반영 잘해주셨네요 !! 
제가 착각했던 코드 컨벤션이 있었어요 ㅜ 뒤늦게 알아서 지금 리뷰 하나 남겼습니자 확인 부탁드려요 !

2024-09-11 10:23 UTC, kyum-q commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
> +    @DisplayName("성공 : Template 을 이용한 TemplateTag 목록 조회")
짱수..! 저도 몰리가 리뷰 달아줘서 알았는데 위키에 컨벤션이 다음과 같더라고요 ㅎ

> "자동차 이름 입력 실패: 쉼표만 입력" 저희 컨벤션

목록 조회 성공: ~~~ 라고 변경해주세요 🥲 저도 몰랐어서 뒤늦게 알려드리네요 🥹

2024-09-11 17:44 UTC, kyum-q approved these changes
짱수 짱 ! 👍🏻 수고하셨습니다 !

2024-09-12 00:06 UTC, jminkkk approved these changes
짱짱

짱수짱짱맨

2024-09-12 00:06 UTC, jminkkk commented on backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
>      void testFindDistinctByTemplateIn() {
이해 됐어요 짱수 친절한 설명 고마워요!!!!!!!!!!!!!!!!!!

대면으로 논의했듯이 templateTag가 아닌 tag를 반환하는 현재 메서드 자체가 어색한 것 같아요
이슈로 파두고 다음 스프린트 때 해결해봅시다 !!!!!!!!!!!!

2024-09-12 01:03 UTC, HoeSeong123 approved these changes

2024-09-12 05:57 UTC, zeus6768 approved these changes
👍

2024-09-12 05:57 UTC, merged