Test/620 member jpa repository
woowacourse-teams/2024-code-zap pull request #624
Opened 2024-09-10 04:39 UTC by kyum-q

## ⚡️ 관련 이슈
close #620 

## 📍주요 변경 사항
MemberJpaRepository 관련 테스트 구현
- 메서드 이름 및 쿼리를 직접 작성한 메서드에 대해 테스트를 작성

## 🎸기타
### 테스트 처음 실행 시 정상 실행 (DB에 테이블 없는 상태에서)
![image](https://github.com/user-attachments/assets/27415cdb-fbc1-4af4-a45b-c74b600045bc)

### 두번 째 실행부터 Flyway 에러 발생 
![image](https://github.com/user-attachments/assets/9bdc3137-1533-4432-9e48-91f9fd05382f)

#### 문제 원인
- V1__init.sql 실행으로 문제 발생 -> 테이블이 이미 존재해서 에러

#### 의문점 - 왜 V1__init.sql 이 계속 실행되는가?  
  - Flyway는 각 마이그레이션 파일에 고유한 버전을 부여하며, 이 버전이 flyway_schema_history 테이블에 기록된 경우 동일한 버전의 스크립트는 재실행되지 않는다. 
  -  flyway_schema_history 확인하면 version 1 등록되어 있음
  - ![image](https://github.com/user-attachments/assets/dc0f60c1-e608-41d6-b5b9-51c13768831d)

2024-09-10 04:40 UTC, kyum-q commented on backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
> +    Optional<Member> findByTemplateId(@Param("templateId") Long templateId);
TemplateTagRepository 테스트

2024-09-11 02:21 UTC, HoeSeong123 requested changes
고생하셨습다 켬미 👍

2024-09-11 02:21 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
>      }
(질문) 오 이렇게 하는건 처음보네요?? 
필드들을 각각 `@Autowired`하는 것과 어떤 차이가 있나요??

2024-09-11 02:21 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +    @DisplayName("아이디가 존재 여부")
정말 사소한 거지만 문장이 어색한 것 같아요.
`아이디 존재 여부` 등으로 수정하는 건 어떤가요?

2024-09-11 02:21 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +        @DisplayName("성공 : 해당 아이디가 존재하면 false를 반환한다.")
⚡
```suggestion
        @DisplayName("성공 : 해당 아이디가 존재하지 않으면 false를 반환한다.")
```

2024-09-11 03:46 UTC, zangsu reviewed
켬미~
코드를 너무 잘 짜 주셨네요!
컨벤션이나 코드 자체에서는 리뷰를 달 부분이 거의 없었던 것 같아요. 
그래서 코드 스타일에 대한 코멘트를 조금 남겼으니 가볍게 확인 부탁드립니다!

2024-09-11 03:46 UTC, zangsu commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +    private final CategoryRepository categoryRepository;
DIP 를 고려한 추상화에 의존 👍

2024-09-11 03:46 UTC, zangsu commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +        @DisplayName("성공 : id로 Member를 알아낼 수 있다.")
DisplayName 컨벤션 👍

2024-09-11 03:46 UTC, zangsu commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +            member = memberRepository.save(member);
```suggestion
            Member member = memberRepository.save(MemberFixture.getFirstMember());
```
[제안]
정말 사소한데, `MemberFixture.getFirstMember()` 를 변수로 추출할 필요는 없을 것 같아요. 
member 변수에 값을 재할당 할 필요 없이 `MemberRepository.save()` 로 저장 한 반환값을 필드로 추출하는 건 어떤가요?

(어떤 방법도 타당하게 느껴져서, 켬미의 선호에 맞게 선택해 주시면 좋을 것 같아요!)

2024-09-11 03:46 UTC, zangsu commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +                    .hasMessage("식별자 " + id + "에 해당하는 멤버가 존재하지 않습니다.");
```suggestion
            long notExistId = 100;

            assertThatThrownBy(() -> memberRepository.fetchById(notExistId))
                    .isInstanceOf(CodeZapException.class)
                    .hasMessage("식별자 " + notExistId + "에 해당하는 멤버가 존재하지 않습니다.");
```
[제안]
변수 명을 조금 더 직관적으로 바꿔보는 것은 어떨까요?

2024-09-11 03:46 UTC, zangsu commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +    @DisplayName("아이디로 Member 조회")
[제안]
아이디와 id 는 타당한 네이밍이지만, 여전히 서로가 헷갈리는 것 같아요.
지금 우리 서비스에서도 아이디를 "아이디(닉네임)" 으로 표시하고 있죠.
필드 이름도 name 이니 "이름" 또는 "닉네임" 이라는 용어를 사용해 보는 것은 어떨까요?

2024-09-11 03:46 UTC, zangsu commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +                    .hasMessage("존재하지 않는 아이디 " + name + " 입니다.");
```suggestion
        void fetchByNameFailByNotExistsId() {
            String notExistName = "켬미";

            assertThatThrownBy(() -> memberRepository.fetchByName(notExistName))
                    .isInstanceOf(CodeZapException.class)
                    .hasMessage("존재하지 않는 아이디 " + notExistName + " 입니다.");
```
위의 제안과 동일합니다.

2024-09-11 03:46 UTC, zangsu commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +            assertThat(actual).isTrue();
```suggestion
            assertThat(memberRepository.existsByName(member.getName()))
                    .isTrue();
```

[제안]
확인하는 내용을 한 눈에 볼 수 있도록 변수 추출을 제거해 보았는데요. 
가볍게 확인 해 보시고 켬미가 보기에 더 편한 것으로 선택해 주세요!

2024-09-11 03:46 UTC, zangsu commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +            boolean actual = memberRepository.existsByName("kkk");
```suggestion
            boolean actual = memberRepository.existsByName("notExist");
```
[제안]
정말정말 사소한 부분이지만, "존재하지 않는다" 라는 컨디션을 확인할 때는 변수 자체를 해당 의미를 내포하도록 사용하면 더 알아보기 편한 것 같아요.

2024-09-11 04:21 UTC, zeus6768 commented on backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
> +    Optional<Member> findByTemplateId(@Param("templateId") Long templateId);
resolve 해주세요~

2024-09-11 04:33 UTC, kyum-q commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +    @DisplayName("아이디로 Member 조회")
닉네임으로 변경하였습니다. ~
하지만 해당 메서드를 묶음 Nested에 DisplayName에는 좀 더 정확하게 닉네임(아이디)로 변경하였습니다 !

2024-09-11 04:36 UTC, kyum-q commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +            assertThat(actual).isTrue();
좋은 의견 같아요 ~ 하지만 저는 when then이 분리되어있는게 더 좋아보여서 고치지 않겠습니다 ~!

2024-09-11 04:36 UTC, zeus6768 reviewed
켬미 고생했어요~

간단한 코멘트 남겼습니다. 

팀원들이 해준 리뷰 반영되면 approve 하러 올게요!

2024-09-11 04:36 UTC, zeus6768 commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +    private final CategoryRepository categoryRepository;
테스트에서는 굳이 생성자를 선언할 필요가 없다고 생각하는데, 켬미는 어떻게 생각하나요?

final 키워드를 제거하고 필드에 `@Autowired`를 선언하면 라인 수를 줄일 수 있을 것 같아요~

```suggestion
    @Autowired
    private MemberRepository memberRepository;
    @Autowired
    private TemplateRepository templateRepository;
    @Autowired
    private CategoryRepository categoryRepository;
```

2024-09-11 04:36 UTC, zeus6768 commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +            member = memberRepository.save(member);
```suggestion
            Member member = MemberFixture.getFirstMember();
            Member saved = memberRepository.save(member);
```
(짱수 코멘트 보고 작성합니다)

저는 이런 방식을 더 선호해요. 

짱수와 달리 저는 가능하다면 호출된 메서드의 반환값을 명시하기 위해 변수를 할당하는 게 좋다고 생각합니다~

2024-09-11 04:36 UTC, zeus6768 commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +    @DisplayName("아이디로 Member 조회")
#632 디스커션에서 논의해볼만한 주제네요.

저는 일단 코드리뷰에서는 넘어가겠습니다!

2024-09-11 04:44 UTC, kyum-q commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
>      }
저도 이전 미션 때 매번 @Autowired를 사용했습니다 ~!
하지만 이번에 수정 전 코드도 생성자 주입으로 되어 있고, 레벨 2 때 어디선가 테스트에서 Setter 주입보다 생성자 주입이 더 빠르다라는 이야기를 들었던 것 같아서 그대로 사용했습니다 !

하지만 초롱에 질문에 답변하기 위해 찾아보니 그런 아티클이나 글은 없더라고요 ㅎㅎ 그래서 ChatGPT한테 물어보니 성능 상은 거의 똑같을 거라고 하네요 ! 

그래도 혹시 몰라 테스트를 실행해 봤습니다. 
**결론적으로 전혀 상관 없네요 ㅎㅎ
가독성이 좋은 @Autowired 사용으로 변경하겠습니다.**
> ![스크린샷 2024-09-11 132631](https://github.com/user-attachments/assets/84712782-574d-4a40-be0e-8989038e843f)
> ![스크린샷 2024-09-11 132759](https://github.com/user-attachments/assets/094275b6-3d8b-4a4a-99ae-93c063eb2b4d)

2024-09-11 05:16 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
>      }
찾아봐줘서 감사합니다!!

2024-09-11 07:12 UTC, jminkkk commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +        }
> "자동차 이름 입력 실패: 쉼표만 입력" 저희 컨벤션

`id로 Member 조회 실패: 존재하지 않는 id` 로 변경하면 어떨가요?

2024-09-11 07:15 UTC, jminkkk commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +            template = templateRepository.save(template);
```suggestion
            Template template = templateRepository.save(new Template(member, "title", "description", category));
```

요렇게 바꿔볼까요?

2024-09-11 07:23 UTC, kyum-q commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +        }
코드 컨벤션 확인까지 하고온 당신 ..! 너무 철저해 ~

2024-09-11 07:59 UTC, HoeSeong123 approved these changes
고생하셨습니다

2024-09-11 08:02 UTC, kyum-q commented on backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
> +            member = memberRepository.save(member);
저는 짱수의 의견에 동의해서  MemberFixture.getFirstMember() 를 변수로 추출하지 않는 방향으로 수정하였습니다 ~

2024-09-11 13:19 UTC, jminkkk submitted a review, later dismissed

2024-09-11 17:59 UTC, zeus6768 approved these changes
👍

2024-09-12 00:14 UTC, zangsu reviewed
놓친 부분이 있었네요 ㅠ
아주아주 사소한 부분이니... 한번만 더 수정 부탁드려용

2024-09-12 01:31 UTC, jminkkk approved these changes

2024-09-12 01:33 UTC, zangsu approved these changes
요구사항 변경 너~~무 고생 많으셨어요!! ⚡

2024-09-12 04:01 UTC, HoeSeong123 approved these changes

2024-09-12 05:58 UTC, zeus6768 approved these changes

2024-09-12 05:58 UTC, merged