TagJpaRepository 테스트 구현
woowacourse-teams/2024-code-zap pull request #625
Opened 2024-09-10 04:45 UTC by kyum-q

## ⚡️ 관련 이슈
close #620 

## 📍주요 변경 사항
TagJpaRepository 관련 테스트 구현
- 메서드 이름 및 쿼리를 직접 작성한 메서드에 대해 테스트를 작성

## 🎸기타
#624 와 동일한 Flyway 문제 발생

2024-09-11 02:26 UTC, HoeSeong123 requested changes
👍

2024-09-11 02:26 UTC, HoeSeong123 commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +    }
이 부분은 얘기할 게 조금 많아 보여요.
우선 처음에는 위 테스트 코드와 완전히 동일한 코드인 줄 알았습니다.
자세히 보니 `fetchByName`과 `findByName`의 차이이더군요.
그런데 저희는 `findByName`은 `fetchByName`에서만 사용하고 있어서 해당 테스트코드가 필요한가? 라는 생각이 들기는 합니다. 제가 그랬던 것처럼 위 테스트와 혼동하기 쉬울 것 같기도 해서요.

하지만 한편으로는 private 메서드가 아닌 이상 필요할 것 같다는 생각도 들기는 합니다.
켬미의 생각은 어떤가요?

2024-09-11 03:56 UTC, zangsu reviewed
대부분 이전 PR 의 리뷰와 동일한 코멘트입니다!
가볍게 확인 해 보시고 켬미의 취향대로 반영해 주시면 좋을 것 같아요!

2024-09-11 03:56 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +        @DisplayName("성공 : id로 태그를 알아낼 수 있다.")
```suggestion
        @DisplayName("성공 : id로 태그를 조회할 수 있다.")
```
[제안]
아주 사소하지만, 클래스 단위의 `@DisplayName` 과 용어를 통일시켜 보아도 좋을 것 같아요.

2024-09-11 03:56 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +                    .hasMessage("식별자 " + id + "에 해당하는 태그가 존재하지 않습니다.");
```suggestion
        void fetchByIdFailByNotExistsId() {
            long notExistId = 100;

            assertThatThrownBy(() -> tagRepository.fetchById(notExistId))
                    .isInstanceOf(CodeZapException.class)
                    .hasMessage("식별자 " + notExistId + "에 해당하는 태그가 존재하지 않습니다.");
```

[제안] 
변수 명을 조금 더 명확하게 지어도 좋을 것 같아요.

2024-09-11 03:56 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +        }
```suggestion
        @Test
        @DisplayName("실패 : 존재하지 않는 태그명인 경우 에러가 발생한다.")
        void fetchByNameFailByNotExistsId() {
            String notExistTagName = "없는태그";

            assertThatThrownBy(() -> tagRepository.fetchByName(notExistTagName))
                    .isInstanceOf(CodeZapException.class)
                    .hasMessage("이름이 " + notExistTagName + "인 태그는 존재하지 않습니다.");
        }
```
[제안]
다른 리뷰와 마찬가지로 변수 명, 변수 값을 더 명확히 변경해 보았어요.

2024-09-11 03:56 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +    }
저도 비슷한 고민이 들긴 했는데요. 
저는 어쨌든 `public` 메서드로 외부에 기능을 제공하고 있는 이상은 테스트 범위에 속하는 것이 좋을 것 같아요.

`fetchByName()` 메서드가 예상과 다르게 동작할 경우 `findByName()` 에 대한 테스트가 잘 작성되어 있으면 `fetchByName()` 메서드 내부로만 문제 범위를 좁힐 수 있을 것 같기도 하네요!

2024-09-11 03:56 UTC, zangsu commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +        }
```suggestion
        @Test
        @DisplayName("성공 : 해당 아이디가 존재하면 true를 반환한다.")
        void existsByNameReturnTrue() {
            Tag tag = tagRepository.save(new Tag("태그"));
            
            assertThat(tagRepository.existsByName(tag.getName()))
                    .isTrue();
        }
```
[제안]
이전 PR 의 리뷰와 마찬가지로 켬미에게 더 좋게 보이는 코드를 선택해주세요!!

2024-09-11 04:45 UTC, zeus6768 approved these changes
켬미짱~~

2024-09-11 04:45 UTC, zeus6768 commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +    }
> 저희는 findByName은 fetchByName에서만 사용하고 있어서 해당 테스트코드가 필요한가? 라는 생각이 들기는 합니다. 제가 그랬던 것처럼 위 테스트와 혼동하기 쉬울 것 같기도 해서요.

저는 초롱이 한 얘기와 같은 이유로 필요하지 않다고 생각합니다.

2024-09-11 04:55 UTC, kyum-q commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +    }
저는 딱 다음 의견에 근거해서 구현하였습니다. 
> 초롱: private 메서드가 아닌 이상 필요할 것 같다는 생각도 들기는 합니다.
> 짱수: public 메서드로 외부에 기능을 제공하고 있는 이상은 테스트 범위에 속하는 것

하지만 초롱과 제우스의 의견에도 동의해요 ! 적절한 근거인 것 같네요 ! 

두 의견 다 동의를 해서 어떻게 할지 빠르게 다수결로 정해보는거 어떤가요?

2024-09-11 07:24 UTC, jminkkk submitted a review, later dismissed
안녕하세요 켬미~!
사소한 코멘트 남겼으니 확인 부탁드립니당 짱

2024-09-11 07:24 UTC, jminkkk commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +            assertThat(actual).isEqualTo(Optional.of(tag));
```suggestion
            assertThat(actual).hasValue(tag);
```

이런 메서드가 있더라구요! 활용해볼까요?

2024-09-11 07:24 UTC, jminkkk commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +    }
멋쟁이들이네요 다들

2024-09-11 07:24 UTC, jminkkk commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +                .containsExactly("태그1", "태그3");
👍

2024-09-11 07:32 UTC, kyum-q commented on backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
> +            assertThat(actual).isEqualTo(Optional.of(tag));
미쳤다 너무 원햇어 이 방법 ..!

2024-09-11 07:59 UTC, HoeSeong123 approved these changes

2024-09-11 13:19 UTC, jminkkk approved these changes

2024-09-11 17:59 UTC, zeus6768 approved these changes
👍

2024-09-12 00:16 UTC, zangsu approved these changes
요구사항 반영 하느라 고생하셨어요!!!

2024-09-12 00:19 UTC, merged