test(repository): SourceCodeJpaRepository 테스트 구현
woowacourse-teams/2024-code-zap pull request #626
Opened 2024-09-10 04:47 UTC by HoeSeong123

## ⚡️ 관련 이슈
close https://github.com/woowacourse-teams/2024-code-zap/issues/620

## 📍주요 변경 사항
- SourceCodeJpaRepository 관련 테스트 구현
- 쿼리 메서드에 대해 테스트를 작성

2024-09-10 06:16 UTC, kyum-q requested changes
초롱 수고했어요 ~ 👍
BeforeEach를 사용으로 각각의 테스트 코드가 간결하네요 ~ 
하지만 테스트 코드 하나를 확인할 때마다 BeforeEach를 확인해야하네요 ㅜ 즉 테스트 코드 하나만으로 테스트 파악이 어려운 것 같아요 . 그 예시로 [커밋](https://github.com/woowacourse-teams/2024-code-zap/pull/626#discussion_r1751264416)으로 자세히 남겨놨어요 !
그래서 저는 코드 내에 save하는 코드가 다 있는 방식이 좋을 것 같아요 ! (너무 길다면 member 같이 중요하지 않은 정보는 beforeEach로 사용해도 좋지만요 !)

초롱이 생각하기에 저와 다르다면 한 번 이야기해보면 좋을 것 같아요 !

2024-09-11 03:57 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +    @DisplayName("소스코드 ID로 소스코드 조회")
하도 오랜만에 테스트 코드를 작성하다보니 놓쳐버렸네요.. 수정하겠습니다!

2024-09-11 04:16 UTC, zangsu requested changes
초롱, 정말 고생 많으셨어요!
가볍게 리뷰 몇가지 남겨 두었어요. 
클래스 명 이외의 리뷰는 가볍게 읽어보시고 초롱의 선호에 맞게 반영하시면 좋을 것 같습니다!

2024-09-11 04:16 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +    }
저도 동일한 의견입니닷..!
혹은 beforeEach 에서 초기화 해 주는 픽스쳐들의 네이밍을 더 직관적으로 해 주면 좋을 것 같아요.

2024-09-11 04:16 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var result = sourceCodeRepository.findAllByTemplate(template1);
## `var` 에 대한 짱수의 생각

### 장점

#### 중복되는 클래스 이름의 제거

객체를 새로 생성하는 시점이라면 다음과 같은 코드가 작성될 것 같아요.
```java
Template template = new Template();
```

이 경우 어짜피 타입이 한 줄에 보이기 때문에 굳이 긴 클래스 명을 여러번 적어 줄 필요는 없다고 생각해요.
그래서 아래와 같이 `var` 를 사용해 주는 것이 편할 것이라 생각합니다.

```java
var template = new Template();
```

#### 불필요한 타입 제한 제거

또한, 타입 자체가 크게 중요하지 않은 경우에도 `var` 는 유용하게 사용할 수 있을 것 같아요.
```java
var templates = templateRepository.findAll();
```

`findAll()` 메서드가 언젠가 `List<Template>` 타입에서 `Templates` 타입으로 변경되더라도 `templates`의 타입을 변경해 줄 필요는 없으니까요.

### 결론

위와 같은 장점에도 여전히 타입 안정성을 보장받을 수 없다는 점이 마음에는 걸려요. 
그래서 저는 
1. 네이밍이 직관적이고
2. 타입이 중요하지 않거나
3. 객체를 생성하는 시점

이라면 `var` 를 사용할 것 같다는 생각입니다.

2024-09-11 04:16 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var result = sourceCodeRepository.findAllByTemplate(template1);
```suggestion
        var sourceCodes = sourceCodeRepository.findAllByTemplate(template1);
```
[제안]
`var` 와는 별개로 지역변수 이름이 더 직관적이었으면 좋겠네요

2024-09-11 04:16 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        assertThat(result).hasSize(0);
```suggestion
        assertThat(result).isEmpty();
```
[제안]
정말정말 사소하지만, 더 직관적인 메서드가 될 것 같아서 제안드려 봅니다!

2024-09-11 04:59 UTC, zeus6768 requested changes
초롱 짱짱맨~~

간단한 코멘트 남겼습니다 👍

2024-09-11 04:59 UTC, zeus6768 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +    }
저도 같은 의견입니다~

2024-09-11 04:59 UTC, zeus6768 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +public class SourceCodeRepositoryTest {
저는 짱수와 조금 다른 의견인데요.

근거는 다음과 같습니다!

1. 클래스 애너테이션에 JPA가 명시되어있음
2. 실제로 테스트 대상이 되는 객체는 JPA가 아닌 인터페이스를 사용하고 있음 (`SourceCodeJpaRepository`가 아닌 `SourceCodeRepository`)
4. JPA를 사용하지 않게 되더라도 본 테스트의 본질은 유효함. DB와 데이터를 잘 주고받을 수 있는지! 만약 그렇게 된다면 애너테이션을 제거하고 메서드를 리팩토링하면 됨.

2024-09-11 04:59 UTC, zeus6768 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var result = sourceCodeRepository.findAllByTemplate(template1);
`actual`이 좋을 것 같아요~

2024-09-11 04:59 UTC, zeus6768 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var sut = new SourceCode(template1, "SourceCode 4", "Content 4", 1);
본 테스트에서 테스트 대상은 SourceCode 객체가 아니라, sourcecodeRepository 객체입니다. 

sut 키워드를 사용할 것이라면 sourcecodeRepository 대신 사용해야 합니다. 

저도 이번 테스트코드를 작성하며 sut 키워드를 사용했는데요. [제 PR](https://github.com/woowacourse-teams/2024-code-zap/pull/627)의 내용을 참고해주세요!
```suggestion
        var sourceCode = new SourceCode(template1, "SourceCode 4", "Content 4", 1);
```

2024-09-11 05:00 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +    }
저도 동일한 의견입니다

2024-09-11 05:03 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var result = sourceCodeRepository.findAllByTemplate(template1);
큰 고민을 해본적은 없지만 짱수와 비슷한 의견인 것 같습니다.
나중에 이에 대해 컨텍스트 공유를 해보면 좋을 것 같네요~~!!
저도 아직은 프로덕션 코드에서 사용은 살짝 꺼려집니다. 그래도 잘 알고 사용한다면 큰 문제는 없을 거라고 생각합니다!

2024-09-11 05:03 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        assertThat(result.get(0).getFilename()).isEqualTo("SourceCode 1");
체이닝 너무 좋네요

2024-09-11 05:04 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var sut = new SourceCode(template1, "SourceCode 4", "Content 4", 1);
단순한 관용어라고만 생각했었는데 명확한 사용 용도가 있었네요.
제우스 PR 보고 수정하였습니다!

2024-09-11 05:06 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +public class SourceCodeRepositoryTest {
저도 제우스의 의견에 동의합니다.

2024-09-11 05:12 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var result = sourceCodeRepository.findAllByTemplate(template1);
보통 `result` 많이 쓰지 않나요?

2024-09-11 05:18 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +public class SourceCodeRepositoryTest {
제가 근거를 더 자세히 적어둘 걸 그랬네요. 코멘트 여러번 왔다갔다 하게 해서 미안합니다 ㅠ

제가 해당 부분에 코멘트를 작성한 이유는 다음과 같습니다.

### 1. 테스트 작성 이유

우리가 테스트를 작성한 이유 중에는 "`JpaRepository` 에서 제공하는, 메서드 명으로 만들어 주는 메서드들이 우리의 예상대로 동작하는지 확인하기 위함" 도 존재한다고 생각해요. 
즉, `Jpa` 라는 환경 때문에 작성되는 테스트라고 생각합니다.

저의 경우 실제로 복잡한 `JpaRepository` 메서드 명을 사용하면 '제대로 작성한 것이 맞나?' 하는 불안함이 들 때가 있고, 이럴 때 테스트코드가 확신을 줄 수 있다고 생각해요.

### 2. 빠르게 테스트 코드를 찾을 수 있다.

아주 사소하지만, 테스트 이름을 클래스 이름과 동일하게 작성해 두면 클래스에서 `cmd + shift + t` 로 빠르게 테스트코드를 찾아갈 수 있습니다.
추가되는 메서드에 대해서도 빠르게 테스트코드를 작성할 수 있게 될거에요.

2024-09-11 05:19 UTC, zeus6768 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var result = sourceCodeRepository.findAllByTemplate(template1);
result도 나쁘진 않다고 생각해요. 

다만 저는 다음과 같은 이유로 actual을 써왔어요.

1. JUnit과 AssertJ의 assert() 메서드에서 파라미터 이름으로 actual을 사용함
2. 어떤 테스트에서는 여러 메서드의 결과를 사용하고, result에 해당하는 값이나 객체가 여러 개일 수도 있음. 이럴 때에도 일관성을 유지하기 위함

### JUnit
![Screenshot 2024-09-11 at 2 16 11 PM](https://github.com/user-attachments/assets/57dde172-40de-49b4-b987-09a3dbde50c7)

### AssertJ
![Screenshot 2024-09-11 at 2 15 21 PM](https://github.com/user-attachments/assets/c17a7ed8-2aa9-4f9e-80a4-935348bbe04c)

2024-09-11 05:23 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var result = sourceCodeRepository.findAllByTemplate(template1);
2번이 잘 이해가 되지 않아서 그런데 조금만 더 자세히 설명해주실 수 있나요??
actual을 사용하면 객체가 여러 개일 때도 일관성을 유지할 수 있다는 게 잘 그려지지 않아서요😅

2024-09-11 05:26 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var result = sourceCodeRepository.findAllByTemplate(template1);
제가 `actual` 이 아닌 `sourceCodes` 를 제안드린 이유는 변수 자체로 `Collection`, 또는 일급 컬렉션 정도의 타입임을 쉽게 추론할 수 있기 때문입니다.
`assertThat(result).hasSize(2);` 보단 `assertThat(sourceCodes).hasSize(2);` 가 더 파악하기 편하다고 느껴졌어요.
하지만 리뷰 본문에서도 말씀드린 것 처럼 가벼운 변수 명 제안이니 초롱이 편한 대로 사용하셔도 전혀 무관합니다!

2024-09-11 07:49 UTC, jminkkk requested changes
안녕하세요 초롱~!
수고하셨어요 🔥
코멘트 확인 부탁드립니다!

2024-09-11 07:49 UTC, jminkkk commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +            sut.save(sourceCode3);
```suggestion
            var sourceCode1 = sut.save(new SourceCode(template1, "SourceCode 1", "Content 1", 1));
            var sourceCode2 = sut.save(new SourceCode(template1, "SourceCode 2", "Content 2", 2));
            var sourceCode3 = sut.save(new SourceCode(template2, "SourceCode 3", "Content 3", 1));
```

이 부분도 바로 위 라인처럼 작성할 수 있지 않을까요?!
라인이 줄어들 것 같아요~!

2024-09-11 07:49 UTC, jminkkk commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        void fetchByIdFailWithWrongId   () {
> @DisplayName은 형식은 다음과 같다. (ex. 자동차 이름 입력 실패: 쉼표만 입력)

⚡️ [코드 컨벤션](https://github.com/woowacourse-teams/2024-code-zap/wiki/%EB%B0%B1%EC%97%94%EB%93%9C-%EC%BD%94%EB%93%9C-%EC%BB%A8%EB%B2%A4%EC%85%98) 에 작성된 컨벤션을 지켜서 변경해볼까요?

`소스코드 ID로 소스코드 조회 실패: 존재하지 않는 ID`처럼 변경할 수 있을 것 같아요!

2024-09-11 07:49 UTC, jminkkk commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        void fetchByTemplateAndOrdinalFaitWithWrongOrdinal() {
```suggestion
        void fetchByTemplateAndOrdinalFailWithWrongOrdinal() {
```
오타인가요......??

2024-09-11 07:49 UTC, jminkkk commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +            var sourceCode4 = new SourceCode(template2, "SourceCode 4", "Content 4", 1);
ordinal인 1을 변수로 빼면 어떨까요? 더 가독성이 좋아질 것 같아요!
```suggestion
            int ordinal = 1;
            
            var sourceCode1 = new SourceCode(template1, "SourceCode 1", "Content 1", ordinal);
            var sourceCode2 = new SourceCode(template1, "SourceCode 2", "Content 2", ordinal);
            var sourceCode3 = new SourceCode(template1, "SourceCode 3", "Content 3", 2);
            var sourceCode4 = new SourceCode(template2, "SourceCode 4", "Content 4", ordinal);
```

2024-09-11 07:49 UTC, jminkkk commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +            var sourceCode2 = new SourceCode(template1, "SourceCode 2", "Content 2", 2);
(꼭 지금 추가하라는 게 아닙니다) 
사소하지만 테스트 전체적으로, 좀 더 읽기 쉽게 개행을 활용해 볼수도 있을 것 같아요~! 
생각해보셔도 좋을 것 같습니당

2024-09-11 07:54 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        void fetchByTemplateAndOrdinalFaitWithWrongOrdinal() {
굉장히 꼼꼼한 몰리
굉꼼몰!!

2024-09-11 07:57 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +            var sourceCode2 = new SourceCode(template1, "SourceCode 2", "Content 2", 2);
추후에 고려해보도록 하겠습니다!!

2024-09-12 00:08 UTC, jminkkk approved these changes
롱초롱초님 수고했어요

롱짱

2024-09-12 00:19 UTC, zangsu approved these changes
요구사항 반영 고생하셨습니다~!!! ⚡

2024-09-12 01:23 UTC, kyum-q approved these changes
초롱 짱 ~!

2024-09-12 05:58 UTC, zeus6768 approved these changes

2024-09-12 05:58 UTC, merged

2024-09-12 06:00 UTC, zeus6768 commented on backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
> +        var result = sourceCodeRepository.findAllByTemplate(template1);
> 2번이 잘 이해가 되지 않아서 그런데 조금만 더 자세히 설명해주실 수 있나요?? actual을 사용하면 객체가 여러 개일 때도 일관성을 유지할 수 있다는 게 잘 그려지지 않아서요😅

이전에 미션 하면서 `assertAll()` 썼던 걸 혹시 기억할까요??

테스트 로직에 따라 검증해야할 결과값이 여러 개일 수도 있다는 의미였습니다!