ThumbnailRepositoryTest 구현
woowacourse-teams/2024-code-zap pull request #627
Opened 2024-09-10 08:43 UTC by zeus6768

## ⚡️ 관련 이슈
#620

## 변수명 `sut`
- `ThumbnailRepository` 객체는 `sut`로 변수명을 선언했습니다. SUT는 'System Under Test'의 약자로, 테스트의 대상이 되는 객체를 의미합니다. 
- 테스트에서 선언된 변수명이 많을 때 테스트 대상을 빠르게 찾기 위해 일관된 변수명을 사용합니다. 
- 출처: [단위 테스트](https://m.yes24.com/Goods/Detail/104084175) 56p, 87p.

## 📍주요 변경 사항
- 기존에 Thumbnail 도메인에 대한 레포 테스트가 존재하지 않았습니다. 
- 이에 구현합니다.

2024-09-11 03:49 UTC, kyum-q approved these changes
제 짱 최 ~ 제우스 짱 최고라는 뜻~

2024-09-11 03:56 UTC, HoeSeong123 submitted a review, later dismissed
피드백은 위 피알과 동일합니다ㅎㅎㅎㅎㅎㅎ

2024-09-11 04:51 UTC, zangsu requested changes
고생하셨어요 제우스!!
클래스명을 제외한 리뷰들은 사소한 것들이니 가볍게 읽어 보시고 제우스가 적절히 반영해 주시면 될 것 같아요.

2024-09-11 04:51 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +public class ThumbnailRepositoryTest {
```suggestion
public class ThumbnailJpaRepositoryTest {
```
⚡ 
우리가 테스트를 하는 것은 `ThumbnailRepository` 가 아니라 `JpaRepository` 를 상속하는 `ThumbnailJpaRepository` 이죠.
테스트 하는 클래스를 명확하게 명시해 줄까요?

2024-09-11 04:51 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +    private ThumbnailRepository sut;
아하, 이렇게 사용한다는거군요!
`sut` 의 메서드만 테스트를 하면 되니 알아보기 좋겠네요 👍

2024-09-11 04:51 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +            var thumbnail = new Thumbnail(template, sourceCode);
```suggestion
            var member = memberRepository.save(new Member("Zappy", "password", "salt"));
            var category = categoryRepository.save(Category.createDefaultCategory(member));
            var template = templateRepository.save(new Template(member, "Template Title", "Description", category));
            var sourceCode = sourceCodeRepository.save(new SourceCode(template, "filename", "content", 1));
```
[제안]
Repository 에 저장되기 전의 객체들은 id 값을 가지기 이전이니 변수로 추출할 필요는 없어 보여요.
그렇다고 변수에 재할당을 할 필요도 없어 보여서 각각을 한 줄로 줄여 보았어요.
가볍게 읽어 보시고 제우스의 취향에 맞게 선택해 주시면 좋을 것 같아요!

2024-09-11 04:51 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +                    .hasMessage("식별자 " + id + "에 해당하는 썸네일이 존재하지 않습니다.");
```suggestion
            var notExistId = 100L;

            assertThatThrownBy(() -> sut.fetchById(notExistId)
                    .isInstanceOf(CodeZapException.class)
                    .hasMessage("식별자 " + notExistId + "에 해당하는 썸네일이 존재하지 않습니다.");
```

[제안]
변수 명을 더 명확하게 변경해 보았어요.

2024-09-11 04:51 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +    class DeleteByTemplateId {
"존재하지 않는 id 로 삭제를 해도 예외로 처리되지 않는다." 라는 테스트를 작성해 두는 것은 어떨까요?
+) 테스트 코드는 부가적으로 코드의 명세 기능도 제공해 줄 수 있어요.

2024-09-11 05:01 UTC, zeus6768 commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +public class ThumbnailRepositoryTest {
저는 다음과 같이 생각하는데요. 

여기에 대해 짱수가 어떻게 생각하는지 궁금해요~

[관련 근거](https://github.com/woowacourse-teams/2024-code-zap/pull/626#discussion_r1753118059)

> 저는 짱수와 조금 다른 의견인데요.
> 
> 근거는 다음과 같습니다!
> 
> 1. 클래스 애너테이션에 JPA가 명시되어있음
> 2. 실제로 테스트 대상이 되는 객체는 JPA가 아닌 인터페이스를 사용하고 있음. SourceCodeJpaRepository가 아닌 SourceCodeRepository.
> 3. JPA를 사용하지 않게 되더라도 본 테스트의 본질은 유효함. DB와 데이터를 잘 주고받을 수 있는지! 만약 그렇게 된다면 애너테이션을 제거하고 메서드를 리팩토링하면 됨.

2024-09-11 05:28 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +public class ThumbnailRepositoryTest {
링크 달아 주신 리뷰에도 답변 달아두었지만 보기 쉽게 여기도 옮겨 둘게요!

> 제가 근거를 더 자세히 적어둘 걸 그랬네요. 코멘트 여러번 왔다갔다 하게 해서 미안합니다 ㅠ
>
>제가 해당 부분에 코멘트를 작성한 이유는 다음과 같습니다.
>
>1. 테스트 작성 이유
>우리가 테스트를 작성한 이유 중에는 "JpaRepository 에서 제공하는, 메서드 명으로 만들어 주는 메서드들이 우리의 예상대로 동작하는지 확인하기 위함" 도 존재한다고 생각해요.
>즉, Jpa 라는 환경 때문에 작성되는 테스트라고 생각합니다.
>
>저의 경우 실제로 복잡한 JpaRepository 메서드 명을 사용하면 '제대로 작성한 것이 맞나?' 하는 불안함이 들 때가 있고, 이럴 때 테스트코드가 확신을 줄 수 있다고 생각해요.
>
>2. 빠르게 테스트 코드를 찾을 수 있다.
>아주 사소하지만, 테스트 이름을 클래스 이름과 동일하게 작성해 두면 클래스에서 cmd + shift + t 로 빠르게 테스트코드를 찾아갈 수 있습니다.
>추가되는 메서드에 대해서도 빠르게 테스트코드를 작성할 수 있게 될거에요.

2024-09-11 07:57 UTC, jminkkk requested changes
안녕하세요 제우스~
수고하셨습니다!
코멘트 확인 부탁드려요 🔥

2024-09-11 07:57 UTC, jminkkk commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +            var thumbnail = new Thumbnail(template, sourceCode);
저도 짱수 제안에 한발 올려봅니당...ㅎㅎ

2024-09-11 07:57 UTC, jminkkk commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +            var member = new Member("Zappy", "password", "salt");
픽스처를 사용하지 않은 이유가 있을까요~?

2024-09-11 07:57 UTC, jminkkk commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +        void fetchByTemplateSuccess() {
⚡️ 실패 케이스로 추가해주세요!

2024-09-11 07:57 UTC, jminkkk commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +        void fetchByIdFail() {
> @DisplayName은 형식은 다음과 같다. (ex. 자동차 이름 입력 실패: 쉼표만 입력)

⚡️ [코드 컨벤션](https://github.com/woowacourse-teams/2024-code-zap/wiki/%EB%B0%B1%EC%97%94%EB%93%9C-%EC%BD%94%EB%93%9C-%EC%BB%A8%EB%B2%A4%EC%85%98) 에 작성된 컨벤션을 지켜서 변경해볼까요?

`썸네일 id로 썸네일 조회 실패: 존재하지 않는 id`처럼 변경할 수 있을 것 같아요!

2024-09-12 05:30 UTC, zeus6768 commented on backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
> +        void fetchByTemplateSuccess() {
넘어간다~

2024-09-12 06:01 UTC, kyum-q approved these changes

2024-09-12 06:02 UTC, jminkkk approved these changes
제수짱

제우스 수고했어 짱

2024-09-12 06:25 UTC, HoeSeong123 approved these changes

2024-09-12 06:25 UTC, merged