CategoryRepositoryTest 구현
woowacourse-teams/2024-code-zap pull request #628
Opened 2024-09-10 08:45 UTC by zeus6768

## ⚡️ 관련 이슈
#620

## 📍주요 변경 사항
- 기존에 Category 도메인에 대한 레포 테스트가 존재하지 않았습니다. 
- 이에 구현합니다.

2024-09-11 03:50 UTC, kyum-q approved these changes
초 제 몰 짱 ! (**초**롱초롱한 **제**우스 홀리 **몰**리 하네요 **짱**!)

2024-09-11 03:55 UTC, HoeSeong123 approved these changes
전체적으로 테스트가 깔끔해서 좋네요!! 보고 참고하겠습니다 ㅎㅎㅎㅎ

2024-09-11 05:00 UTC, zangsu requested changes
고생 많으셨습니다 제우스!!
이전 PR 의 코멘트와 동일합니다.
클래스 명 이외에는 편하게 확인 부탁드려요~~

2024-09-11 05:00 UTC, zangsu commented on backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
> +public class CategoryRepositoryTest {
```suggestion
public class CategoryJpaRepositoryTest {
```
⚡ 
이전 PR 의 리뷰와 동일합니다.
우리가 테스트 하는 객체를 명확하게 명시해 주면 좋을 것 같아요

2024-09-11 05:10 UTC, zeus6768 commented on backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
> +public class CategoryRepositoryTest {
저는 다음과 같이 생각하는데요. 

여기에 대해 짱수가 어떻게 생각하는지 궁금해요~

[SourceCodeJpaRepository 테스트 구현 PR](https://github.com/woowacourse-teams/2024-code-zap/pull/626#discussion_r1753118059)

> 저는 짱수와 조금 다른 의견인데요.
> 
> 근거는 다음과 같습니다!
> 
> 1. 클래스 애너테이션에 JPA가 명시되어있음
> 2. 실제로 테스트 대상이 되는 객체는 JPA가 아닌 인터페이스를 사용하고 있음. SourceCodeJpaRepository가 아닌 SourceCodeRepository.
> 3. JPA를 사용하지 않게 되더라도 본 테스트의 본질은 유효함. DB와 데이터를 잘 주고받을 수 있는지! 만약 그렇게 된다면 애너테이션을 제거하고 메서드를 리팩토링하면 됨.

2024-09-11 05:29 UTC, zangsu commented on backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
> +public class CategoryRepositoryTest {
중복되는 논의일 것 같으니 [초롱의 PR](https://github.com/woowacourse-teams/2024-code-zap/pull/626#discussion_r1753086683) 에서 논의 이어서 진행하시죠 ㅎㅎ

2024-09-11 08:12 UTC, jminkkk requested changes
안녕하세요 제우스
수고하셨어요🔥

코멘트 확인 부탁 드립니당

2024-09-11 08:12 UTC, jminkkk commented on backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
> +        @DisplayName("성공: id로 카테고리를 조회할 수 있다.")
⚡️ 이전 pr에 작성한 코멘트와 동일한 이유로 컨벤션 확인해주세요!

2024-09-11 08:12 UTC, jminkkk commented on backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
> +            assertThat(actual).containsExactly(category1, category2, category3);
member가 아닌 다른 사람이 작성한 카테고리도 하나 저장하면 ByMember가 적용된 것을 명시적으로 알 수 있겠어요

2024-09-11 08:12 UTC, jminkkk commented on backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
> +        @DisplayName("실패: 일치하는 카테고리가 없을 경우")
⚡️ 이 케이스는 실패는 아닌 것 같다는 생각인데, 제우스의 의견이 궁금해요~!
제가 생각하는 실패는 목적을 달성하지 못했을 때에 가까운 것 같아요

예를 들어 fetchBy는 카테고리를 꼭 반환해야 하는 메서드이기 때문에 예외가 발생한다면, 반환하지 못해 실패 케이스라고 할 수 있지만,
이 메서드의 목적은 여부를 확인하는 것이기 때문에 "여부를 조회하는 것"은 성공한 것 이라는 생각이 드네유,,

즈후의 의견이 궁금해요~

2024-09-12 05:45 UTC, zeus6768 commented on backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
> +    class FindAllByMemberOrderById {
다음의 두 가지 이유로 그렇게 작성했습니다~!

### 1. 일관성
다른 테스트에서 메서드마다 `@Nested` 테스트 클래스를 선언했습니다. 같은 형식으로 작성하면 읽기 더 쉬운 코드가 된다고 생각해요. 

### 2. 확장성
지금은 코드를 간단히 작성해서 테스트 메서드가 하나밖에 존재하지 않습니다. 다만 실패 케이스가 얼마든지 추가될 수 있고, 테스트 케이스 추가를 위해 `@ParameterizedTest`등을 적용한다면 해당 클래스 내부에 테스트케이스를 만드는 정적 메서드를 사용해야 할텐데, 그렇다면 클래스로 미리 나누어져 있는 게 코드를 읽기 더 쉬울 것 같습니다.

2024-09-12 05:54 UTC, zeus6768 commented on backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
> +        @DisplayName("실패: 일치하는 카테고리가 없을 경우")
저도 성공이라고 생각해요!! 좋은 의견 땡큐 몰리~

2024-09-12 06:01 UTC, kyum-q approved these changes
제짱~

2024-09-12 06:03 UTC, zangsu approved these changes
요구사항 반영 고생 많으셨어요~~! ⚡

2024-09-12 06:26 UTC, HoeSeong123 approved these changes

2024-09-12 08:20 UTC, jminkkk approved these changes

2024-09-12 08:21 UTC, merged