Template Repository단 테스트 작성
woowacourse-teams/2024-code-zap pull request #629
Opened 2024-09-10 09:06 UTC by jminkkk

## ⚡️ 관련 이슈
close #620

## 📍주요 변경 사항
### 1. Template Repository단 테스트 작성

2024-09-11 03:53 UTC, kyum-q requested changes
초 제 몰 짱 ! (초롱초롱 제기발랄초 제 몰 짱 ! (**초**롱초롱 **제**(재)기발랄 **몰**리 **짱** !)

간단한 코멘트 남겨놨어요 확인 부탁드려요 ~

2024-09-11 03:53 UTC, kyum-q commented on backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
> +    @DisplayName("카테고리 식별자로 템플릿 존재 여부 확인")
⚡ 저희 코드 컨벤션으로 정했던 "성공 : ~" "실패 : ~ " 형식으로 변경해주세요 ~

2024-09-11 03:53 UTC, kyum-q commented on backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
> +
해당 줄바꿈이 없으면 given/when/then 을 더 구분하기 쉬울 것 같아요 ~

2024-09-11 05:10 UTC, zangsu requested changes
몰리~~ 고생 많으셨어요!!
테스트를 찾지 못한 메서드에 대한 코멘트만 남겨 두었으니 확인 부탁드려요!

2024-09-11 05:10 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
> +class TemplateJpaRepositoryTest {
⚡ 
`existsByCategoryId` 이외의 메서드를 테스트 하지 않은 이유가 있을까요??
혹시나 어딘가 이유가 적혀있을까봐 PR 과 이슈 본문, comment 확인해 봤는데 안보이네용...ㅎㅎ

2024-09-11 05:10 UTC, zangsu commented on backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
> +class TemplateJpaRepositoryTest {
`findAll()` 메서드는 `TemplateRepositoryFindAllTest` 에 작성되어 있군요!
이젠 실제 `JpaRepository` 를 상속하는 `TemplateJpaRepository` 에 대한 테스트가 작성되었으니 이곳으로 테스트 메서드를 옮겨도 좋을 것 같아요.

`findByMemberId()`, `fetchById()` 메서드에 대한 테스트를 함께 작성해 주면 좋을 것 같아요.

2024-09-11 05:15 UTC, HoeSeong123 approved these changes
필요한 피드백은 다 작성된 것 같네요! 고생하셨습니
다👍

2024-09-11 13:11 UTC, jminkkk commented on backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
> +        void setUp() {
흠 이 부분이 뭔가 마음에 들지 않는데, 검색인만큼 조건을 확인할 수 있는 데이터들이 저장되어 있어야해서 최선인 것 같네요...
좋은 아이디어 있으시면 피드백 부탁드려요!

2024-09-11 18:05 UTC, zeus6768 submitted a review, later dismissed
훌륭한 테스트코드 잘 봤어요 🚀

2024-09-11 18:05 UTC, zeus6768 commented on backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
> +        void setUp() {
저도 켬미와 같은 의견입니다!

2024-09-12 01:33 UTC, kyum-q approved these changes
GOOD 👍

2024-09-12 01:35 UTC, zangsu approved these changes
요구사항 반영 하느라 고생 많으셨어요 몰리!!! ⚡

2024-09-12 04:02 UTC, HoeSeong123 approved these changes
고생하셨습니다 몰리 👍

2024-09-12 06:01 UTC, zeus6768 approved these changes

2024-09-12 06:01 UTC, merged