Member Service 테스트
woowacourse-teams/2024-code-zap pull request #646
Opened 2024-09-15 06:57 UTC by kyum-q

## ⚡️ 관련 이슈
close #645 

## 📍주요 변경 사항
MemberService Test 보충 및 MemberServiceTest 실제 DB 사용으로 변경

## 🎸기타
Repository 단에서 나는 에러 처리도 서비스 테스트에서 확인하는게 맞을지 의문이 들긴합니다.
일단 추가하긴했는데 함께 고민하면 좋을 것 같아요 여러분들의 의견은 어떤가요?

2024-09-16 12:06 UTC, zangsu reviewed
크게 변경을 요구해야 할 만한 부분이 없네요!
꼼꼼하게 테스트 잘 작성해 주셨습니다!!!
코멘트 한번씩 확인 부탁드려요~

2024-09-16 12:06 UTC, zangsu commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
[고민]
이건 리뷰라기 보단, 이 부분과 관련된 고민을 다 같이 나누어 보고 싶어서 다는 코멘트입니닷!

이전에 제가 테스트를 짜면서 고민했던 부분이기도 한데, "아직 저장되지 않은 정보" 라는 것을 어떻게 해야 잘 표현할 수 있을지 모르겠네요.

현재 켬미는 `memberRepository.save()` 메서드를 호출하지 않음으로써 저장되지 않은 멤버를 나타내고 있는 것 같아요.
그런데 "저장하는 코드가 없다" 라는 것이 한 눈에 보이지는 않는 것 같아요.
Fixture 를 가져오는 시점에서 이미 DB 에 저장되어 있는 정보를 가져오는 것인지 파악을 하기도 어려운 것 같고요.

그렇다고 `long notSavedId = 100L` 처럼 작성을 할까 하니, `100L` 이라는 값을 정말 저장되지 않은 값으로 써도 되는가? 에 대한 고민이 들기도 하네요.
하나의 member 정보를 저장한 후 그 id 값 + 1 을 하는 것 역시 위와 같이 값의 사용에 대한 고민이 들고요.

어떤 방법이 최선인걸까요? 🤔

2024-09-16 14:59 UTC, kyum-q commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
>          void findMember() {
생각해보니 Nested 클래스를 클래스로 생각안했었네요 !
현재 테스트 코드는 변경했습니다 !

> (앞으로 이런 상황에 어떻게 해야할까요??? 이미 이전에 머지시켰던 내역이니 언급하지 않는 것이 맞을까요???)

언급하는 게 좋을 것 같아요 ! 그리고 수정하지 못한 레포지토리 테스트는 이슈로 따로 파놓고 추후에 수정하는 식으로 하는건 어떨까요? 😊

2024-09-16 15:01 UTC, kyum-q commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
네 해당 부분은 서비스 단에서는 예외처리 로직이 존재하지 않고, 레포지토리 단에 예외 로직이 있어요 !
그래서 추가할까 고민했었습니다 !
짱수 의견 말해줘서 고마워요 ~ 저도 동의합니다 !

2024-09-16 15:03 UTC, kyum-q commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
짱수 의견처럼 3가지 방법이 있는 것 같아요

1. memberRepository.save() 메서드를 호출하지 않음
2. long notSavedId = 100L 처럼 저장되지 않을 것 같은 id 사용
3. member 정보를 저장한 후 그 id 값 + 1 을 하는 것

고민이 많이 되고 테스트 코드 작성할 때 세개 다 써본 것 같네요 ! 굳이 고르자면 저는 2번이 가장 괜찮은 것 같네요 ! (순위를 매기자면 2 -> 1 -> 3 순으로 좋은 것 같아요)

2024-09-16 15:36 UTC, HoeSeong123 requested changes
고생하셨습니다 켬미.
여전히 작업이 빠르네요.
추석은 잘 보내고 있죠?

피드백 남긴 건 거의 없고, 사소한 질문 몇 가지 남겼습니다. 확인 후 답변 부탁드려요!

2024-09-16 15:36 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +@SpringBootTest
(질문) 랜덤포트를 사용하지 않는 이유가 있나요?

2024-09-16 15:36 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
저도 짱수 의견에 동의합니다.
테스트 코드는 문서화와 같다고 생각해요. 해당 메서드를 실행했을 때 어떤 오류들이 발생할 수 있는지를 나타내는 것 또한 문서화의 일종이기 때문에 해당 테스트 코드가 전혀 어색하지 않다고 생각합니다.

2024-09-16 15:36 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
정확한 이유는 아직 잘 모르겠기는 한데 해당 어노테이션 때문에 발생하는 오류로 보입니다.

해당 어노테이션은 어떤 어노테이션인가요?
간단히 찾아보았을 때는 테스트를 할 때 실제 데이터베이스를 사용하게 해주는 설정이라고 하는데, 해당 설정이 없어도 실제 데이터베이스를 사용하고 있지 않나요??

잘 몰라서 질문 남깁니다

2024-09-16 15:36 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
매 테스트마다 데이터베이스가 초기화가 되고 있다는 것을 안다는 전제하에 2번의 방법이 가장 적절하지 않을까요?
`매번 DB가 초기화 된다는 사실을 어떻게 알 수 있냐`라고 생각할 수 있지만, 애초에 그건 잘못된 테스트라고 생각합니다.
해당 테스트 코드에서 저장하는 코드가 없다는 것만으로도 `long notSavedId = 100L`이 저장되지 않은 정보라는 것을 쉽게 알 수 있을 것 같아요.

비슷한 이유로 저희가 `@BeforeEach`에 데이터를 저장하는 로직을 사용하지 않았다고 할 수 있겠네요.

2024-09-16 15:36 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +            assertThatCode(() -> memberService.getByTemplateId(100L))
```suggestion
            Long notSavedId = 100L;
            
            assertThatCode(() -> memberService.getByTemplateId(notSavedId))
```

사소하지만 확인하고 싶은 id도 별도의 변수로 빠져있으면 좋을 것 같습니다.

2024-09-16 15:37 UTC, kyum-q commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +@SpringBootTest
CI 테스트가 되지 않는 이유를 찾다가 RAMDOM_PORT 문제로 발견해서 방금 눈물 뚝뚝 흘리면서 변경했어요 ㅜㅜ

PR 본문에 이유 적어두었습니다 확인해주세요 ~!

2024-09-16 15:40 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +@SpringBootTest
어 리뷰 달 때만 해도 저런 내용 없었는데ㅋㅋㅋ수정됐었군요.
확인했습니다. 이거 정확한 이유를 좀 찾아봐야겠네요

2024-09-16 15:53 UTC, kyum-q commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
실제로 찾아보니 해당 어노테이션은 없어도 될 것 같아요 !

위에 실제 DB를 사용하지 않는다는 조건은 `@DataJpaTest` 테스트 시에만 유효하네요 ! 그래서 `@DataJpaTest` 이 아니라면 db.yml 설정에 맞게 실제 DB를 사용한다고 합니다 ! 

서치 해보면 해당 어노테이션은 `@DataJpaTest`에서 사용하더라고요 !
그래서 ChatGPT 선생 도움을 받아보니 다음과 같다고 하네요 !

---

##### `@DataJpaTest`와 `@AutoConfigureTestDatabase`
`@DataJpaTest`는 JPA 관련 테스트만을 실행하기 위해 데이터 레이어만 컨텍스트에 로드합니다. 테스트 환경에서 JPA 기능(리포지토리, 엔티티 등)만 테스트하려는 경우에 사용됩니다.
기본적으로 Spring Boot는 `@DataJpaTest`를 사용하면 임베디드 데이터베이스(예: H2)를 자동으로 사용하도록 설정합니다.
이때 실제 데이터베이스(MySQL, PostgreSQL 등)를 사용하고 싶으면 `@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)`를 추가하여 임베디드 데이터베이스로 대체되지 않도록 설정하는 것입니다.

##### `@SpringBootTest`에서는 왜 설정하지 않아도 되는가?
`@SpringBootTest`는 애플리케이션의 모든 빈을 로드하여 전체 애플리케이션을 통합적으로 테스트합니다.
이 경우 Spring Boot는 application.yml 또는 application.properties 파일에 정의된 실제 데이터베이스 설정을 그대로 사용합니다. 즉, `@SpringBootTest`는 임베디드 데이터베이스로 대체되지 않고, 실제 데이터베이스 설정을 따릅니다.
따라서, 별도로 `@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)`를 지정할 필요가 없습니다.

##### 요약
- `@DataJpaTest`: JPA 관련 테스트에서 임베디드 데이터베이스 사용을 방지하려면 `@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)`를 추가해야 함.
- `@SpringBootTest`: 실제 application.yml 설정을 따르기 때문에, 임베디드 DB로 대체되지 않고 별도의 설정이 필요 없음.

2024-09-16 15:55 UTC, HoeSeong123 commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
오호 좋은 정보 감사합니다 👍

2024-09-17 06:44 UTC, jminkkk requested changes
본문의 문제는 RandomPort일 때 flyway 버전 체크 때문에 발생하는 문제인거죠?
테스트 시에는 버전 관리가 필요하지 않으니 flyway를 비활성화하는 게 맞는 것 같아요.

코멘트 남겼으니 확인 부탁드려용
짱짱 수고했어요 🔥

2024-09-17 06:44 UTC, jminkkk commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +            assertThatThrownBy(() -> memberService.assertUniqueName(memberName))
`회원가입 실패: 아이디 중복` 경우 처럼 이 부분도 일관성 있게 작성해도 좋을 것 같아요.
또 메서드 내부 변수 할당이 크게 가독성에 영향을 끼치지 않아서 추출하지 않아도 될 것 같아요

```
Member savedMember = memberRepository.save(MemberFixture.memberFixture());

assertThatThrownBy(() -> memberService.assertUniqueName(savedMember.getName()))
```

2024-09-17 06:44 UTC, jminkkk commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
저도요~ 
모두와 동일하게 생각해요~

[고민]

그래서 테스트를 작성하고 리뷰를 작성하다가 의문이 드는 게 있어요.
테스트에 대한 이야기는 아니지만,,, 테스트를 보다가 생긴 의문이라 공유할게요~

바로 이전 `회원가입,` `아이디 중복 검사` 테스트에서 아이디 길이나, 비밀번호 길이와 같은 부분은 검증되어 있지 않아요.(다른 도메인의 서비스에서도 마찬가지)
아마 Controller에서 검증을 하고 있기 때문에 작성되어 있지 않는 것 같아요.

그런데 읽다보니 어색하더라구요~
저는 아이디 길이나, 비밀번호 길이이도 우리 애플리케이션 고유의 요구사항이 비즈니스 로직이라고 생각해요. 
따라서 우리 서비스에서 검증이 필요하다고 생각해요. 
(그렇다고 null 체크도 검사하자는 것은 아닙니다. null 체크는 어떤 애플리케이션이든 필요하고 우리 서비스만의 규칙이 아님. 근데 아이디 길이를 8~20자로 제한한다든지, 비밀번호에 특수문자를 꼭 넣어야 한다든지 하는 건 우리 서비스만의 특별한 규칙이라고 생각)

여러분들의 의견이 궁금한 것이 있어요. (의견이 많이 갈릴 것 같은데 쓰읍)

1. Controller 에서 검증을 하고 있지만, 이 부분은 Service에서 검증이 필요하지 않을까요?
2. (않다면) 이 부분은 도메인 규칙이 아닐까요?0?
3. (않다면2) 여러분이 생각하는 Controller와 Service의 역할, 나아가 Presentation Layer, Business Layer의 역할은 무엇일까요?

2024-09-17 06:44 UTC, jminkkk commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        @Test
⚡️ 일관성 있게 한줄 띄어주세용

2024-09-17 06:44 UTC, jminkkk commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +            boolean isDefaultCategory = categoryRepository.existsByNameAndMember("카테고리 없음", member);
```suggestion
            boolean existsDefaultCategory = categoryRepository.existsByNameAndMember("카테고리 없음", member);
```
변수명을 조금만 수정해보면 의미가 좀 더 명확해질 것 같아요

2024-09-17 09:55 UTC, zangsu commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
@jminkkk 
오, 저도 비슷한 생각을 헀다가 놓쳤네요. 
저도 동일하게 도메인 규칙이고, 비즈니스 로직이라 생각해요.
Service 부분에서의 검증이 진행되는 것이 이상적이며, 우리 서비스에서도 동일하게 적용할 수 있다고 생각합니다.

+) 
저는 Controller 의 검증 (즉, DTO 가 스스로 검증) 과 도메인에서의 검증 중 하나만 선택하라면 후자를 선택할 것 같아요.
도메인 검증은 추가하는 것이 좋겠네요

2024-09-17 10:19 UTC, HoeSeong123 commented
이 브랜치 혹시 어디서 분기하신건가요??
현재 깃허브에 올라가있는 dev/be 코드와 다른 부분이 있는 것 같습니다.
제가 확인한 코드는 `MemberFixture` 클래스입니다.
확인 부탁드려요.

2024-09-17 12:28 UTC, kyum-q commented
> 이 브랜치 혹시 어디서 분기하신건가요??
> 
> 현재 깃허브에 올라가있는 dev/be 코드와 다른 부분이 있는 것 같습니다.
> 
> 제가 확인한 코드는 `MemberFixture` 클래스입니다.
> 
> 확인 부탁드려요.

@HoeSeong123 

bev/be 에서 분기했습니다 그리고 MemberFixture 의 변경 사항이 있다면 변경이 잡히지 않은 점이 이산하네요..! 어떤 부분에서 MemberFixture 가 다르다고 생각하셨나요? 
현재 MemberFixture가 두개 있습니다 그 둘 중에 무엇이 다르다고 하시는건가요?

+ MemberFixture는 나중에 하나로 통일하면 좋을 것 같으니 몰리 파놓은 이슈에 해당 내용 추가해놓겠습니다

2024-09-17 12:41 UTC, HoeSeong123 commented
아 member 패키지 안에 `MemberFixture`가 또 있었군요;; 확인했습니다.
목요일에 당장 하나로 합쳐야겠네요.

2024-09-19 11:31 UTC, zeus6768 requested changes
켬미 최고~! 테스트하면서 고민을 많이 했네요 😭

반영될 내용이 있는 것 같아 RC 하고 갑니당

2024-09-19 11:31 UTC, zeus6768 commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
>          @DisplayName("회원 정보 조회 실패: 본인 정보가 아닌 경우")
`정보` 대신 더 명시적으로 ID라고 하는 건 어떨까요?

2024-09-19 11:31 UTC, zeus6768 commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
@jminkkk
@zangsu 

저는 조금 다르게 생각하는 부분이 있어요. 

1. Service에서 검증할 필요 없다고 생각합니다. 
2. 도메인 규칙이 맞습니다. 

Service 계층에서 도메인 검증을 테스트할 필요 없다고 생각해요.  

도메인 객체의 검증 로직은 도메인의 테스트 코드를 만들어서 테스트해야 하지 않을까요?

DTO에 검증 로직이 들어갔다면 DTO 테스트 코드를 만들어야 한다고 생각해요. 

그렇게 하면 서비스 테스트의 부담이 줄어들 것 같네요. 

결론은 도메인 테스트와 DTO 테스트를 추가해야 한다 입니다~!

다른 의견 있다면 얼마든지 부탁해용

2024-09-19 11:31 UTC, zeus6768 commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
저도 2번 방법이 좋다고 생각해요~!

2024-09-19 15:59 UTC, kyum-q commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
모두 맞는말이라 어렵네요 ~
이런 모든 고민은 'Service 단에서 어디까지 테스트할 것인가'의 고민인 것 같네요. 

레포지토리 예외처리도 처리한다, 하위 서비스 예외처리도 처리한다, 도메인 검증도 처리한다.
이 모두 결국엔 현재 테스트에 파생되는 모든 검증, 예외 로직을 처리할 것인가에 대해 정확하기 이야기 안되서 인 것 같아요.

그래서 가장 큰 틀로 오늘 조금 이야기 한 주제인 '서비스 테스트는(이 외에도) 어디까지 테스트를 고려할 것인가?'에 대해 이야기해보면 좋을 것 같아요 ~
1. 해당 서비스 단에서 하는 로직만 테스트 구현한다 (하위 서비스 단 로직, 도메인 로직은 고려하지 않는다)
2. 헤당 서비스와 연관된 클래스 로직도 고려해서 테스트 구현한다. 
    - 레포지토리단 예외 처리
    - 하위 서비스 예외 처리
    - 도메인 검증

이번 계기로 생각해보니 저는 1번 방식을 선호합니다. 그렇지 않으면 로직을 분리할수록 중복되는 테스트 코드가 너무 많아질 것 같아요.
그래서 블랙박스 테스트로 연관된 클래스를 고려하지 않고, 해당 클래스와 해당 클래스의 용도만 생각했을 때 실패 케이스를 작성하는 방식으로 테스트를 구현하는 것이 좋을 것 같아요 ~

2024-09-19 16:05 UTC, kyum-q commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +            assertThatThrownBy(() -> memberService.assertUniqueName(memberName))
![image](https://github.com/user-attachments/assets/3b47cc01-c146-4450-af12-9069b1ec679f)

변수 추출 하지 않으면 경고 표시 뜨는게 싫어서 분리했었습니다 ~
하지만 결국엔 경고고,, 사소하니,, 몰리 말처럼 추출하지 않는 방법으로 수정하겠습니다 ~

2024-09-19 16:09 UTC, kyum-q commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
> Controller 에서 검증을 하고 있지만, 이 부분은 Service에서 검증이 필요하지 않을까요?

직접적으로 도메인 검증 로직을 호출하는 서비스에서는 처리해야하고, 위에 말했듯이 직접 사용하지 않는 상위 서비스에서는 하지 않아도 될 것 같습니다.

> (않다면) 이 부분은 도메인 규칙이 아닐까요?0?

도메인 규칙은 맞는 것 같아요 
Dto와 도메인 두군데에서 중복 검증해야할 것 같네요 

> (않다면2) 여러분이 생각하는 Controller와 Service의 역할, 나아가 Presentation Layer, Business Layer의 역할은 무엇일까요?

컨트롤러는 요청을 받아 넘겨주고 반환하는 역할, 서비스는 받은 요청에 따른 비즈니스 로직을 처리하는 역할이라고 생각합니다.

2024-09-20 05:02 UTC, jminkkk commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +            assertThatThrownBy(() -> memberService.assertUniqueName(memberName))
omg 그랬었군요 🥲

2024-09-20 05:08 UTC, HoeSeong123 approved these changes
변경사항 확인했습니다.
고생하셨습니다 켬미~~

2024-09-20 05:08 UTC, zeus6768 approved these changes
👍

2024-09-20 06:50 UTC, jminkkk approved these changes
켬신
켬미는 신이야

2024-09-20 10:10 UTC, zangsu commented on backend/src/test/java/codezap/member/service/MemberServiceTest.java
> +        }
앗 저도 제우스 의견에 더 가깝네요.
도메인의 예외 처리에 대한 테스트는 도메인 테스트에서 확인을 하면 될 것 같군요.
추가적인 예외처리가 있는 경우에만 서비스 테스트에서 추가 확인을 해 주어도 될 것 같아요~

켬미가 고정해 준 이야기 주제에선 저도 1번 방법을 선호합니다!

2024-09-20 10:15 UTC, merged