SourceCodeService 테스트 추가
woowacourse-teams/2024-code-zap pull request #653
Opened 2024-09-16 14:12 UTC by jminkkk

## ⚡️ 관련 이슈
close #645

## 📍주요 변경 사항
1. 생성, 삭제, 조회, 수정 등에 대한 테스트 작성

## 🎸기타
1. 테스트를 하면서 로직이 이상한 경우 또는 검증이 되어있지 않는 경우가 다수 있었습니다. 해당 pr은 테스트에 대한 것이기 때문에 main 로직의 수정이 필요한 경우에 대해서는 우선 작성하고 @Disable 처리를 해놓았습니다.

이슈 #650 에 여러가지 문제 사항들을 정리를 해두었으니 확인 부탁드립니다.

2. 또 현재 소스 코드 수정 로직이 복잡합니다. (매우)

열심히 작성했지만 놓친 엣지 케이스나 잘못 작성된 부분이 있다면 알려주세요~

2024-09-17 13:37 UTC, zangsu reviewed
예외 상황들을 정말 꼼꼼하게 잘 추가해 주셨네요~~ 👍 
몇가지 제안 사항 남겨 두었으니 확인해 주세요~~

2024-09-18 10:04 UTC, kyum-q requested changes
안녕하세요 몰리 ~ 즐거운 추석 보냈나요 ~
다양한 실패 케이스까지 추가한 거 완전 굿 👍 수고하셨어요 😊

junit 사용에 관한 코멘트 남겼어요 확인해주세요. 그리고 개행 처리가 자동으로 예쁘게 안되죠..ㅜㅜ 스타일을 다시 건들던가 해야겠네요 ! 개행 처리에 관한 코멘트도 몇가지 남겨뒀습니다.

2024-09-19 07:47 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class CreateSourceCodes {
정확히 어떤 코드에서 픽스처 사용이 필요해보이는지 궁금해요! 🥲
SourceCodeFixture는 SourceCode 엔티티를 반환하는데, 생성 부분에서는 SourceCode 엔티티가 필요없지 않나요?0?

2024-09-19 07:49 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +        @DisplayName("실패: 순서가 1부터 시작하지 않는 코드")
소스 코드를 말한 건데 `실패: 순서가 1부터 시작하지 않는 소스 코드` 혹시 이렇게 변경해도 애매할까요~?
도메인 용어라 괜찮을 것 같은데 어떤가요?

2024-09-19 07:52 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +        @DisplayName("실패: 순서가 1부터 시작하지 않는 코드")
소스 코드로 변경하니 좋네요 ~ 굿 !

2024-09-19 07:54 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class CreateSourceCodes {
어마맛 생성 로직에서 사용하는 건 CreateSourceCodeRequest 군요 .. 마이 미스테이크 .. 암 쏘 쏘리 벗 알러뷰 ~

2024-09-19 07:58 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +                    () -> assertEquals(2, sourceCodes.get(1).getOrdinal()));
흠 저는 상황에 따라 작성해도 된다고 생각했어요~
그렇다면 assertAll도 junit 코드인데 제거해야 할까요~? 제거를 한다면 켬미가 작성해준 코멘트와 정확하게 반대로 갈 것 같기도 하네요

```java
import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
```

assertEquals도 틀린 테스트에 경우 무엇이 다른지 보여주긴 하구요
![image](https://github.com/user-attachments/assets/1d0d6771-57c6-4bef-af0c-6ad587ce20c9)

---

하지만.............
사소하기 때문에 변경하겠습니다.

2024-09-19 08:00 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +                    () -> assertEquals(2, sourceCodes.get(1).getOrdinal()));
놉 사소하기 때문에 변경하지 않아도 돼요 ㅋㅋㅋㅋㅋ 
그냥 여기저기 의견이 궁금했을 뿐 ! 몰리 의견 이해 됐습니다 변경 안하셔도 되용~

2024-09-19 08:17 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +            assertThatList(sourceCodeService.findSourceCodesByTemplate(template)).containsExactly(sourceCode1,
새롭게 알게된 메서드인데, List가 명확하게 사용해봤습니당
수정할게요~!

2024-09-19 08:32 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +        }
더불어 소스 코드 전체 삭제가 불가능한 것도 추가되어야겠네요~!
이슈에 추가해놓겠습니답

2024-09-19 08:36 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +        @DisplayName("실패: 템플릿에 해당하는 소스 코드가 존재하지 않음")
> 템플릿에 소스코드가 아무것도 존재하지 않는다.
템플릿에 원하는 순서의 소스코드가 존재하지 않는다.

켬미 설명이 맞아요.
흠 그런데 당장에 검증할 수 없긴 하네요... 🥲
일단 이슈에 적어두고 제거하겠습니다..!

2024-09-19 08:37 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +        }
너무 자세하게 검증보단 필요한 것만 하는게 더 낫겠네요~ ㅎㅎ
변경하겠습니다!

2024-09-19 11:43 UTC, HoeSeong123 requested changes
고생하셨습니다 몰리!!
소스 코드가 우리 서비스의 중심이 되는 부분이라 테스트할 부분이 굉장히 많았는데 정말 잘해주셨네요.
역시 꼼꼼몰리
꼼몰 최고!!
아주 간단한 피드백 몇 개 남겼습니다. 놓칠 수도 있을까봐 보이는 부분마다 집어놔서 반복되는 피드백들도 많습니다ㅎㅎ
고생하셨습니다.

2024-09-19 11:43 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class CreateSourceCodes {
소스 코드의 순서가 올바른지에 대한 검증도 필요할 것 같습니다!
예를 들면 1, 3, 4 이런 식으로 오는 경우에 대한 예외처리입니다.

2024-09-19 11:43 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +                    () -> assertThat(sourceCodeService.getByTemplateAndOrdinal(template, 1)).isEqualTo(sourceCode1));
일부러 순서 뒤집어서 검사하는 꼼꼼함 👍
꼼꼼몰리
꼼몰

2024-09-19 11:43 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class getByTemplateAndOrdinal {
(고민) 저희 코드 로직상 같은 순서의 소스코드가 테이블에 추가되는 경우(템플릿 업데이트시)가 있습니다. 
물론 추가됐다가 바로 사라지기는 하지만 중복된 순서에 대한 검증도 필요하지 않을까요?
`fetchByTemplateAndOrdinal`를 할 때는 반드시 모든 소스코드가 중복되지 않은 순서를 가지는 것을 보장해야 할 것 같습니다.

2024-09-19 11:43 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class getByTemplateAndOrdinal {
```suggestion
    class GetByTemplateAndOrdinal {
```

2024-09-19 11:43 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class findSourceCodesByTemplate {
```suggestion
    class FindSourceCodesByTemplate {
```

2024-09-19 11:43 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class updateSourceCodes {
```suggestion
    class UpdateSourceCodes {
```

2024-09-19 11:43 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class deleteByIds {
```suggestion
    class DeleteByIds {
```

2024-09-19 11:43 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +                            "새로운 제목1"),
줄바꿈이 조금 어색한 것 같아요. 이런 줄바꿈은 어떤가요? 사실 둘 다 좀 어색한 거 같아서 이건 몰리 편한대로 정해주세요~~
```suggestion
                    () -> assertThat(sourceCodeRepository.fetchByTemplateAndOrdinal(template, 2).getFilename())
                    .isEqualTo("새로운 제목1"),
```

2024-09-19 11:43 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +                            "새로운 제목3")
똑같은 줄바꿈 피드백인데 놓칠까봐 잡아놓습니다! 마찬가지로 선택은 몰리가 편한대로!!
```suggestion
                    () -> assertThat(sourceCodeRepository.fetchByTemplateAndOrdinal(template, 1).getFilename())
                    .isEqualTo("새로운 제목3")
```

2024-09-19 13:30 UTC, zeus6768 requested changes
고생 많았어요 몰리~!! 꼼몰짱

`@DisplayName` 전반에 대해 다음의 피드백을 적용해주세요 😁

![image](https://github.com/user-attachments/assets/e38c6b9f-2dc6-43c9-bf9e-793e2f2e5b60)

2024-09-20 00:25 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class CreateSourceCodes {
Wowowowo 꼼초;;;;;

생각하지도 못했네요 🔥
추가했습니다 심지어 검증 코드가 없나봐요 대박~
이슈에도 추가해놓을게요

2024-09-20 00:35 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class getByTemplateAndOrdinal {
> fetchByTemplateAndOrdinal를 할 때는 반드시 모든 소스코드가 중복되지 않은 순서를 가지는 것을 보장해야 할 것 같습니다.

혹시 이 부분이 조금 이해가 안되는데 어떤 경우가 있을지 설명해줄 수 있나요~?
특정 Template의 모든 소스코드를 fetchByTemplateAndOrdinal 해서 Ordinal 를 체크해야 한다는 것일까요?

2024-09-20 02:27 UTC, jminkkk commented
> 고생 많았어요 몰리~!! 꼼몰짱
> 
> `@DisplayName` 전반에 대해 다음의 피드백을 적용해주세요 😁
> 
> ![image](https://private-user-images.githubusercontent.com/81848498/369006615-e38c6b9f-2dc6-43c9-bf9e-793e2f2e5b60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTg4NzEsIm5iZiI6MTcyNjc5ODU3MSwicGF0aCI6Ii84MTg0ODQ5OC8zNjkwMDY2MTUtZTM4YzZiOWYtMmRjNi00M2M5LWJmOWUtNzkzZTJmMmU1YjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAyMTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5OTI1ZjgzNmVlNDgyNWNmMjMxOTAxNjNkZjM1YzYwZmNjZjczOGE1OTBkMDczODM0NzBjODAwMjg4NDY1YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.soeH8gNfHplp25FUt7KroZN72BYt4Cb6ru9sX8XYENQ)

안녕하세요 제우스
직전 레포지토리 테스트 때의 코멘트군요.
당시 논의 때 테스트 코드에서 @Nested 사용 시 @DisplayName의 말투나, @Nest의 DisplayName을 중복으로 작성할 것인지는 자율로 하기로 결정했었던 걸로 기억합니다.

이 pr을 포함해 다른 pr에도 비슷하게 작성되어 있어서 저 이미지와 완전하게 동일한 형식으로 가려면 다시 논의를 해야할 것 같아요.

2024-09-20 05:27 UTC, zeus6768 approved these changes
몰리 정말 고생 많았어요! 👍👍

DisplayName 컨벤션은 크루들과 한 번 더 가볍게 얘기하면 좋겠네요!

2024-09-20 05:54 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +    class getByTemplateAndOrdinal {
아닙니다. 이 부분은 꽤 복잡한 수정이 들어갈 것 같네요...

2024-09-20 05:59 UTC, HoeSeong123 approved these changes
확인했습니다!!
어려운 테스트코드였을 거 같은데 고생하셨습니다~~

2024-09-20 09:30 UTC, kyum-q approved these changes
몰리 짱 수고하셨어요 !!

2024-09-20 10:05 UTC, zangsu commented on backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
> +        }
앗, 따로 비교 메서드를 만드는 것에 대한 제안이었긴 한데~~~
필요한 필드만 확인하는 것도 나쁘지는 않은 것 같습니닷

2024-09-20 10:06 UTC, zangsu commented
고생 많으셨습니다~! 20000 머지 할게요~

2024-09-20 10:07 UTC, zangsu approved these changes

2024-09-20 10:07 UTC, merged