MemberCategoryApplicationService 테스트 구현
woowacourse-teams/2024-code-zap pull request #654
Opened 2024-09-16 15:30 UTC by kyum-q

## ⚡️ 관련 이슈
close #645 

## 📍주요 변경 사항
MemberService Test 보충 및 MemberServiceTest 실제 DB 사용으로 변경

## 🎸기타
#645 에 CI 테스트 문제에 대해 이야기 해보고 싶음
일단 해당 PR은 CI 문제가 발생하지 않도록 세팅해놓음

2024-09-18 07:50 UTC, zangsu reviewed
고생하셨어요!
크게 남길 코멘트는 없었고, 남긴 것 중에서도 중복되는 내용이 많네요 ㅎㅎ
읽어보시고 적용하고 싶은 부분만 적용해 주셔도 될 것 같아요~

2024-09-18 07:50 UTC, zangsu commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +    @DisplayName("카테고리 수정")
카테고리 수정 권한이 없는 경우는 테스트를 하지 않았네요!
`CategoryService` 의 테스트에서 확인해야 할 부분이라고 생각하셨던걸까요?
켬미의 생각이 궁금합니닷

2024-09-18 07:50 UTC, zangsu commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            assertThatThrownBy(() -> sut.update(memberDto, notExistsId, updateCategoryRequest))
놓치지 않도록 이곳에서도 동일 내용 표시해 둘게요!
```suggestion
            assertThatThrownBy(() -> sut.update(MemberDto.from(member), notExistsId, updateCategoryRequest))
```

2024-09-18 07:50 UTC, zangsu commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            assertThatThrownBy(() -> sut.update(memberDto, notExistsId, updateCategoryRequest))
```suggestion
            assertThatThrownBy(() -> sut.update(MemberDto.from(member), notExistsId, updateCategoryRequest))
```

2024-09-19 00:10 UTC, jminkkk requested changes
안녕하세요 켬미 
수고하셨어요 리뷰 남겼으니 확인 부탁드려요 🔥

2024-09-19 14:42 UTC, zeus6768 requested changes
켬미 고생 많았어요~👍👍👍 간단한 제안 있으니 확인해주세요

2024-09-19 14:42 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +        }
```suggestion
        @Test
        @DisplayName("카테고리 수정 실패 : 멤버 존재하지 않음")
        void updateFailNotExistsMember() {
            MemberDto nonExistentMemberDto = MemberDto.from(MemberFixture.memberFixture());
            String renameCategoryName = "카테고리 수정";
            UpdateCategoryRequest updateCategoryRequest = new UpdateCategoryRequest(renameCategoryName);

            assertThatThrownBy(() -> sut.update(nonExistentMemberDto, 1L, updateCategoryRequest))
                    .isInstanceOf(CodeZapException.class)
                    .hasMessage("식별자 " + memberDto.id() + "에 해당하는 멤버가 존재하지 않습니다.");
        }
```

이 테스트코드만 보고 무엇이 실패의 원인인지 파악하기 어려운 것 같아요. 그래서 다음과 같이 제안합니다~

2024-09-19 14:42 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            String renameCategoryName = "카테고리 2";
중복이 실패의 원인이니 `duplicateCateogry`도 좋아 보여요~

2024-09-19 14:42 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            String renameCategoryName = "카테고리 수정";
```suggestion
            String updatedCategoryName = "카테고리 수정";
```

제안합니당

2024-09-19 14:42 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            String renameCategoryName = "카테고리 수정";
```suggestion
            String updatedCategoryName = "카테고리 수정";
```

여기두요~

2024-09-19 16:23 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            sut.update(memberDto, category.getId(), updateCategoryRequest);
해당 부분은 합쳐도 되겠네요 !

고민이 되는 부분은 assertThatCode, assertThatThrownBy 코드에요
람다는 메서드 호출을 하나로 해서 예외 발생 가능을 하나로 하라고 경고가 뜨더라고요

그래서 현재는 경고가 뜨지 않게 모두 변수 추출했는데 이부분도 합치는게 좋다고 생각하는지 궁금하네요 ~
> Refactor the code of the lambda to have only one invocation possibly throwing a runtime exception.
> : 람다의 코드를 리팩터링하여 런타임 예외가 발생할 수 있는 호출이 한 번만 발생하도록 합니다.

2024-09-19 16:24 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            assertThatThrownBy(() -> sut.create(memberDto, createCategoryRequest))
https://github.com/woowacourse-teams/2024-code-zap/pull/654#discussion_r1767128830

위에 코멘트에 남겼습니다
확인해주세요

2024-09-19 16:31 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +    @DisplayName("카테고리 수정")
까먹 ㅎㅎ 추가하겠습니다 ~

2024-09-19 16:32 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            assertThatThrownBy(() -> sut.update(memberDto, notExistsId, updateCategoryRequest))
https://github.com/woowacourse-teams/2024-code-zap/pull/654#discussion_r1767128830

위에 코멘트에 남겼습니다
확인해주세요

2024-09-19 16:34 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            CreateCategoryResponse response = sut.create(memberDto, createCategoryRequest);
왜 Dto가 필요 없는지 모르겠어요 ㅜㅜ
메서드 인자가 MemberDto인데 어디에 id만 전달해되 되는건가요?

2024-09-19 16:39 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +        @DisplayName("멤버에 따른 카테고리 조회 성공")
해당 테스트는 `sut.findAllByMember(member.getId());`을 테스트하고 있습니다.
 인자로 memberDto와 같이 자신의 인증 정보를 전달하지 않는 것부터 다른 사람의 카테고리를 조회할 수 있다를 알 수 있다고 생각해요.

그리고 실제로 테스트 코드를 추가한다고 하면, 다른 회원의 카테고리를 조회할 수 있다를 어떻게 테스트해야할지 감이 안잡히는 것도 있네요.
인자로 원하는 카테고리 멤버 id만 인자로 넘기고 있는데, 내 카테고리 다른 사람 카테고리를 어떻게 구분하여 테스트할 수 있을까요? 결국엔 똑같은 코드일 것 같아요 !

제가 제대로 이해하지 못한 거라면 다시 한 번 이야기해주면 고마울 것 같아요 ~

2024-09-19 16:44 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            Long notExistsId = category.getId() + 1;
어이쿠 실수..
수정하였습니다. ㅎㅎ

2024-09-19 16:50 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            sut.update(memberDto, category.getId(), updateCategoryRequest);
하지만 사소하고 경고 문구에 불구하니 가독성이 더 좋게 변수 추출 제거할게요 ~

2024-09-19 16:59 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +        @DisplayName("멤버에 따른 카테고리 조회 성공")
아 지금 이해했어요 ~ 
서비스 로직을 이야기하신 거군요 ~
인졍 ~ 몰리 짱 ~

2024-09-20 01:00 UTC, jminkkk approved these changes
수고했어요 켬미 👍

2024-09-20 01:02 UTC, jminkkk commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            CreateCategoryResponse response = sut.create(memberDto, createCategoryRequest);
앗 메서드 인자를 말한 거였어요!
로직에 대한 얘기이니 넘어가셔도 됩니당

2024-09-20 05:09 UTC, HoeSeong123 approved these changes
고생하셨습니다!

2024-09-20 05:10 UTC, zeus6768 approved these changes
고생많았어요~!

2024-09-20 10:24 UTC, zangsu commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
> +            sut.update(memberDto, category.getId(), updateCategoryRequest);
`assertThatCode()`, `assertThatThrownBy()` 모두 예외 발생 여부를 확인하기 위한 코드라 상관 없을 것 같기는 한데~~ 모르겠네용 ㅋㅎ...

2024-09-20 10:26 UTC, zangsu approved these changes
고생했어요 켬미~~~~ 켬고~~~

2024-09-20 10:27 UTC, merged