MemberCategoryTemplateApplicationService 테스트
woowacourse-teams/2024-code-zap pull request #655
Opened 2024-09-16 16:27 UTC by kyum-q

## ⚡️ 관련 이슈
close #645 

## 📍주요 변경 사항
MemberCategoryTemplateApplicationService Test 구현

## 🎸기타
#645 에 CI 테스트 문제에 대해 이야기 해보고 싶음
일단 해당 PR은 CI 문제가 발생하지 않도록 세팅해놓음

2024-09-18 08:00 UTC, zangsu reviewed
고생하셨습니다 켬미!
이번 리뷰도 이전과 마찬가지로 정말 사소한 의견들을 남겨 보았어요.
한번 읽어보시고 마음에 드는 쪽으로 결정해 주세요~

2024-09-18 08:00 UTC, zangsu commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryTemplateApplicationServiceTest.java
> +            Long categoryId = category.getId();
```suggestion
            Category category = categoryRepository.save(Category.createDefaultCategory(member));
            Long categoryId = category.getId();
```
```suggestion
            Category defaultCategory = categoryRepository.save(Category.createDefaultCategory(member));
            Long defaultCategoryId = defaultCategory.getId();
```

변수 이름을 조금 더 명확하게 나타내 보았어요

2024-09-19 00:17 UTC, jminkkk submitted a review, later dismissed
안녕하세요 켬미 
수고하셨습니다 🔥
충분히 잘 작성된 것 같아 approve하겠습니다 🍀

2024-09-19 00:17 UTC, jminkkk commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryTemplateApplicationServiceTest.java
> +        @DisplayName("카테고리 아이디로 카테고리 삭제 실패 : 기본 카테고리")
👍

2024-09-19 00:17 UTC, jminkkk commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryTemplateApplicationServiceTest.java
> +            MemberDto memberDto = MemberDto.from(member);
이 부분도 이전 pr처럼 회원의 id만 받으면 MemberDto를 따로 생성하지 않아도 되겠군요..!

2024-09-19 14:49 UTC, zeus6768 requested changes
고생 많았어요 켬미 👍👍👍👍

남긴 코멘트에서 의견 나누고 싶어 RC 남깁니다!

그런데 질문이 있어요. 

본 PR에서는 새로운 파일을 생성하고 있는데 Refactor 라벨이 적절한지 의문입니다!


---

> CI 테스트 문제에 대해 이야기 해보고 싶음

해당 CI 테스트 문제에 대해 조금만 더 자세히 언급해줄 수 있을까요~?

2024-09-19 14:49 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryTemplateApplicationServiceTest.java
> +        @DisplayName("카테고리 아이디로 카테고리 삭제 실패 : 기본 카테고리")
```suggestion
        @DisplayName("카테고리 아이디로 카테고리 삭제 실패 : 기본 카테고리는 삭제할 수 없음")
```

조금 더 자세히 이렇게 하면 어떤가요?

2024-09-19 14:49 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryTemplateApplicationServiceTest.java
> +        @DisplayName("카테고리 아이디로 카테고리 삭제 실패 : 템플릿 존재")
```suggestion
        @DisplayName("카테고리 아이디로 카테고리 삭제 실패 : 해당 카테고리에 속한 템플릿이 존재하면 삭제할 수 없음")
```

조금 더 자세한 DisplayName 제안합니다~!

2024-09-19 16:58 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/facade/MemberCategoryTemplateApplicationServiceTest.java
> +            MemberDto memberDto = MemberDto.from(member);
아 지금 이해했어요 ~ 
서비스 로직을 이야기하신 거군요 ~
인졍 ~ 몰리 짱 ~

2024-09-19 17:02 UTC, kyum-q commented
@zeus6768 
> 해당 CI 테스트 문제에 대해 조금만 더 자세히 언급해줄 수 있을까요~?
허걱 제가 앞에 링크를 잘못 걸어뒀었네요. !

https://github.com/woowacourse-teams/2024-code-zap/pull/646 <- 이 PR 기타에 CI문제에 자세하게 적어놨습니다 !

2024-09-20 01:02 UTC, jminkkk approved these changes
켬미 짱

2024-09-20 05:09 UTC, HoeSeong123 approved these changes
고생하셨습니다!

2024-09-20 05:14 UTC, zeus6768 approved these changes
고생많았어요 켬미~

#646 에서 언급한 CI 문제는 글만 봐서는 의도를 이해하기 어려운 것 같아요. 

이슈나 디스커션으로 분리해서 정리하면 더 좋겠어요!

2024-09-20 10:27 UTC, zangsu approved these changes
켬미 너무 수고 많으셨어요~~~~ 고켬~~~

2024-09-20 10:29 UTC, merged