CategoryService 테스트
woowacourse-teams/2024-code-zap pull request #656
Opened 2024-09-17 10:27 UTC by zangsu

## ⚡️ 관련 이슈
close #645 

## 📍주요 변경 사항
CategoryService Test 구현

2024-09-17 10:28 UTC, zangsu commented on backend/src/main/java/codezap/category/service/CategoryService.java
>              throw new CodeZapException(HttpStatus.NOT_FOUND, "식별자 " + id + "에 해당하는 카테고리가 존재하지 않습니다.");
이 메서드가 사용되고 있지 않던데, 그냥 지우기엔 제가 작업한 코드가 아니라서요 ㅎㅎ,,
확인해 보고, 이슈에 해당 내용 추가 부탁드려도 될까요~~

2024-09-17 10:29 UTC, zangsu commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +        }
확인해야 하는 엣지 케이스에 해당하는 것 같으나, 존재하지 않는 멤버로 조회를 시도하는 상황에 대한 별다른 예외처리가 존재하지 않아요.
사용하는 곳에서는 이미 존재하는 Member 만을 파라미터로 전달해 주고 있기도 합니다.
지금의 테스트 코드가 필요할까요? & 프로덕션 코드에서 예외 처리가 존재하지 않아도 괜찮을까요?

2024-09-17 11:39 UTC, zangsu commented
테스트가 갑자기 터져서~ 잠시 PR 닫아 둘게요

2024-09-17 12:14 UTC, zangsu commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
>          @DisplayName("카테고리 수정 성공")
수정 성공 테스트가 현재 실패하는데요. 
이유를 확인해 보니 `Member.equals()` 메서드의 아래 부분이 문제였습니다.
```java
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
```

현재 `Category` 의 `Member` 필드에는 lazy loading 이 걸려있습니다. 
때문에 프록시 객체가 `Member` 필드로 들어가게 되고, 클래스 비교에서 `false` 가 반환되는 것이 문제입니다.

프로덕션 코드의 수정이 일어나야 해 이슈에 남겨두고 넘어가겠습니다.

2024-09-17 12:18 UTC, zangsu commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +        }
이 부분을 실제 DB 사용으로 변경하니 데이터베이스 에러인 `InvalidDataAccessApiUsageException` 가 터지게 됩니다.
이에 대해 예외 처리가 필요할지 고민을 해 보아야 할 것 같습니다.

2024-09-18 10:30 UTC, kyum-q requested changes
짱수 추석에도 열일 하셨네요 ~!
고생하셨어요 ~
몇가지 코멘트 남겨놨으니 확인 부탁드려요 ~

2024-09-18 10:30 UTC, kyum-q commented on backend/src/main/java/codezap/category/service/CategoryService.java
>              throw new CodeZapException(HttpStatus.NOT_FOUND, "식별자 " + id + "에 해당하는 카테고리가 존재하지 않습니다.");
해당 메서드는 fetchById(id) 내에서 예외처리 되는 걸로 처리되어서 사용하지 않게 된 것 같네요 ~ 삭제 목록에 추가해도 될 것 같습니다 ~

2024-09-18 10:30 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +            );
멤버정보까지 확인하면 더 좋을 것 같네요 ~

2024-09-18 10:30 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
>                      .isEqualTo(2L);
categoryService.create(otherMember, createCategoryRequest) 을 분리하면 더 좋을 것 같아요 !

분리하고 위에 성공 케이스처럼 아이디, 이름, 멤버 다 비교하면 더 굿 !

2024-09-18 10:30 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +        }
고민되는 부분이네요 !
상위 파사드에서 멤버를 체크하니 여기서 또 하기에는 중복 로직이 생기고 이렇게 되면 분리의 의미가 없어지는 느낌도 들고,, 어렵네요..! 멤버와 완전한 분리가 되지 않다보니 더 어려워진...

2024-09-19 01:15 UTC, jminkkk requested changes
안녕하세요 짱수!
수고하셨어요 🔥
리뷰 남겨보았으니 확인 부탁드려요!

2024-09-19 01:15 UTC, jminkkk commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +    class FindAllCategoryTest {
카테고리 없을 때 빈 리스트 반환하는 것도 추가해주심 좋을 것 같아용

2024-09-19 01:15 UTC, jminkkk commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +        }
실제 DB 사용과 별개로 이 부분은 CodeZapException이 발생해야 할 것 같은데...흠...
다른 서비스에서 CategoryService의 이 메서드를 사용하면 어떻게 되는 거죵....너무 어렵네요....흠

2024-09-19 12:12 UTC, HoeSeong123 requested changes
고생하셨습니다 짱수!!
크게 피드백할 부분이 없는 것 같아서 간단한 코멘트 몇 개 남겨두었습니다~~

2024-09-19 12:12 UTC, HoeSeong123 commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +        }
Member 대신 memberId로 조회를 하는 건 어떤가요?

2024-09-19 12:12 UTC, HoeSeong123 commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
>          @DisplayName("카테고리 수정 성공")
원활한 CI 진행을 위해 @Disabled 처리를 해놓는 건 어떤가요?

2024-09-19 15:23 UTC, zeus6768 approved these changes
짱수 고생 많았어요~!

주요 변경사항은 다른 분들이 이야기해줬고

저는 딱히 RC 요청할 만한 부분이 없는 것 같아 승인합니다.

2024-09-19 15:23 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +            String duplicatedCategoryName = "category";
exists는 동사형이므로 이곳의 맥락에서는 변수에 사용하기에 적절하지 않습니다. "중복" 대신 "기존"이라는 의미를 나타내고 싶다면 existent가 더 적절해요~

변수에 동사형 접두사를 붙인 다른 케이스에서는 사소하다고 생각했는데, 여기선 언급해야 할 것 같아 코멘트 남깁니다...😅

DisplayName과 메서드명에서 중복을 실패의 원인으로 명시했으니, 실패의 원인이 되는 파라미터의 이름도 중복의 의미를 담는 Duplicated를 유지하는 게 더 좋다고 생각합니다.

2024-09-19 15:23 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
>          @DisplayName("카테고리 생성 성공: 다른 멤버, 중복된 이름의 카테고리 이름 생성")
짱수가 의도한 맥락이 있는 게 아니라면 이 성공 테스트를 실패 테스트보다 위로 옮기는 것에 대해 어떻게 생각하시나요?

그렇게 하면 성공 케이스를 먼저 모아 볼 수 있고, 그렇게 하는 편이 읽기 더 쉬울 것 같다는 생각이 들어서요~!

2024-09-19 15:23 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
>                      .isEqualTo(2L);
저도 켬미와 같은 의견입니다!

2024-09-19 15:23 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +        }
저는 굳이 이런 예외까지 처리해주지 않아도 된다는 의견입니다~

현재 우리의 비즈니스 로직에서 존재하지 않는 멤버가 생길 수 있는 지 의문이에요. 

또, 이렇게 테스트해야 한다면 다른 도메인을 사용하는 다른 모든 서비스에서도 그 도메인 객체가 존재하는지 아닌지 테스트해줘야 한다는 말인데, 납득이 가지 않아요.

2024-09-19 15:23 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
>          @DisplayName("카테고리 수정 성공")
#664 관련 이슈 코멘트합니다.

2024-09-20 04:17 UTC, zangsu commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +            CreateCategoryRequest createCategoryRequest = new CreateCategoryRequest(categoryName);
이름은 제가 지정한 값 그대로 잘 저장이 되었는지 확인하기 위해 변수 추출을 했어요.
몰리가 제안 주신것 처럼 `CreateCategoryRequest` 에서 다시 값을 꺼내와도 되지만, 지금과 같은 형태가 훨씬 직관적이라 느껴져서 유지하겠습니다!

2024-09-20 04:36 UTC, zangsu commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +            String duplicatedCategoryName = "category";
몰리, 제우스 둘다 좋은 의견 감사해요!
제우스 의견을 반영해 그대로 유지하겠습니다!

2024-09-20 04:44 UTC, zangsu commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +            Category category2 = categoryRepository.save(new Category("category2", member));
픽스쳐를 사용하는 건 좋은 의견이군요!
그런데, 지금은 `member` 의 서로 다른 두 카테고리를 저장해야 해요.
픽스쳐는 `MemberFixture.getFirstMember()` 의 카테고리 하나와 `MemberFixture.getSecondMember()` 의 카테고리 하나밖에 존재하지 않아서 직접 생성하는 것이 가장 좋을 것 같습니다!

2024-09-20 06:22 UTC, zangsu commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +        }
@HoeSeong123 오, memberId 로 조회하면 DB 에러가 나지는 않는군요. 
`NoSuchElementException` 이 발생하고, 얘는 `java.util` 의 예외네요.
그런데 이건 프로덕션 코드의 수정이 필요해서 리팩토링 이슈에 달아둘게요

2024-09-20 06:26 UTC, zangsu commented on backend/src/test/java/codezap/category/service/CategoryServiceTest.java
> +        }
논의가 마무리 되지 않은 것으로 판단하여 일단 코드는 남겨두겠습니닷

2024-09-20 11:05 UTC, jminkkk approved these changes
수짱
수고했어요 짱수 🔥
리뷰 반영 완료된 것 같아 approve 할게요!

2024-09-20 12:31 UTC, HoeSeong123 approved these changes
변경사항 확인했습니다.
고생하셨습니다~~~

2024-09-20 13:24 UTC, kyum-q approved these changes
짱수 굿 수고하셨어용 ~

2024-09-22 06:55 UTC, zeus6768 approved these changes

2024-09-22 06:56 UTC, merged