AuthService 테스트
woowacourse-teams/2024-code-zap pull request #657
Opened 2024-09-17 12:28 UTC by zangsu

## ⚡️ 관련 이슈
close #645

## 📍주요 변경 사항
기존에 필요한 테스트 코드가 잘 짜여 있었어요.
Fake DB 를 삭제하는 변경사항밖에 존재하지 않습니다.

2024-09-18 10:38 UTC, kyum-q reviewed
짱수 수고하셨어요 ~!

그런데 RepositoryTest에서 CI 실패하는 원인은 무엇인가여..?

변경되지 않은 코드 중에 junit을 사용한 코드가 있네요 이에 대해 어떻게 생각하시나요?
좀 더 명확한 차이를 알 수 있게 assertJ로 통일 시키는건 어떤가요?
제가 assertJ를 선호하는 이유는 이번 톰켓 미션에서 폴라와 이야기했던 PR 남겨둘게요 ~
https://github.com/woowacourse/java-http/pull/660#discussion_r1757276882

2024-09-18 14:51 UTC, zangsu commented
> 변경되지 않은 코드 중에 junit을 사용한 코드가 있네요 이에 대해 어떻게 생각하시나요? 좀 더 명확한 차이를 알 수 있게 assertJ로 통일 시키는건 어떤가요? 제가 assertJ를 선호하는 이유는 이번 톰켓 미션에서 폴라와 이야기했던 PR 남겨둘게요 ~ [woowacourse/java-http#660 (comment)](https://github.com/woowacourse/java-http/pull/660#discussion_r1757276882)

사실 저도 assertJ 를 선호하긴 합니다!
그런데, 아시겠지만 기존의 테스트코드를 제가 작성한 것이 아니라서요!
제 개인 선호 때문에 이 부분을 변경하는 것이 조금 조심스러워서 우선 그대로 두었습니다.

2024-09-19 00:27 UTC, kyum-q approved these changes
굿 그것도 맞는 말이네요 ~ ! 수고하셨습니다 ~

2024-09-19 04:13 UTC, jminkkk requested changes
안녕하세요 짱수~
수고하셨어요 🔥
기존에 있던 테스트지만 코멘트 하나 남겼으니 확인 부탁드립니당

2024-09-19 04:13 UTC, jminkkk commented on backend/src/test/java/codezap/auth/service/AuthServiceTest.java
> +    private AuthService authService;
쿠키 인증 테스트 -> 로그인 인증 테스트가 더 적절할 것 같아요...! 변경 부탁드려욥

2024-09-19 04:13 UTC, jminkkk commented on backend/src/test/java/codezap/auth/service/AuthServiceTest.java
> +    private AuthService authService;
쿠키 인증 테스트 -> 로그인 인증 테스트가 더 적절할 것 같아요...! 
변경 부탁드려욥

2024-09-19 12:18 UTC, HoeSeong123 submitted a review, later dismissed
좋네요!! 👍

2024-09-19 15:25 UTC, zeus6768 approved these changes

2024-09-20 11:21 UTC, jminkkk commented on backend/src/test/java/codezap/auth/service/AuthServiceTest.java
> +    @DisplayName("로그인 상 확인 테스트")
굿!!!!!!!!!!!!!
그런데 혹시.......... 내부 테스트 메서드들도 함께 바꿔주실 수 있는지.......... 🥺

2024-09-20 12:30 UTC, HoeSeong123 submitted a review, later dismissed

2024-09-20 13:25 UTC, kyum-q submitted a review, later dismissed
굿 짱수 수고하셨엉욧 `

2024-09-21 11:28 UTC, zeus6768 approved these changes

2024-09-23 03:46 UTC, zangsu commented on backend/src/test/java/codezap/auth/service/AuthServiceTest.java
> +    @DisplayName("로그인 상 확인 테스트")
헉 잊고있었다...!
수정 완료~!

2024-09-23 06:00 UTC, jminkkk approved these changes
짱수 수고했어요 🔥

2024-09-23 15:23 UTC, kyum-q approved these changes

2024-09-23 15:51 UTC, HoeSeong123 approved these changes

2024-09-26 16:46 UTC, zeus6768 approved these changes

2024-09-26 16:46 UTC, merged