CategoryTemplateService 테스트
woowacourse-teams/2024-code-zap pull request #658
Opened 2024-09-17 12:41 UTC by zangsu

## ⚡️ 관련 이슈
close #645

## 📍주요 변경 사항
- 실제 db 사용하도록 변경
- 테스트 코드의 오류 수정

## 🎸기타
- `CategoryTemplateService` 의 존재에 대해 이야기를 해 보면 좋을 것 같아요.
  - 우선 이슈에 글을 달아둘게요.

2024-09-18 14:32 UTC, kyum-q reviewed
수고했어요 짱수 간단한 코멘트 남겨뒀어요 ~

2024-09-18 14:32 UTC, kyum-q commented on backend/src/test/java/codezap/category/service/CategoryTemplateServiceTest.java
>      void deleteCategorySuccess() {
해당 카테고리 id가 존재하는지 확인까지 하면 좋을 것 같아요

```java
assertAll(
        () -> assertThat(categoryRepository.findAllByMemberOrderById(member)).hasSize(beforeDeleteSize - 1),
        () -> assertThat(categoryRepository.existsById(savedCategory.getId()))
                .isInstanceOf(CodeZapException.class)
                .hasMessage("식별자 " + savedCategory.getId() + "에 해당하는 카테고리가 존재하지 않습니다.");
);
```

2024-09-19 04:18 UTC, jminkkk requested changes
안녕하세요 짱수~!
수고하셨습니다 🔥
코멘트 남겼으니 확인 부탁드립니당

2024-09-19 04:18 UTC, jminkkk commented on backend/src/test/java/codezap/category/service/CategoryTemplateServiceTest.java
> +    void deleteCategoryFailWithNotExistCategory() {
`@Nested` 로 변경해주는 건 어떨까요?

2024-09-19 04:18 UTC, jminkkk commented on backend/src/test/java/codezap/category/service/CategoryTemplateServiceTest.java
> +    private CategoryTemplateService categoryService;
⚡️
```suggestion
    private CategoryTemplateService categoryTemplateService;
```

2024-09-19 12:31 UTC, HoeSeong123 requested changes
고생하셨습니다 짱수!!
메소드가 별로 없어서 간단하고 좋네요ㅎㅎ

2024-09-19 12:31 UTC, HoeSeong123 commented on backend/src/test/java/codezap/category/service/CategoryTemplateServiceTest.java
> +    void deleteCategoryFailWithNotExistCategory() {
짱수가 작성한 코드는 아니지만 테스트 코드의 질을 높이기 위한 작업중이니까 의견 남기겠습니다!!
`categoryService.deleteById`에 대한 테스트인데 해당 테스트 코드는 `deleteById`가 정상적으로 동작한다는 가정하에 작성된 코드 같아요.
이미 없는 카테고리를 삭제하는 테스트보다는 애초에 없는 ID에 대한 삭제 테스트를 하는 건 어떤가요?
이전까지의 테스트 코드에서 했던 것처럼 `notSavedId`등을 활용해서요!

2024-09-19 15:29 UTC, zeus6768 requested changes
짱수최고 👍

간단한 제안 남겼습니다.

2024-09-19 15:29 UTC, zeus6768 commented on backend/src/test/java/codezap/category/service/CategoryTemplateServiceTest.java
>      @DisplayName("카테고리 삭제 실패: 이미 없는 카테고리")
`이미 없는` 이라는 표현이 어색하네요. 여기서 `이미`가 맥락을 충분히 주는 것 같지 않습니다. 

`카테고리 삭제 실패: 존재하지 않는 카테고리는 삭제할 수 없음` 은 어떤가요?

2024-09-20 11:07 UTC, jminkkk approved these changes
장수 수고했어요 
기념으로 장수 합시다 깔깔 최고 🔥

2024-09-20 12:30 UTC, HoeSeong123 approved these changes
굿!! 고생하셨습니다.

2024-09-20 13:26 UTC, kyum-q approved these changes
짱 수 굿 ~!!!!

2024-09-21 11:28 UTC, zeus6768 approved these changes
고생많았어요 짱수!

2024-09-21 11:28 UTC, merged