CategoryTemplateApplicationTest 추가
woowacourse-teams/2024-code-zap pull request #660
Opened 2024-09-17 13:19 UTC by jminkkk

## ⚡️ 관련 이슈
close #645

## 📍주요 변경 사항
1. CategoryTemplateApplicationService 테스트를 작성하였습니다.
2. ServiceTest가 SourceCodeService pr 과 중복됩니다. pr 머지 시 충돌이 발생할 수 있으나 필요하다고 생각하여 추가했습니다~

## 🎸기타
1. 리팩토링이 필요한 부분이 있는 듯합니다. 의견을 이슈에 작성해놓았으니 https://github.com/woowacourse-teams/2024-code-zap/issues/650#issuecomment-2355273823 참고해주세요.
2. 테스트를 하기 위해 해당 서비스의 역할을 생각해보았습니다. 관련 의문과 제안을 이슈에 작성해두었으니 참고해주세요.
3. https://github.com/woowacourse-teams/2024-code-zap/issues/650#issuecomment-2355576069 짱수와 동일한 프록시 객체 접근 문제가 발생합니다~ @Transactional 어노테이션을 통해 트랜잭션을 생성하는 방식으로 처리했습니다.

2024-09-18 08:12 UTC, zangsu reviewed
고생 하셨어요 몰리!
request 를 만드는 코드가 상당히 복잡하네요. 
하지만 저도 개선 방안이 딱히 떠오르지 않아서 고민입니다 ㅠㅠ

대부분의 코드 꼼꼼하고 가독성 좋게 잘 짜 주셔서 코멘트를 남길 부분이 크게 없는 것 같아요!
사소한 코멘트 남겨 두었으니 확인 부탁드려요~~

2024-09-18 08:12 UTC, zangsu commented on backend/src/test/java/codezap/template/service/facade/CategoryTemplateApplicationServiceTest.java
> +            assertThat(result).isEqualTo(1L);
확인하고 싶은 것이 "저장된 템플릿의 아이디가 1L 이다" 보단, 원하는 대로 잘 저장되었음을 확인하고 싶은 것이니..
아래와 같이 바꾸어 보는 것은 어떨까요?
```suggestion
            assertThat(categoryRepository.existsById(result)).isTrue();
```

2024-09-18 08:12 UTC, zangsu commented on backend/src/test/java/codezap/template/service/facade/CategoryTemplateApplicationServiceTest.java
> +    @DisplayName("템플릿 수정")
수정하려는 템플릿이 존재하지 않는 경우 / 카테고리가 존재하지 않는 경우 등에 대한 테스트가 존재하지 않아도 괜찮을까요?
( 사실 `CategoryService`, `TemplateService` 등에서 처리를 해 주는 부분이라면 이 테스트클래스의 범위가 아닐지도 모르겠네요. 
단순히 몰리의 생각이 궁금했어요!)

2024-09-18 10:49 UTC, kyum-q reviewed
몰리 수고했어요 ~!

궁금한 점이 있어서 코멘트 남겨놨으니 확인 부탁드려요 ~ (답변 필수 아님 ~ 지금 바쁘면 나중에 만나서 말해줘요 ~)

2024-09-18 10:49 UTC, kyum-q commented on backend/src/test/java/codezap/global/ServiceTest.java
> +public class ServiceTest {
(단순 궁금증) JpaRepositoryTest는 어노테이션으로 구현하여 사용하였었는데 ServiceTest는 상속해서 사용하도록 제작하셨네요 !
제가 생각하기에 ServiceTest는 변수가 있어서 인 것 같아요. 
지금 생각해보니 변수가 없더라도 JpaRepositoryTest도 어노테이션으로 구현하지 않고 ServiceTest처럼 상속하도록 할 수 있었을 것 같네요. JpaRepositoryTest를 어노테이션으로 구현했던 이유가 있을까요? 
몰리가 어노테이션으로 구현하는 것들의 기준이 궁금합니다 ~ (무엇을 어노테이션을 구현하고 무엇을 클래스로 구현해서 상속하게 하는지)

2024-09-18 10:49 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/facade/CategoryTemplateApplicationServiceTest.java
> +                    List.of(updateSourceCodeRequest), Collections.emptyList(), category.getId(), Collections.emptyList());
개행을 하면 가독성이 더 좋아질 것 같아요
```suggestion
            UpdateTemplateRequest request = new UpdateTemplateRequest(
                  "Updated Template", 
                  "Updated Description", 
                  Collections.emptyList(),
                  List.of(updateSourceCodeRequest), 
                  Collections.emptyList(), 
                  category.getId(), 
                  Collections.emptyList());
```

2024-09-19 08:41 UTC, jminkkk commented on backend/src/test/java/codezap/global/ServiceTest.java
> +public class ServiceTest {
해결완

2024-09-19 08:50 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/facade/CategoryTemplateApplicationServiceTest.java
> +    @DisplayName("템플릿 수정")
흠 이 서비스 계층이 가지는 책임에 대해 테스트를 해야한다고 생각을 해서 이렇게만 작성을 했어요.
사실 이 계층의 역할 자체를 스스로 테스트하면서도 모르겠어서 논의가 필요할 것 같네요...!

2024-09-19 15:32 UTC, zeus6768 requested changes
몰리 꼼꼼한 테스트 코드 잘 봤어요~!

다만 다음과 같이 컨벤션을 맞춰 주세요 😁

![image](https://github.com/user-attachments/assets/30fa4c16-c9ab-44ee-b269-610a336cb1f7)

2024-09-20 02:32 UTC, jminkkk commented
> 몰리 꼼꼼한 테스트 코드 잘 봤어요~!
> 
> 다만 다음과 같이 컨벤션을 맞춰 주세요 😁
> 
> ![image](https://private-user-images.githubusercontent.com/81848498/369067495-30fa4c16-c9ab-44ee-b269-610a336cb1f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTk3NDUsIm5iZiI6MTcyNjc5OTQ0NSwicGF0aCI6Ii84MTg0ODQ5OC8zNjkwNjc0OTUtMzBmYTRjMTYtYzlhYi00NGVlLWIyNjktNjEwYTMzNmNiMWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAyMzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhOTExZTllYmI4ZTEyYTg3YmZkMTkzOTk1ZmUwNTg5NTQyNzgzYmMyY2M3NTQ0YTQ0MTZkMTM0YjA4YjQyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XjkeqLXttM8-whr-fF_rh1GpgTupoLU2MIUic3_oZyg)

https://github.com/woowacourse-teams/2024-code-zap/pull/653#issuecomment-2362582993 
이전 pr과 동일한 답변 드립니다~!

2024-09-20 05:28 UTC, zeus6768 approved these changes
몰리 정말 고생 많았어요~~~!

2024-09-20 06:01 UTC, HoeSeong123 approved these changes
리뷰를 못해서 아쉽네요..
고생하셨습니다!

2024-09-20 09:34 UTC, kyum-q approved these changes
몰리 짱 ~! 수고하셨어요 ~!

2024-09-20 10:28 UTC, zangsu commented on backend/src/test/java/codezap/template/service/facade/CategoryTemplateApplicationServiceTest.java
> +    @DisplayName("템플릿 수정")
테스트 넘모 어려웡

2024-09-20 10:28 UTC, zangsu approved these changes
몰리 고생 많으셨습니다~~!!
몰고~~

2024-09-20 10:28 UTC, merged