TemplateServiceTest 추가
woowacourse-teams/2024-code-zap pull request #661
Opened 2024-09-18 00:44 UTC by HoeSeong123

## ⚡️ 관련 이슈
close #645 

## 📍주요 변경 사항
TemplateService 테스트 작성

## 🎸기타
### 중복되는 테스트 코드
- TemplateService의 경우 아래 코드와 같이 TemplateRepository의 반환값을 그대로 리턴하는 메소드들이 몇 개 있습니다.
```java
public Template getById(Long id) {
    return templateRepository.fetchById(id);
}

public List<Template> getByMemberId(Long memberId) {
    return templateRepository.findByMemberId(memberId);
}

public Page<Template> findAll(
        Long memberId, String keyword, Long categoryId, List<Long> tagIds, Pageable pageable
) {
    return templateRepository.findAll(
            new TemplateSpecification(memberId, keyword, categoryId, tagIds), pageable);
}
```
- 이런 경우 RepositoryTest와 중복되는 테스트들이 몇 개 생겨나는데 이런 경우에도 ServiceTest를 작성해야 하는지 의문입니다.
  - 우선 저는 중복되더라도 테스트 코드를 작성하였습니다.
  - 테스트 코드는 해당 클래스의 명세서와도 같고, 테스트 코드를 봤을 때 해당 클래스를 `어떻게 사용하는거구나, 어떤 에러가 발생할 수 있구나` 등을 알 수 있게 하는 것이 목적이라고 생각하기 때문입니다.
  - 다른 분들의 의견이 궁금합니다.

## 지연 로딩 문제
- https://github.com/woowacourse-teams/2024-code-zap/issues/650#issuecomment-2355576069 
- 저도 마찬가지로 짱수와 동일한 프록시 객체 접근 문제가 발생합니다. 
- 몰리와 동일하게 `@Transactional` 어노테이션을 통해 트랜잭션을 생성하는 방식으로 처리했는데, 우선은 프로덕션 코드는 수정되면 안 될 것 같아서 테스트 코드에 `@Transactional`을 추가하는 식으로 해결하였습니다. 
- 추후에 해당 어노테이션을 지우고, 프로덕션 코드에 적용하는 식으로 변경해야 할 것 같습니다.

2024-09-18 15:05 UTC, kyum-q requested changes
초롱 검색 케이스까지 철저하게 테스트 구현해주셨네요 ~~ 수고하셨어요 ~! 굿 !
간단한 코멘트 남겨뒀습니다. 확인부탁드려요 !

2024-09-18 15:05 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +                    () -> assertThat(actual.getCategory()).isEqualTo(category)
description이랑 소스코드, 썸네일 순서, 태그도 확인하면 좋을 것 같아요 !

2024-09-18 15:05 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +                    .containsExactly(template1, template2);
다른 멤버꺼는 보여지지 않는다는 의미로 doesNotContain까지 해주는 건 어떤가요?
근데 생각해보면 containsExactly로 정확한 비교를 하니 없어도 될 것 같기도 ~!

```suggestion
            assertThat(actual).hasSize(2)
                    .containsExactly(template1, template2);
                     .doesNotContain(FindCategoryResponse.from(template3));
```

2024-09-19 05:00 UTC, jminkkk requested changes
안녕하세요 초롱~ 
수고하셨습니다 🔥
확인 부탁드려요 ㅎㅎ

2024-09-19 05:00 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +        @DisplayName("멤버 ID로 템플릿 조회 성공: 해당하는 템플릿이 없는 경우")
```suggestion
        @DisplayName("멤버 ID로 템플릿 조회 성공: 해당하는 템플릿이 없는 경우 빈 목록을 반환")
```

2024-09-19 05:00 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +    class FindAll {
```suggestion
    @DisplayName("템플릿 목록 조회")
    class FindAll {
```

2024-09-19 05:00 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +        @DisplayName("검색 기능: 회원 ID로 템플릿 조회 성공")
```suggestion
        @DisplayName("템플릿 목록 조회 성공: 특정 회원의 템플릿 목록 조회")
```

2024-09-19 05:00 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            Page<Template> actual = sut.findAll(memberId, keyword, categoryId, tagIds, pageable);
```suggestion
            Pageable pageable = PageRequest.of(0, 10);

            Page<Template> actual = sut.findAll(memberId, null, null, null, pageable);
```

(다른 메서드도 포함) 변수 할당을 안해도 의미가 충분히 보일 것 같아요!

2024-09-19 05:00 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +                                    templateRepository.fetchById(2L)),
이것도 취향 차이지만...
한줄로 적어도 좋을 것 같아요!
위의 allMatch보다 길이가 짧아서 가능할 것 같은...??

```suggestion
                            .containsExactlyInAnyOrder(templateRepository.fetchById(1L),templateRepository.fetchById(2L)),
```

2024-09-19 05:00 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            );
```suggestion
                                    template.getMember().getId().equals(member1.getId())
                                            && (template.getTitle().contains(keyword) 
                                            || template.getDescription().contains(keyword)))
            );
```
으엥 이렇게 보니까 이상한 것 같긴 한데 .. 암튼 요런 느낌.. 어떨까요?
<img width="414" alt="image" src="https://github.com/user-attachments/assets/898e9159-21dc-44cc-ae08-2f3840743ba7">

2024-09-19 05:00 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +                            templateRepository.fetchById(2L))
⚡️ 전체적으로 통일을 위한 확인이 필요할 것 같아용

2024-09-19 06:50 UTC, zangsu reviewed
고생하셨어요 초롱! 몇가지 코멘트 남겨 두었으니 확인 부탁드려요~~~

2024-09-19 06:50 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            var template3 = templateRepository.save(TemplateFixture.get(member2, category));
카테고리는 멤버마다 따로 존재하는 개념이었죠?
`Repository.save()` 를 해서 문제는 일어나지 않지만, 지금의 데이터는 논리적으로 잘못된 데이터가 되겠네요.
멤버마다 카테고리를 분리해 두는 것이 좋지 않을까요?

2024-09-19 06:50 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            }
테스트를 위한 코드인가요? 단순 확인을 위한 코드라면 삭제해도 좋을 것 같습니다! 👀

2024-09-19 06:50 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            );
저도 몰리 의견에 한 표 추가합니다!

[6.4. 줄바꿈 허용 위치](https://naver.github.io/hackday-conventions-java/#line-wrapping-position)
네이버 핵데이 컨벤션인데요. 여기서도 연산자 앞에서 줄바꿈을 규칙으로 지정하고 있어요.

조건 연산자로 연결된 줄이 길어질 경우, 조건 연산자 앞에서 개행을 해주면 훨씬 가독성이 좋아지는 것 같네용

2024-09-19 16:45 UTC, zeus6768 reviewed
테스트 코드가 정말 많네요. 작성하느라 고생 많았어요 😭

다른 분들이 변경사항에 대해 충분히 언급하신 것 같아, 저는 의견만 이모지로 표현했습니다. 

---

> 테스트 코드는 해당 클래스의 명세서와도 같고, 테스트 코드를 봤을 때 해당 클래스를 어떻게 사용하는거구나, 어떤 에러가 발생할 수 있구나 등을 알 수 있게 하는 것이 목적이라고 생각하기 때문입니다.

테스트 코드는 클래스의 명세가 아니라 기능의 명세라고 정정하고 싶어요. 

클래스의 명세라는 관점으로 접근하면, 그 클래스의 구현까지 고려해야할 것 같다는 생각이 들기 때문입니다. 

반면 저는 원하는 기능만 올바르게 동작하는지 확인하면 된다고 생각해요. 

서비스는 DB에 의존하고 있으니 서비스 테스트에서 DB에 잘 저장되었는지까지 확인해야 할까요?

그렇다면 어떤 객체를 테스트할 때 그 객체의 모든 의존성이 발생할 수 있는 예외를 검증해야 하는데, 이건 말이 안 된다고 생각해요. 

단위 테스트 책에서 리팩토링 내성에 관한 챕터를 읽어보면 좋을 것 같습니다. 

다른 의견 있다면 답변 부탁드려요~!

2024-09-19 16:45 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            );
저는 findAll 메서드의 결과만 놓고 검증해야 한다고 생각합니다. 

구체적인 로직을 몰라도 테스트를 할 수 있어야 한다고 생각하기 때문입니다.

2024-09-19 16:45 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +    class FindAll {
pageable이 있는 경우와 없는 경우를 먼저 테스트해서 Pageable이 필수 인자라는 것을 보여주면 좋을 것 같아요.

2024-09-20 04:04 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            );
저도 제우스 의견에 동의합니다.
해당 메소드에 대한 테스트는 `어떤 입력을 했을 때 이런 출력이 나와`를 테스트하는 거지, 내부의 로직이 전부 정상적으로 동작하는지를 확인하는 것은 아니라고 생각합니다.

2024-09-20 04:07 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            );
> description이랑 소스코드, 썸네일 순서, 태그도 확인하면 좋을 것 같아요 !
썸네일 순서와 태그는 Template이 가지고 있는 필드가 아니어서 검사 로직에서 제외했습니다. description과 sourceCode는 추가하였습니다.

2024-09-20 04:22 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +                    .containsExactly(template1, template2);
더욱 명시적으로 나타낼 수는 있다고 생각하지만 켬미가 얘기한 것처럼 `containsExactly`를 사용하기 때문에 불필요하다고 생각됩니다

2024-09-20 04:25 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +    class FindAll {
몰리가 작성했던 테스트들을 그대로 가져왔던 것들인데 검색 기능이 더 명확하지 않나요?
템플릿 목록 조회도 하기는 하지만, 옵션에 따라 다르게 반환하는데 단순히 템플릿 목록 조회라고 하면 명확하지 못 한 것 같습니다.

2024-09-20 04:28 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            Page<Template> actual = sut.findAll(memberId, keyword, categoryId, tagIds, pageable);
저는 조금 반대입니다. 다른 테스트들도 같이 본다면 변수 할당을 하지 않아도 어떤 변수들에 null이 들어간건지 바로 알 수 있지만, 해당 테스트 코드만을 봤을 때는 알기 힘들다고 생각해요

2024-09-20 04:30 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +                                    templateRepository.fetchById(2L)),
이거...한 줄로 쓰면 자동으로 줄바꿈 됩니다..😭

2024-09-20 04:32 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            );
해당 테스트 코드들을 `TemplateJpaRepositoryTest`에서 가져와서..
줄바꿈 수정하는 김에 해당 클래스도 같이 수정해서 올리겠습니다.

2024-09-20 04:36 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +    class CreateTemplate {
해당 검증에 대한 구현은 되어있습니다.
다만 현재 저희 서비스 로직에서 카테고리 사용 권한에 대한 검증은 다른 클래스에서 진행되고 있어서 해당 클래스에서는 진행하지 않았습니

2024-09-20 04:37 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            var template3 = templateRepository.save(TemplateFixture.get(member2, category));
오 그렇네요!! 완전히 놓치고 있었네요. 좋은 피드백 감사합니다.

2024-09-20 04:38 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +            }
어이쿠...당장 삭제했습니다!

2024-09-20 04:46 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +    class FindAll {
좋은 테스트네요!! 다만 현재는 Pageable에 대한 null 체크가 없어서 NPE가 발생하고 있습니다.
추후에 null 체크 로직이 필요할 것 같아서 @Disabled 처리해놨습니다!

2024-09-20 05:19 UTC, zeus6768 approved these changes
고생 많았습니다 🚀

2024-09-20 09:35 UTC, kyum-q approved these changes
초롱 수고하셨어요 ~

2024-09-20 10:13 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +    class CreateTemplate {
> 않았습니...

앗 그렇군요! 확인했습니다~

2024-09-20 10:14 UTC, zangsu approved these changes
고생했습니다 초롱~! 
이번 미션도 여기서 approve 하겠습니다!
다음 미션도 파이팅입니다 🔥

2024-09-20 11:11 UTC, jminkkk reviewed
안녕하세요 초롱 ~ 
리뷰 반영된 것 같아 어프루브 합니다! 최고 👍

별개로 리뷰 중 제 의도와 다르게 전달된 부분들이 있는 것 같아서 코멘트를 남겼는데 확인해주시면 좋을 것 같아요~!

2024-09-20 11:11 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +    class FindAll {
맞아요~ 요청드린 것 중에 여러개가 제가 작성한 것도 알고 있어요
그래서 제가 더 정정해야겠다고 생각했어요

---

저는 템플릿을 조회하는 기능 중에 키워드 검색이 있는 것 같다고 생각을 했었어요.
또 검색 보다는 조회가 더 큰 범위라고 생각해서 정정 부탁드렸습니답...

마이페이지에서 내 글만 조회를 하거나, 필터링이 전혀 없이 단순 `GET /templates` 을 한다고 생각을 했을 때 오히려 조회가 더 명확할 것 같아서요. 그런데 사람마다 다르게 느껴질 수도 있겠네요 🤔

제 의견에 대한 설명이 없어서 의도와 다르게 전달된 것 같아서 의견 전달만 명확하게 드려봅니다~ 🔥

2024-09-20 11:12 UTC, jminkkk approved these changes

2024-09-20 13:27 UTC, merged