썸네일 서비스 테스트코드 작성
woowacourse-teams/2024-code-zap pull request #662
Opened 2024-09-18 01:27 UTC by HoeSeong123

## ⚡️ 관련 이슈
close #645 

## 📍주요 변경 사항
ThumbnailSerivce 테스트 작성

## 🎸기타
### 리팩토링
- 사용하지 않는 메서드 삭제
  - https://github.com/woowacourse-teams/2024-code-zap/issues/650#issuecomment-2357303578
- 중복 검사 로직
  - https://github.com/woowacourse-teams/2024-code-zap/issues/650#issuecomment-2357302571

2024-09-18 15:08 UTC, kyum-q reviewed
굿 ~! 수고하셨습니다 초롱 ~~

2024-09-18 15:08 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +            assertThat(actual.get(0).getTemplate()).isEqualTo(template);
assertAll로 뭉쳐줄까요?!

2024-09-19 05:03 UTC, jminkkk reviewed
안녕하세요 초롱~
수고하셨습니다 🔥
코멘트 남겨보았으니 확인 부탁드립니당

2024-09-19 05:03 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +            var template = templateRepository.save(TemplateFixture.get(member, category));
중복되는 코드 private 메서드로 추출해볼까요?

2024-09-19 12:06 UTC, zangsu commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +            var template = templateRepository.save(TemplateFixture.get(member, category));
@jminkkk 
몰리가 이야기한 중복되는 코드가 바로 위의 3줄일까요?
그렇다면 저는 이정도 길이의 given 절이라면 굳이 메서드로 추출하지 않는 것이 가독성에 더 좋다고 생각하는데요...!

코드 블럭에서 사용하는 대부분의 변수들을 모두 파악할 수 있어야 가독성이 좋아진다고 생각해요.

2024-09-19 12:32 UTC, zangsu reviewed
초롱 고생 많으셨어요~~
몇가지 코멘트 남겨둡니다!

2024-09-19 12:32 UTC, zangsu commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +            assertThat(actual.get(0).getTemplate()).isEqualTo(template);
```suggestion
            var member = memberRepository.save(MemberFixture.getFirstMember());
            var category = categoryRepository.save(CategoryFixture.getFirstCategory());
            var template = templateRepository.save(TemplateFixture.get(member, category));
            var sourceCode = sourceCodeRepository.save(new SourceCode(template, "Filename 1", "Content 1", 1));
            var savedThumbnail = thumbnailRepository.save(new Thumbnail(template, sourceCode));
            var nonExistentID = 100L;

            sut.deleteByTemplateIds(List.of(nonExistentID));
            var actual = thumbnailRepository.findAll();

            assertThat(actual).hasSize(1)
                    .containsExactly(savedThumbnail);
```

2024-09-19 12:32 UTC, zangsu commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +            assertThat(actual.get(0).getTemplate()).isEqualTo(template2);
```suggestion
            var member = memberRepository.save(MemberFixture.getFirstMember());
            var category = categoryRepository.save(CategoryFixture.getFirstCategory());
            var template1 = templateRepository.save(TemplateFixture.get(member, category));
            var sourceCode1 = sourceCodeRepository.save(new SourceCode(template1, "Filename 1", "Content 1", 1));
            var thumbnail1 = thumbnailRepository.save(new Thumbnail(template1, sourceCode1));
            var template2 = templateRepository.save(TemplateFixture.get(member, category));
            var sourceCode2 = sourceCodeRepository.save(new SourceCode(template2, "Filename 2", "Content 2", 1));
            var thumbnail2 = thumbnailRepository.save(new Thumbnail(template2, sourceCode2));

            sut.deleteByTemplateIds(List.of(template1.getId()));
            var actual = thumbnailRepository.findAll();

            assertThat(actual).hasSize(1)
                    .containsExactly(thumbnail2)
                    .doesNotContain(thumbnail1);
```

이부분도 체이닝으로 변경해 보았어요.

2024-09-19 12:32 UTC, zangsu commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +        @DisplayName("썸네일 삭제 성공")
하나의 썸네일이 삭제되는 걸 확인했을 때 여러개의 삭제가 잘 동작함을 보장받는 것은 조금 어려울 것 같아요.
하지만 여러개의 삭제를 확인한다면 하나의 삭제가 잘 동작할거라 보장받을 수 있을 것 같습니다.

두 개 이상의 썸네일을 삭제하도록 코드를 작성해도 좋을 것 같아요.

2024-09-19 12:32 UTC, zangsu commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +class ThumbnailServiceTest {
`findAll()` 메서드는 예외 상황이 없어서 테스트코드를 작성하지 않은거죠?

2024-09-19 16:52 UTC, zeus6768 requested changes
초롱 고생많았어요 😭

간단한 제안 몇 개 남겼습니다~!

2024-09-19 16:52 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +        }
id와 소스코드까지 assert문으로 검증하는 건 어떨까요?

2024-09-19 16:52 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +            assertThat(actual).hasSize(1);
fetchByTemplate이나 fetchById로 가져와서 필드가 일치하는지 확인하는 게 더 좋다고 생각하는데, 초롱은 어떤가요~?

2024-09-20 04:51 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +class ThumbnailServiceTest {
`findAll()` 메서드는 현재 사용되지 않고 있습니다!! 본문에 링크 걸어놨습니닷!

2024-09-20 04:55 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +            var template = templateRepository.save(TemplateFixture.get(member, category));
이거는 일부러 분리하지 않았는데요, 전에 켬미와 얘기했던 @BeforeEach를 사용하지 않는 이유에 동의했기 때문입니다!
물론 private 메서드로 분리하는 것은 @BeforeEach보다는 덜하겠지만 그래도 어떤 객체들이 저장되어 있는지 테스트 코드 안에서 바로 확인할 수 있는게 보다 명확하게 알 수 있지 않을까 싶어서 분리하지 않았습니다.
또한 코드의 길이가 길지 않아 테스트 코드의 가독성을 해친다는 느낌도 없는 것 같은데 몰리의 의견은 어떤가요?

2024-09-20 05:02 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +        @DisplayName("썸네일 삭제 성공")
그렇네요!! 추가했습니다!

2024-09-20 05:07 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +            assertThat(actual).hasSize(1);
훨씬 좋은 것 같네요!! 반영했습니다😁

2024-09-20 05:21 UTC, zeus6768 approved these changes
👍

2024-09-20 09:36 UTC, kyum-q approved these changes
초롱 짱 ! 수고하셨어요 ~!

2024-09-20 11:18 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
> +            var template = templateRepository.save(TemplateFixture.get(member, category));
`@BeforeEach`를 사용하지 않았던 이유가 특정 테스트만 조회할 때 `@BeforeEach` 보지 못하고 이해하지 못할까봐로 저는 알고 있는데 같은 이유가 맞나요? 

그렇다면, private 메서드는 `@BeforeEach`과 다르게 메서드 안에서 "선언"을 해주기 때문에 괜찮다고 생각해요.
또 private 메서드를 사용하더라도 이름을 명확하게 설정해주면 메서드를 정말 확인하지 않아도 파악할 수 있을 것 ~~(레벨 1 네오 강의 의견처럼요)~~ 이라고도 생각해요.

2024-09-22 04:13 UTC, jminkkk approved these changes

2024-09-22 04:13 UTC, merged