TemplateApplicationService 테스트
woowacourse-teams/2024-code-zap pull request #665
Opened 2024-09-18 07:21 UTC by zeus6768

## ⚡️ 관련 이슈
close #645, #664

## 📍주요 변경 사항
예외 케이스까지 한 번에 하려니 너무 오래 걸려서 happy case 테스트만 작성했습니다 😵‍💫😵🫠

또, happy case에서도 sut 실행 결과의 객체 그래프가 너무 깊은 경우 `assertThatCode().doesNotThrowAnyException()`을 사용했습니다. 

점진적으로 케이스를 추가해야할 것 같습니다 😭

## 🎸기타
테스트코드만 작성하기로 했는데, 프로덕션 코드를 변경하지 않으면 happy case조차 작성할 수 없을 것 같아 변경사항이 있습니다. 

#664 에서 논의를 제안합니다.

2024-09-18 07:56 UTC, zeus6768 commented
테스트케이스 추가 작업이 필요한 내용에 대해 기록합니다. 

### `TemplateApplicationServiceTest findAllBy()` 테스트

- memberId, keyword, categoryId, tagIds , pageable 을 인자로 받는 메서드
- 파라미터의 존재 여부만으로도 2^5=32 개의 테스트 케이스가 나온다. 
- 여기서 TagId의 유효성과 개수에 따라 테스트 케이스가 수십개 발생한다.

2024-09-19 07:34 UTC, jminkkk requested changes
안녕하세요 제우스
수고하셨습니다 🔥
실패 테스트는 이 계층에 맞는 실패케이스만 작성하면 될 것 같은데 어렵긴 하네요 😭

2024-09-19 07:34 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +                    sourceCode2.getOrdinal());
⚡️ 소스 코드를 저장하고 저장한 소스코드에 대한 UpdateSourceCodeRequest를 반환하는 메서드를 추출해보면 어떨까요?

2024-09-19 07:34 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +            var sourceCode1 = sourceCodeRepository.save(new SourceCode(template1, "filename1", "content1", 1));
SourceCodeFixture를 사용해보면 어떨까요?

2024-09-19 07:34 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +            var template1 = templateRepository.save(new Template(member, "title1", "description", category));
현재 있는 TemplateFixture를 사용하지 않은 이유가 있을까요? 
없다면 참고해보시면 좋을 것 같습니답

2024-09-20 02:34 UTC, kyum-q submitted a review, later dismissed
어제 합의 전에 간단하게 코멘트 적었던 것 입니다~
시간되면 확인 부탁드려요 ~

2024-09-20 04:27 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +    ThumbnailRepository thumbnailRepository;
본 테스트코드에서는 필드의 접근제어자가 큰 의미가 없다고 생각해서, 타이핑을 덜 하는 방향으로 작성했어요 😀

몰리는 private으로 선언하는 게 더 좋다고 생각하나요? 그렇다면 이유가 궁금해요~

몰리가 이전의 PR에서 ServiceTest 추상클래스를 만들었던데, 머지 이후 해당 추상클래스를 상속받으면 좋을 것 같아요.

2024-09-20 04:31 UTC, zeus6768 commented on backend/src/main/java/codezap/template/domain/Template.java
>              throw new CodeZapException(HttpStatus.UNAUTHORIZED, "해당 템플릿에 대한 권한이 없습니다.");
그렇게 할게요~!

2024-09-20 04:50 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +                    sourceCode2.getOrdinal());
```suggestion
            var sourceCode1 = sourceCodeRepository.save(new SourceCode(template, "filename1", "content1", 1));
            var sourceCode2 = sourceCodeRepository.save(new SourceCode(template, "filename2", "content2", 2));
            thumbnailRepository.save(new Thumbnail(template, sourceCode1));
            var createRequest = List.of(new CreateSourceCodeRequest("filename3", "content3", 3));
            var updateRequest1 = updateSourceCodeRequest(sourceCode1);
            var updateRequest2 = updateSourceCodeRequest(sourceCode2);
                    
        private UpdateSourceCodeRequest updateSourceCodeRequest(SourceCode sourceCode) {
            return new UpdateSourceCodeRequest(
                    sourceCode.getId(),
                    sourceCode.getFilename(),
                    sourceCode.getContent(),
                    sourceCode.getOrdinal());
        }
```

소스코드를 저장하는데 필요한 도메인 객체들이 단언문에서 사용되고 중간에 다른 도메인을 저장하기도 하기 때문에 소스코드의 저장부터 request 반환까지 한 번에 처리하는 로직을 작성하는데는 어려움이 있어요. 

일단 updateSourceCodeRequest를 줄이기 위한 메서드 분리까지는 했습니다!

2024-09-20 04:55 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +            var sourceCode1 = sourceCodeRepository.save(new SourceCode(template1, "filename1", "content1", 1));
SourceCodeFixture가 존재하지 않는데, 클래스를 새로 만들어 사용하라는 의견이 맞나요? 

일단 픽스처 클래스를 만드는 작업은 우선순위가 낮다고 생각해 넘어갔습니다!

2024-09-20 04:56 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +            var template1 = templateRepository.save(new Template(member, "title1", "description", category));
반영했습니다!

2024-09-20 05:09 UTC, HoeSeong123 approved these changes
리뷰를 하지는 못했지만 고생많으셨습니다.

2024-09-20 09:39 UTC, kyum-q approved these changes
제우스 짱 ! 수고하셨습니다 ~!

2024-09-20 10:29 UTC, zangsu approved these changes
고생 많으셨어요 즈후~~~

2024-09-22 04:14 UTC, jminkkk approved these changes

2024-09-22 04:15 UTC, merged