좋아요 swagger 문서화 제공
woowacourse-teams/2024-code-zap pull request #675
Opened 2024-09-20 01:10 UTC by zangsu

## ⚡️ 관련 이슈
close #668 

## 📍주요 변경 사항
- 좋아요 API 제공
- 기존 템플릿 조회 정보에 좋아요 수, 좋아요 여부 포함

## 🎸기타
@vi-wolhwa 
코드 읽을만하면 미리 문서 확인 후 변경이 필요한 부분을 공유해 주시면 더 좋아요~~

2024-09-20 10:47 UTC, vi-wolhwa commented on backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
> +        Boolean isLike,
isLiked로 변경 가능할까용가리모콘칩..!

2024-09-20 10:48 UTC, zangsu commented on backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
> +        Boolean isLike,
절대 가능하죠~!! 반영해두겠습니다~

2024-09-20 12:13 UTC, jminkkk requested changes
안녕하세요 짱수 
문서화 수고하셨어요 👍
코멘트 남겨보았으니 확인 부탁드려요!

같이 얘기 편하게 나눠봅시당 🔥

2024-09-20 12:13 UTC, jminkkk commented on backend/src/main/java/codezap/template/controller/LikeController.java
> +    @PostMapping("dislike/{templateId}")
`좋아요`라는 리소스를 취소한다는 API이군요!
⚡️ POST는 서버 입장에서 새로운 리소스를 생성한다는 의미로 받아들여지기 때문에, 좋아요를 삭제하는 API는 DELETE는 어떨까 싶네요!

---

혹시 만약 우리 서비스가 커져서, 템플릿 언따봉(ㅋㅋ) 기능이 생긴다면 어떻게 API를 구현할 수 있을까요?
함께 생각해보면 도움이 될 것 같아요 🔥

2024-09-20 13:47 UTC, kyum-q requested changes
짱수 좋아요까지 하려니 고생이 많아요 ㅜㅜ 좋아요 기능에 관해 DB 테이블 고민을 더 해보면  좋을 것 같아서 코멘트로 제 의견 달아둿어요 ~ 함께 고민해봐요 ~

2024-09-20 13:47 UTC, kyum-q commented on backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
> +
⚡(해당 부분에 대해 이야기해봐야한다고 생각해서 ⚡표시 달아요 ~!)
조회 회원의 좋아요 여부가 뭔지 모르겠어요 
말 그대로 템플릿을 조회하는 회원이 해당 템플릿에 좋아요를 눌렀는지 여부인건가요?
하나의 템플릿이 조회 멤버에 따라 해당 값이 다르겠죠? 그렇다면 해당 필드는 템플릿에 있을 필드가 아니라고 생각합니다. 

위에 몰리가 작성한 코멘트처럼 좋아요 필드를 따로 빼서 관리하면 더 좋을 것 같아요

어떻게 말씀드릴지 몰라 간단하게 erd를 작성해봤는데 다음과 같이 like 도메인을 빼서 멤버와 템플릿 정보를 저장하면 더 편리할 것 같아요.

그리고 템플릿의 좋아요 수는 like 테이블에 해당 템플릿의 like 개수를 세면 되고, 조회 회원의 좋아요 여부는 해당 테이블에 값이 존재하는지 확인하면 되지 않을까요?

![image](https://github.com/user-attachments/assets/1be329f3-b3e6-4389-9f48-69618861e9c1)

2024-09-21 11:27 UTC, zeus6768 requested changes
고생 많았어요 짱수~~👍

몰리 말처럼 도메인 분리가 더 좋다고 생각해 RC 남겨요~

2024-09-21 11:27 UTC, zeus6768 commented on backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
> +        @Schema(description = "조회 회원의 좋아요 여부", example = "true")
LikeController 명세에서는 `멤버`라고 했는데 여기서는 `회원`이라고 칭하고 있어요.

하나로 통일하는 건 어떨까요?

2024-09-21 11:27 UTC, zeus6768 commented on backend/src/main/java/codezap/template/controller/SpringDocsLikeController.java
> +            @ErrorCase(description = "템플릿 Id 에 해당하는 템플릿이 존재하지 않는 경우", exampleMessage = "식별자 1에 해당하는 템플릿이 존재하지 않습니다.")
둘 중 무엇이든 `ID`와 `식별자` 중 하나로 통일하는 건 어떨까요?

2024-09-21 16:06 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/LikeController.java
> +package codezap.template.controller;
오, 단순히 좋아요는 템플릿에 의존적이니까... 라고 생각하고 하나의 패키지에 두었는데요!
API 이야기도, 확장에 관련된 의견도 동의합니다!
패키지를 분리해 둘게요!

2024-09-21 16:10 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/LikeController.java
> +    @PostMapping("dislike/{templateId}")
언따봉 ㅋㅋ
너무 이해되었습니다~!!
몰리 체고~~

2024-09-21 16:18 UTC, zangsu commented on backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
> +        @Schema(description = "조회 회원의 좋아요 여부", example = "true")
오, 문서를 작성하면서는 이런 부분이 잘 안보이는군요 ㅠㅠ
바~로 수정해 두겠습니닷!

2024-09-21 16:23 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocsLikeController.java
> +            @ErrorCase(description = "템플릿 Id 에 해당하는 템플릿이 존재하지 않는 경우", exampleMessage = "식별자 1에 해당하는 템플릿이 존재하지 않습니다.")
흠 이부분은 "식별자 XX 에 해당하는 YY 가 존재하지 않습니다." 가 공통적으로 사용되는 에러 메시지 인 것 같아서 차용하였는데요.
그렇다고 템플릿 식별자에 해당하는 템플릿이 존재하지 않는 경우 라고 적으면 지금보다 잘 이해가 될까 라는 생각이 들기도 해요.
zeus~ 는 어떻게 생각하시나요?!

2024-09-21 16:23 UTC, zangsu commented
@kyum-q 
맞아요! 다대다 관계이기에 중간 테이블을 둘 생각입니다!

2024-09-22 06:17 UTC, kyum-q approved these changes
굿 ! 짱 수 정 말 최 고 에 요

2024-09-22 06:59 UTC, HoeSeong123 approved these changes
피드백이 많이 달려서 추가할만한 건 없는 것 같네요.
고생하셨습니다!!

2024-09-22 07:30 UTC, zeus6768 approved these changes
짱수 👍

2024-09-22 07:32 UTC, zeus6768 commented on backend/src/main/java/codezap/template/controller/SpringDocsLikeController.java
> +            @ErrorCase(description = "템플릿 Id 에 해당하는 템플릿이 존재하지 않는 경우", exampleMessage = "식별자 1에 해당하는 템플릿이 존재하지 않습니다.")
이미 해당 표현이 다른 곳에서도 사용되고 있어서 고민이 좀 되겠는걸요 ㅎㅎ...

개인적으로는 모든 곳에서 ID로 통일하면 좋겠어요~!

2024-09-22 07:37 UTC, vi-wolhwa commented
좋아요좋아요! 주말 동안 고생하셨습니다!!

2024-09-22 08:43 UTC, vi-wolhwa approved these changes

2024-09-22 08:50 UTC, jminkkk approved these changes

2024-09-22 08:51 UTC, merged