서비스 계층 리팩토링
woowacourse-teams/2024-code-zap pull request #679
Opened 2024-09-22 18:12 UTC by zeus6768

## ⚡️ 관련 이슈
#650 

## 📍주요 변경 사항

서비스 레이어 전체를 리팩토링했습니다.

그래서 변경된 파일이 많이 잡히는데, 주요 리뷰 포인트는 다음과 같습니다. 

1. `ArgumentResolver`의 반환타입 변경 `MemberDto` → `Member`
2. 서비스 레이어 다이어트
3. 테스트코드 병합 잘 됐는지

## 🎸 더 할 일
- 메서드명 통일
- 레거시 코드 제거 및 개선
- 주석 표시된 테스트코드 해결

2024-09-23 11:37 UTC, zangsu reviewed
제우스 고생하셨습니다~!!
최대한 열심히 살펴보았어요...!
가벼운 코멘트 남겨 두었으니 확인 부탁드려용~

2024-09-23 11:37 UTC, zangsu commented on backend/src/main/java/codezap/tag/service/TagService.java
> -    public List<Long> getTemplateIdContainTagIds(List<Long> tagIds) {
이 메서드는 필요가 없어서 완전히 삭제된 메서드인가요??
그렇다면 `TemplateTagRepository.findAllTemplateIdInTagIds()` 메서드도 함께 삭제해도 될 것 같아요!

+) 얘는 그럼 `Template` 목록 조회에 합쳐진건가용?

2024-09-23 13:44 UTC, jminkkk reviewed
안녕하세요 제우스~
리팩토링 어마어마하네요 🔥
진짜 왕수고하셨습니다 

자잘한 코멘트 남겨보았으니 확인해주세욥 퐈이팅  🔥🔥🔥

2024-09-23 13:44 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        category.validateAuthorization(member);
이게 이 pr 내용에 포함되어도 되는 리뷰인지는 모르겠지만 아니라도 기록은 있어야 할 것 같아 남겨요!
(제우스 판단 하에 반영 여부를 결정하시면 좋을 것 같슴다)

```suggestion
        Category category = categoryService.findOwnCategoryById(member, createTemplateRequest.categoryId()); // 메서드 이름은 더 적절한 것으로 바꾸기
```

이 로직이 2번 사용되고 있는데 두번 다 권한 확인까지 하고 있어요!
categoryService단에서 권한까지 확인한 후 권한이 있는 경우에만 카테고리를 반환하는 로직으로 가도 좋을듯합니다!

2024-09-23 13:44 UTC, jminkkk commented on backend/src/main/java/codezap/tag/service/TagService.java
> +        return findAllByTemplates(template);
이거 findAllByTemplates가 여기에서만 사용되는 것 같고 findAllByMemberId의 역할이 크지 않아보여서 메서드 합쳐버려도 좋을 것 같아요~!

2024-09-23 13:44 UTC, jminkkk commented on backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
> +                FindMemberResponse.from(template.getMember()),
와우 이건 계속 null로 가고 있었나보군요 꼼꼼 굿 👍

2024-09-23 13:44 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +                .toList();
⚡️ 엇 이 부분 예전 코드로 기억하는데 롤백된 이유가 있나요...??

예전에 작성자 정보 응답에 추가하면서 있었던 코드 같은데, 리팩토링 했던 걸로 기억해요....(아닐수도)
코드가 잘못 들어간 것 같아서 확인 부탁드립니답

2024-09-23 15:46 UTC, HoeSeong123 requested changes
고생하셨습니다 제우스!!
테스트 코드에 대한건 나중에 다시 한 번 전체적으로 확인이 필요하다고 생각돼서 주의깊게 보지는 않았습니다.
큰 작업이었을텐데 엄청 꼼꼼하게 하셨네요!!👍

2024-09-23 16:35 UTC, kyum-q requested changes
제우스 수고하셨어욧 !! 이번에 전반적으로 깔끔해진 것 같아서 좋네요 ~!
이번에 서비스 리펙터링하는 김에 최대한 꼼꼼히 보려고 하다보니 변경되지 않은 부분도 다 확인해서 코멘트 달아뒀어요
거의 대부분이 사용하지 않는 메서드, 혹은 transaction 처리 관련입니다. 확인 부탁드려요 ~

2024-09-23 16:35 UTC, kyum-q commented on backend/src/main/java/codezap/member/service/MemberService.java
> -import codezap.member.dto.MemberDto;
> 변경사항이 잡히지 않은 부분이라서 해당 위치에 코멘트 합니다 

⚡ signup 로직에도 @Transactional이 있어야한다고 생각합니다.
멤버가 만들어졌는데 카테고리 제작 중 문제가 생겼을 때 롤백 되어야한다 생각합니다 !

2024-09-23 16:35 UTC, kyum-q commented on backend/src/main/java/codezap/member/service/MemberService.java
> +        if (!Objects.equals(member.getId(), id)) {
checkSameMember 메서드가 사용되는 public 메서드(findMember) 바로 아래에 위치하면 더 좋을 것 같아요

2024-09-23 16:35 UTC, kyum-q commented on backend/src/main/java/codezap/member/service/MemberService.java
> -import codezap.member.dto.MemberDto;
> 변경사항이 잡히지 않은 부분이라서 해당 위치에 코멘트 합니다

⚡ `public Member getById(Long id)` 가 테스트 외에는 사용되지 않는 메서드 인 것 같습니다 확인하고 제거해주세요

2024-09-23 16:35 UTC, kyum-q commented on backend/src/main/java/codezap/tag/service/TagService.java
> +import codezap.template.repository.TemplateRepository;
> 변경사항이 잡히지 않은 부분이라서 해당 위치에 코멘트 합니다

`public void deleteByIds(List<Long> templateIds)` 로직에 @transactional이 있어야하지 않을까요?
제 생각에 있어야할 것 같은데, 잘 모르겠네요 ~🤔

2024-09-23 16:35 UTC, kyum-q commented on backend/src/main/java/codezap/tag/service/TagService.java
> +import codezap.template.repository.TemplateRepository;
> 변경사항이 잡히지 않은 부분이라서 해당 위치에 코멘트 합니다

다음 메서드들이 fakeDB 혹은 테스트 외에는 사용되지 않더라고요! 근데 기본으로 제공하는 메서드이니 그냥 남겨두어도 될까요? 잘 모르겠어서 일단 알려드려요 !

+ TagRepository
    + `boolean existsById(Long id);` , `boolean existsByName(String name);`, `Tag save(Tag tag);`

+ TemplateTagRepository
    + `List<TemplateTag> findAll();`, `TemplateTag save(TemplateTag templateTag);` 
    + 심지어 findAll은 아무데서도 사용되지 않음

+ MemberRepository
    + `boolean existsById(Long id);`

+ SourceCodeRepository
    + `List<SourceCode> findAll();`
    + `SourceCode save(SourceCode sourceCode);`

+ TemplateRepository
    + `List<Template> findAll();`

2024-09-23 16:35 UTC, kyum-q commented on backend/src/main/java/codezap/tag/service/TagService.java
> +import codezap.template.repository.TemplateRepository;
> 변경사항이 잡히지 않은 부분이라서 해당 위치에 코멘트 합니다

⚡ TemplateTagRepository의 `List<Long> findAllTemplateIdInTagIds(List<Long> tagIds, long tagSize);`가 테스트 코드 말고는 어디에서도 사용되지 않습니다 ~ 확인하고 제거해주세요 

⚡ ThumbnailRepository의 `Thumbnail fetchById(Long id);`도 테스트 코드 말고는 어디에서도 사용되지 않습니다 ~ 확인하고 제거해주세요

2024-09-23 16:35 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +                .toList();
예전 코드인지는 잘 모르겠지만 변경되기 전인 `return makeTemplatesResponse(templates);`로 그대로 해도 무관할 것 같습니다 !
그렇게 된다면 memberService는 해당 파사드 서비스에서 없어지겠네요 ~

2024-09-23 16:35 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/SourceCodeService.java
> +
> 코드 변경이 없어서 여기다 코멘트 남깁니다

정말 사소하지만 updateSourceCodes메서드에서 사용되는 private 메서드 순서를 호출하는 순서대로 정렬하면 보기 더 편할 것 같아요 !

1. updateSourceCode 
2. createSourceCode
3. updateThumbnail
4. refreshThumbnail
5. validateSourceCodesCount

2024-09-26 04:41 UTC, zeus6768 commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +                .toList();
`FindAllTemplateItemResponse`를 `FindTemplateResponse`의 로직과 같게 만들어 해당 부분 고쳤습니다 🚀

2024-09-26 06:15 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/service/CategoryService.java
>  public class CategoryService {
확인했씁니당!!

2024-09-26 06:28 UTC, jminkkk approved these changes
완전 수고했어요 
🔥🔥 즈후 최고 🔥🔥

2024-09-26 06:28 UTC, jminkkk commented on backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
> +                        .map(FindTagResponse::from)
<img src = https://github.com/user-attachments/assets/a670190c-14f3-4858-8365-bade6a0faf4f width = 70%>

2024-09-26 07:47 UTC, kyum-q approved these changes
귯 쟙 입니다 ~!!!!! 수고하셨어용 ~~~~~

2024-09-26 08:13 UTC, zangsu approved these changes
그저 빛 ⚡ 
고생하셨습니다~

2024-09-26 08:27 UTC, HoeSeong123 approved these changes
확인했습니다 고생하셨습니다~~

2024-09-26 08:28 UTC, merged