좋아요 기능 구현
woowacourse-teams/2024-code-zap pull request #680
Opened 2024-09-23 03:17 UTC by zangsu

## ⚡️ 관련 이슈
#668

## 📍주요 변경 사항
- 좋아요, 좋아요 취소 기능
- "구경가기" 에서 좋아요 순으로 정렬 기능
- 상세 정보, 목록 조회에 좋아요 정보 포함
  - 좋아요 수, 좋아요 여부

2024-09-23 03:19 UTC, zangsu commented on backend/src/main/java/codezap/template/domain/Template.java
> +    @Formula("(select count(*) from likes where likes.template_id = id)")
`@Formula` 는 실제 DB 에 컬럼으로 존재하지 않는 값을 필드로 매핑하기 위해 사용합니다.
"좋아요 많은 순으로 정렬" 기능을 구현하기 위해 추가되었습니다.

출처 : [벨로그](https://velog.io/@dlthgml0108/JPA-Formula-%EA%B2%8C%EC%8B%9C%EA%B8%80-%EC%A2%8B%EC%95%84%EC%9A%94-%EC%88%9C%EC%9C%BC%EB%A1%9C-%EC%A0%95%EB%A0%AC%ED%95%98%EA%B8%B0)

이곳에서도 성능 문제가 발생할 가능성이 존재하며, "좋아요 순 정렬" 의 구현 방법 자체에 대해 더 논의가 필요할 수 있겠습니다.

2024-09-23 03:30 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +    @Operation(summary = "템플릿 조회 (회원)", description = """
템플릿 단건조회 / 목록 조회 api 가 회원 전용 / 비회원 전용 으로 분리되었습니다.
이유는 아래와 같습니다.

## 1. 현재 로그인 확인 기능의 구현

좋아요 기능이 추가되면서 템플릿 정보에 "좋아요 여부" 가 포함되었습니다.
즉, 조회하는 사람 기준으로 해당 템플릿을 좋아요 했는지 확인해야 하는데요.
이 때, 로그인이 되어 있지 않으면 무조건 좋아요를 하지 않았다고 정보를 넘겨 주어야 합니다.

문제는, 컨트롤러에서 로그인 정보를 확인하기 위해 `MemberDto` 를 파라미터로 받는 순간 로그인이 되지 않은 요청은 잘못된 요청으로 간주하게 됩니다. 
문제를 해결하기 위해 api 를 분리하였습니다.

추후 `Optional<Member>` 를 파라미터로 받는 등의 방법으로 개선하여 api 를 다시 하나로 합칠 수 있을 것 같습니다.

2024-09-23 03:32 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +              - 좋아요 수가 많은 순 (likesCount, desc) \n
@vi-wolhwa 
좋아요 순 정렬 요청 조건이 변경될 예정입니다. 참고해 주세요~
sort = like -> sort = likesCount

2024-09-23 09:41 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +    @GetMapping("/{id}/login")
@vi-wolhwa 
로그인을 한 이후의 요청은 템플릿 조회 요청 뒤에 "/login" 을 붙여주세요!

- 템플릿 단건 조회
    - GET /template/1 -> GET /template/1/login 
- 템플릿 목록 조회
    - GET /templates -> GET /templates/login

2024-09-23 12:49 UTC, HoeSeong123 requested changes
안녕하세요 짱수!!
혼자서 기능 하나를 통째로 담당하느라 힘들었을 것 같은데 짧은 시간 안에 굉장히 빠르게 구현해주셨네요.
시간이 얼마 없어서 놓친 부분이 혹시나 있을까봐 최대한 꼼꼼하게 리뷰해봤습니다.
조금이라도 도움이 됐으면 좋겠네요!!

고생 많으셨습니다 짱수 👍👍👍👍👍

2024-09-23 12:49 UTC, HoeSeong123 commented on backend/src/main/java/codezap/like/service/LikesService.java
> +        }
⚡
```suggestion
        if (isLike(template, member)) {
            return;
        }
```

2024-09-23 12:49 UTC, HoeSeong123 commented on backend/src/main/java/codezap/like/service/LikesService.java
> +        }
이 코드가 전에 얘기했던 요청이 여러번 오는 것에 대한 처리인가요? 만약 맞다면 조금만 더 자세히 이야기해주세요. 그 때 이야기를 자세히 들었던 건 아니라..
해당 코드의 필요성을 잘 모르겠어서 물어봅니다!!

2024-09-23 12:49 UTC, HoeSeong123 commented on backend/src/main/java/codezap/like/service/LikesService.java
> +        Likes likes = template.like(member);
```suggestion
        Likes likes = new Likes(template, member);
```
`Likes` 생성에 대한 책임을 `Template`에게 넘겨준 이유가 있으신가요? 위와 같이 `LikesSerivce`에서 `Likes`를 생성해도 크게 어색하지 않은 것 같아서요!

2024-09-23 12:49 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +              - 좋아요 수가 많은 순 (likesCount, desc) \n
오늘 얘기가 나온 김에 리뷰 달아놓습니다~~ 나중에 논의를 해봐야할까요? 아니면 다른 의견 있으신 분은 댓글로? 어떻게 하는게 좋으려나~
```suggestion
              - 좋아요 순 (likesCount, desc) \n
```

2024-09-23 12:49 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +    @GetMapping("/{id}/login")
> - 템플릿 단건 조회
>   - GET /template/1 -> GET /template/1/login

템플릿 단건 조회시에도 /templates/1 아닌가요??

2024-09-23 12:49 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +    @GetMapping("/{id}/login")
/login이 붙으면 헷갈리지 않을까요..?
이 부분은 Optional로 쓰게 되면 사라질 부분인거죠? 만약 안 사라지게 된다면 엔드포인트에 대한 논의가 필요할 것 같기도 하네요..

2024-09-23 12:49 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +    private FindAllTemplatesResponse makeTemplatesResponse(Page<Template> page, LikePredicate likePredicate) {
코드가 조금 많이 복잡한 것 같은데 LikePredicate 대신 Member를 넘겨주고 로그인이 안 되어 있는 경우에는 null을 넘겨주는 건 어떤가요? `likesService.isLike()`에서 만약 null이면 false를 반환한다는 식으로 처리해주는 방식으로요.

2024-09-23 12:49 UTC, HoeSeong123 commented on backend/src/test/java/codezap/like/repository/LikesJpaRepositoryTest.java
> +            assertThat(likesRepository.countByTemplate(template)).isEqualTo(1);
save에 대한 repository 테스트인데 `countByTemplate`이 사용되는 것이 어색한 것 같아요.
```suggestion
            Likes likes = likesRepository.save(new Likes(null, template, member));

            assertAll(
                () -> assertThat(likes.getMember).isEqualTo(member),
                () -> assertThat(likes.getTemplate).isEqualTo(template)
```
추가로 저희 직접 작성한 jpa 쿼리 메소드에 대해서만 테스트를 진행하기로 하지 않았었나요??

2024-09-23 12:49 UTC, HoeSeong123 commented on backend/src/test/java/codezap/like/service/LikesServiceTest.java
> +            likesService.like(MemberDto.from(member), template.getId());
이 부분도 `cancelLike`에 대한 테스트인데 `like`가 사용되는 것이 어색하게 느껴지네요. 아래와 같은 변경은 어떤가요??
```suggestion
            likesRepository.save(new Likes(null, template, member);
```

2024-09-23 12:53 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +    @GetMapping("/{id}/login")
> 템플릿 단건 조회시에도 /templates/1 아닌가요??

앗 고마워요 초롱! 수정해 두었습니다~

> 이 부분은 Optional로 쓰게 되면 사라질 부분인거죠? 만약 안 사라지게 된다면 엔드포인트에 대한 논의가 필요할 것 같기도 하네요..

사라질 예정입니다!
엔드포인트가 상당히 마음에 안들기는 한데, 로그인을 한 경우에만 보낼 api 의 엔드포인트를 어떻게 나타내야 할지를 모르겠네용...ㅎ

2024-09-23 12:54 UTC, zangsu commented on backend/src/main/java/codezap/like/controller/LikesController.java
>  package codezap.like.controller;
`Like` 는 MySQL 에서 문자열 검색에 사용하는 예약어더라구용...ㅎㅎ
오류가 나서 삽질하다가 깨달았습니다! :kk:

2024-09-23 13:02 UTC, zangsu commented on backend/src/main/java/codezap/like/service/LikesService.java
> +        }
이미 좋아요를 한 상황에서 똑같은 좋아요 요청이 들어오는 상황에 대한 처리입니다!
즉, 중복으로 하나의 템플릿에 한 명의 사람이 좋아요를 여러개 생성하는 것을 방지하기 위해 이미 좋아요를 하고 있으면 바로 반환을 해 주는 코드에요!

+) 혹시 제 설명이 부족하다면 해당 부분 주석 처리 후 테스트를 돌려 보셔도 좋습니다!
제 로컬 기준으로 딱 하나의 테스트가 실패하고, 그 경우를 처리하기 위해 작성했어요!

2024-09-23 13:03 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +              - 좋아요 수가 많은 순 (likesCount, desc) \n
저는 이 수정방향 좋은데요~ 
좋아요순 이라는 선택지만 있으면 아무도 좋아요가 적은 순으로 정렬할 것이라 생각하지 않을 것 같아요~!

2024-09-23 13:05 UTC, zangsu commented on backend/src/main/java/codezap/like/service/LikesService.java
> +        Likes likes = template.like(member);
만약 DB 를 사용하지 않는 콘솔 프로그램이었다면 `Likes` 생성 책임이 누구에게 있는 것이 자연스러울까? 
누구에게 `like()` 라는 메서드가 구현될까? 
정도의 고민에서 나온 코드입니다..!

다들 많이 어색하게 느껴지신다면... 수정하겠습니닷 ㅠ
의견 많이들 달아주세용~

2024-09-23 13:06 UTC, zangsu commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +    private FindAllTemplatesResponse makeTemplatesResponse(Page<Template> page, LikePredicate likePredicate) {
흠, 코드가 많이 복잡해 보이는군요,,,ㅠ 
파라미터로 `null` 이 넘어간다는 것은 마음에 드는 선택지는 아니라... 조금 더 고민해 보겠습니닷

2024-09-23 13:09 UTC, zangsu commented on backend/src/test/java/codezap/like/repository/LikesJpaRepositoryTest.java
> +            assertThat(likesRepository.countByTemplate(template)).isEqualTo(1);
> save에 대한 repository 테스트인데 countByTemplate이 사용되는 것이 어색한 것 같아요.

이 부분은 개인적으로는 저장, 삭제, 조회 등을 테스트할때 어쩔 수 없이 발생하는 모순이라 생각해요.
결국 제가 확인하고 싶었던 것은 `save()` 를 저장했을 때 반환값이 아닌, 올바르게 값이 들어있다는 것을 확인하고 싶었습니다.

> 추가로 저희 직접 작성한 jpa 쿼리 메소드에 대해서만 테스트를 진행하기로 하지 않았었나요??

그렇긴 한데, 빠른 시간 내에 기능을 개발하려다 보니 마음이 불안해서...
테스트를 작성해 버리고 말았어요...ㅎㅎ

2024-09-23 13:10 UTC, zangsu commented on backend/src/test/java/codezap/like/service/LikesServiceTest.java
> +            likesService.like(MemberDto.from(member), template.getId());
그렇기도 하고, `Service` 계층 테스트 셋업을 하는데 자신의 다른 메서드를 사용할 필요는 없겠군요!
좋습니닷

2024-09-23 14:17 UTC, jminkkk reviewed
안녕하세요 짱수 🔥
수고했어요 좋아요 굿~!

코멘트 남겼으니 확인 부탁드립니다 
퐈이팅 👍👍👍👍👍👍👍

2024-09-23 14:17 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        return makeTemplatesResponse(templates, (template -> likesService.isLike(template, loginMember)));
음 LikePredicate 을 아예 안쓰고 false, likesService.isLike(template, loginMember))만 넘겨줘도 똑같지 않나요...?
짱수가 LikePredicate를 어떻게 사용하게 되었는지를 제가 이해하지 못한 것 같아요ㅠ
설명 좀...

```suggestion
        return makeTemplatesResponse(templates, false);
    }

    public FindAllTemplatesResponse findAllByWithMember(Long memberId, String keyword, Long categoryId,
            List<Long> tagIds, Pageable pageable, Member loginMember
    ) {
        Page<Template> templates = templateService.findAll(memberId, keyword, categoryId, tagIds, pageable);
        return makeTemplatesResponse(templates, likesService.isLike(template, loginMember));
```

2024-09-23 14:17 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +                            .templates();
정렬이 뭔가 이상한 것 같....

2024-09-23 14:17 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +                    () -> assertThat(notLikesTemplate).allMatch((template) -> template.isLiked() == false)
👍

2024-09-23 14:28 UTC, zangsu commented on backend/src/main/java/codezap/like/domain/Likes.java
> +    private Member member;
오오와!!! 완전히 까먹고 있었습니닷
바로 추가해둘게요~!

2024-09-23 14:42 UTC, zangsu commented on backend/src/main/java/codezap/like/repository/LikesRepository.java
> +}
오, 이 부분은 이야기를 좀 나누어 봐도 좋을 것 같아요.

저는 JpaRepository 들은 일종의 Repository 구현체라고 생각해요.
확장성을 생각한다면 구체적인 것 보단 추상적인 것에 의존을 하는 것이 좋다고 생각하고요.
그래서 저는... Fake 사용 여부와는 상관 없이 이렇게 구현한 것인데, 다들 어떻게 생각하시나요???

2024-09-23 14:42 UTC, zangsu commented on backend/src/main/java/codezap/like/repository/LikesJpaRepository.java
> +@Repository
오!!! 그러네요!!
바로 반영하겠습니닷

2024-09-23 14:52 UTC, zangsu commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +                            .templates();
여기 정렬 어캐해도 이상해보여서...ㅠㅠ 
어떻게 하는 것이 그나마 예쁠까요 선생님들...

2024-09-23 15:23 UTC, zangsu commented
## `LikePredicate` 사용처

`LikePredicate` 사용에 대해 많이들 궁금해 하시는 것 같아 조금 더 설명을 남겨 두겠습니다.
간단하게 말하면 **"전략패턴"** 을 사용한 것인데요.

### 의도

저는 "분리된 두 개의 메서드에서 동일한 `makeTemplatesResponse(Page<Template> page)` 메서드를 사용하고 싶었어요.
`makeTemplatesResponse()` 메서드는 내부적으로 `List<Template>`의 `Template` 들을 각각 `FindAllTemplateItemResponse`으로 변환해 줍니다. 
그 다음 변환된 객체들을 모아 `FindAllTemplatesResponse` 을 만들어 주어야 하고요.

우리는 로그인 여부에 따라 `Template` -> `FindAllTemplateItemResponse` 으로 변환해 주는 과정에서 좋아요 여부를 확인하는 방법이 달라져야 해요.
로그인이 되어 있지 않으면 항상 `isLiked` 는 `false`, 로그인이 되어 있으면 `likesService.isLike()` 결과를 사용합니다.

### 구현

그래서...! 우리는 이 변환 과정에서 사용할 "**좋아요 여부를 확인**" 하는 방법 자체를 **파라미터**로 전달할거에요.
자바에서는 메서드 자체를 파라미터로 전달 하기 위해서 함수형 인터페이스를 사용하고요!

그리고 그 파라미터로 `Predicate` 대신 추상화 계층을 맞춘 `LikePredicate` 를 전달해 준 것입니다.

설명을 잘 했는지... 자신이 없는데 궁금한 점이 있다면 얼마든지 코멘트 더 남겨주세요!!

2024-09-23 15:24 UTC, zangsu commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        return makeTemplatesResponse(templates, (template -> likesService.isLike(template, loginMember)));
아래 [코멘트](https://github.com/woowacourse-teams/2024-code-zap/pull/680#issuecomment-2368629133)로 답변 남겨두었어요.

2024-09-23 15:57 UTC, vi-wolhwa commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +              - 좋아요 수가 많은 순 (likesCount, desc) \n
`likesCount`인 이유가 있을까요? API 응답에서는 `likeCount`를 갖고 있어서 여쭤봅니다~

2024-09-23 16:13 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +              - 좋아요 수가 많은 순 (likesCount, desc) \n
앗, 왜 `like` 가 아닌 `like"s"` 인건지 물어보신거죠?
그렇다면 API 응답의 `likeCount` 가 `likesCount` 로 수정되는 편이 좋을 것 같아요.

백엔드 코드에서 `Like` 라는 이름의 도메인을 [다음](https://github.com/woowacourse-teams/2024-code-zap/pull/680#discussion_r1771351339) 과 같은 이유로 사용하지 못하는데요.
그래서 전체 코드에서 `Like` -> `Likes` 변경이 있었습니다!

API 응답을 수정해 둘게요!

2024-09-23 17:17 UTC, kyum-q requested changes
짱수 수고했어요 ~!!!
굿굿!! 최고다 짱수 ~!
코멘트 간단하게 남겨뒀어요 확인부탁드려요 ~

2024-09-23 17:17 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +            List<Long> tagIds, Pageable pageable, Member loginMember
개행을 줘봐요잉~
```suggestion
    public FindAllTemplatesResponse findAllByWithMember(
            Long memberId, String keyword, Long categoryId, List<Long> tagIds, Pageable pageable, Member loginMember
```

2024-09-23 17:17 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +    private FindAllTemplatesResponse makeTemplatesResponse(Page<Template> page, LikePredicate likePredicate) {
optional 을 사용하는건 어떤가요?? 보통 null을 인자로 주는게 불안전해서 optional을 많이 쓰잖아욧~

```java
    public FindAllTemplatesResponse findAllBy(
            Long memberId, String keyword, Long categoryId, List<Long> tagIds, Pageable pageable
    ) {
        Page<Template> templates = templateService.findAll(memberId, keyword, categoryId, tagIds, pageable);
        return makeTemplatesResponse(templates, Optional.empty());
    }

    public FindAllTemplatesResponse findAllByWithMember(
           Long memberId, String keyword, Long categoryId, List<Long> tagIds, Pageable pageable, Member loginMember
    ) {
        Page<Template> templates = templateService.findAll(memberId, keyword, categoryId, tagIds, pageable);
        return makeTemplatesResponse(templates, Optional.of(loginMember)));
    }

    private FindAllTemplatesResponse makeTemplatesResponse(Page<Template> page, Optional<Member> member) {
        List<FindAllTemplateItemResponse> findTemplateByAllResponse = page.stream()
                .map(template -> FindAllTemplateItemResponse.of(
                                template,
                                templateTagService.getByTemplate(template),
                                thumbnailService.getByTemplate(template).getSourceCode(),
                                member.map(loginMember -> likesService.isLike(template, loginMember))
                                        .orElse(false)
                        )
                )
                .toList();
        return new FindAllTemplatesResponse(page.getTotalPages(), page.getTotalElements(), findTemplateByAllResponse);
    }
```

2024-09-23 17:17 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +                            .templates();
```suggestion
            List<FindAllTemplateItemResponse> templates =
                    sut.findAllByWithMember(null, null, null, null, Pageable.ofSize(1), loginMember)
                            .templates();
```

이렇게 해도 자동정렬 다시 안되서 괜찮을 것 같아요 ~

2024-09-24 02:37 UTC, zeus6768 requested changes
짱수 미션과 병행하느라 바빴을텐데 정말 고생했어요~~!👍👍👍

---

사소해 보일 수도 있지만,

저는 좋아요라는 기능을 명세한다면 "사용자가 템플릿을 좋아요 표시한다"가 될 것 같아요. 

영어로는 "Member likes template" 이 되겠죠.

그렇다면 관계의 방향이 멤버에서 템플릿으로 가는 방향이라고 생각해요. 

Member → Template 

그래서 member와 template 객체 둘을 파라미터로 하는 메서드들의 파라미터 순서가 member, template 순이었으면 좋겠어요. 

- `LikesService.isLike`
- `LikesRepository.existsBy...`
- `LikesRepository.deleteBy...`
- `LikesJpaRepositoryTest`
  - `@DisplayName("템플릿과 멤버 정보로 좋아요 조회 테스트")` → `멤버 정보와 템플릿으로`
  - `@DisplayName("템플릿과 멤버로 좋아요 삭제 테스트")` → 상동

짱수 생각은 어떤가요?

2024-09-24 02:37 UTC, zeus6768 commented on backend/src/main/resources/db/migration/V3__add_likes.sql
> +    ADD CONSTRAINT FKbrgthyu05fsswb9ysi2l79g7r FOREIGN KEY (template_id) REFERENCES template (id)
⚡
저는 SQL 문법 오류 때문에 실행이 안 되네요. 

다음과 같이 바꿔 주세요~

```suggestion
) ENGINE=InnoDB;

-- Add foreign key constraints
ALTER TABLE likes
    ADD CONSTRAINT FKa4vkf1skcfu5r6o5gfb5jf295 FOREIGN KEY (member_id) REFERENCES member (id);
ALTER TABLE likes
    ADD CONSTRAINT FKbrgthyu05fsswb9ysi2l79g7r FOREIGN KEY (template_id) REFERENCES template (id);
```

2024-09-24 02:37 UTC, zeus6768 commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +    @GetMapping("/{id}/login")
로그인을 하지 않았을 경우에는 서버든 프론트든 예외를 처리하는 게 낫지 않을까요?

로그인 없이 좋아요를 누를 경우 alert 후 로그인 페이지로 이동하는 선택지를 주는 게 일반적인 상용 서비스의 흐름이니까요.

2024-09-24 02:37 UTC, zeus6768 commented on backend/src/main/java/codezap/template/domain/Template.java
> +    @Formula("(select count(*) from likes where likes.template_id = id)")
해당 내용 PR 메시지에도 간단하게 언급해주시면 좋겠어요~~ 리뷰가 끝나고 resolve 되면 잊어버릴 수 있다는 생각이 드네용

2024-09-24 02:37 UTC, zeus6768 commented on backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
> +    ) {
개행을 return 값과 일관성 있게 하면 어떨까 제안해요~

```suggestion
    public static FindTemplateResponse of(
            Template template,
            List<SourceCode> sourceCodes,
            List<Tag> tags,
            Boolean isLiked
    ) {
```

2024-09-24 02:37 UTC, zeus6768 commented on backend/src/main/java/codezap/template/service/facade/MemberTemplateApplicationService.java
짱수 리뷰가 먼저 머지된다면... #679 에서 많은 작업을 해야겠네요 🥹🥹🥹

2024-09-24 02:37 UTC, zeus6768 commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +    private FindAllTemplatesResponse makeTemplatesResponse(Page<Template> page, LikePredicate likePredicate) {
\+

null이 들어올 수 있는 Optional을 쓰고 싶으면 `Optional.ofNullable()`을 써야 해요~!

2024-09-24 02:37 UTC, zeus6768 commented on backend/src/test/java/codezap/likes/repository/FakeLikeRepository.java
> +//기존의 Fake repo 사용 코드가 터지지 않도록 임시로 구현하는 코드
해당 주석 없어도 괜찮아 보여요~

2024-09-24 02:37 UTC, zeus6768 commented on backend/src/test/java/codezap/likes/service/LikesServiceTest.java
> +    @DisplayName("좋아요 취소 기능 테스트")
```suggestion
    @DisplayName("좋아요 취소")
```

2024-09-24 02:37 UTC, zeus6768 commented on backend/src/test/java/codezap/likes/service/LikesServiceTest.java
> +    @DisplayName("좋아요 기능 테스트")
기능 테스트라는 말은 없어도 괜찮지 않을까요~!

```suggestion
    @DisplayName("좋아요")
```

2024-09-24 02:37 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/facade/MemberTemplateApplicationServiceTest.java
> +            );
개행 불필요해 보여요~

2024-09-24 02:39 UTC, jminkkk requested changes
안녕하세요 짱수 🔥
리뷰 반영 수고했어요 쵝오 👍
아주 열심히 구현하신 게 보입니다 👀

아직 함께 이야기 나눠보고 싶은 부분이 있어요 조금 더 얘기 나눠봐요 퐈이팅 😁

2024-09-24 02:39 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        return makeTemplatesResponse(templates, (template -> likesService.isLike(template, loginMember)));
짱수~ 코멘트 보고 다시 답변해요

제가 전략패턴을 오해하고 있는 걸 수도 있으니 서로 편하게 이야기 해봅시다.
짱수의 의도는 전략 패턴을 통해 로그인했을 경우, 안했을 경우 좋아요 조회 방식을 적용하고 싶은 것 같아요.
다만 현재 코드상으로 그게 잘 보이지는 않는 것 같아요

제가 생각하기에 어색하다고 느껴지는 이유가 

1. 현재 짱수가 말한 전략 패턴이 사용된 건지 한눈에 파악하기 어려운 것 같아요.
2. 좋아요 전략이 조금만 변경이 되어도  Template 파사드가 변경되어버려요. (전략의 책임이 TemplateApplicationSerivce에 있는 것 같아요)

이전에 이야기가 잠깐 나왔던 것처럼 만약 비회원도 좋아요 기능을 사용하게 된다면 어떨까요?
(비회원의 IP를 사용해 좋아요 기능을 구현한다던지, 브라우저 로컬 스토리지에 좋아요를 저장한다던지 여러 방법이 있겠지만 백엔드가 처리한다고 가정해봅시다)
비회원의 좋아요 전략이 변경되면서 위의 현재 `(template) -> false`가 변경되면서 Template 파사드가 변경되어버려요.

제가 이해한 [전략 패턴](https://refactoring.guru/ko/design-patterns/strategy)은 클라이언트 (여기는 전략을 사용하는 TemplateApplication) 가 내부 로직까지는 몰라도 된다고 생각해요.

따라서 LikePredicate 인터페이스를 작성해주신만큼 각 전략에 대한 구현체를 만들면 어떨까요?

(예시 - 이렇게 하라는 거 아님)
```java
@RequiredArgsConstructor
public class LoginMemberLikeStrategy implements LikeStrategy {

    private final LikesService likesService;

    public boolean isLike(Template template, Member member) {
        return likesService.isLike(template, member);
    }
}

// TemplateApplicationService.java

    public FindAllTemplatesResponse findAllByWithMember(Long memberId, String keyword, Long categoryId,
            List<Long> tagIds, Pageable pageable, Member loginMember
    ) {
        Page<Template> templates = templateService.findAll(memberId, keyword, categoryId, tagIds, pageable);
        return makeTemplatesResponse(templates, loginMember, new LoginMemberLikeStrategy(likesService));
    }

```

2024-09-24 02:45 UTC, zeus6768 commented on backend/src/main/java/codezap/like/repository/LikesRepository.java
> +}
아직 컨트롤러 테스트에서 Fake를 사용하고 있지 않나요?

컨트롤러 테스트 리팩토링이 끝나고 다시 논의해도 좋을 것 같아요.

2024-09-24 03:02 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +    @GetMapping("/{id}/login")
@zeus6768 
위에서 언급한 api 분리는 템플릿의 단건/목록 조회에 관련된 이야기입니다!
로그인을 하지 않은 경우에 대한 좋아요 요청은 기존과 동일하게 `@AuthenticationPrinciple` 어노테이션으로 처리하겠습니다!

2024-09-24 03:55 UTC, zangsu commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        return makeTemplatesResponse(templates, (template -> likesService.isLike(template, loginMember)));
> 1. 현재 짱수가 말한 전략 패턴이 사용된 건지 한눈에 파악하기 어려운 것 같아요.

이 부분이 문제라면.. 제 구현의 한계라고 생각합니다 🥲 
조금 더 고민을 해 보거나,, 다른 방법을 찾아 볼게요

> 2. 좋아요 전략이 조금만 변경이 되어도 Template 파사드가 변경되어버려요. (전략의 책임이 TemplateApplicationSerivce에 있는 것 같아요)

좋아요 전략 변경에 대해 Service 로직이 변경 되는 것은 문제인가요?
구현체를 생성해서 넣어주는 것도 물론 좋은 방법이라 생각합니다.
다만, 좋아요 전략이 변경되었다는 것은 말 그대로 "사용할 전략" 이 변경 되었다는 것이고, 어떤 전략을 사용할지를 선택하는 `TemplateApplicationSerivce` 의 코드가 변경 되는 것도 문제는 없을 것 같습니다!

다시 한번 말하지만, 몰리가 말한 대로 해당 전략의 구현 클래스를 만드는 것도 충분히 좋은 선택이라 생각해요!
단지 `(template) -> false` 로 표현할 수 있는 전략에 구현체를 만들지 말지는 트레이드 오프의 영역으로 느껴져서 코멘트 남깁니다!

2024-09-24 04:00 UTC, zangsu commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +                            .templates();
오호라, 단지 파라미터 정보를 함께 표시해 주느라 라인이 길어진 것 처럼 보였나보네요~

2024-09-24 04:09 UTC, zangsu commented on backend/src/main/java/codezap/likes/service/LikesService.java
> +        Likes likes = template.like(member);
`Likes` 도메인 생성의 책임을 특정 도메인의 책임으로 준 이유는 객체의 책임 설계를 할 때 DB 를 사용한다는 가정을 벗어나서 설계했기 때문이에요.
(꼭 그래야 한다는 것이 아니라, 제가 그렇게 생각하는 것에 익숙해져서.. 제 생각의 흐름을 설명드리기 위함입니다!
저는 레벨 2부터 계속해서 웹 / DB 사용 등의 조건에 종속적이지 않은 Service layer 코드를 작성하는 것을 이상적이라 생각하고 있어요)

우선 이 부분은 `new Likes()` 로 반영을 해 두겠습니다!

2024-09-24 04:18 UTC, zeus6768 commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +    @GetMapping("/{id}/login")
제 이해가 부족했습니다!!

엔드포인트를 개선할 방법을 찾아봐야겠네요 🥲

2024-09-24 04:20 UTC, HoeSeong123 commented on backend/src/main/java/codezap/like/controller/LikesController.java
>  package codezap.like.controller;
아 예약어..이럴수가ㅠㅠㅠ

2024-09-24 04:29 UTC, zangsu commented on backend/src/main/java/codezap/likes/service/LikesService.java
> +        Likes likes = template.like(member);
> ...
> 그래서 member와 template 객체 둘을 파라미터로 하는 메서드들의 파라미터 순서가 member, template 순이었으면 좋겠어요.

제우스는 "좋아요" 라는 기능이 `Member` 의 책임에 더 가깝다라고 느꼈군요!
저도 이 부분에 대해 고민을 했는데요.

1. 우리의 핵심 도메인은 템플릿이고 
2. "내가 좋아요 한 템플릿 조회" 기능이 존재하지 않기에

좋아요 의 관리 책임은 `Template` 에게 있다고 느껴졌어요.
(DB 를 사용하는 상황이 아니라고 가정한다면 `Member` 클래스의 `List<Template> likesTemplate` 가 아닌 `Template` 클래스의 `List<Member> likesMember` 로 구현을 했을 것 같아요.)

"Member likes template" 로 생각을 하는 것도 꽤나 편리하고 자연스럽기도 하지만, 사용자의 동작을 생각해 본다면 `Template` 의 하트 버튼을 직접 눌러서 좋아요 한 사람 목록에 나를 추가하는 것이기도 하니까요!

---

아무튼 저도 이 부분에 대해 고민을 해 보다가, 결국 `Template` 이 조금 더 중요한 정보가 아닌가~ 하는 생각에 파라미터 순서를 일부러 `Template` 이 먼저 오도록 수정해 둔 상황인데요.
하지만, 제우스의 의견도 꽤나 깊이 공감이 가니 읽어보시고 제우스의 의견을 한번만 더 말해주세요!
얼마든지 바꿀 의향이 있어요~~

2024-09-24 04:31 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        return makeTemplatesResponse(templates, (template -> likesService.isLike(template, loginMember)));
> 다만, 좋아요 전략이 변경되었다는 것은 말 그대로 "사용할 전략" 이 변경 되었다는 것이고, 어떤 전략을 사용할지를 선택하는 TemplateApplicationSerivce 의 코드가 변경 되는 것도 문제는 없을 것 같습니다!

저도 같은 의미에서 남긴 코멘트였습니다 ㅎㅎ
다시 한번 말하지만 LoginMemberLikeStrategy 또는 UnLoginMemberLikeStrategy 둘 다 선택은 Service에서 하는 게 맞다고 생각해요. 다만 구현 내용까지 Service가 몰라도 된다는 것이었어요.
짱수는 트레이드 오프로 구현체를 만들지 않는 것을 선택했다면 저도 좋아요~ 현재 크게 복잡한 로직은 아니니까요 😁
다만 변경 가능성을 조금 더 고민해보자는 것이었습니다.

> 이 부분이 문제라면.. 제 구현의 한계라고 생각합니다 🥲

구현은 잘되어 있다고 생각해요. 다만 이름만 Predicate가 아닌, 조금 더 의미를 알 수 있도록 Strategy로만 변경해도 바로 파악할 수 있을 것 같아요 😁

2024-09-24 04:36 UTC, kyum-q commented on backend/src/main/java/codezap/likes/service/LikesService.java
> +        Likes likes = template.like(member);
> Likes 도메인 생성의 책임을 특정 도메인의 책임으로 준 이유는 객체의 책임 설계를 할 때 DB 를 사용한다는 가정을 벗어나서 설계했기 때문이에요.

그럼 짱수는 특정 도메인의 책임으로 안주고 서비스에서 객체를 생성하는 방식은 DB를 사용한다를 고려한 건가요?
저는 이 또한 DB를 고려하지 않은 설계라고 생각해요! DB를 고려한, 즉 짱수가 말하는 DB를 사용한다는 가정을 가지고 설계한 코드는 무엇인지 궁금합니다 ~! 지금 당장 이야기 안해줘도 됩니다 ~ 단순 궁금증이니 나중에 이야기해줘도 돼요~ 

> 우선 이 부분은 new Likes() 로 반영을 해 두겠습니다!

굿 ~!

2024-09-24 04:48 UTC, kyum-q commented on backend/src/main/java/codezap/likes/service/LikesService.java
> +        Likes likes = template.like(member);
> createLike라는 이름은 "좋아요를 생성한다"인데, 코드가 어떻게 동작하는지 그 구현을 구체적으로 언급하는 것처럼 느껴져요.
>
> 만약 구현을 나타내는 이름을 제대로 짓고 싶다면, createAndSaveLike라고 해야 하는 건 아닐까요?

몇 번 계속 읽어보니 제가 like를 좋아요를 한 행위로 생각하지 않고 좋아요라는 명사로 생각했던 것 같네요.
그래서 `like(좋아요)를 만드는 건데 왜 템플릿이 이 행위를 하는건지?`, `like(좋아요)라는 메서드명은 너무 getter 같은데?`라고 생각했던 것 같아요. 
그래서 처음 봤을 때 드는 생각은 `template가 like를 가지고 있고, template가 record 인가?` 였습니다. (record에서 getter를 변수명으로 설정)

like를 행위로 보니 like라는 메서드명도 꽤 괜찮은 것 같네요 ~ 🤔

2024-09-24 05:13 UTC, zangsu commented on backend/src/main/resources/db/migration/V3__add_likes.sql
> +    ADD CONSTRAINT FKbrgthyu05fsswb9ysi2l79g7r FOREIGN KEY (template_id) REFERENCES template (id)
앗 뭔가 터지길래 열심히 찾고 있었는데 ㅠ 감사합니닷

2024-09-24 05:16 UTC, zangsu commented on backend/src/main/java/codezap/template/service/facade/MemberTemplateApplicationService.java
함께 할게욥... ㅠㅠ

2024-09-24 05:30 UTC, zeus6768 commented on backend/src/main/java/codezap/likes/service/LikesService.java
> +        Likes likes = template.like(member);
회의 완료 🚀

2024-09-24 05:32 UTC, zangsu commented on backend/src/test/java/codezap/likes/repository/FakeLikeRepository.java
> +//기존의 Fake repo 사용 코드가 터지지 않도록 임시로 구현하는 코드
아잇, 이거 지우고 올릴랬는데 ㅠ
바로 반영 했습니다~!

2024-09-24 05:36 UTC, zangsu commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +
오 동의합니다!
구현하는 순간에는 사용하는 곳에 있어야 코드 이해가 빠르려나? 하는 생각이 들었는데, 좋아요에 관련된 기능이라서 따로 파일 분리를 하는 것이 좋겠네요~

2024-09-24 06:05 UTC, zangsu commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        return makeTemplatesResponse(templates, (template -> likesService.isLike(template, loginMember)));
LikeChecker 로 변경했서용

2024-09-24 06:13 UTC, zangsu commented on backend/src/main/java/codezap/likes/service/LikesService.java
> +        Likes likes = template.like(member);
DB 를 사용한다는 것을 인지한 상태로 책임을 설계한다면 테이블이 먼저 나왔을거에요.
다대다 연관관계이니 자연스럽게 `Likes` 도메인이 존재했을 것 같습니다.
`Likes` 도메인이 존재하니 `Template.like()` 메서드 대신 service 계층에서 해당 도메인을 생성했을 것 같고요.

반대로 DB 를 사용한다는 생각을 하지 않는다면 굳이 `Like` 라는 도메인이 객체의 책임을 고려할 때 부터 만들어 질 필요가 없다고 생각해요.
우리가 다대다 테이블을 직접 관리하기로 결정 했기 때문에 해당 메서드의 반환값으로 `Likes` 도메인이 반환 되어서 `LikesRepository` 에 저장이 되는 코드로 변했을거에요.
만약 우리가 `@ManyToMany` 로 다대다 연관관계를 관리했다면 service 계층의 코드 변화도 없었지 않을까 생각합니다!

2024-09-24 06:20 UTC, zangsu commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +    private FindAllTemplatesResponse makeTemplatesResponse(Page<Template> page, LikePredicate likePredicate) {
전략 패턴을 사용하는 것 자체는 유지하기로 했습니다. 
그 이유는, 
1. `null` 을 파라미터로 넘기는 것이 마음에 걸리기도 했고
2. `null` 의 예외 처리 과정에서 `FindAllTemplatesResponse` 을 생성하는 로직이 중복이 되는 것도 마음에 걸렸어요.
    1. 관리 포인트가 늘어날 뿐 아니라 이 로직이 상당히 길어서, 읽기도 불편할 것이라 판단하였습니다.

대신 이름을 조금,,, 더 친절하게 변경해 보았어요...

2024-09-24 06:26 UTC, kyum-q approved these changes
귯 ~ 짱수 최곱니다 !!!

2024-09-24 06:27 UTC, jminkkk approved these changes
Wow 짱수 완전 수고했어요 
이 PR에 좋아요를 바칩니다~!!!!!!!!!!!

쵝5쵝6쵝7쵝8

2024-09-24 06:28 UTC, kyum-q approved these changes
귯 짭 ~

2024-09-24 06:36 UTC, zeus6768 approved these changes
고생많았어요~!

2024-09-24 06:45 UTC, HoeSeong123 commented on backend/src/test/java/codezap/like/repository/LikesJpaRepositoryTest.java
> +            assertThat(likesRepository.countByTemplate(template)).isEqualTo(1);
테스트가 많은 건 좋죠ㅎㅎㅎ 좋습니다!!

2024-09-24 06:45 UTC, HoeSeong123 approved these changes
변경사항 확인했습니다.
고생하셨습니다 👍수~~

2024-09-24 07:15 UTC, merged