Feat/668 template like
woowacourse-teams/2024-code-zap pull request #686
Opened 2024-09-24 05:39 UTC by vi-wolhwa

## ⚡️ 관련 이슈
#668

## 📍주요 변경 사항
1. 좋아요 API 함수 및 Mutation 훅 구현
2. TemplateCard에 좋아요 기능 추가
3. TemplatePage에 좋아요 기능 추가

2024-09-24 05:58 UTC, vi-wolhwa commented on frontend/src/api/like.ts
> +  if (response.status >= 400) {
@Jaymyong66 @Hain-tain 

기존 조건식이 200번대 응답을 에러로 판단하는 문제가 존재하여 이와 같은 조건식을 사용하였습니다.
``` javascript
typeof response === 'object' && response !== null && 'status' in response
```

2024-09-24 05:58 UTC, vi-wolhwa commented on frontend/src/api/templates.ts
> +  const url = `${TEMPLATE_API_URL}${memberId ? '/login' : ''}?${queryParams.toString()}`;
@Jaymyong66 @Hain-tain 

변경된 API 명세에 따른 반영 (현재파일 이하 변경사항 동일)
#680

2024-09-24 05:58 UTC, vi-wolhwa commented on frontend/src/assets/images/like.tsx
> +  }[state];
@Jaymyong66 @Hain-tain 

세 가지 타입의 'Like' 아이콘을 컴포넌트화 하여 구현하였습니다.

2024-09-24 05:58 UTC, vi-wolhwa commented on frontend/src/components/LikeWidget/LikeWidget.tsx
> +    <Text.Small color={theme.color.light.secondary_800}>{formatWithK(likeCount)}</Text.Small>
@Jaymyong66 @Hain-tain 

좋아요의 수를 'k' 단위로 표기합니다.
- 999 -> 999
- 1000 -> 1k
- 1100 -> 1.1k
- 1199 -> 1.1k

2024-09-24 05:58 UTC, vi-wolhwa commented on frontend/src/components/LikeWidget/LikeWidget.style.ts
> +`;
@Jaymyong66 @Hain-tain 

좋아요 수 10만 미만(소수자리 포함 3자리)을 가정한 레이아웃 디자인 입니다.

2024-09-24 05:58 UTC, vi-wolhwa commented on frontend/src/components/TemplateCard/TemplateCard.tsx
> +            <LikeWidget likeCount={template.likeCount} isLiked={template.isLiked} />
@Jaymyong66 @Hain-tain 

템플릿 카드의 레이아웃을 변경하였습니다. (#671)

2024-09-24 05:58 UTC, vi-wolhwa commented on frontend/src/pages/TemplatePage/TemplatePage.tsx
> +                  </Heading.Large>
@Jaymyong66 @Hain-tain 

템플릿 제목의 사이즈를 변경하였습니다. (Medium > Large)

2024-09-24 05:58 UTC, vi-wolhwa commented on frontend/src/pages/TemplatePage/TemplatePage.tsx
> +                      {template.member.name}
@Jaymyong66 @Hain-tain 

테스트를 위한 기존의 코드를 수정했습니다.
(Mock 데이터에서 template의 member가 없었을 때의 소스코드)

2024-09-24 05:58 UTC, vi-wolhwa commented on frontend/src/queries/likes/useDislikeMutation.ts
> +  });
@Jaymyong66 @Hain-tain 

현재 요청 실패 시, 사용자에게 알리고 있지 않습니다. (좋아요 낙관적업데이트만 롤백) (useLikeMutation 동일)
사용자에게 요청 실패를 전달할 방법에 대한 논의가 필요합니다.

2024-09-24 05:58 UTC, vi-wolhwa commented on frontend/src/queries/templates/useTemplateExploreQuery.ts
> +    queryFn: () => getTemplateExplore({ sort, page, size, memberId }),
@Jaymyong66 @Hain-tain

변경된 API 명세에 따른 반영 (useTemplateQuery 동일)
#680

2024-09-24 07:36 UTC, Hain-tain requested changes
안녕하세요, 월하! 일정이 빠듯했는데도 불구하고 잘 구현해주셨네요! 정말 고생많으셨습니다 👍👍
특히 이번에 예기치 못하게 api 가 수정되어 자잘하게 수정된 부분이 많았는데
월하가 코멘트 세심하게 미리 달아주신 덕분에 캐치를 잘 할 수 있었던 것 같습니다.

현재 네이밍과 같이 사소한 코멘트 몇개와 `useLike` 내부에서 사용하는 상태 및 toggle 함수에 대한 코멘트 남겨두었으니 확인 부탁드립니다!

2024-09-24 07:36 UTC, Hain-tain commented on frontend/src/pages/TemplatePage/hooks/useLike.ts
> +  const [isProcessing, setIsProcessing] = useState(false);
별도의 상태를 두기보다는 기존 Mutation 에서 제공하는 `isPending`을 사용해보는건 어떨까요?

2024-09-24 07:36 UTC, Hain-tain commented on frontend/src/pages/TemplatePage/hooks/useLike.ts
> +      }
저희 컨벤션대로 얼리 리턴을 활용해보면 어떨까요?

2024-09-24 07:36 UTC, Hain-tain commented on frontend/src/pages/TemplatePage/hooks/useLike.ts
> +interface UseLikeProps {
저는 export 하지 않는 경우에는 그냥 `Props` 로 사용하고있는데요, 통일성을 위해 `Props` 로 통일하거나 `UseLikeProps` 처럼 이름으로 통일하거나 하나로 통일해보면 좋을 것 같네요! 별것 아니지만 이런 사소한 부분도 통일성이 지켜지면 좋을 것 같아서 이것도 함께 논의해봅시다!ㅎㅎ

2024-09-24 07:36 UTC, Hain-tain commented on frontend/src/pages/TemplatePage/hooks/useLike.ts
> +    }
현재 `toggleLike` 함수를 보면 하나의 요청이 모두 처리될 때까지 다른 요청을 막고 있는 것 같아요!

만약 좋아요를 빠르게 타닥 하고 누르면 좋아요 요청 뒤에 좋아요 요청 취소 요청이 날아가거나 애초에 처음 보낸 좋아요 요청을 취소해야할 것 같은데,
지금 코드상으로는 좋아요를 빠르게 타닥 하고 누르면 좋아요 처리만 될 것 같아요..! 
이러한 부분에 대한 처리가 필요해보입니다!!

2024-09-24 07:53 UTC, vi-wolhwa commented on frontend/src/components/LikeWidget/LikeWidget.tsx
> +    <Text.Small color={theme.color.light.secondary_800}>{formatWithK(likeCount)}</Text.Small>
10만 미만을 가정하고 있습니다. 쉽게 확장할 수 있고, 좋아요 수 100만이 넘을 가능성은 지금 고려하지 않아도 될거라 생각했어용

2024-09-24 07:57 UTC, vi-wolhwa commented on frontend/src/pages/TemplatePage/TemplatePage.tsx
> +                  />
버튼으로 사용되지 않는 경우도 생각해서 Widget로 생성해봤습니다. 같이 의논해봐요~

2024-09-24 08:00 UTC, vi-wolhwa commented on frontend/src/components/LikeWidget/LikeWidget.tsx
> +  clickable?: boolean;
1. 처음에는 `disable`로 했었으나 `disabled`는 비활성화 되었다는 의미입니다. 위젯을 클릭할 수 있는가의 여부는 `clickable`가 더 적절하다고 판단했습니다.
2. role와 함께 논의해보면 좋을 것 같네요~

2024-09-24 08:06 UTC, vi-wolhwa commented on frontend/src/pages/TemplatePage/hooks/useLike.ts
> +    }
이 부분은 의논 후 의도한 부분인데, 다시 이야기 해봐요~

2024-09-24 08:13 UTC, Jaymyong66 reviewed
헤인과 겹치는 코멘트가 많네요. 추가로는 현재 좋아요 UI가 아래 그림처럼 되어있는데, 한자리 일때 꽤 비어보여서 center에 두거나 width를 줄일지 논의해보면 좋겠습니다.

두번째로 MSW로 확인을 해보고자 했는데, 다른 handler에도 '/login'을 붙여야 동작을 하네요. 이것도 해당 PR에서 변경사항이라면 반영해야할까? 싶었습니다.

마지막으루 로컬에서 확인했을 때 템플릿 수정, 삭제 버튼 UI 변경이 확인되지 않아서, UI 변경은 현재는 스토리북을 쓰고 있지 않으니 스크린샷으로 공유하는 것도 좋을 것 같습니당~

짧은 기간인데 고생했어요 월ha~

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/78a933ca-7db4-410a-ac37-28596fee0d83">

2024-09-24 08:13 UTC, Jaymyong66 commented on frontend/src/components/TemplateCard/TemplateCard.tsx
> +              <ClockIcon width={14} />
요 icon들 14로 거의 쓸거 같다면 기본값을 14로 해도 좋을 것 같네요!

2024-09-25 02:25 UTC, Jaymyong66 submitted a review, later dismissed

2024-09-25 04:38 UTC, Hain-tain reviewed
고생하셨습니다~!! 아주 작고 사소한 코멘트 2개정도 달았으니 확인 부탁드려요!

+) 지금 UI 확인해보니까 align 이 살짝 깨지는 부분이 있고, 컬러적으로 채도가 맞지 않아 아쉬운 부분이 있어서 사진 첨부합니다!!

![image](https://github.com/user-attachments/assets/755be1a8-e725-4738-85cd-d6c7ae883d10)

999k 가 되어도 한 줄로 잘 나오도록 align맞춰주시고, 컬러는 함께 논의해서 같이 바꿔봐요!!

- 현재 컬러
![image](https://github.com/user-attachments/assets/066bf6d3-d448-4f3a-8919-ddeeb64da4f5)

- 제안 1 
![image](https://github.com/user-attachments/assets/52e79423-0c11-4181-8289-e48f725cbe79)

2024-09-25 04:38 UTC, Hain-tain commented on frontend/src/components/LikeButton/LikeButton.tsx
> +const LikeCounter = ({ likesCount, isLiked, onLikeButtonClick }: Props) => (
여기 이름이 `LikeCounter` 인것은 의도하신걸까요..? 파일 이름과 동일하게 `LikeButton` 으로 바꿔보면 어떨까요??

2024-09-25 04:38 UTC, Hain-tain commented on frontend/src/pages/TemplatePage/hooks/useLike.ts
>        setLikesCount((prev) => prev + (isLiked ? -1 : 1));
아주 사소한데 아래처럼 여기도 `initialLikesCount` 로 초기화해줘도 좋을 것 같네요!!

2024-09-25 05:02 UTC, vi-wolhwa commented on frontend/src/components/LikeButton/LikeButton.tsx
> +const LikeCounter = ({ likesCount, isLiked, onLikeButtonClick }: Props) => (
default export라서 import하는 이름만 변경되고 원본의 이름이 변경되지 않았었네요!
주의해야겠어용 감사합니다 (- -)(_ _)

2024-09-25 05:47 UTC, vi-wolhwa commented on frontend/src/pages/TemplatePage/hooks/useLike.ts
> +        setLikesCount(initialLikesCount - 1 + +!initialIsLiked);
지금과 같이 변경한 이유는 like와 dislike의 요청 순서가 뒤섞였을 경우에도 정확한 값을 보장할 수 있기 때문입니다!
기존 방법이 명시적이라는 의견에 동의하지만, 안전성 측면에서는 0에서 싫어요가 두 번 카운트되어 -1(클라리언트)이 될 가능성을 고려하였습니당

2024-09-25 06:52 UTC, Hain-tain approved these changes
자잘한 코멘트들이 계속 있었는데, 단기간에 고생많으셨습니다! 👏👏
좋아요 버튼 디자인 및 색상에 대해서는 QA 기간에 백엔드 팀원들과 다함께 상의해봐요!

2024-09-25 07:02 UTC, Jaymyong66 approved these changes

2024-09-25 07:03 UTC, merged