전문 검색 인덱스 적용
woowacourse-teams/2024-code-zap pull request #719
Opened 2024-09-27 02:13 UTC by jminkkk

## ⚡️ 관련 이슈
close #673

## 📍주요 변경 사항
### 1. 템플릿 조회 시 전문 검색 인덱스 적용하였습니다.

## 🎸기타
### 1. 이런걸 더 고려해봐야 할 것 같습니다.
### - 이런 것도 해야해요.

2024-09-28 08:57 UTC, jminkkk commented on backend/src/main/java/codezap/template/repository/FullTextSearchMySQLDialect.java
> +        }
MySQL의 전문 검색 인덱스를 사용하려면 `MATCH ... AGAINST` 구문으로 조회해야합니다.
JPA에서는 해당 구문을 지원하지 않기 때문에 Hibernate의 MySQLDialect를 사용하여 직접 사용할 문법을 함수로 만들어야 합니다.

따라서 이 객체는 검색 키워드를 인자로 받아 `MATCH ... AGAINST` 을 적용하는 것을 "MATCH"라는 SQL 함수로 등록하는 역할이라고 생각하면 됩니다.

2024-09-28 08:57 UTC, jminkkk commented on backend/src/main/java/codezap/template/repository/TemplateSpecification.java
> +                            criteriaBuilder.literal(searchKeyword)));
앞서 등록한 MATCH라는 함수에 검색 대상 컬럼(템플릿의 title, description)을 지정하고 검색 키워드 `searchKeyword `를 넘깁니다. 함수 MATCH의 결과가 true인, 즉 전문검색으로 키워드가 포함된 템플릿만을 조회합니다.

아래의 소스코드 부분도 동일하게 MATCH가 true인 소스코드만을 조회합니다.

2024-09-28 08:57 UTC, jminkkk commented on backend/src/test/java/codezap/global/DatabaseCleaner.java
> +        jdbcTemplate.execute("ALTER TABLE source_code ADD FULLTEXT INDEX idx_source_code_fulltext (content, filename)");
다른 DDL('@Entity == CREATE' or @ManyToOne == FK)은 하이버네이트를 통해 DDL 쿼리가 알아서 나가는데요.
JPA에서 FULLTEXT 인덱스를 지원하지 않기 때문에 직접 SQL(flyway를 통해)로 작성을 해주었습니다.

하지만 create-drop이라 ddl이 리셋되는 테스트 환경에서는 FULLTEXT 인덱스를 시작 시에 미리 넣을 수 없습니다.
따라서 격리 목적으로 매 테스트에 실행되는 해당 파일을 이용하여 FULLTEXT 인덱스가 없는 경우에 인덱스를 추가하는 구문을 넣었습니다.

2024-09-28 13:51 UTC, kyum-q reviewed
몰리 수고하셨어욧~ 간단한 코멘트 남겨놨습니다 확인해주세요 ~!

2024-09-28 13:51 UTC, kyum-q commented on backend/src/test/java/codezap/global/DatabaseCleaner.java
> +        }
있을 경우 drop하고 생성하는 로직인 것 같아요.
DB 접근을 줄이기 위해 있을 경우 놔두고 없을 경우 create해주는 건 어떨까요?
인자로 인덱스 주고 싶은 필드를 받으면 가능할 것 같아요 ~!

```suggestion
        if (indexCount == 0) {
            jdbcTemplate.execute("ALTER TABLE " + tableName + " ADD FULLTEXT INDEX " + indexName + " (" + String.join(", ", fields) + ")");
        }
```

2024-09-28 13:51 UTC, kyum-q commented on backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
> +//        saveInitialData();
주석 제거해주세요 ~

2024-09-29 09:12 UTC, HoeSeong123 submitted a review, later dismissed
리마큐 살짝 읽어보면서 공부해봤는데 진짜 너무 어렵네요...
나중에 살짝 설명 가능할까요 몰리선생님..😭

2024-09-29 12:04 UTC, zangsu submitted a review, later dismissed
고생 많으셨어요 몰리~~~ :몰리해피:
되게 신기하네용,,, 많이 보고 배웁니닷 👍

2024-09-29 12:04 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +            saveInitialData();
몰리는 어떤 경우에 SQL 문으로 초기화를 하고, 어떤 경우에 `private` 메서드로 초기화 하시나요?

2024-09-29 13:20 UTC, zeus6768 requested changes
고생 많았어요 몰리...!

그런데 저는 `TemplateSearchJpaRepositoryTest` 중 다음의 네 개 테스트가 실패하는데, 몰리는 성공하나요?

`test` 모듈 전체를 테스트하면 통과하고, 해당 클래스만 실행하면 실패해요. 

제 지식으로는 코드에서 어느 부분이 문제인지 모르겠어요...!

PR 본문에 언급한 yml 설정은 잘 되어있어요. 

확인 한 번 부탁해요 😭

<img width="360" alt="스크린샷 2024-09-29 오후 10 17 34" src="https://github.com/user-attachments/assets/2594431c-7c6a-4f3c-aed6-de3e8ee93f85">

2024-09-29 13:20 UTC, zeus6768 commented on backend/src/test/java/codezap/global/DatabaseCleaner.java
> +        jdbcTemplate.execute("ALTER TABLE source_code ADD FULLTEXT INDEX idx_source_code_fulltext (content, filename)");
해당 의도를 코드만 보고 알 수 있게 메서드로 분리하는 건 어떨까요?

2024-10-01 12:13 UTC, jminkkk commented on backend/src/test/java/codezap/global/DatabaseCleaner.java
> +        }
켬미 굿~! 

테스트 데이터가 많지는 않아서 DROP해도 괜찮을 거라고 생각하고 구현하긴 했는데 좋은 피드백이네요 👍

`CREATE FULLTEXT INDEX idx_source_code_fulltext ON source_code (content, filename);`
ALTER 문 말고 CREATE 를 사용하면 이미 있는 경우에 에러 메시지는 발생하지만 실행은 무시하더라구요?!

CREATE을 사용해서 DROP 하지 않도록 변경했습니다!

2024-10-01 13:32 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +            saveInitialData();
짱수~ 보통 private 메서드로 초기화합니다.
다만 이번 PR에서 사용한 전문 검색 인덱스는 JPA에서 지원하지 않기 때문에 데이터베이스 엔진 레벨에서 관리되어요. 즉, 데이터베이스에 실제로 저장된 데이터에 대해서만 동작합니다. ~~대면으로 말씀 드렸었는데 전달이 제대로 안됐었나보군요 🥲~~

만약 기존 다른 테스트처럼 private 메서드를 사용하면 save 메서드와 full text read 메서드가 같은 트랜잭션으로 묶이게 됩니다.
그렇게 되면 저장 메서드를 먼저 호출하더라도 트랜잭션이 종료되는 시점에 JPA가 저장 쿼리를 날라가고 full text read 메서드는 영속성 컨텍스트를 사용할 수 없기 때문에 직전에 저장을 날린 데이터에 대해서는 조회할 수 없어요.

때문에 테스트를 하려면 무조건 미리 저장된 데이터가 필요한데요. 두가지 방식을 고려할 수 있을 것 같아요.

1. EntityManager를 사용하여 테스트 메서드 내에서 수동 commit 
2. @Transactional 제거
3. SQL 파일로 초기화

---

의도가 `RepositoryTest`와 `SerivceTest` 가 다른 초기화 방식을 지니고 있어서 질문 주신 거라고 생각하고 답변할게요!

먼저 1번 방식은 메서드 내에서 사용된 private 메서드를 확인할 수 있지만 테스트 코드가 복잡해지고, 각 테스트마다 이 로직을 반복해야 합니다. 저장이나 수동 커밋 로직이 없어도 검색 조건 때문에 테스트 내용이 긴 상황 속에서 적절하지 않다고 파악했어요.

2번 방식은 `RepositoryTest`에서는 적용이 불가능합니다. `@DataJpaTest`를 사용하는 이상 `@Tramsactional`이 내장되어 있기 때문에 직접 제거할 수 없어요. 

따라서 1번 또는 3번 중에 골라야 하는데 앞서 말씀 드린 이유로 `RepositoryTest`에서는 3번 방식을 선택했어요.
같은 테스트 클래스에서 동일한 초기 데이터 상태를 보장하기 때문에 파악에 큰 어려움은 없다고도 생각했구요. (개인적으로 테스트가 너무 길면 아예 읽기가 싫어서 귀찮더라도 command + b 누르는게 낫다고 생각합니다)

반면 `SerivceTest`에서는 `@Transactional` 이 제거 가능하기 때문에 다른 서비스 메서드들처럼 private 메서드는 유지하고 트랜잭션을 제거해줬습니다.

정리하자면 각 테스트 상황에서 더 적절한 방식을 선택했습니다. 😁
---

그런데 TemplateSearchServiceTest나 TemplateSearchRepositoryTest 모두 `@Sql`로 통일하는 것도 괜찮을 것 같다는 생각이 들기도 하네요 ㅋㅋ

짱수는 어떤가요~? 짱수 의견도 궁금해요~

2024-10-02 01:40 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +            saveInitialData();
> 다만 이번 PR에서 사용한 전문 검색 인덱스는 JPA에서 지원하지 않기 때문에 데이터베이스 엔진 레벨에서 관리되어요. 즉, 데이터베이스에 실제로 저장된 데이터에 대해서만 동작합니다

앗, 이 부분은 기억하고 있어요!! 
아직 트랜잭션을 완벽히 이해하지 못해 설명해 주신 부분을 생각하지 못했나봐요 ㅎㅎ

몰리 의견에 동의합니다! 저도 sql 파일이 너무 많아지지 않는다면, 충분히 sql 파일로 초기화 하는 방법도 좋다고 생각해요.
하나의 테스트 코드에서 모든 내용을 볼 수 없는 것은 아쉽지만, 테스트 하려는 행동이 "검색" 이니 만큼 초기 데이터를 잘 쌓아 두는 것도 중요하다고 생각합니다.

> 그런데 TemplateSearchServiceTest나 TemplateSearchRepositoryTest 모두 @Sql로 통일하는 것도 괜찮을 것 같다는 생각이 들기도 하네요 ㅋㅋ

좋은 생각이네요~~ 

사실 저는 적절한 방법을 선택하기만 한다면 `private` 메서드로 초기화를 하던, sql 파일로 초기화를 하던 중요한 부분은 아니라고 생각해요. 다만, 동일한 초기화 조건에 대해선 동일한 방법을 선택하면 "더" 좋겠다~ 정도의 생각은 있는 듯 하네요 ㅎㅎ

2024-10-02 01:45 UTC, zangsu reviewed
몰리~~
친절한 답변 너무 고마워요! 완전히 이해했습니다.
변경사항에 대해 아주 사소한 코멘트 하나 남겨 두었어요...ㅎㅎ

2024-10-02 01:45 UTC, zangsu commented on backend/src/test/resources/search.sql
> +-- 전문 검색 인덱스가 존재하는지 조회
정말정말 사소하지만, 주석으로 정보를 제공해 준다면 최대한 간결하게 중요한 정보를 다 전달해 줄 수 있으면 좋겠어요!!!
```suggestion
-- 템플릿 테이블에 전문 검색 인덱스가 존재하는지 조회
```

2024-10-02 01:48 UTC, jminkkk commented on backend/src/test/resources/search.sql
> +-- 전문 검색 인덱스가 존재하는지 조회
추가했습니다~!

2024-10-02 03:26 UTC, zangsu commented on backend/src/test/resources/search.sql
> +-- 전문 검색 인덱스가 존재하는지 조회
몰체~~~~

2024-10-02 03:26 UTC, zangsu approved these changes

2024-10-02 04:50 UTC, zeus6768 approved these changes

2024-10-02 04:50 UTC, HoeSeong123 approved these changes

2024-10-02 04:53 UTC, kyum-q approved these changes

2024-10-02 04:53 UTC, merged