좋아요한 템플릿 삭제 시 좋아요 테이블 삭제 구현
woowacourse-teams/2024-code-zap pull request #737
Opened 2024-10-04 14:59 UTC by kyum-q

## ⚡️ 관련 이슈
close #734

## 📍주요 변경 사항
템플릿 삭제 시 템플릿에 연관된 좋아요 삭제 로직 추가

## 🎸기타

### cascade
템플릿과 소스코드 양방향 연관관계를 제거한 후, Cascade 설정으로 제거하는 방안 어떨까요?
cascade는 쉽게 설명해서 cascade 설정을 하면 템플릿 삭제 시 자동으로 템플릿과 연관된 데이터가 삭제되는 설정을 의미한다.

> [JPA Cascade는 무엇이고 언제 사용해야 할까?](https://tecoble.techcourse.co.kr/post/2023-08-14-JPA-Cascade/)

#### cascade를 고려해도 좋을 것 같은 도메인

cascade는 ‘게시물’과 ‘댓글’의 관계처럼 부모 - 자식 구조가 명확하다면 Cascade를 사용하는 것은 괜찮은 선택이다. 
우리 서비스에서 이에 해당하는 관계는 다음과 같다. 하지만 하나의 자식에 여러 부모가 대응되는 경우(‘수강 중인 수업’과 ‘학생’의 관계 등)에는 사용하지 않는 것이 좋다. 

우리 서비스에서 템플릿 삭제 시 삭제해야 하는 모든 관계는 부모 - 자식 구조가 명확하다고 생각한다.
- template - like
- template - sourcecode
- sourcecode- thumbnail
- template - tag

#### 현재 바로 변경하지 않은 이유
template와 sourcecode가 양방향 매핑이고, 아직 잘 알진 못하니 더 찾아보려고
+의논이 필요할까해서~ 

> 양방향 매핑은 cascade 사용이 위험하다.
> 그 이유는 위에 참고 자료 확인!
> 간단하게 말하자면 양방향 매핑이면, sourcecode 삭제 시 템플릿 삭제될 수도 있음

2024-10-05 09:50 UTC, jminkkk requested changes
켬미 수고했어요 최고입니다 🔥🔥
리뷰 몇개 남겼으니 확인하시고 같이 얘기해봐용 🙌

+) #734 에 cascade 부분도 추가해주시면 어떨까요?
동일한 문제이니 이슈를 같이 사용해도 좋을 것 같습니당

2024-10-05 09:50 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +            var deleteIds = List.of(template1.getId(), template2.getId());
👍👍👍👍👍👍👍

2024-10-06 07:34 UTC, kyum-q commented on backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
> +    void deleteByTemplateIds(List<Long> templateIds);
좋아요 !
혹시 그럼 fix해야할 부분으로 남겨두고 해당 PR과 별개로 수정해도 될까요? 해당 부분을 수정하려고 보니 어정쩡한 메서드명이 꽤 있어서요 !

### 메서드명 수정 필요 

- deleteByMemberAndIds(Member member, List<Long> ids) 
   - deleteAllByMemberAndTemplateIds(Member member, List<Long> templateIds) 
- 서비스 단에 모든 deleteByTemplateIds(List<Long> templateIds)
   - deleteAllByTemplateIds(List<Long> templateIds)
- 레포지토리 단에 모든 deleteByTemplateIds(List<Long> ids)
   - deleteAllByTemplateIds(List<Long> templateIds)

![image](https://github.com/user-attachments/assets/e1a9219d-c8e7-42d2-9499-153feb351e97)

![image](https://github.com/user-attachments/assets/b1648b96-70ab-4d13-a8ce-6567807848f2)

2024-10-06 07:35 UTC, jminkkk commented on backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
> +    void deleteByTemplateIds(List<Long> templateIds);
당연하지요 최고야

2024-10-06 07:42 UTC, jminkkk submitted a review, later dismissed
굿굿 최고입니다 👍

2024-10-06 08:20 UTC, zeus6768 approved these changes
멋져요 👍

2024-10-07 06:04 UTC, HoeSeong123 approved these changes
너무 빨라!!!!
고생하셨습니다 켬미👍

2024-10-07 06:34 UTC, zangsu reviewed
켬미~~~ 고생 많으셨어요!!!
제안 사항은 없고, 궁금한 것만 코멘트로 남겨 두었어요!!

2024-10-07 06:34 UTC, zangsu commented on backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
> +    void deleteByTemplateIds(List<Long> templateIds);
JPA 에서 제공하는 메서드 (`deleteByTemplateIdIn(List<Long> templateId)`) 를 사용하지 않은 이유는 성능 최적화를 위함인가요??

+) 확실히 쿼리를 확인해 보니 select 를 할 때 `IN` 절을 사용하고 `DELETE` 쿼리는 여러번 나가긴 하네요.
`@Modifying(clearAutomatically = true)` 를 사용해도 마찬가지고요...

2024-10-07 06:34 UTC, zangsu commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        likesService.deleteAllByTemplateIds(ids);
PR 본문 확인했습니다!
나중에 여유가 된다면 저는 CASCADE 적용 해 보아도 괜찮을 것 같아요!
기회 될 때 함께 이야기 해 보시죠! 기대가 되네요~~

2024-10-07 06:51 UTC, kyum-q commented on backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
> +    void deleteByTemplateIds(List<Long> templateIds);
네 ! 제가 알기로는 JPQL을 사용하지 않으면 결국에는 조회하고 삭제하는 로직을 거치는 것으로 알고 있습니다.
그렇게 되면 아마 select문에서 모든 필드를 다 알아낸 다음에 삭제하기 때문에 연관관계가 있는게 모두 조회됩니다...! 그래서 이러한 필요없는 조회 로직을 없애기 위해 JPQL을 사용하였습니다 !

---

내가 말을 잘 못한것 같아서 ChatGPT 선생 말을 빌려 봅니다

deleteByTemplateIdIn 같은 JPA 메서드는 편리하지만, 내부적으로는 엔티티를 조회하고 이를 삭제하는 방식으로 작동할 수 있습니다. 즉, 삭제 전에 해당 엔티티를 가져와야 할 수 있어서, 대량의 데이터를 처리할 때 성능이 떨어질 수 있습니다. 반면, 직접적으로 쿼리를 작성하면 조회 과정을 생략하고 바로 삭제할 수 있기 때문에 성능 상 이점이 있을 수 있습니다.

특히, @Query로 직접 DELETE 쿼리를 작성하면 JPA가 조회 과정 없이 바로 데이터베이스에서 삭제를 처리하므로 대량의 데이터를 다룰 때 더 효율적입니다. IN 절을 사용하는 것은 하나의 DELETE 쿼리로 여러 항목을 한 번에 삭제할 수 있는 방식이며, JPA가 여러 번의 DELETE 쿼리를 실행하는 상황을 피할 수 있습니다.

실제로 그렇습니다. deleteByTemplateIdIn은 내부적으로 엔티티를 조회 후 삭제할 수 있지만, 직접 쿼리로 처리하면 조회 없이 바로 삭제가 이루어져 성능 면에서 더 유리합니다.

2024-10-07 06:51 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        likesService.deleteAllByTemplateIds(ids);
귯귯~!

2024-10-07 07:03 UTC, jminkkk approved these changes

2024-10-08 00:57 UTC, zangsu commented on backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
> +    void deleteByTemplateIds(List<Long> templateIds);
어우 대답 너무 알차~ 고마워요 켬미!!

2024-10-08 00:58 UTC, merged