전반적으로 자잘한 코드 컨벤션 정리
woowacourse-teams/2024-code-zap pull request #738
Opened 2024-10-04 15:48 UTC by kyum-q

## ⚡️ 관련 이슈
#650

## 📍주요 변경 사항
진짜진짜 사소한 코드 컨벤션들 정리했어요 ~
- 클래스 상단 개행 추가
- Nested 테스트 클래스명 첫문자 대문자로
- 사용하지 않는 메서드 삭제

- (이건 다시 원상복구 시킬까 고민중~) lombok.Getter로 코드 개선

## 🎸기타

2024-10-06 05:50 UTC, jminkkk submitted a review, later dismissed
꼼꼼해 당신 최고야

---

> (이건 다시 원상복구 시킬까 고민중~) lombok.Getter로 코드 개선

원상복구 고민하는 이유가 뭐죵

2024-10-06 07:36 UTC, kyum-q commented
> > (이건 다시 원상복구 시킬까 고민중~) lombok.Getter로 코드 개선
> 
> 원상복구 고민하는 이유가 뭐죵

@jminkkk 

혹시 반대파가 있을까 밑밥.. '너가 싫다면 현재 PR에서 제거할게~ 여기서 깊게 이야기하지 말자~' 의 의미였습니다. !

2024-10-06 08:03 UTC, zeus6768 requested changes
간단한 코멘트 남겼어요 확인 부탁해요 켬미최고~!

2024-10-06 08:03 UTC, zeus6768 commented on backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
> +            """)
이 부분은 요렇게 하는게 어떨까요? 그래야 25~37 라인과 일관성이 있을 것 같아용
```suggestion
            SELECT DISTINCT t
            FROM Tag t
            WHERE t.id IN (
                SELECT DISTINCT tt.id.tagId
                FROM TemplateTag tt
                WHERE tt.id.templateId IN (
                   SELECT te.id FROM Template te WHERE te.member.id = :memberId
                )
            )
            """)
```

2024-10-06 08:07 UTC, kyum-q commented on backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
> +            """)
바로 반영 ~!!!

2024-10-06 08:15 UTC, zeus6768 approved these changes

2024-10-06 16:35 UTC, zangsu approved these changes

2024-10-07 05:55 UTC, HoeSeong123 reviewed
왜이렇게 꼼꼼해!!👍👍👍👍
엄청 사소하지만 컨벤션 맞추는 김에 눈에 보였던 거 하나 달아놨습니다!!

2024-10-07 05:55 UTC, HoeSeong123 commented on backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
> +                    )
```suggestion
            SELECT DISTINCT t
            FROM Tag t
            WHERE t.id IN (
                SELECT DISTINCT tt.id.tagId
                FROM TemplateTag tt
                WHERE tt.id.templateId IN (
                    SELECT te.id FROM Template te WHERE te.member.id = :memberId
                )
```

2024-10-07 06:27 UTC, jminkkk approved these changes

2024-10-07 06:54 UTC, kyum-q commented on backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
> +                    )
어우 꼼꼼이들 너무 좋아요 ~

2024-10-08 01:00 UTC, zangsu approved these changes

2024-10-08 01:53 UTC, jminkkk approved these changes

2024-10-08 13:19 UTC, HoeSeong123 approved these changes
변경사항 확인했습니다.
고생하셨습니다~~👍

2024-10-10 01:43 UTC, zeus6768 approved these changes

2024-10-10 01:43 UTC, merged