AuthenticationPrinciple 어노테이션에 required 속성 추가
woowacourse-teams/2024-code-zap pull request #747
Opened 2024-10-06 16:28 UTC by zangsu

## ⚡️ 관련 이슈
close #745 

## 📍주요 변경 사항
- `AuthenticationPrinciple` 어노테이션에 `required` 속성 추가
- `AuthArgumentResolver` 로직 변경 및 테스트 추가

## 🎸기타
- 기존의 `/login` 을 사용하는 분기는 `@Deprecated` 처리해 두었습니다. 
    - 아직 프론트에 작업 요청을 하지 않았기 때문에 그 동안의 하위 호환성을 제공하기 위함입니다.
- 기존의 `XXXWithMember` 를 사용하는 서비스 메서드 이름을 오버로딩으로 변경하였습니다.
    - 파라미터로 `Member loginMember` 라고만 적어 두어도 간결한 메서드 이름으로 더 명확하게 동작을 나타낼 수 있을 것으로 판단하였습니다.
- 로직 처리를 Controller 에서 분기하였습니다.
    - 파라미터가 `null` 로 들어오는 것을 예상할 수 있는 가장 빠른 곳에서 분기를 해 주는 것이 인지 부조화가 가장 적다고 판단하였습니다.

2024-10-07 07:35 UTC, jminkkk requested changes
고생했어요 짱수~!! 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
리뷰 남겼으니 확인 부탁드려욥

2024-10-07 07:35 UTC, jminkkk commented on backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
> +    public static final String CREDENTIAL_COOKIE_NAME = "credential";
접근제한자 변경한 이유가 뭘까요?0?

2024-10-07 07:35 UTC, jminkkk commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +    AuthArgumentResolver authArgumentResolver = new AuthArgumentResolver(credentialManager, credentialProvider);
제한이 없길래 외부에서 사용되는 코드가 있을 것 같아서 찾아봤는데 없네요ㅠ
⚡️ 접근 제한자 붙여주세요!

2024-10-07 07:35 UTC, jminkkk commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +        @DisplayName("AuthenticationPrinciple 어노테이션이 파라미터에 존재하면 지원할 수 있는 메서드이다.")
⚡️ `@DisplayName` 형식이 컨벤션과 다른 것 같아요~! 🥲

2024-10-07 07:35 UTC, jminkkk commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +        Cookie credentialCookie = new Cookie(CREDENTIAL_COOKIE_NAME, credentialProvider.createCredential(member));
⚡️ 마찬가지로 접근 제한자 추가해주십셔 😁

2024-10-07 07:35 UTC, jminkkk commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +    @DisplayName("지원하는 파라미터 테스트")
`AuthArgumentResolver`가 동작하는 조건을 테스트하려는 것 같은데, 더 명확하게 변경해보면 어떨까요?

2024-10-07 07:35 UTC, jminkkk commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +        }
👍👍

2024-10-07 07:35 UTC, jminkkk commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +            Method notRequiredMethod = ReflectionSupport.findMethod(ResolveTestController.class,
⚡️ 요기두요!

2024-10-07 07:35 UTC, jminkkk commented on backend/src/test/java/codezap/auth/provider/PlainCredentialProvider.java
> +    @Override
⚡️ 줄바꿈을 줄까요~~?

2024-10-07 07:35 UTC, jminkkk commented on backend/src/test/java/codezap/auth/provider/PlainCredentialProvider.java
> +public class PlainCredentialProvider implements CredentialProvider {
`Plain`말고 `FakeCredentialProvider`나 `StubCredentialProvider` 은 어떨까요?
뭔가 실제 구현체 같이 느껴져서 테스트용 객체인지 바로 파악하기 어려운 것 같아요...

2024-10-07 07:35 UTC, jminkkk commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +                    modelAndViewContainer,
`ModelAndViewContainer` 따로 지역 변수로 빼지 않아도 될 것 같슴다.
이유가 있었다면 말해주세요!

```suggestion
            WebDataBinderFactory webDataBinderFactory = (request, target, objectName) -> null;

            return authArgumentResolver.resolveArgument(
                    new MethodParameter(method, 0),
                    new ModelAndViewContainer(),
```

2024-10-07 09:58 UTC, zangsu commented on backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
> +    public static final String CREDENTIAL_COOKIE_NAME = "credential";
`CredentialManager` 는 응답에 쿠키를 설정해 주는 방식으로 인증 정보를 제공합니다.
테스트에선 요청에 인증 정보가 들어 있어야 하며, 이는 브라우저에서 제공하는 `set-cookie` 방식을 활용할 수 가 없습니다.

테스트를 작성할 때 `CredentialManager` 가 제공하는 인증 쿠키 이름을 그대로 사용하기 위해 접근 제어자를 변경하였습니다.

+) 테스트 때문에 접근제한자가 변경되었긴 하지만, 상수에 대한 접근이기에 숨겨야 할 필요성이 크게 느껴지진 않았어요!

2024-10-07 09:59 UTC, zangsu commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +    AuthArgumentResolver authArgumentResolver = new AuthArgumentResolver(credentialManager, credentialProvider);
이전의 테스트 코드 리팩토링에서 테스트 클래스의 필드 접근 제한자는 크게 의미가 없었던 것으로 기억해 생략했는데요.
테스트 클래스에서도 접근 제한자를 제한해야 하는 이유가 궁금합니닷...!

2024-10-07 10:00 UTC, zangsu commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +        @DisplayName("AuthenticationPrinciple 어노테이션이 파라미터에 존재하면 지원할 수 있는 메서드이다.")
아아앗! 바-로 수정해 두겠습니다~

2024-10-07 10:07 UTC, zangsu commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +                    modelAndViewContainer,
없었습니다!!!
몰리가 제안해 준 코드 보니까 깔끔하고 좋네용~

2024-10-07 10:10 UTC, zangsu commented on backend/src/test/java/codezap/auth/provider/PlainCredentialProvider.java
> +public class PlainCredentialProvider implements CredentialProvider {
개인적으로는 해당 객체가 테스트만을 위한 Fake 객체인지 어떤지 크게 상관이 없다고 생각하기는 해요.
클래스 이름은 최대한 그 클래스의 역할을 잘 표현해야 한다고 생각하기도 하고요.

테스트용 객체인지 파악이 필요하다면 조금 더 설명을 해 주시면 감사하겠습니닷...!

2024-10-07 10:15 UTC, zangsu commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +    @DisplayName("지원하는 파라미터 테스트")
이 부분이 저도 참 마음에 안들었는데요,,,
메서드 이름이 `supportsParameter()` 라서 이렇게 적는 게 가장 명확하지 않을까 하는 생각에 일단 이렇게 두었거든요,,,
더 좋은 이름이 생각이 나지 않아서 우선 다른 사람들의 리뷰를 기다려보겠습니다 👀

2024-10-08 08:05 UTC, kyum-q requested changes
짱수 수고하셨어요 ~!!~!! 짱 ~! 몇가지 의견 남겨뒀어요 ~ 확인 부탁드려요 ~~

2024-10-08 08:05 UTC, kyum-q commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +        );
⚡️ (의견을 좀 강력하게 주장하고 싶어서 잽 달아둬요 ! 이야기가 필요하면 한번 같이 해봐요 ~)

컨트롤러에서 비즈니스 로직을 처리하는 것은 적절하지 않다고 생각해요. 컨트롤러는 HTTP 요청을 받고 결과를 반환하는, 즉 외부와의 통신을 담당하는 역할에 집중해야 한다고 봅니다. 예전에 자바로 미션을 할 때도 컨트롤러는 뷰와 모델 사이에서 값 전달만을 담당하는 객체로 사용했었죠.

'분기를 빠르게 처리하기 위해 컨트롤러에서 하자'는 의견에 대해, 만약 컨트롤러가 가장 빠르게 분기 처리를 할 수 있는 곳이라면, 우리가 예전에 검색 로직을 처리할 때도 컨트롤러에서 하는 게 더 좋은 방법이었을까요? 검색 로직에서도 분기 처리가 많았지만, 결국엔 지금 상황과 동일한 분기 처리라고 볼 수 있어요.

따라서 간단한 분기 처리라도 비즈니스 로직의 일환으로 보고, 서비스 단에서 처리하는 것이 더 적절하다고 생각합니다. 그리고 저는 분기를 처리하는 가장 빠른 지점은 컨트롤러가 호출하는 서비스 레이어라고 생각해요. 컨트롤러는 분기 처리를 담당하는 클래스가 되어서는 안 된다고 봅니다.

정리하자면,
컨트롤러는 외부 요청과 응답을 처리하는 역할에 충실해야 하고, 비즈니스 로직은 서비스 레이어에서 처리하는 게 맞다고 생각합니다. 컨트롤러가 비즈니스 로직을 포함하게 되면, 코드의 역할 분리가 흐려지고 유지보수에 어려움이 생길 것 같아요 ~ 컨트롤러와 서비스의 역할이 명확했으면 좋겠습니다. !

2024-10-08 08:05 UTC, kyum-q commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +
given 없으면 지울까요?

2024-10-08 08:05 UTC, kyum-q commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +        @DisplayName("required 값이 true 라면")
🍜? ㅋㅋㅋㅋㅋ
```suggestion
        @DisplayName("required 값이 true 일 경우")
```
로 수정하는 건 어떤가요?

2024-10-08 08:05 UTC, kyum-q commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +            @DisplayName("실패: credential 정보가 없을때 예외가 발생한다..")
```suggestion
            @DisplayName("실패: credential 정보가 없을때 예외가 발생한다.")
```
점 제거

2024-10-08 10:42 UTC, zangsu commented on backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
> +    public static final String CREDENTIAL_COOKIE_NAME = "credential";
> 테스트 때문에 접근 제한자가 변경되었다고 하셨는데, 그렇다면 테스트 내에서 상수를 새로 정의하는 건 어떻게 생각하세요?

우선, 현재 코드에서는 `CredentialManager` 에게 인증 정보의 확인 책임을 위임하고 있어요.
테스트 내에서 상수를 새로 하나 정의한다고 해도 똑같은 `String "credential"` 을 사용해야 합니다.
그럴리는 없겠지만, 이 `String` 값이 변경된다고 가정하면 테스트 코드의 값도 동일하게 변경되어야 하고요.

저는 이런 상황이 되게 어색하게 느껴졌어요. 사실 해당 상수는 `CredentialManager` 의 상수와 완전 동일한 존재여야 하지 않나? 하는 생각이 듭니다.

> 짱수는 static final로 선언된 상수를 항상 public으로 하시나요?

물론 그런건 아니고, 왠만하면 `private` 으로 설정하려고 해요. 다만, 이 경우 보통은 해당 값이 내부 로직에만 영향을 주는 값이기에 외부에서 "**알 필요가 없는**" 경우가 대부분이고요.
지금의 상수는 외부에 세팅되는 값이고, 그렇기에 상수의 영향이 외부로 전파되는 상황입니다.
이런 상황에서의 상수 캡슐화는 필요한지 잘 모르겠어요.

+) 사소한 부분이긴 하지만, '상수니까 숨기지 말아야 한다!' 라기 보단, '상수니까 조금 더 마음 편하게 밖으로 보여질 수 있다' 정도의 생각을 했습니다. 뭐 비슷하긴 한 것 같네요 ㅋㅋㅋㅋㅋㅋ

아무튼 상수를 새로 정의하는것이 "절대 안된다" 까지의 의견은 아니지만, 꽤나 손이 가지 않는 방법이긴 하네요...ㅎㅎ
다른 의견이 있다면 얼마든지 더 말씀해 주세요!

2024-10-08 10:56 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +        );
우선, 제 의견이 잘못 전달된 것 같아 그 부분 먼저 정정할게요.

제가 컨트롤러에서 분기를 한 이유는 "분기를 빠르게 처리하자" 가 아닌, "nullable 한 파라미터를 가장 빠르게 확인할 수 있는 곳에서 분기를 처리하자" 입니다.
우리는 `required = false` 값을 포함한 어노테이션을 파라미터에서 바로 확인할 수 있기 때문에 컨트롤러에서는 파라미터의 null 가능성을 쉽게 인지할 수 있지만, 한 뎁스만 더 들어가도 파라미터가 nullable 한지 확인하는 것이 꽤나 큰 인지적 부담이 될 것 같았어요.

---
추가로, Controller 의 역할이 "뷰와 모델 사이에서 값 전달만을 담당하는" 역할이라는 것에는 동의하지 않아요.
MVC 패턴에서 Controller 의 역할은 "뷰의 요청에 대해 적절히 모델을 호출" 하는 역할로 이해하고 있습니다.
혹시나 제 개인적인 견해일까 우려가 되어 책을 찾아봐서 이 부분도 함께 첨부해 드려요.

> 컨트롤러가 그냥 '모델한테 전달하는' 일만 하는 것은 아닙니다. 컨트롤러는 사용자가 입력한 내용을 해석해서, 모델을 조작하는 임무를 맡고 있습니다.
- 헤드퍼스트 디자인패턴 개정판 p.559

그래서 켬미의 "컨트롤러는 HTTP 요청을 받고 결과를 반환하는, 즉 외부와의 통신을 담당하는 역할에 집중해야 한다고 봅니다." 라는 의견에는 동의하지만, 그 통신 담당중 일부로 적절한 로직 분기도 가능하다고 생각하고 있어요.

2024-10-08 11:04 UTC, zangsu commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +        @DisplayName("required 값이 true 라면")
🍜  호록,,,

2024-10-08 11:13 UTC, kyum-q commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +        );
짱수의 의견을 명확하게 전달해줘서 고마워요 !

> nullable 한 파라미터를 가장 빠르게 확인할 수 있는 곳에서 분기를 처리하자

라는 의도면 해당 로직을 비즈니스 로직이라고 생각하지 않고 우리 dto의 validate가 컨트롤러 단에서 실행되는 것처럼? 파라미터 검증? 입력 검증? 쪽에 가깝겠네요 !

즉, 이 코드는 비즈니스 로직이라기보다는 컨트롤러에서 처리할 수 있는 입력 검증 및 흐름 제어 로직인 것 같아요 !

이렇게 생각하니 컨트롤러 단에 해당 로직이 존재하는 것도 크게 거부감 들지 않는 것 같아요 😊 
굿이에여~~

2024-10-08 13:22 UTC, kyum-q commented on backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
> +    public static final String CREDENTIAL_COOKIE_NAME = "credential";
굿굿 ! 단지 의견이었을 뿐 ! 그렇다면 짱수가 선호하는 방향으로 해도 전 상관없습니다~

2024-10-08 14:42 UTC, jminkkk commented on backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
> +    public static final String CREDENTIAL_COOKIE_NAME = "credential";
저는 계속 어색한 느낌이 들었던 게, 
처음 `CredentialManager`를 추상화하면서 `CookieCredentialManager`라는 객체를 만든 이유가 

`Cookie에 인증 정보를 관리할 건데, "어떻게" 관리할 건지(credential을 key로 사용 등)은 너가 알아서 책임을 가지고 해줘`

라는 의미로 "어떻게" 관리하는지를 위임하려고 한 것이었어요. 외부에서 `CookieCredentialManager`이 무엇을 하는지만 알면 어떻게 하는지는 알 필요가 없죠. 

그런데 credential이라는 값을 완전 public으로 열어두면 "어떻게"가 외부에 공개된 것이기 때문에 어색하다고 느껴져요.

해당 상수를 사용하는 테스트 코드는 목적 자체가 `CookieCredentialManager`의 내부 구현 즉, 어떻게 하고 있는지를 테스트하려는 거니까 당연히 이 값을 알아야 한다고 생각해요. 

하지만 여전히 이 두 곳이 아닌 곳에서 "어떻게"인 key값을 알 필요가 없죠.
결국 `CookieCredentialManager`이 아닌 곳에서 이 값을 사용할 일이 없습니다. 
그러면 곧 저 테스트에서만 사용된다는 건데 프로덕션 코드가 테스트 때문에 변경된 것과 똑같은 의미로 느껴집니다. 🥲

---

> 우선, 현재 코드에서는 CredentialManager 에게 인증 정보의 확인 책임을 위임하고 있어요.
테스트 내에서 상수를 새로 하나 정의한다고 해도 똑같은 String "credential" 을 사용해야 합니다.
그럴리는 없겠지만, 이 String 값이 변경된다고 가정하면 테스트 코드의 값도 동일하게 변경되어야 하고요.

이거는 조금 설명을 더 듣고 싶어요.
어떻게 구현하는 지가 변경되면 내부 구현을 테스트하려는 테스트 코드도 당연히 변경해야 하는 게 아닐까요?

만약 어떤 객체의 내부 구현이 변경되어 이 때문에 다른 객체까지 영향을 받아 변경이 퍼진다면 어색하지만,
즉 `CookieCredentialManager`가 아닌 다른 객체가 변경이 된다면, 그건 문제가 있겠지만 앞서 말한듯이 `CredentialManager`를 만든 것 자체가 그런 사태를 방지하려고 한 것이기 때문에 그런 일은 없을 거라고 생각합니다. 

(잘못 추상화된 것이나 제가 잘못 알고 있는 게 있다면 말해주십셔)

2024-10-09 00:55 UTC, zeus6768 requested changes
required 옵션을 사용해서 문제를 해결하려고는 아무도 생각하지 못했는데 창의적이고 멋지네요 👍👍👍

코드잽에서 처음으로 하위 호완성을 고려한 API 설계가 등장했네요.

`@Deprecated` 도입한 짱수 멋져요~~~!

2024-10-09 08:32 UTC, zangsu commented on backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
> +    public static final String CREDENTIAL_COOKIE_NAME = "credential";
저 역시 `CredentialManager` 가 가지고 있는 책임, 사용하는 값을 캡슐화 하는 것이 가장 좋다는 것에는 동의해요.

다만, 테스트코드에서 `CredentialManager.CREDENTIAL_COOKIE_NAME` 와 똑같은 값을 상수로 가지고 있는 것은 여전히 어색합니다.
테스트 코드 역시 "코드" 이며, 동일한 상수 값이 여러 곳에 존재하는 것은 너무 이상하게 느껴져요. `CredentialManager` 의 책임이어야 할 `CREDENTIAL_COOKIE_NAME` 이 여러 곳에 흩어지는 것 같습니다. 오히려 `CredentialManager` 의 상수를 가져와서 사용하는 것이 `CredentialManager` 의 책임을 다른 곳과 나누지 않고 한 곳에 둘 수 있는 방법이라 느껴져요.

특정 상수 값과 똑같은 상수를 외부에 하나 더 두는 것은 마치 Reflection 으로 해당 값을 꺼내서 쓰는 것과 같은 느낌이 들기도 했고요.

---

**그런데**, 아무래도 이 방법에 어색함을 느끼는 팀원분들이 많은 것 같아서 우선 접근 제한자를 원래와 같이 `private` 으로 둘 수 있는 방법을 더 고민을 해 보았습니다. 그리고 그 결과가 [c112462](https://github.com/woowacourse-teams/2024-code-zap/pull/747/commits/c1124620a9d54215046b30f629246657dccffc65) 커밋에 해당하는데요.
`CredentialManager` 에게 `MockHttpServletResponse` 를 넘겨 쿠키를 세팅하고, 해당 쿠키를 그대로 `MockHttpServletRequest` 에 세팅해 주는 방법입니다.

접근 제한자의 변경 없이, 동일한 값을 중복해서 설정해 주지도 않을 수 있는 방법이라 저는 괜찮아 보이는데요.
조금 번거롭겠지만, 해당 부분 리뷰 다시 한번 부탁드립니다...! 😅

2024-10-09 08:45 UTC, zangsu commented on backend/src/main/java/codezap/auth/manager/CredentialManager.java
> +    boolean hasCredential(final HttpServletRequest httpServletRequest);
어라 왜 `final` 이...?

2024-10-09 08:50 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +        );
오! 저는 꽤나 만족스러운 결과처럼 보이는데요!!!
다만 이 부분은 컨벤션과 관련된 부분이라서 다른 크루들의 의견도 묻고 싶어요. (괜히 수정했다가 롤백 하게 될까봐... 😅 )
@jminkkk @kyum-q @HoeSeong123 다들 어떻게 생각하시나용??

2024-10-10 07:02 UTC, jminkkk commented on backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
> +    AuthArgumentResolver authArgumentResolver = new AuthArgumentResolver(credentialManager, credentialProvider);
이건 짱수의 [코멘트](https://github.com/woowacourse-teams/2024-code-zap/pull/747#discussion_r1793102248)를 인용하겠습니다 ㅋㅋ 

> 테스트 코드 역시 "코드" 이며,

2024-10-10 07:04 UTC, jminkkk commented on backend/src/test/java/codezap/auth/provider/PlainCredentialProvider.java
> +public class PlainCredentialProvider implements CredentialProvider {
제가 처음이 클래스를 봤을 때 헷갈려서 말씀드렸는데 저만 헷갈린다면 저도 괜춘해요~
굿~!

2024-10-10 07:20 UTC, HoeSeong123 approved these changes
열심히 읽어봤는데 이미 폭풍 리뷰가 많이 달려서 제가 추가할만한 부분이 거의 없는 것 같아요.
삼항연산자 관련해서는 정말 많이 고민해봤는데 아무리 생각해도 저게 최선일 것 같네요....

고생하셨습니다 짱수!!

2024-10-10 07:22 UTC, HoeSeong123 commented on backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
> +    public static final String CREDENTIAL_COOKIE_NAME = "credential";
저도 몰리 의견에 동의합니다~~
짱수가 새롭게 바꾼 방법 좋아보이네요!!

2024-10-10 08:21 UTC, jminkkk approved these changes
required 아이디어 너무 좋았습니다 짱수 굳~ 
수고했어요

2024-10-10 08:21 UTC, jminkkk commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +        );
저도 동의합니답~~

2024-10-10 11:15 UTC, kyum-q approved these changes
귯쟙

2024-10-10 11:16 UTC, kyum-q commented on backend/src/main/java/codezap/template/controller/TemplateController.java
> +        );
모두 동의한다면 반박할 이유가 없어용~!~! 굿 쟞~!

2024-10-10 11:16 UTC, merged