템플릿 공개 여부에 따른 Swagger 파일 수정
woowacourse-teams/2024-code-zap pull request #748
Opened 2024-10-07 06:31 UTC by kyum-q

## ⚡️ 관련 이슈
#739

## 📍주요 변경 사항
템플릿 공개 여부 설정 추가로 Swagger 파일 수정
- 템플릿 생성 시, isPublic 필드 추가
- 템플릿 조회 시, 멤버 정보에 따라 템플릿 반환 값 다름을 문서에 표시

## 🎸기타

### 기존 template 생성자 그대로 둠
현재 템플릿 공개 여부인 isPublic 필드 추가됨에 따라 생성자 변경 생김
하지만 테스트 코드에서 template 생성자를 너무 많이 사용하고 있어서 기존에 있는 생성자를 부생성자로 그대로 두고 그 경우에는 isPublic을 true로 하도록 설정해두었다.

```java
    public Template(Member member, String title, String description, Category category) {
        this(member, title, description, category, true);
    }

    public Template(Member member, String title, String description, Category category, boolean isPublic) {
        this.member = member;
        this.title = title;
        this.description = description;
        this.category = category;
        this.isPublic = isPublic;
    }
```

이 부분에 대해서 삭제해야 할지 그대로 나둬도 될지 여러분은 어떻게 생각하나요?

### 마이그레션에 isPublic default 처리

마이그레이션 보면 isPublic 설정 시 default 값도 설정했는데 혹시 맘에 안 들면 말해주세요 ~
위에 말했듯이 기존 template 생성자 그대로 두고 기본 값을 true로 설정해놨으니 DB단에도 default 설정도 한겁니다

2024-10-07 06:50 UTC, zangsu reviewed
켬미 집에서도 쉬지 않고 작업하시네요~~~~ 고생하셨어요!!
너무 고맙지만, 몸도 챙기면서 작업 하셔야 합니다~~!!

몇가지 제안사항, 의견들 코멘트로 달아 두었어요.

+) 왜 문서화에서 자동으로 공백이 있는 줄이 생기는 걸까요???
뭐가 문제인건지...

2024-10-07 06:50 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +
👀

2024-10-07 06:50 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +            - 멤버 ID가 로그인된 멤버 정보와 동일하지 않으면 공개 템플릿만 반환
👍

2024-10-07 06:50 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +
👀

2024-10-07 06:50 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +              - 좋아요순 (likesCount, desc) \n
👍

2024-10-07 06:50 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +
👀

2024-10-07 06:50 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +
참고로 "/login" 부분이 개선 되면 현재 메서드의 문서화는 삭제될 예정이에요!
추가 작업이 필요한 건 아니고~ 
그냥 나중에 혹시나 충돌 나면 해결 하기 편하게 언급 해 둘게요!

2024-10-07 06:50 UTC, zangsu commented on backend/src/main/java/codezap/template/domain/Template.java
> +        this(member, title, description, category, true);
저는 이거 좋네요!
다만 생성의 기본값을 "public" 으로 할지, "private" 으로 할 지는 조금 고민이 되네요.
이 기본값은 프론트와 백이 동일한 기본값을 가지게 될 것 같아요.

### public 이 기본값
코드잽 측에서 공개 발행을 조금 더 유도하는 것으로 해석이 됩니다.
구경 가기에 좀 더 많은 데이터가 쌓일 수 있을 것 같아요.
다만, 켬미의 경우 private 으로 발행하고 싶은 니즈가 있었는데요. 
이런 사용자들은 항상 private 으로 변경하여 글을 발행해야 하는군요.

### private 이 기본값

이 경우는 반대로 사용자가 부담 없이 글을 발행하는 데 더 도움을 주겠지만, 굳이 public 으로 게시하고 싶지 않은 사람이 많다면 구경가기의 데이터는 느리게 쌓이겠네요.
그래도 무의미한 중복 데이터가 기본으로 "공개" 발행 되는 것 보다는 공개를 선택 해야 노출이 되는 것이 조금 더 서비스 정책에 도움이 될 것 같아요.
물론 마이그레이션을 하고 난 뒤에는 잠시동안 구경가기에 아무런 게시글도 보이지 않겠지만요...!

### 아무튼...!

어떤 방향이던 나름 합리적이라고 느껴지기에 어느 방향으로 선택되어도 좋을 것 같은데요.
그래도 다 같이 잠깐이라도 이야기를 나누어 보면 더 좋을 것 같아요!
저는~~~ `false` 가 기본값인 것이 더 마음에 드네요!!

2024-10-07 06:56 UTC, kyum-q commented on backend/src/main/java/codezap/template/domain/Template.java
> +        this(member, title, description, category, true);
이야기 나눠보는 거 굿 !~!~!
짱수가 설명 자세히 해줘서 뭔가 둘 다 좋게 느껴지네요 ㅋㅎㅋㅎㅎㅋㅎㅋ

2024-10-07 06:57 UTC, kyum-q commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +
켬미 '나는 자동 정렬한 것뿐 왜 저럴까..?'라고 억울함을 말하다

2024-10-07 15:32 UTC, Hain-tain commented on backend/src/main/java/codezap/template/domain/Template.java
> +        this(member, title, description, category, true);
### 기본값은? `public` vs `private`
이 부분은 프론트에서도 함께 고민해보면 좋을 것 같아서 제 개인적 소견도 남겨봅니다.

개인적으로 `public`을 기본으로 두는것이 더 나을 것 같다고 생각했습니다. (즉, `isPublic : true`)

왜냐하면 `private`이 기본으로 되어있으면 공개 발행을 위해 `public`을 클릭해야 할텐데요, 이 부분을 놓치는 사용자도 많을 것 같고, `이게 공개 발행할만한 내용인가?` 를 한번 더 고민하게 될 것 같아요.

반대로 `public`을 기본으로 두면 사용자가 민감한 정보가 담긴 글이나 정말 원하지 않는 경우 `private`을 눌러 내 템플릿을 보호한다는 느낌을 받을 수 있을 것 같아요...!

### 현재 등록되어있는 템플릿들은 public으로 둬야할까 private 처리를 해줘야 할까?
- 현재 템플릿들은 이미 구경가기에 노출이 되어있고, 사람들도 노출이 된다는 것을 알고 있는 상황에서 작성한 글이므로 public으로 처리해도 괜찮을 것 같다는 생각이 듭니다!

2024-10-08 14:34 UTC, HoeSeong123 submitted a review, later dismissed
꼼꼼함은 켬미를 따라올 사람이 없네요 정말!!!!
아픈건 괜찮나요? 너무 고생하셨습니다👍

2024-10-08 15:30 UTC, jminkkk submitted a review, later dismissed
굿입니다 켬미 체공

2024-10-09 04:30 UTC, zeus6768 requested changes
빠른 작업 멋져요 켬미 👍

의견 하나 남겼으니 확인 부탁해요~!

2024-10-09 04:30 UTC, zeus6768 commented on backend/src/main/java/codezap/template/domain/Template.java
> +    private boolean isPublic;
`isPublic` 보다는 공개 범위를 의미하는 `visibility`가 더 적절할 것 같은데 어떤가요?

또한 boolean 값을 보고 private과 public을 판단하는 것보다, enum으로 명시하면 더 좋을 것 같아요. 

그렇게하면 만약 `private`, `public` 외에도 `friends only` 등의 공개 범위가 정책적으로 추가되더라도 대응이 쉬울 것 같아요.

2024-10-09 05:51 UTC, jminkkk reviewed
켬미 이 PR 변경사항에 잡히지 않았던 부분을 #761 보면서 확인해서 추가로 코멘트 남겨요!
`SpringDocTemplateController.java`에 단건 조회 부분에서 다른 회원의 비공개 글을 조회하면 403이 터져야 할 것 같아요.

이 부분도 문서화 추가 부탁드립니다!

2024-10-09 14:41 UTC, kyum-q commented on backend/src/main/java/codezap/template/domain/Template.java
> +    private boolean isPublic;
공개 여부는 추후에 변경 사항이 안생길거라 생각하여 enum으로 할 필요 없다고 판단해었습니다. 그런데 friends only 등의 공개 범위가 추가될 수도 있겠네요 ~!
그럼 visibility로 하여 enum 으로 하도록 할게요 굿 ~!

2024-10-09 15:05 UTC, kyum-q commented
[제우스 의견](https://github.com/woowacourse-teams/2024-code-zap/pull/748#discussion_r1792823186)에 따라 isPublic을 visibility로 변경하였습니다.

Visibility는 enum 클래스로 public과 private가 있습니다

2024-10-10 08:07 UTC, HoeSeong123 submitted a review, later dismissed
변경사항 확인했습니다👍

2024-10-10 08:07 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/domain/Visibility.java
> +public enum Visibility {
👍

2024-10-10 08:24 UTC, zangsu approved these changes
켬 고~ 켬미 고생했어요~~

2024-10-10 12:22 UTC, zeus6768 approved these changes
👍

2024-10-11 00:46 UTC, jminkkk approved these changes

2024-10-11 01:12 UTC, jminkkk approved these changes

2024-10-11 01:12 UTC, zangsu approved these changes

2024-10-11 01:14 UTC, HoeSeong123 approved these changes

2024-10-11 01:14 UTC, zeus6768 approved these changes

2024-10-11 01:14 UTC, Hain-tain approved these changes
켬미 짱❤️❤️❤️

2024-10-11 01:14 UTC, merged