로그백 롤링 파일 정책 변경
woowacourse-teams/2024-code-zap pull request #764
Opened 2024-10-09 11:10 UTC by jminkkk

## ⚡️ 관련 이슈
close #763

## 📍주요 변경 사항
1. 로그백의 설정을 SizeAndTimeBased -> TimeBased로 변경합니다.

## 🎸기타
1. 이슈에 변경 이유 작성해놓았으니 참고 부탁드립니다~

2024-10-09 11:20 UTC, zeus6768 requested changes
멋져요 몰리~!

몰리의 이슈를 저도 금방 공식문서를 찾아봤는데, TimeBasedRollingPolicy를 사용하면서도 용량으로 rolling할 수 있는 것 같아요. 

해당 내용 이슈에 [코멘트](https://github.com/woowacourse-teams/2024-code-zap/issues/763#issuecomment-2402037547) 남겼는데, 어떻게 생각하는지 궁금해요~!

2024-10-09 11:42 UTC, zangsu approved these changes
문제 상황에 빠른 대처, 몰리 킹왕캡짱굳갓잽

2024-10-09 15:14 UTC, HoeSeong123 approved these changes
이런건 또 언제 찾아봤대!!
멋져요 몰리👍

2024-10-09 23:26 UTC, kyum-q submitted a review, later dismissed
몰리 체고에요 ~ 문제를 파악하고 해결하는 멋진 몰리네요 ~

2024-10-09 23:29 UTC, zeus6768 approved these changes
👍

2024-10-09 23:48 UTC, zeus6768 requested changes
TotalSizeCap을 늘려야 할 것 같아요~

짱수의 이슈 코멘트를 보고 찾아봤는데, TotalSizeCap은 모든 날짜의 모든 로그의 용량의 총합을 의미한대요. 

1GB가 좋을 것 같아요~!

2024-10-10 04:12 UTC, jminkkk commented
대면 회의에서 논의했던 것처럼 1GB는 부족할 수도 있을 것 같아, 10GB로 변경완료하였습니다~!

2024-10-10 07:30 UTC, HoeSeong123 approved these changes

2024-10-10 08:41 UTC, zeus6768 requested changes
🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

2024-10-10 11:53 UTC, kyum-q submitted a review, later dismissed
몰리 체고~

2024-10-11 05:42 UTC, zeus6768 approved these changes

2024-10-12 08:59 UTC, HoeSeong123 approved these changes

2024-10-12 09:10 UTC, kyum-q approved these changes

2024-10-12 11:11 UTC, zangsu approved these changes
지민크크크 수고했습니다~!!

2024-10-12 11:11 UTC, merged