TemplateControllerTest를 MockMvcTest로 변경
woowacourse-teams/2024-code-zap pull request #772
Opened 2024-10-11 01:34 UTC by jminkkk

## ⚡️ 관련 이슈
close #767

## 📍주요 변경 사항
1. 이슈에 따른 테스트 변경했습니다.
2. 문자열 DTO 관련 부분에 대해 가독성이 너무 떨어지고 알아보기 어려웠습니다. 따라서 Stream<Argument> 로 개선하였습니다.~

2024-10-13 13:31 UTC, HoeSeong123 reviewed
몰리~~~~ 컨트롤러 테스트 건들기 무섭다고 계속 그랬으면서 그런거 치고 정말 순식간에 해치워버리셨네요
너무 고생하셨습니다!!
역시 코드잽 백엔드의 자랑 몰리
코백자몰👍

2024-10-13 13:31 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static CreateTemplateRequest createValidTemplateRequest() {
👀
```suggestion
        private CreateTemplateRequest createValidTemplateRequest() {
```

2024-10-13 13:31 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static Stream<Arguments> invalidTemplateData() {
👀
```suggestion
        private Stream<Arguments> invalidTemplateData() {
```

2024-10-13 13:31 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static CreateTemplateRequest createRequestWithInvalidTitle(String invalidTitle) {
이하 생략하겠습니닷!
```suggestion
        private CreateTemplateRequest createRequestWithInvalidTitle(String invalidTitle) {
```

2024-10-13 13:31 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        @DisplayName("템플릿 생성 실패: 잘못된 소스 코드 순서 입력 시 400 반환")
흠.. 제목이 조금 애매한 것 같아요.
저희가 블랙박스 테스트를 적용하기로 이야기 했으니까 해당 예외는 컨트롤러가 몰라야 할 것 같아요.
아마 `잘못된 소스 코드 순서` 그 자체보다는 그냥 예외가 발생했을 때 400을 반환하는지 확인하고 싶은 것 같은데 그렇다면 그냥 `템플릿 생성 실패시 400 반환` 등으로 보다 넓은 범위로 DisplayName을 짓는 건 어떤가요??

2024-10-13 13:31 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        @DisplayName("템플릿 단건 조회 성공")
단건 조회 실패 시 404 에러 반환 테스트도 추가해주세욧!

2024-10-13 13:31 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static UpdateTemplateRequest createValidUpdateTemplateRequest() {
헉👀
```suggestion
        private UpdateTemplateRequest createValidUpdateTemplateRequest() {
```

2024-10-13 13:31 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
>          @DisplayName("템플릿 수정 실패: 잘못된 소스 코드 순서 입력")
위에서 얘기한 것과 같은 이유로 해당 테스트는 서비스에서 테스트 하고 있으니까 없어져도 될 것 같은데 어떤가요??
실패시 400을 반환하는 것에 대해서만 체크하면 될 것 같아요~~

2024-10-13 13:31 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        @DisplayName("템플릿 삭제 성공")
삭제에 실패하는 경우에는 어떤 에러코드를 출력하나요?

(근데 이거 제가 블랙박스 테스트를 제대로 이해한게 맞나요? 제가 이해하기로는 성공 또는 실패시 적절한 상태 코드를 반환하는지를 컨트롤러 테스트에서 확인해야 한다고 이해했는데 맞나요?)

2024-10-13 14:00 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        @DisplayName("템플릿 생성 실패: 잘못된 소스 코드 순서 입력 시 400 반환")
엇 저도 처음에 서비스단에 있을 검증일 것 같아 삭제하려구 했는데요! 
기존 구현이 `@SourceCodesOrdinal`이라는 커스텀 어노테이션으로 순서 검증을 컨트롤러 단에서 하도록 되어 있더라구요!
`UpdateTemplateRequest` 보시면 `ValidatedSourceCodesOrdinalRequest`를 구현하고 있습니다...

2024-10-13 14:01 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        @DisplayName("템플릿 단건 조회 성공")
내부 구현을 컨트롤러가 모르게 되면 404 컨트롤러 테스트에서는 하지 않아도 될 것 같은데 초롱은 어떻게 생각하시나요!
에러를 던질 때 매핑된 상태코드를 서비스단에서 같이 테스트하면 좋을 것 같다는 생각입니답

2024-10-13 14:02 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
>          @DisplayName("템플릿 수정 실패: 잘못된 소스 코드 순서 입력")
이 부분도 위와 동일하게 컨트롤러 DTO에서 하고 있습니다!

2024-10-13 14:03 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static Stream<Arguments> invalidTemplateData() {
굿! 추가하겠습니다!

2024-10-13 14:15 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static CreateTemplateRequest createValidTemplateRequest() {
`@MethodSource`를 사용하려면 static이여야 한다는 사실...

2024-10-13 14:15 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static Stream<Arguments> invalidTemplateData() {
@MethodSource를 사용하려면 반환되는 메서드는 static이여야 한다는 사실...

2024-10-13 14:15 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static CreateTemplateRequest createRequestWithInvalidTitle(String invalidTitle) {
@MethodSource를 사용하려면 반환되는 메서드는 static이여야 한다는 사실... ㅠㅠ

2024-10-13 14:16 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static UpdateTemplateRequest createValidUpdateTemplateRequest() {
@MethodSource를 사용하려면 반환되는 메서드는 static이여야 한다는 사실... 흑흑

2024-10-13 14:23 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        @DisplayName("템플릿 삭제 성공")
음 삭제를 실패할 경우가 지금은 TemplateService에서 던지는 태그 아이디 중복 에러가 있네요.
제가 이해하기로는 서비스 단에서 터지는 에러는 이제 서비스단에서 확인해야 한다고 생각합니다.

에러를 던지는 게 서비스 단이기 때문에 컨트롤러는 몰라도 되지 않을까요? 
터지는 에러 확인하려고 Service 타고 들어가면서 느낌~~

2024-10-13 14:30 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static CreateTemplateRequest createValidTemplateRequest() {
이럴수가 전혀 몰랐네요..심지어 컴파일 에러도 안잡히던데 미친코드..
아무튼 좋네요!!👍

2024-10-13 14:30 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        @DisplayName("템플릿 생성 실패: 잘못된 소스 코드 순서 입력 시 400 반환")
오 그렇군요 그러면 이런 식으로 검증에서 터지는 예외에 대해서만 실패 테스트를 진행하고 있었던거군요 
확인했습니다!!👍

2024-10-13 14:30 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        @DisplayName("템플릿 단건 조회 성공")
위와 같은 이유로 동의합니다!!

2024-10-13 14:31 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        @DisplayName("템플릿 삭제 성공")
아 그렇군요 제가 잘못 이해하고 있었네요!!
확인했습니다!!👍

2024-10-13 14:31 UTC, HoeSeong123 approved these changes
따봉👍

2024-10-14 12:46 UTC, kyum-q requested changes
몰리 진짜 최고 ~~!!
코드가 완전 깔쌈해졌네용 👍
간단한 코멘트 남겨뒀습니다 확인 부탁드려요 ~

2024-10-14 12:46 UTC, kyum-q commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +                    Arguments.of(createRequestWithLongTag(), "태그 명은 최대 30자까지 입력 가능합니다."));
@NotNull(message = "템플릿 공개 여부가 null 입니다.", groups = NotNullGroup.class)

visibility가 null 일 경우도 해주세용 ~!

2024-10-14 12:46 UTC, kyum-q commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static Stream<Arguments> invalidTemplateData() {
> @NotNull(message = "썸네일 순서가 null 입니다.", groups = NotNullGroup.class)
> int thumbnailOrdinal

CreateTemplateRequest에 thumbnailOrdinal 값은 null 이 될 수 없으니 지금 PR에서 제거해줘도 좋을 것 같아요 ~

2024-10-14 13:13 UTC, zeus6768 requested changes
작업량이 어마어마하네요...🔥

간단한 질문 남겼어요 !!

2024-10-14 13:13 UTC, zeus6768 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +    void FindAllTemplatesSuccess() throws Exception {
얼마 전에 ArgumentResolver의 기능이 개선되었는데요~~

`member`가 `AuthenticationPrinciple`에 의해 파라미터로 들어온 경우와 들어오지 않은 경우를 구분해서 테스트하는 내용이 추가되면 좋을 것 같은데 몰리는 어떻게 생각하나요~!

2024-10-14 13:13 UTC, zeus6768 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +    class findTemplateTest {
> member가 AuthenticationPrinciple에 의해 파라미터로 들어온 경우와 들어오지 않은 경우를 구분해서 테스트하는 내용이 추가되면 좋을 것 같은데 몰리는 어떻게 생각하나요~!

이 부분도 같은 질문 드려요~!

2024-10-14 13:13 UTC, zeus6768 commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        @DisplayName("템플릿 생성 실패: 문자열 잘못된 형식인 경우 400 빈환")
😁

```suggestion
        @DisplayName("템플릿 생성 실패: 문자열 잘못된 형식인 경우 400 반환")
```

2024-10-14 15:36 UTC, zangsu commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
>      class CreateTemplateTest {
궁금한 게 있는데, 몰리는 어떤 것을 기준으로 테스트 해야할 상황을 정하나요?
테스트를 살펴보니 DTO에 적혀있는 검증 어노테이션들을 기준으로 테스트를 하는 것 같은데 맞을까요?

뭐라고 하는 게 아니라 저도 참고하고 싶어서 ㅋㅎ

2024-10-14 15:37 UTC, zangsu commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static Stream<Arguments> invalidTemplateData() {
넘모 꼼꼼해 최고~~

2024-10-14 15:38 UTC, zangsu commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
>      private static final int MAX_LENGTH = 255;
개선하는 김에 몰리의 변경사항이 아니지만, 수정하고 가도 좋을 것 같은데요.
템플릿 생성에서 사용될 수 있는 "최대길이" 는 여러 값이 있어요. 
(태그 길이, 제목 길이, 코드 길이...)

같은 값을 가지고 있지만, 조금 더 명시적으로 나누어 두면 읽기 편하지 않을까 하는 생각에 값 분리를 제안드려봅니다!

2024-10-14 15:40 UTC, zangsu commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +    void FindAllTemplatesSuccess() throws Exception {
오, "인증 정보가 있는 / 없는" 경우로 나누어서 테스트를 해 볼 수 있을 것 같네요.
그렇다면 다른 메서드 테스트에서도 인증 정보가 없는 경우에 대한 실패 테스트가 존재해도 좋을 것 같군요.

2024-10-14 15:44 UTC, zangsu commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +    class findTemplateTest {
실패 테스트가 없는것은 전부 서비스계층의 책임이기 때문인것이죠?

2024-10-15 14:22 UTC, kyum-q commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +                    Arguments.of(createRequestWithLongTag(), "태그 명은 최대 30자까지 입력 가능합니다."));
굿굿 👍🏻 기능이 추가될 때 테스트가 구현되야하는 건 맞지만 이미 구현된 Dto 여서 말했슴당🫶🏻

2024-10-15 14:24 UTC, kyum-q commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static Stream<Arguments> invalidTemplateData() {
thumbnailOrdinal int 로 primitive 타입입니다 그러면 해당 값이 들어가는 부분이 null일 경우 dto 검증이 오기 전에 스프링 단에서 예외가 발생할 것 같아요. 왜냐 int 는 primitive 타입이라 일단 null을 가질 수 없음.
그러니 dto 에 있는 primitive는 null 체크 검증을 없애도 될 것 같습니다!

2024-10-15 14:48 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static Stream<Arguments> invalidTemplateData() {
아 아예 검증 자체를 제거하자는 거였군요!
오케오케 이해했습니다 여기서 그냥 지워버릴게요???!!!!!!!!!!!!!!!!!

2024-10-15 14:49 UTC, kyum-q commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static Stream<Arguments> invalidTemplateData() {
굿굿 !!

2024-10-16 04:09 UTC, zeus6768 submitted a review, later dismissed
👍

2024-10-16 14:32 UTC, kyum-q commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +        private static Stream<Arguments> invalidTemplateData() {
해당 뷰분 int 를 Integer로 라고 null 아닌지 검증 살리기로 결정 했음~!

2024-10-17 09:21 UTC, zangsu commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
>      private static final int MAX_LENGTH = 255;
옹 그냥 저는 "이게 무슨 값에 대한 MAX_LENGTH 인거지?" 라고 의문이 들었던거라 굳이 안바꿔도 상관은 없습니다~
가독성 측면에서 제안드린거였어요!

2024-10-17 09:21 UTC, zangsu commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
>      private static final int MAX_LENGTH = 255;
법칙가?

2024-10-17 09:22 UTC, zangsu approved these changes

2024-10-17 10:22 UTC, kyum-q approved these changes

2024-10-18 01:20 UTC, zeus6768 approved these changes

2024-10-18 06:25 UTC, HoeSeong123 approved these changes

2024-10-18 06:25 UTC, merged