템플릿 공개 범위 설정 기능 구현
woowacourse-teams/2024-code-zap pull request #785
Opened 2024-10-14 15:16 UTC by kyum-q

## ⚡️ 관련 이슈
#739

## 📍주요 변경 사항
- [x] 템플릿 생성 시, 공개 여부 포함하도록 body 변경
- [x] 템플릿 조회 시, memberId가 없으면 public 템플릿만 반환
- 템플릿 조회 시, memberId가 있으면
    - [x] memberId와 현재 쿠키 정보가 동일할 경우 private 템플릿까지 반환
    - [x] 동일하지 않으면 public 템플릿만 반환
- [x] 템플릿 수정 시, 공개 여부 포함하도록 body 변경

## 🎸기타
[헤인] - @Hain-tain 수정 시에도 공개 여부 request에 넣어주실 수 있나요? 안그러면 visibility 수정을 못해요..!

2024-10-14 15:34 UTC, Hain-tain commented
수정 시에도 visibility 필수로 다 넣어드릴게요!! 👍

2024-10-15 14:46 UTC, jminkkk requested changes
켬미 짱
리뷰 확인해주쎄옹 체고🔥

2024-10-15 14:46 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        if (memberId == null || memberId.equals(loginMember.getId())) {
⚡️loginMember 에게 물어볼까요~~~~~~~~~~~?
```suggestion
        if (memberId == null || loginMember.hasSameId(memberId)) {
```

2024-10-15 14:46 UTC, jminkkk commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +                    Visibility.PUBLIC
.............제 템플릿 컨트롤러 테스트 말고 켬미 PR이 먼저 머지되어야겠네요........... 다들 참고 🥲

2024-10-15 14:46 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +            thumbnailRepository.save(new Thumbnail(template, sourceCode));
⚡️ 이거 추가된 3개 메서드 모두에서 사용 중인 것 같은데, 메서드로 빼면 어떨까요??

그리구 픽스처가 있는 친구들은 재활용해볼까요?~ 의미없는 상수로부터 눈이 조금이나마 자유로워질 수 있을 것 같아요
``
```suggestion
            var template = templateRepository.save(TemplateFixture.get(member, category));
            var sourceCode = sourceCodeRepository.save(SourceCodeFixture.get(template, 1));
            thumbnailRepository.save(new Thumbnail(template, sourceCode));
```

2024-10-15 14:46 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +            thumbnailRepository.save(new Thumbnail(privateTemplate, privateSourceCode));
여기도 메서드 추출 + 픽스처 사용이 가능할 것 같아요~!
전 메서드 시그니처로 충분히 의미가 보일 수 있다고 생각해요 👀

```java
        public Template savePrivateTemplate(final Member member, final Category category) {
            var privateTemplate = templateRepository.save(TemplateFixture.get(member, category, Visibility.PRIVATE));
            var privateSourceCode = sourceCodeRepository.save(SourceCodeFixture.get(privateTemplate, 1));
            thumbnailRepository.save(new Thumbnail(privateTemplate, privateSourceCode));
            return privateTemplate;
        }
```

2024-10-16 02:22 UTC, zeus6768 approved these changes
깔끔하게 구현했네요! 👍

2024-10-16 04:13 UTC, kyum-q commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +                    Visibility.PUBLIC
고니까요.. 테스트 추가는 안했으니 몰리 테스트로 덮어쓰기 해야할 것 같아요 !

2024-10-16 04:21 UTC, HoeSeong123 requested changes
훌륭하네요 켬미!!
켬미의 업무수행 속도는 항상 놀랍네요 정말

2024-10-16 04:21 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +    }
⚡
memberId가 null인 경우는 구경가기 탭에 접속한 경우라고 생각됩니다.
그렇다면 Visibility는 PUBLIC이어야 할 것 같네요!

2024-10-16 04:21 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +            );
```suggestion
            assertThat(actual.getContent()).hasSize(1)
                                         .containsExactlyInAnyOrder(templateRepository.fetchById(4L));
```

2024-10-16 04:21 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
> +        );
```suggestion
        assertThat(actual.getContent()).hasSize(1)
                                     .containsExactlyInAnyOrder(templateRepository.fetchById(3L));
```

2024-10-16 04:21 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
> +        );
```suggestion      
        assertThat(actual.getContent()).hasSize(1)
                                     .containsExactlyInAnyOrder(templateRepository.fetchById(4L));
```

2024-10-16 04:28 UTC, zangsu reviewed
켬큐 고생 많았어요~~~
작업하기 상당히 복잡했을 것 같은데, 잘 구현해 주셨네요ㅠㅠ 최고!!
가벼운 질문 & 제안정도밖에 없어 코멘트로만 남겨 둘게요~~

2024-10-16 04:28 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +        void findAllSuccessByMemberIdAndVisibility() {
검증부의 `fetchById(3L)` 부분이 조금 고민이 되었는데요.
데이터 업데이트 과정이 복잡하기 때문에 미리 데이터를 입력해 두어야 하지만, 또 4L 아이디가 어떤 것을 의미하는지 알아보기 어렵기도 해서 말이에요.

그래서 말인데 이런 방법은 어떻게 생각하시나요?
데이터 초기화때 `List<Template> templates = List.of(template1, template2, template3, template4);` 를 만들어 두고 각 테스트의 상단에 아래 코드를 추가하는 방법입니다.
```java
 List<Template> canSearchTemplates = templates.stream()
            .filter(template -> template.getMember().getId().equals(memberId)
                    || template.getVisibility() == Visibility.PUBLIC)
            .toList();
```

+) 
바로 적용해 달라는 것은 아니에요! 
이 테스트 코드에 전반적으로 공유되는 문제라고 생각이 들어서 나중에 한번에 리팩토링을 해도 좋을 것 같은데요.
다만, 이 테스트에 대한 논의가 이루어 지는 시점에서 생각을 공유 드리는 것이 가장 이해가 빠를 것 같아 언급만 드렸으니 편하게 의견만 달아 주셔도 좋을 것 같아요!

2024-10-16 04:28 UTC, zangsu commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> +        @DisplayName("검색어, 카테고리ID, 태그ID로 템플릿 검색 성공: 사용자ID와 로그인 정보가 같을 경우 (private 템플릿 포함)")
상세한 테스트 설명 👍

2024-10-16 16:16 UTC, kyum-q commented on backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
> +        Visibility visibility
PUBLIC, PRIVATE가 아닌 enum에 없는 값일 경우 검증을 이야기하는 게 맞을까요?

만약 enum에 존재하지 않는 값이 들어온다면, 다음과 같이 스프링에서 검증해줍니다 ! DTO까지 들어오지 않아요 ! 그래서 따로 검증 로직을 추가할 필요 없을 것 같습니다 !
![image](https://github.com/user-attachments/assets/02f0e2f6-1e62-466c-87f2-93f4148c0a9b)

> 현재 해당 에러는 [PR](https://github.com/woowacourse-teams/2024-code-zap/pull/796) 에서 더 정확한 에러가 반환되도록 수정되었습니다 !

2024-10-16 16:53 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +        void findAllSuccessByMemberIdAndVisibility() {
굿 !! 
태그 검색 관련은 도메인 비교로는 어려울 것 같아서 당장은 수정하지 않고 태그가 아닌 다른 테스트들은 모두 수정했습니다 ~

2024-10-17 01:15 UTC, jminkkk requested changes
켬미 마지막까지 ㅍㅇㅌ.........

2024-10-17 01:15 UTC, jminkkk commented on backend/src/main/java/codezap/member/domain/Member.java
> +
테스트 추가해주세요~!

2024-10-17 09:23 UTC, zangsu commented on backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
> +        Visibility visibility
오 그렇군요...!!!
좋습니닷 👍

2024-10-17 09:27 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +        void findAllSuccessByMemberIdAndVisibility() {
나중에 `assertThat` 부분에 존재하는 부분 `templates.stream().....toArray()` 도 given 절로 빼도 좋을 것 같네요!

2024-10-18 01:06 UTC, jminkkk approved these changes

2024-10-18 06:26 UTC, HoeSeong123 submitted a review, later dismissed

2024-10-18 08:00 UTC, zeus6768 submitted a review, later dismissed

2024-10-18 08:12 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +        void findAllSuccessByMemberIdAndVisibility() {
이거 나중에 해주세용~~

2024-10-18 08:12 UTC, zangsu approved these changes

2024-10-18 08:25 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +        void findAllSuccessByMemberIdAndVisibility() {
귯!

2024-10-18 08:51 UTC, HoeSeong123 approved these changes

2024-10-18 08:51 UTC, zangsu approved these changes

2024-10-18 09:03 UTC, zeus6768 approved these changes

2024-10-18 09:11 UTC, jminkkk approved these changes

2024-10-18 09:11 UTC, merged