템플릿 공개 범위 설정(visibility) 기능 구현
woowacourse-teams/2024-code-zap pull request #787
Opened 2024-10-14 18:09 UTC by Hain-tain

## ⚡️ 관련 이슈
- #739 

## 🪧 구현 사항
<details>
<summary> visibility 선택 UI는 아래와 같이 토글로 구현하였습니다. </summary>

https://github.com/user-attachments/assets/ef454086-0016-451c-a439-62dca595f7a8

</details>

<details>
<summary> 템플릿 카드에서 private 표시 </summary>
<img width="742" alt="스크린샷 2024-10-15 오전 2 06 10" src="https://github.com/user-attachments/assets/4a29f99f-a1d8-4ec9-a053-b9b3e898884e">

</details>

<details> 
<summary> 상세페이지에서 private 표시 </summary> 

|제목 짧을 경우| 제목 길 경우|
|--------------------------|-------------------------|
|<img width="892" alt="스크린샷 2024-10-15 오전 2 18 09" src="https://github.com/user-attachments/assets/168334df-ac6c-4a5b-bb46-f047bfe4effa">|<img width="908" alt="스크린샷 2024-10-15 오전 2 30 02" src="https://github.com/user-attachments/assets/f01658a7-9ee7-4a4a-b0e9-ac9337472a73">|

</details>

## 📍주요 변경 사항
### 1. Toggle 컴포넌트 생성
- 길이가 2인 배열로 옵션을 받습니다. 0번째가 왼쪽, 1번째가 오른쪽 옵션이 됩니다.

### 2. Template 관련 타입에 visibility 추가
- `constants 파일`에서 `TEMPLATE_VISIBILITY` 를 선언하고, 이를 바탕으로 타입 `TemplateVisibility`을 추출하였습니다.

### 3. `TemplateUploadPage`, `TemplateEditPage`에 visibility Toggle 추가

### 4. visibility가 private인 경우 템플릿 카드, 상세 페이지에서 privateIcon 보이도록 설정
- public인 경우에는 지금과 디자인적 차이는 없습니다. 그냥 private인 경우 privateIcon(자물쇠 아이콘)을 추가해서 구분해주었어요!

## 🎸기타
- 우려했던 상황이 발생했습니다. 수정 페이지에 변경사항이 생기면 `TemplateUploadPage`, `TemplateEditPage` 두 파일 모두 수정해주어야 해서 굉장히 번거롭습니다...🥲 이 부분에 대해 또 다시 추상화를 진행해도 괜찮을까요?
- `Toggle` 컴포넌트가 생기면서 `useToggle`이 마치 이 컴포넌트를 위해 존재하는 훅처럼 느껴질까봐 조금 걱정이 됩니다. 현재 `Toggle` 컴포넌트는 `useToggle`을 사용하지 않습니다. option을 T 로 받고, selectedOption 또한 T 로 관리하기 때문입니다. 커스텀 훅의 이름을 위와 같이 지은 이유는 boolean 값을 토글처럼 바꾼다는 의미에서 가져온 것인데 자칫 혼동을 줄 수 있을 것 같아 한 번 더 언급해봅니다. 혹시 계속 혼동될 것 같다면 커스텀 훅 네이밍을 바꿔도 좋을 것 같습니다. 

## 🍗 PR 첫 리뷰 마감 기한
10/16(수) 18:00

2024-10-15 16:36 UTC, Jaymyong66 requested changes
빠른 시간안에 구현해주셨네요 헤인!
점점 실력이 느는게 보여서 대단합니다.

코드 관련 사항은 코멘트 남겼고, 디자인 관련해서는 내일 상의해보아요.
예를 들어, visibility 토글을 저장 버튼 옆에 둘건지 등등,,

고생하셨습니다~!

2024-10-15 16:36 UTC, Jaymyong66 commented on frontend/src/components/TemplateCard/TemplateCard.tsx
> +  const isPrivate = visibility === 'PRIVATE';
이 문자열도 constant로 관리하면 좋겠네요!

2024-10-15 16:36 UTC, Jaymyong66 commented on frontend/src/components/Toggle/Toggle.style.ts
> +  width: calc(50%);
요건 어떤 식인가요?!

2024-10-15 16:36 UTC, Jaymyong66 commented on frontend/src/pages/TemplateEditPage/TemplateEditPage.style.ts
> +  padding-top: 0.5rem;
👍👍

2024-10-15 16:36 UTC, Jaymyong66 commented on frontend/src/components/Toggle/Toggle.tsx
> +  optionSliderColor = [undefined, undefined],
해당 값들을 undefined로 기본값을 줘야하는 이유가 뭔가요?! 혹시 이후 사용처에서 옵셔널 체이닝을 쓰지 않기 위함인가요?

2024-10-15 16:36 UTC, Jaymyong66 commented on frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
> +                <PublicIcon key={TEMPLATE_VISIBILITY[0]} width={18} />,
key가 필요한 이유가 뭔가요?!

2024-10-15 16:36 UTC, Jaymyong66 commented on frontend/src/pages/TemplatePage/TemplatePage.tsx
> +                        <PrivateIcon width={14} color={theme.color.light.black} />
원래 컬러가 black 아닌가요? 다른 사용처에서는 color 속성을 주지 않길리 질문드림다

2024-10-15 16:36 UTC, Jaymyong66 commented on frontend/src/components/TemplateCard/TemplateCard.tsx
> +            {isPrivate && <PrivateIcon width={14} color={theme.color.light.secondary_800} />}
아이콘의 width를 14나 18 처럼 쓰고있는데, 이런 매직넘버를 줄이고 나중에는 여기서는 몇을 써야하지? 같은 상황을 방지하기 위해 해당 icon을 svg component롤 만들어서 해당 값들을 의미 있는 변수로 할당하면 좋겠네요!

2024-10-16 01:05 UTC, Hain-tain commented on frontend/src/components/Toggle/Toggle.style.ts
> +  width: calc(50%);
오른쪽 옵션을 선택하면 오른쪽으로 슬라이더를 보내주는 부분입니다!

2024-10-16 01:07 UTC, Hain-tain commented on frontend/src/components/TemplateCard/TemplateCard.tsx
> +            {isPrivate && <PrivateIcon width={14} color={theme.color.light.secondary_800} />}
저도 다른 PR에서도 느꼈어요! 스타일 관련된 상수 파일을 하나 만들어도 좋을 것 같다는 생각이 듭니다!

2024-10-16 02:50 UTC, Jaymyong66 commented on frontend/src/components/Toggle/Toggle.style.ts
> +  width: calc(50%);
`width: calc(50%);` 부분이면 그냥 50%랑 같지 않을까 해서요!

2024-10-16 04:41 UTC, Hain-tain commented on frontend/src/components/Toggle/Toggle.style.ts
> +  width: calc(50%);
앗, 그 부분은 50%랑 동일합니다! (원래 계산식이 있었는데 수정하면서 빠졌나봐요)
`width: 50%;` 으로 수정해두겠습니다!! 👍

2024-10-16 05:03 UTC, Hain-tain commented on frontend/src/components/Toggle/Toggle.tsx
> +  optionSliderColor = [undefined, undefined],
현재 아래와 같이 구조분해 할당을 해서 사용하고 있는데,
```ts
 const [leftOptionAdornment, rightOptionAdornment] = optionAdornments;
```
해당 값들에 기본값을 주지 않으면 아래와 같은 에러가 납니다.
```
'[ReactNode, ReactNode] | undefined' 형식에는 반복기를 반환하는 '[Symbol.iterator]()' 메서드가 있어야 합니다.
```

2024-10-16 05:58 UTC, Hain-tain commented on frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
> +                <PublicIcon key={TEMPLATE_VISIBILITY[0]} width={18} />,
아래와 같은 eslint 에러를 해결하기 위해 key 를 넣어주었습니다.

``` 
Missing "key" prop for element in array
```

개인적인 추측으로는 인자로 전달되는 ReactNode 이기 때문에 key 값으로 변경을 감지하기 위해 경고해주는 것 아닐까 싶습니다.

2024-10-16 12:23 UTC, Jaymyong66 commented on frontend/src/components/Toggle/Toggle.tsx
> +  optionSliderColor = [undefined, undefined],
두 props를 분리해서 쓰면 더 명확해지는 대신 props가 많아질까요?

2024-10-16 12:24 UTC, Jaymyong66 commented on frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
> +                <PublicIcon key={TEMPLATE_VISIBILITY[0]} width={18} />,
오홍 아마 두 아이콘이 배열로 전달되어서 그런 것 같네용

2024-10-17 00:22 UTC, Hain-tain commented on frontend/src/pages/TemplatePage/TemplatePage.tsx
> +                        <PrivateIcon width={14} color={theme.color.light.black} />
현재 `PrivateIcon` 과 `PublicIcon`은 상위 컨텐츠의 색상을 따르도록 되어있으나(`fill="currentColor"`), 해당 부분에서 왜인지 `#393e46`값을 가지더라고요. 제목과 같은 줄에 있으므로 제목과 같은 컬러를 사용해주는 것이 좋을 것 같아 위와 같이 색상을 지정해주었습니다.

2024-10-17 09:03 UTC, Hain-tain commented
https://github.com/user-attachments/assets/730acb33-9a23-47e2-bbc5-14ef84a6f283

최종 디자인 결과입니다!

2024-10-17 09:34 UTC, Jaymyong66 approved these changes

2024-10-17 14:30 UTC, Jaymyong66 commented on frontend/src/assets/images/Hamburger.tsx
> +      height={ICON_SIZE.LARGE}
오 이렇게 처리를 했군요?! 사실 상수로 할 생각은 안해봐서 신박했습니다.
원래는 `HamburgerIcon`에 Props를 필요에 따라 medium, large 이런 식으로 하려 했거든요.
다만 상수로 하니까 애매한 건 MEDIUM_LARGE 같은 상수가 나와버리네요..! ㅋㅋㅋ

2024-10-18 05:43 UTC, vi-wolhwa approved these changes

2024-10-18 06:06 UTC, merged