멤버 별 템플릿 페이지 구현
woowacourse-teams/2024-code-zap pull request #815
Opened 2024-10-18 08:42 UTC by vi-wolhwa

## ⚡️ 관련 이슈
close #749

## 📍주요 변경 사항
> 멤버별 템플릿 페이지 구현
> - MyTemplatePage 라우팅 주소 변경
> - getMemberName API 구현

> API 함수 파라미터 수정 (tagList, categoryList)
> - memberId를 Optional에서 필수 값으로 변경

> 변수명 변경 (Header.tsx)
> - `menuOpen` -> `isMenuOpen`

## 🍗 PR 첫 리뷰 마감 기한
10/20 00:00

2024-10-20 08:31 UTC, Jaymyong66 requested changes
고생하셨습니다!
코멘트 몇가지 남겼으니 확인해주시고 예비군 조심히 다녀오시길,,

2024-10-20 08:31 UTC, Jaymyong66 commented on frontend/src/components/Header/Header.tsx
> +            )}
PR 메시지에 `MyTemplatePage 라우팅 주소 변경` 관련해서 변경된 이유를 함께 설명해주면 리뷰하기 편할 것 같아요~!

2024-10-20 08:31 UTC, Jaymyong66 commented on frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
>    const [description, handleDescriptionChange] = useInput(template.description);
이게 memberId의 타입은 number | undefined인데, !로 단언해서 쓰는게 조금 걸리네요.
로그인한 유저의 memberId와 query로 쓰는 memberId를 분리하거나 undefined를 그냥 제거하는 방향도 생각해봐야겠네요.

혹은 해당 쿼리를 보낼 때, 로그인하지 않았다면 에러를 발생시키는 방법도 있겠네요.

2024-10-20 08:31 UTC, Jaymyong66 commented on frontend/src/pages/TemplatePage/TemplatePage.tsx
> +  };
template 부분을 SuspenseQuery로 하면 해당 옵셔널 체이닝을 제거할 수 있을까요?

2024-10-20 08:31 UTC, Jaymyong66 commented on frontend/src/routes/endPoints.ts
> +  memberTemplates: (memberId: number) => `/members/${memberId}/templates`,
혹시 `:memberId`가 맨뒤로 가지 못하는 이유가 무엇이었나요?!

API endpoint와 route를 분리하긴 해야겠네요,,

2024-10-20 08:31 UTC, Jaymyong66 commented on frontend/src/types/api.ts
> +}
Get을 빼도 될거 같긴 하지만 굳이 반영 안해도 될 것 같습니다~

2024-10-21 10:05 UTC, Hain-tain reviewed
전반적으로 memberId를 단언해서 사용하거나 상위에서 받은 것이 없는 경우 자신의 아이디를 넣어준 경우가 있는데, 조금 더 안전하게 사용하는 방향으로 리펙토링 해봐도 좋을 것 같아요..!

2024-10-21 10:05 UTC, Hain-tain commented on frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
>    const [description, handleDescriptionChange] = useInput(template.description);
!로 단언해서 쓰기보다는 타입 가드를 통해 안전하게 사용하는게 추후 디버깅에 용이할 것 같다는 생각이 듭니다..!

2024-10-22 07:49 UTC, Hain-tain commented
일단 배포일이므로 추후 리펙토링합시다~!!

2024-10-22 07:53 UTC, Hain-tain approved these changes

2024-10-22 07:54 UTC, Jaymyong66 approved these changes
배포 기한때문에 추후 변경 부탁드립니당

2024-10-22 07:54 UTC, merged