서비스 트랜잭션 적용
woowacourse-teams/2024-code-zap pull request #834
Opened 2024-10-20 07:52 UTC by HoeSeong123

## ⚡️ 관련 이슈
close #830

## 📍주요 변경 사항
> 모든 서비스 로직에 @Transactional을 적용했습니다.

## 🎸기타
- #830 에서 적어놓은 것은 `@Transactional`을 모든 서비스 클래스에 기본으로 설정해놓고, `readOnly`가 필요한 메소드만 별도로 `@Transactional(readOnly = true)` 를 붙여주는 것이었습니다.
- 하지만 이렇게 할 경우 다른 개발자가 합류했다고 했을 때, 어떤 트랜잭션 옵션이 붙어있는지 확인하기 힘들 수도 있겠다는 생각이 들었습니다.
- 또한, 이슈에 적은 방법을 제안한 이유는 write인데 readOnly를 붙여서 발생하는 휴먼에러를 방지하기 위함인데, 그렇게 하지 않아도 어차피 발생할 수 있는 오류라고 생각됩니다. 
- 따라서 모든 메소드에 명시적으로 작성하는 방법을 제안하는데 다들 의견이 어떠신가요??

## 🍗 PR 첫 리뷰 마감 기한
00/00 00:00

2024-10-20 12:32 UTC, zangsu requested changes
고생했어요 초롱!
readOnly 가 사용되지 않은 부분이 하나 있어 남겨 두었어요.
+) `AuthService.login()` 메서드에서도 DB 조회가 일어나니 이 부분도 추가해 주어야 할 것 같습니다!

2024-10-20 12:32 UTC, zangsu commented on backend/src/main/java/codezap/template/service/TemplateService.java
> +    @Transactional
얘는 왜 readOnly 가 사용되지 않죠?

2024-10-21 05:07 UTC, kyum-q approved these changes
굿 쟙 ~!!!

2024-10-21 05:14 UTC, jminkkk reviewed
안녕하세요 초롱~
수고하셨습니다 🔥
나누고 싶은 의견 있어서 아래 작성해보았어요 확인 부탁드립니다!

> 모든 메소드에 명시적으로 작성하는 방법을 제안하는데 다들 의견이 어떠신가요??

초롱의 의견과 우려가 이해가 가는데요. 그래도 저는 불필요한 코드 중복처럼 느껴져요. 
또 반대로 나~중에 새 메서드를 만들 때, 타입 단에 어노테이션이 있겠지 하고 메서드 단에 빼먹을 확률도 있을 수도 있을 것 같구요.

만약 중복으로 메서드에 작성하게 되면, 클래스에서 메서드 전체에 적용되는 `@ReqeustMapping` 같은 어노테이션들도 똑같이 클래스가 아닌 메서드에 다 부착이 되어야 할 것 같다고 생각되어요. 이것도  똑같이 조금 불필요하다고 생각이 들구요. 🥲

그리고 만약 한 파일이 너무 커져서 class 타입에 어노테이션이 붙은 것을 파악하지 못할 정도까지 간다면 파일을 분리해야 하는 신호가 아닌가 싶습니다...ㅎㅎ

2024-10-21 05:17 UTC, HoeSeong123 reviewed
반영했습니다 다시 확인해주세요~~

2024-10-21 05:17 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/service/TemplateService.java
> +    @Transactional
아주 꼼꼼해 짱수
아꼼짱👍

2024-10-21 05:26 UTC, zeus6768 submitted a review, later dismissed
초롱 최고에요~~

2024-10-21 05:30 UTC, HoeSeong123 commented
다수결에 의해 클래스 상단에 Transactional을 붙이는 것으로 결정하였습니다.
readOnly를 기본값으로 했는데, 이유는 휴면 에러가 발생할 경우 테스트 단에서 잡아줘야 한다고 생각했기 때문입니다.
물론 저희는 아직 리더 라이터가 로컬에서 분리가 안돼있기 때문에 테스트에서 터지지는 않지만 즈후가 조만간 수정할 예정이라고 합니닷.

2024-10-21 05:35 UTC, kyum-q approved these changes
귯 ~

2024-10-21 05:57 UTC, jminkkk approved these changes
굿

2024-10-21 06:00 UTC, zeus6768 approved these changes

2024-10-21 06:00 UTC, zangsu approved these changes
아오 왜 또 내가 꼴찌 ㅋㅋ

2024-10-21 06:01 UTC, merged