좋아요한 템플릿 목록 조회 API 구현
woowacourse-teams/2024-code-zap pull request #848
Opened 2024-10-21 15:19 UTC by kyum-q

## ⚡️ 관련 이슈
#846

## 📍주요 변경 사항
`template/lliked/{memberId}` 로 좋아요한 템플릿 목록 조회하는 API 구현하였습니다
+) 더 좋은 아이디어 언제든 환영~

내가 좋아요한 템플릿만 볼 수 있도록 제한하려고 하였으나, 다른 사람이 좋아요한 것도 볼 수 있으면 좋지 않을까? 해서 제한을 없앴습니다~
로그인 하든 안하든 누구나 `template/lliked/{memberId}` 로 memberId인 회원인 템플릿을 조회할 수 있습니다.

## 🎸기타

## 🍗 PR 첫 리뷰 마감 기한
10/24 12:00

2024-10-21 16:24 UTC, Jaymyong66 commented
진짜 뭐이리 빨라 켬미~ 이러면 프론트도 해야겠네~~

2024-10-22 06:24 UTC, jminkkk approved these changes
켬미 굿!
수고했어요 🔥

2024-10-22 14:26 UTC, zeus6768 submitted a review, later dismissed

2024-10-22 14:29 UTC, HoeSeong123 requested changes
진짜 빠르구만!!! 너무 멋집니다 켬미 고생하셨어요👍

2024-10-23 06:26 UTC, kyum-q commented on backend/src/main/java/codezap/likes/repository/LikesRepository.java
> +            """)
나 왜 저기 둠..?ㅋㅋㅋㅋ 좋아요~

2024-10-23 07:33 UTC, jminkkk approved these changes

2024-10-24 02:08 UTC, zangsu approved these changes

2024-10-24 02:08 UTC, zangsu commented on backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
> +            WHERE l.member.id = :memberId AND (l.template.member.id = :memberId OR l.template.visibility = 'PUBLIC')
캬 꼼꼼해꼼꼼해

2024-10-24 02:08 UTC, zangsu commented on backend/src/test/java/codezap/global/MockMvcTest.java
> +        when(credentialManager.hasCredential(any())).thenReturn(true);
지금 반영하자는 건 아니고, 나중에 `any()` 말고 특정 값에 따라 리턴값이 달라져도 좋을 것 같네요.
그냥 머릿속에 떠올라서 공유만~~

2024-10-24 02:08 UTC, zangsu commented on backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
> +            when(templateApplicationService.findAllBy(any(), any(), any(), any(), any(), any())).thenReturn(
`any(), any(), any(), any(), any(), any()` 
ㅋㅋㅋ

2024-10-24 04:49 UTC, HoeSeong123 approved these changes

2024-10-24 04:59 UTC, zeus6768 approved these changes

2024-10-24 05:10 UTC, jminkkk approved these changes

2024-10-24 05:10 UTC, zeus6768 approved these changes

2024-10-24 05:12 UTC, HoeSeong123 approved these changes

2024-10-24 05:12 UTC, zangsu approved these changes

2024-10-24 05:12 UTC, merged