상세 조회에서 다른 사람의 비공개 템플릿 확인 시 예외 처리
woowacourse-teams/2024-code-zap pull request #852
Opened 2024-10-22 05:37 UTC by kyum-q

## ⚡️ 관련 이슈
#739

## 📍주요 변경 사항
- 단건 조회 시 다른 사람의 비공개 템플릿 조회일 경우 예외 발생
   - ErrorCode.FORBIDDEN_ACCESS, "해당 템플릿은 비공개 템플릿입니다."
- DB에서 템플릿 기본 값을 PUBLIC으로 설정

## 🎸기타
> 고려해야 하는 내용을 작성해 주세요.

## 🍗 PR 첫 리뷰 마감 기한
10/23 10:00

해당 PR은 내일 릴리즈 전에 올라가야할 것 같습니다~ 빠른 리뷰 부탁드려요 !

2024-10-22 05:44 UTC, zeus6768 requested changes
켬미 작업 너무 빨라~~ RC 남겼으니 확인 바라요~~

2024-10-22 05:44 UTC, zeus6768 commented on backend/src/main/java/codezap/template/domain/Template.java
> +    }
ErrorCode는 뷰 로직 같은데, 도메인에서 의존하면 안 되지 않을까요?

Template에서는 예외를 직접 발생시키기보다 boolean을 반환하면 더 좋다고 생각하는데, 켬미는 어떤가요?

다음과 같이 제안해요. 메서드명도 바꿔 봤어요!

```java
public boolean ownedBy(Member member) {
    return getMember().equals(member);
}

public boolean isPrivate() {
    return visibility.isPrivate();
}

public boolean isPublic() {
    return visibility.isPublic();
}
```

2024-10-22 07:15 UTC, jminkkk reviewed
켬미 리뷰 하나! 남겼어요~~
수고했어요 🔥

2024-10-22 07:15 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        }
메서드 추출해보면 어떨까요~~ 위에 것도!

2024-10-22 07:24 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +            @ErrorCase(description = "다른 사람의 private 템플릿인 경우", exampleMessage = "해당 템플릿은 비공개 템플릿입니다."),
이 예외 상황은 403 FORBIDDEN 으로 처리되어야 하지 않을까 고민이 되서 의견 한번 남겨봐요!

2024-10-22 07:26 UTC, zangsu commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +            @ErrorCase(description = "다른 사람의 private 템플릿인 경우", exampleMessage = "해당 템플릿은 비공개 템플릿입니다."),
+) 이미 로직에선 FORBIDDEN 으로 처리되고 있네요!
문서에서만 분리해 주시면 될 것 같습니다!

2024-10-22 14:35 UTC, HoeSeong123 reviewed
고생하셨습니다 켬미~~ 간단한 코멘트라 리체 말고 코멘트로 남겼어요~~

2024-10-22 14:35 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/domain/Template.java
> +    }
일부러 getMember 사용하신건가요?
```suggestion
    public boolean matchMember(Member member) {
        return this.member.equals(member);
    }
```

2024-10-23 06:19 UTC, zeus6768 submitted a review, later dismissed

2024-10-23 06:22 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +        }
[Commit](https://github.com/woowacourse-teams/2024-code-zap/pull/852/commits/bf4fc852bed557f392d7c4f6e5a1d43ee59efe1c)에 반영 했습니다~

2024-10-23 06:22 UTC, kyum-q commented on backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
> +            @ErrorCase(description = "다른 사람의 private 템플릿인 경우", exampleMessage = "해당 템플릿은 비공개 템플릿입니다."),
[Commit](https://github.com/woowacourse-teams/2024-code-zap/pull/852/commits/ad0c35db838377d28e929b2f514ea51b4d6e37c3)에 반영했습니다~

2024-10-23 06:30 UTC, zangsu approved these changes

2024-10-23 07:04 UTC, HoeSeong123 approved these changes

2024-10-23 08:09 UTC, jminkkk approved these changes

2024-10-23 08:10 UTC, zeus6768 approved these changes

2024-10-23 08:10 UTC, merged