백엔드 로그 리팩토링
woowacourse-teams/2024-code-zap pull request #859
Opened 2024-10-23 06:00 UTC by HoeSeong123

## ⚡️ 관련 이슈
close #768 

## 📍주요 변경 사항
- 400번대 응답은 WARN으로 변경하였습니다.
- 500번대 응답은 ERROR로 변경하였습니다.
- 위 두 변경에 대한 이유는 에러 로그가 찍힐 때 어떤 요청에서 발생한 에러인지 확인하기가 어려운 것 같았기 때문입니다.
- 아래 화면과 같이 스택 트레이스는 한 로그에 포함되도록 수정하였습니다.
<img width="1027" alt="스크린샷 2024-10-23 14 56 11" src="https://github.com/user-attachments/assets/bf7d9990-ae19-4b7b-ad37-6335f6443ef7">
- 위에 있는 두 로그로 어떤 요청에서 발생한 오류인지 확인할 수 있습니다.
- 정규표현식 이슈로 로그에 색은 포함시키지 못했습니다..
  - 이 부분은 5 레벨에 시간이 되면 개선해보도록 하겠습니다..ㅠ

## 🎸기타
- spring 로그와 nginx 로그를 분리하였습니다.
- nginx 로그에서는 status 별로 필터링하여 확인이 가능합니다.
- spring 로그에서는 level 별로 필터링하여 확인이 가능합니다.
- 운영 서버에서 INFO 로그는 찍히지 않습니다.

## 🍗 PR 첫 리뷰 마감 기한
10:24 23:59

2024-10-24 05:59 UTC, zangsu requested changes
초롱~ 수정사항 남겨두었어요!!

2024-10-24 05:59 UTC, zangsu commented on backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
> +            log.error(requestMessage);
```suggestion
            log.error(responseMessage);
```

2024-10-24 05:59 UTC, zangsu commented on backend/src/main/resources/logger/file/error-appender.xml
> +            <pattern>[%level][%d{MM-dd HH:mm:ss}][%X{correlationId}][%logger{20}] %msg%exception{full}%n</pattern>
👍

2024-10-24 10:53 UTC, jminkkk reviewed
악 펜딩상태였네요ㅠ 리뷰 하나 봐주세요 
초롱 수고했어요!!!!!!!!

2024-11-04 12:49 UTC, kyum-q approved these changes
초롱 수고하셨어요 ~!
미루고 미루다 이제 봤네요 ,,, ! 체곱니다 !

2024-11-07 05:05 UTC, HoeSeong123 commented on backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
> +            log.error(requestMessage);
와우 정말 치명적인 실수 
감사합니다 짱수👍

2024-11-07 05:10 UTC, HoeSeong123 commented on backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
> +        }
너무 좋아요👍

2024-11-08 09:42 UTC, HoeSeong123 reviewed
## 공통
- level, timestamp, correlationId 등 불필요한 정보는 화면에 보이지 않고 필드로만 가지고 있게 변경하였습니다.
- correlationId의 경우 로그의 순서가 뒤섞일 수도 있어서 검색을 통해 원하는 요청에 대한 로그만 확인할 수 있습니다.
- level 필터링을 통해 원하는 레벨의 로그만 확인할 수 있습니다. 

## WARN
- WARN의 경우는 아래와 같이 스택 트레이스를 제거했습니다.
- 이미 우리가 예상하고 있는 에러이기 때문에 에러 제목만으로도 해결할 수 있다고 판단했습니다.
![image](https://github.com/user-attachments/assets/1ffa9540-31e8-400a-a5ef-1ce87d0e638d)

## ERROR
- ERROR의 경우는 아래와 같이 스택 트레이스가 같이 보이게 하였습니다.
- 로그 한 줄에 전부 포함되게 하였으며 로그를 클릭하면 아래로 펼쳐지는 형태로 변경하였습니다.
- 하지만 스택 트레이스가 너무 길어서 하나의 로그에 전부 담기지 못하고 있습니다.
- 그래도 충분한 길이의 스택 트레이스가 담기기는 해서 이걸로 웬만하면 해결 가능하지 않을까 싶어서 일단 냅뒀습니다.
  - 만약 필요하다고 판단되면 해결책을 다시 생각해볼게요..
![image](https://github.com/user-attachments/assets/2d1f6487-7272-4685-b10e-0f792bc4b99e)

2024-11-09 03:16 UTC, jminkkk approved these changes
correlationId를 더 쉽게 사용할 수 있군요 너무 편하겠어요~~
수고하셨씁니다~~

2024-11-10 01:10 UTC, zeus6768 requested changes
드디어 로그가 개선되는군요 멋져요 👍

간단한 코멘트 남겼으니 확인해줘요 초롱~~

2024-11-10 01:10 UTC, zeus6768 commented on backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
>      }
저는 다음과 같이 작성하는 게 더 낫다고 생각해서 제안해요~

이렇게하면 
1. Early Return으로 호출되는 코드 수를 줄일 수 있어요. 
2. `logResponse()` 메서드에서 하나의 메서드만 호출하면 돼요. 
3. `RequestResponseLogger` 클래스의 전체 라인 수가 줄어들어요. 

```suggestion
    private void logByStatus(int status, String requestMessage, String responseMessage) {
        if (status >= ERROR_CODE) {
            log.error(requestMessage);
            log.error(responseMessage);
            return;
        }
        if (status >= WARN_CODE) {
            log.warn(requestMessage);
            log.warn(responseMessage);
            return;
        }
        log.info(requestMessage);
        log.info(responseMessage);
    }
```

2024-11-10 01:10 UTC, zeus6768 commented on backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
> +    }
동일한 로직이지만, [디미터의 법칙](https://www.baeldung.com/java-demeter-law) 측면에서 개선할 수 있을 것 같아 제안해요~

```java
    private String getHeaderAsJson(ContentCachingRequestWrapper requestWrapper) {
        Map<String, String> headersMap = new HashMap<>();
        Enumeration<String> headerNames = requestWrapper.getHeaderNames();
        while (headerNames.hasMoreElements()) {
            String headerName = headerNames.nextElement();
            headersMap.put(headerName, requestWrapper.getHeader(headerName));
        }
        return convertMapToJson(headersMap);
    }

    private String getHeaderAsJson(ContentCachingResponseWrapper responseWrapper) {
        Map<String, String> headersMap = new HashMap<>();
        for (String headerName : responseWrapper.getHeaderNames()) {
            headersMap.put(headerName, responseWrapper.getHeader(headerName));
        }
        return convertMapToJson(headersMap);
    }
```

2024-11-11 07:40 UTC, HoeSeong123 reviewed
- 다음과 같이 prod, dev 별로 로그를 따로 확인할 수 있도록 변경하였습니다.
  - 이렇게 변경한 이유는 prod에서 인스턴스 별로 로그를 나눠서 확인하기 위함입니다.
  - 이를 위해 production의 secret 값이 변경되었으므로 확인 부탁드립니다.
<img width="541" alt="스크린샷 2024-11-11 16 39 03" src="https://github.com/user-attachments/assets/002258cb-ed3f-4a7b-8b69-1a972e27084a">

2024-11-11 07:40 UTC, HoeSeong123 commented on backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
> +    }
가독성도 더 올라가는 것 같네요!!

2024-11-11 07:43 UTC, zeus6768 approved these changes

2024-11-12 05:56 UTC, zangsu approved these changes

2024-11-14 02:32 UTC, jminkkk approved these changes

2024-11-14 02:37 UTC, merged