응답 헤더에 hostname 변수 추가
woowacourse-teams/2024-code-zap pull request #868
Opened 2024-10-23 10:17 UTC by HoeSeong123

## ⚡️ 관련 이슈
close #828

## 📍주요 변경 사항
- 응답 헤더에 인스턴스 정보를 추가하였습니다.
- 도커를 실행시키기 전에 `export` 명령어를 통해 `HOSTNAME` 변수에 인스턴스의 `$hostname`을 동적으로 할당하게 변경하였습니다.
- 아래 3개의 이름이 각각 인스턴스에 맞게 할당됩니다.
  - production-a
  - production-b
  - develop

## 🍗 PR 첫 리뷰 마감 기한
10/25 18:00

2024-10-24 05:01 UTC, zangsu approved these changes

2024-10-24 11:50 UTC, zeus6768 approved these changes

2024-10-24 11:51 UTC, kyum-q approved these changes

2024-10-24 11:55 UTC, zeus6768 requested changes
https://github.com/woowacourse-teams/2024-code-zap/actions/runs/11498538116/job/32004632118

![image](https://github.com/user-attachments/assets/a7b3a9b7-24aa-469b-9bbe-b4f35ccb8fb6)

위와 같은 이유로 실패하네요. CD 과정에서 문제 없는지 확인해주세요~~

2024-11-11 08:32 UTC, zeus6768 approved these changes

2024-11-14 02:31 UTC, merged