QueryDSL 도입
woowacourse-teams/2024-code-zap pull request #869
Opened 2024-10-23 13:40 UTC by jminkkk

## ⚡️ 관련 이슈
close #740 

## 📍주요 변경 사항
> 파일 체인지 ... 이러고 싶지 않았어요.... 그래도 어려운 건 몇개 없음! FunctionContributor 부분과 TemplateTagQueryDSLRepository 말고는 위치 변경이랑 쿼리 작성 정도에요~ 이 두 부분을 중점적으로 보면 좋을듯!!

1. JPQL을 사용하여 작성했던 메서드를 QueryDSL로 변경했습니다.
2. Repository 라이브러리가 변경되었을 때 Service단의 변경이 발생되는 것이 이상하여 의존 관계를 변경하였습니다.
    - Service는 각 Repository 만을 의존하고, 각 Repository는 구현체를 합성하여 가지고 있습니다.
3. 기존 검색에 동적 쿼리를 Specification을 사용하여 만들었던 것을 QueryDSL을 사용하여 변경하였습니다.
4. Full Text Index 를 사용하기 위해 정의한 Function을 MySQLDialect 대신 FunctionContributor로 등록하였습니다. (QueryDSL에서 Function을 사용하기 위해)

## 🍗 PR 첫 리뷰 마감 기한
10:26 18:00

2024-11-04 14:04 UTC, kyum-q commented on backend/src/main/java/codezap/tag/repository/TemplateTagQueryDSLRepository.java
> +    }
이건 그냥 제안인데 다른 메서드들은 대부분 id값을 비교하고 있으니 해당 메서드도 id를 받아 id를 비교하는 거 어떨까요?

2024-11-04 14:07 UTC, kyum-q commented on backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
> +    }
사용하지 않는 메서드이니 제거해주세요 !

2024-11-04 14:26 UTC, kyum-q commented on backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
> +    private List<Template> getTemplates(
보기 편하게 먼저 사용되는 private 메서드를 위로 올려주세요 !

2024-11-04 14:33 UTC, kyum-q commented on backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
> +                .longValue();
⚡
제가 이해한 바로는 `fetchOne()`은 하나의 값만 반환하니 count 하니 언제나 결과가 1일 것 같아요 !
`fetch()` 로 변경하면 해당 문제가 해결될 것 같습니다 !

2024-11-04 14:36 UTC, kyum-q commented on backend/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
> +codezap.template.repository.FullTextFunctionContributor
실행 시에 저 클래스의 'contributeFunctions'가 자동 실행되게 등록 하는 건가용?

2024-11-05 12:18 UTC, jminkkk commented on backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
> +                .longValue();
<img width="758" alt="image" src="https://github.com/user-attachments/assets/7f9f4257-096c-4885-9871-c396c4978711">

NPE 린트 경고 떠서 변경했었어요
fetchOne이랑 Objects.requireNonNull로 바꿀게요~

2024-11-05 12:37 UTC, jminkkk commented on backend/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
> +codezap.template.repository.FullTextFunctionContributor
뉑!!! 맞슴다 천재야

2024-11-05 13:00 UTC, jminkkk commented on backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
>      @Query("""
켬미 PR 내용에서 추가된 부분이여서요~
먼저 머지되면서 일단 리베이스만 받았습니다.

또 `Pageable` 타입을 인자로 받고 정렬을 하려면 Sort 객체를 QueryDSL OrderSpecifier로 변환해야 하는데 작업량이 이 PR에서 더 처리하기엔 너무 크다고 판단했어요~!

켬미 생각은 어떤가욥

2024-11-05 13:11 UTC, jminkkk commented on backend/src/main/java/codezap/tag/repository/TemplateTagQueryDSLRepository.java
> +    }
이것도 로직도 영향이 갈 것 같아서 이 PR 보다 다음 작업 사항으로 두는 게 좋을 것 같아요~!

2024-11-05 13:21 UTC, jminkkk commented on backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
> +    }
이것도 다른 테스트까지 영향이 가서 다음 작업 사항에 변경하는 게 나을 것 같다는 생각입니답..!

2024-11-06 07:47 UTC, kyum-q commented on backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
>      @Query("""
좋아용 ~~

2024-11-06 07:49 UTC, kyum-q commented on backend/src/main/java/codezap/tag/repository/TemplateTagQueryDSLRepository.java
> +    }
귯 쟙 ! 그러면 변경하는게 좋을 것 같은지 몰리의 의견이 궁금해영~

2024-11-06 08:24 UTC, kyum-q commented on backend/src/main/java/codezap/tag/repository/TagJpaRepository.java
> +public interface TagJpaRepository extends JpaRepository<Tag, Long> {
귯...! 안되네용
근데 확인해보니 findByName 은 테스트에서만 사용되고 있네요.. 이번 PR 올라가고 한번 다시 쭉 봐야겠네 왜케 안쓰이는게 많아 ㅋㅋㅋ쿠ㅜㅜㅜㅜ

'COLLATE utf8mb4_bin' 사용도 그렇다면 고민해봐야겠어요..!  더 찾아보니 테이블 컬럼에 설정하는게 더 빠를수도 있다하니 추후 속도 확인해보고 변경해봐요~

2024-11-06 08:40 UTC, kyum-q commented
몰리 체고 ~~~!
진짜진짜 추후 수정하기 귀찮아지고 까먹으니 마지막 코멘트 하나만 !

![image](https://github.com/user-attachments/assets/e34ba9a4-4f75-4501-8493-d01d4e70a8c2)
![image](https://github.com/user-attachments/assets/8fda9ddb-cb8f-47b2-8922-405c089bba19)
![image](https://github.com/user-attachments/assets/da87b7b8-9ab2-4954-a567-ac9e037066eb)

`@RequiredArgsConstructor`으로 변경 !
이전 리뷰에서 생략했었는데 몰리가 놓친 부분이 있는 것 같아서 다 모아왔어용 이것만 해줘요 ~!!

2024-11-06 09:36 UTC, zangsu submitted a review, later dismissed
이건 너무 늦어진 관계로,, 따로 코드 보면서 이해하겠습다 😓 
고생했어요 몰리!

2024-11-06 13:38 UTC, zeus6768 requested changes
바쁜 와중에 작업하느라 고생 많았어요 몰리~

나름대로 열심히 검토해봤어요. 

변경사항에 잡히지 않았지만 변경이 필요하다고 생각한 부분은 다음과 같이요. 

1. @SuppressWarnings("unused") 애너테이션 삭제
이제 QueryDSL을 사용하며 JpaRepository들에서 unused warning이 발생하지 않으니 해당 애너테이션을 지우면 좋겠어요. 

2. 사용하지 않는 import문 삭제

3. 테스트 실패

저는 다음과 같이 테스트에서 실패하는데, 도저히 원인을 모르겠어요. 

CI에서 성공하니까 일단 넘어가도 될까요...?

<img width="600" alt="스크린샷 2024-11-06 오후 5 39 48" src="https://github.com/user-attachments/assets/e833d115-162f-41c4-aa19-c4e52d366b5f">


실패하는 테스트만 단독으로 실행하면 성공해서 왠지 모르겠네요.

<img width="306" alt="스크린샷 2024-11-06 오후 5 40 08" src="https://github.com/user-attachments/assets/a975b362-6563-4937-bfcd-40c9525a51d0">

2024-11-06 13:38 UTC, zeus6768 commented on backend/src/main/java/codezap/template/repository/TemplateOrderSpecifierUtils.java
> +    }
핵심 로직인 것 같아서 신경써서 들여다봤어요. 

가독성 측면에서 몇 가지 개선할 부분이 있다고 생각했어요. 

1. String 상수들이 Map에서만 사용되는 것 같아 분리하지 않고 Map 내부에서 명시하는 게 더 좋을 것 같은데, 어떻게 생각하나요? 
2. addOrder 메서드가 분리되었지만 파라미터가 3개나 되고, 삼항연산자를 사용할 때의 이점도 크지 않다고 생각했어요. 
3. entityPath는 항상 TemplatePath에요. 그래서 상수로 사용해도 된다고 생각해요. 

결과적으로 아래와 같이 변경 제안해요!

```suggestion
private static final PathBuilder<Template> TEMPLATE_PATH = new PathBuilder<>(Template.class, "template");

    private static final Map<String, Path<? extends Comparable<?>>> ORDER_FIELD_PATHS = Map.of(
            "likesCount", template.likesCount,
            "createdAt", template.createdAt,
            "modifiedAt", template.modifiedAt);

    public static OrderSpecifier<?>[] getOrderSpecifier(Sort sort) {
        List<OrderSpecifier<?>> orderSpecifiers = new ArrayList<>();
        sort.forEach(order -> {
            Order direction = getOrder(order);
            OrderSpecifier<?> orderSpecifier = createOrderSpecifier(order.getProperty(), direction);
            orderSpecifiers.add(orderSpecifier);
        });
        return orderSpecifiers.toArray(new OrderSpecifier[0]);
    }

    private static Order getOrder(Sort.Order order) {
        if (order.isAscending()) {
            return Order.ASC;
        }
        return Order.DESC;
    }

    private static OrderSpecifier createOrderSpecifier(String property, Order direction) {
        if (ORDER_FIELD_PATHS.containsKey(property)) {
            return new OrderSpecifier(direction, ORDER_FIELD_PATHS.get(property));
        }
        return new OrderSpecifier(direction, TEMPLATE_PATH.get(property));
    }
```

2024-11-06 13:38 UTC, zeus6768 commented on backend/src/main/java/codezap/category/repository/CategoryJpaRepository.java
변경내역에 포함되지 않았는데, 아래의 두 import 문은 불필요해요. 

```java
import codezap.global.exception.CodeZapException;
import codezap.global.exception.ErrorCode;
```

2024-11-06 15:00 UTC, HoeSeong123 reviewed
이럴수가 리뷰해놓고 pending 상태로 냅뒀었네요..
이미 켬미가 다 적어놨네요😅
고생하셨습니다!!

2024-11-06 15:06 UTC, jminkkk commented on backend/src/main/java/codezap/template/repository/TemplateOrderSpecifierUtils.java
> +    }
forEach문에 블록으로 넣는 것은 저는 가독성이 확 떨어진다고 느껴서 삼항 연산자만 제거할게요
나머지는 반영할게요~

2024-11-06 15:12 UTC, jminkkk commented on backend/src/main/java/codezap/tag/repository/TemplateTagQueryDSLRepository.java
> +                .innerJoin(QTemplateTag.templateTag.tag).fetchJoin()
동작은 하지만 N + 1이 발생하겠죠...??

2024-11-06 15:13 UTC, jminkkk commented on backend/src/main/java/codezap/tag/repository/TemplateTagQueryDSLRepository.java
> +                .innerJoin(QTemplateTag.templateTag.tag).fetchJoin()
TagService에서 내부 Tag에 접근하기 때문에 fetchJoin을 해줘야 할 것 같아요~

2024-11-06 15:15 UTC, jminkkk commented
@zeus6768 

<img width="291" alt="image" src="https://github.com/user-attachments/assets/8f306341-494a-423f-8eaa-fe3050590dc8">

제 로컬에서도 전체 통과해서 다시 한번만 확인 부탁드려요~!!

2024-11-06 15:22 UTC, HoeSeong123 commented on backend/src/main/java/codezap/tag/repository/TemplateTagQueryDSLRepository.java
> +                .innerJoin(QTemplateTag.templateTag.tag).fetchJoin()
아 N+1!!!
확인했습니다!!

2024-11-06 15:22 UTC, HoeSeong123 approved these changes

2024-11-06 15:46 UTC, kyum-q approved these changes

2024-11-06 15:47 UTC, Jaymyong66 approved these changes

2024-11-06 23:29 UTC, zeus6768 approved these changes

2024-11-06 23:30 UTC, merged