페이지네이션 처리 시 최대 다음 페이지 수를 5개로 제한
woowacourse-teams/2024-code-zap pull request #902
Opened 2024-11-08 15:48 UTC by jminkkk

## ⚡️ 관련 이슈
close #899

## 📍주요 변경 사항
1. 목록 조회에서 페이지네이션이 들어갈 경우, Page 반환타입은 전체 페이지와 요소 갯수를 반환합니다.
그 과정에서 전체 로우를 풀스캔하기 때문에 비효율적입니다.

(조회 조건에 해당되는 컬럼이 100만건이라면 100만 로우를 전체 카운팅)

현재 페이지네이션 바가 5개까지 나타나기 때문에 전체 로우를 카운팅하지 않고 다음 5개 페이지까지가 있는지 반환합니다.
```
예) 
조건에 맞는 전체 페이지가 10개인 경우: nextPages는 5개 
조건에 맞는 전체 페이지가 1개인 경우: nextPages는 1개 
```

2. `내가 좋아요한 템플릿 목록 조회 API`에서 동일한 페이지네이션 바가 사용되기 때문에 `템플릿 목록 조회 API`와 동일하게 5개까지만 반환하는 처리를 하였습니다.
그 과정에서 `내가 좋아요한 "템플릿" 목록 조회` 레포지토리 메서드를 template 패키지로 이동하였습니다. (이전 담당자와 상의 완, 참고바람~~)

## 🎸기타
> 관련 논의 디스커션 참고: [템플릿 목록 응답의 전체 템플릿 수의 필요성에 대해 이야기해봐요](https://github.com/woowacourse-teams/2024-code-zap/discussions/778)

Repository 단 테스트 시에 관련 Config 들을 Import해야하는데 TemplateSearchRepositoryTest는 

## 🍗 PR 첫 리뷰 마감 기한
11/11 18:00

2024-11-10 02:02 UTC, zeus6768 requested changes
채용 일정으로 바쁠텐데 작업하느라 수고했어요 몰리~!

간단한 코멘트 남겼는데, 코멘트 한 번 주고받은 뒤 승인할게요!!

2024-11-11 05:58 UTC, kyum-q submitted a review, later dismissed
몰짱 ~!

2024-11-11 06:05 UTC, HoeSeong123 requested changes
고생하셨습니다 몰리!!
여전히 정말 빠른 작업속도네요👍

간단한 코멘트 몇 개 남겼으니 확인 부탁드립니다!

2024-11-11 06:05 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
> +    private int countNextFixedPage(Long memberId, Pageable pageable) {
오버로딩을 사용한 것 같은데 개인적으로는 이해하기 조금 힘들었던 것 같아요.
매개변수에 따라서 역할이 드러나는 것 같지도 않아서 오버로딩이 적절한지 조금 고민이네요..
조금만 더 명시적으로 바꿔주는 건 어떤가요??

하지만 조금은 사소하다고 생각해서 몰리가 편한대로 결정해주세요!!

2024-11-11 06:05 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/repository/TemplateRepositoryTest.java
> +        @DisplayName("성공: 다른 사람의 private은 제외, 내 private은 포함")
아까 가서 물어본 거에 대한 정답이 여기 있었네요ㅋㅋ👍

2024-11-11 13:23 UTC, zangsu reviewed
몰리~~ 아까 DM으로 한번만 봐달라고 해서 일단 리뷰 날려봐용,,
사실 막 뭐 큰 수정사항은 없는 것 같으니까 한번만 봐주세용,,,

2024-11-11 13:29 UTC, jminkkk commented on backend/src/test/java/codezap/global/pagination/FixedPageCounterTest.java
> +    @DisplayName("페이지가 10개까지 있어도, 최대 5페이지까지만 카운팅")
앗, `@DisplayName`을 확인하지 못했네요!
총 페이지는 5가 되어야 합니다!

2024-11-12 04:11 UTC, jminkkk commented on backend/src/main/java/codezap/global/pagination/FixedPageCounter.java
> +                .size();
처음에 select(entityPath.count()) + fetchOne로 작성하려고 했었는데요. 그때 null check가 남아있었네요 변경할게요 최고 👍

2024-11-12 04:13 UTC, jminkkk commented on backend/src/main/java/codezap/global/pagination/FixedPageCounter.java
> +    private static final int MAXIMUM_PAGE = 5;
> 현재 페이지네이션 바가 5개까지 나타나기 때문에 전체 로우를 카운팅하지 않고 현재 페이지 포함 5개 페이지까지가 있는지 반환합니다.

현재 페이지 포함이라 5개입니다!

2024-11-12 04:17 UTC, jminkkk commented on backend/src/test/java/codezap/global/pagination/FixedPageCounterTest.java
> +class FixedPageCounterTest {
테스트 추가 최고에요~! 👍

2024-11-12 04:20 UTC, jminkkk commented on backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
> +    private int countNextFixedPage(Long memberId, Pageable pageable) {
저는 완전하게 동일한 역할이라고 생각했어요!
조회 조건이 달라질 수 있지만, 조건에 맞는 로우의 갯수를 조회하는 것이여서요!
초롱이 명시적으로 어떤 부분을 나타내고 싶은지 의견을 말해주면 제가 좀 더 고민해볼 수 있을 것 같아요 🤔

2024-11-12 04:23 UTC, jminkkk commented on backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
> +    private int countNextFixedPage(Long memberId, Pageable pageable) {
엇 다른 부분들이 다 Pageable이 마지막 인자로 있기 때문에 이 메서드 말고 위의 다른 메서드 하나를 변경할게요~~!

2024-11-12 04:26 UTC, zangsu commented on backend/src/main/java/codezap/global/pagination/FixedPageCounter.java
> +    private static final int MAXIMUM_PAGE = 5;
OHHHHH 감사합니닷

2024-11-12 04:40 UTC, jminkkk commented on backend/src/main/java/codezap/global/pagination/FixedPageCounter.java
> +                .size();
저는 List가 해당 로직에서 크게 의미가 없는 값이라고 생각했어요! 즉시 변수로 빼어 전달하게 될 의도가 없기두 하구요! (중요한 건 count이라고 생각했습니답)

그런데 기존에 불필요한 null 체크 때문에 체이닝 메서드의 린트가 달라서 가독성이 좋지 않았을 수도 있을 것 같아요~!
번거롭지만 제거한 로직을 다시 확인해주실 수 있나요~?

2024-11-12 05:32 UTC, HoeSeong123 commented on backend/src/test/java/codezap/global/pagination/FixedPageCounterTest.java
> +    @DisplayName("페이지가 10개까지 있어도, 최대 5페이지까지만 카운팅")
아 아뇨 5페이지까지만 나오는건 맞는데 `@DisplayName`이 `페이지가 7개까지 있어도, 최대 5페이지까지만 카운팅` 이어야 한다는 얘기였습니다ㅎㅎ

2024-11-12 05:38 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
> +    private int countNextFixedPage(Long memberId, Pageable pageable) {
그 조회 조건이 파라미터를 통해 구분되지 않는다는 것이 위험하다고 생각해요.
저는 개인적으로 오버로딩을 사용할 때는 메소드명과 파라미터만 봐도 그 메소드의 역할이 무엇인지 알고, 명확하게 구분되어야 한다고 생각해요.
하지만 현재는 로직을 봤을 때는 두 메소드가 구분이 되기는 하지만 파라미터만으로는 전혀 구분이 되지 않는 것 같아요.

제가 만약 두 메소드 중 하나를 사용하게 된다면, 어떤 메소드를 사용해야 할지 확인하기 어려울 것 같아요.

`고정된 페이지를 가져온다`라는 동일한 동작을 하더라도 그 동작을 하는 조건이 다르고 그 조건을 파라미터를 통해 나타낼 수 없다면 두 메소드는 다른 역할을 하는 것이라고 생각됩니다.
몰리의 의견은 어떤가요??

2024-11-12 06:01 UTC, zangsu commented on backend/src/main/java/codezap/global/pagination/FixedPageCounter.java
> +                .size();
> 그런데 기존에 불필요한 null 체크 때문에 체이닝 메서드의 린트가 달라서 가독성이 좋지 않았을 수도 있을 것 같아요~!

제 생각에도 이 문제가 가장 원인이었던 것 같아요. 
저도 해당 변수가 의미 없는 값이라는 것에 동의하기에 가독성이 좋은 지금은 이대로도 좋을 것 같아요~~

2024-11-12 06:03 UTC, zangsu reviewed
몰리~~ 변경된 코드 확인 후 정말정말 사소한 코멘트 하나 추가로 남겨둘게요!

2024-11-12 06:03 UTC, zangsu commented on backend/src/main/java/codezap/global/pagination/FixedPageCounter.java
> +                .size();
```suggestion
        long nextFixedElementCounts = queryFactory.selectFrom(entityPath)
                .where(conditions)
                .offset(pageable.getOffset())
                .limit(maximumElementsCount)
                .fetch()
                .size();
```

아주아주 사소하지만,,, stream() 메서드를 붙여서 쓰는 것 처럼 `selectFrom()` 도 동일한 형식으로 포매팅 해 주면 더 읽기 편할 것 같아요!

2024-11-12 16:13 UTC, kyum-q approved these changes

2024-11-12 21:53 UTC, zeus6768 approved these changes

2024-11-13 02:24 UTC, jminkkk commented on backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
> +    private int countNextFixedPage(Long memberId, Pageable pageable) {
앗 이해했습니다~!
예시로 좋아요한 템플릿 목록이 아닌 싫어요한 템플릿 목록~~(이 생길리는 없겠지만)~~이 생기면 초롱 의견처럼 구분이 불가능할 것 같네요 좋은 의견 감사합니다 👍

2024-11-13 06:55 UTC, zangsu approved these changes
몰리 너무 고생 많았습니다~!!

2024-11-13 12:08 UTC, kyum-q approved these changes

2024-11-14 03:18 UTC, zeus6768 approved these changes

2024-11-14 03:18 UTC, kyum-q approved these changes

2024-11-14 12:04 UTC, HoeSeong123 approved these changes

2024-11-14 12:04 UTC, merged