문의하기 구글 스프레드시트 API 요청 책임을 클라이언트에서 서버로 변경
woowacourse-teams/2024-code-zap pull request #923
Opened 2024-11-16 02:45 UTC by zeus6768

## ⚡️ 관련 이슈
#851

## 📍주요 변경 사항
> 주요 변경 사항에 대해 작성해주세요.

## 🎸기타
> 고려해야 하는 내용을 작성해 주세요.

## 🍗 PR 첫 리뷰 마감 기한
00/00 00:00

2024-11-17 09:22 UTC, zeus6768 commented
### CI 실패 관련 메모

gradle test fast fail

https://blog.mrhaki.com/2019/09/gradle-goodness-stop-build-after-one.html

2024-11-18 05:33 UTC, zeus6768 commented on backend/src/test/java/codezap/voc/service/VocServiceTest.java
> +    }
테스트가 의도한 대로 동작하지 않아요 😭

기대 상황: mockServcer에서 40x 또는 50x 상태코드를 응답하면, contact() 메서드에서 예외 발생
실제 상황: contact() 메서드에서 예외 발생하지 않음

contact() 메서드는 restclient에서 post 요청을 하는 게 전부에요. 

설정은 RestClient Builder에 모두 되어 있어요. 

`@BeforeEach` 절에서 확인할 수 있어요. 

RestClient에 세팅된 VocErrorHandler가 동작하지 않는 것으로 보여요. 

도움 부탁해요 😥😥😥

2024-11-18 05:33 UTC, zeus6768 commented on backend/src/test/java/codezap/voc/service/VocServiceTest.java
> +                .andRespond(withStatus(HttpStatus.CREATED));
이 테스트도 문제가 있어요. 

서버 응답이 CREATED일 때만 통과해야 하는데, HttpStatus.CREATED가 아닌 다른 어떤 상태로 변경해도 테스트가 통과해요.

2024-12-02 18:10 UTC, kyum-q requested changes
제우스 수고했어요 ~
오랜만에 restClient 보니 어질어질하네요 ~ ㅋㅋㅋ
간단한 코멘트 몇개 남겨뒀으니 확인 부탁드려요 ~

> Interceptor 테스트 고민에 대해서는 잘 모르겠네요 ~ 조금 더 고민해볼게요 !
> 로깅 고민에 대해서는 댓글 달아두었습니다 확인부탁드려요 ~

2024-12-02 18:10 UTC, kyum-q commented on backend/src/main/java/codezap/voc/config/VocResponseErrorHandler.java
> +public class VocResponseErrorHandler implements ResponseErrorHandler {
> 만약 기존에 만들어진 RequestResponseLogger와 GlobalExceptionHanlder로 적절히 로그를 남길 수 있다면 좋겠다는 생각이 들었는데요.
> 그런데 기존의 logger를 사용할 수 있는지, 만약 사용할 수 있다면 어떻게 사용해야 할지 잘 모르겠어요.
> 이 부분에서 조언 부탁해요 😭

이 부분에 대해 간단하게 생각하면 이 코드를 그냥 GlobalExceptionHanlder에 두어도 되지 않을까요?
그리고 VocConfiguration 에 defaultStatusHandler 설정을 GlobalExceptionHanlder로 하면 이 코드 제거해도 테스트가 모두 통과합니다 ~ 이렇게 되면 따로 이 핸들러를 만들지 않고도 RequestResponseLogger와 GlobalExceptionHanlder로 적절히 로그를 남길 수 있습니다 ~ 이걸 원하신게 맞을까요?

저는 이렇게해서 Voc 관련 에러 핸들링도 GlobalExceptionHanlder에서 한꺼번에 해도 좋을 것 같아요 ~

![image](https://github.com/user-attachments/assets/3b606de9-f727-4d1b-9bcb-a1c8856d4544)

2024-12-03 07:40 UTC, HoeSeong123 reviewed
어렵네요 진짜..
로그 관련해서 계속 고민해봤는데 마땅한 해결책이 생각나지는 않네요.
그래도 현재 방식이 엄청 어색하다고 생각되지는 않습니다!!
나중에 로그 관련 코드를 한 번 정리하면 좋긴 하겠네요.
고생하셨습니다!

2024-12-03 07:40 UTC, HoeSeong123 commented on backend/src/main/java/codezap/voc/config/VocResponseErrorHandler.java
> +            log.error(e.getMessage(), e);
아무리 생각해도 지금 코드에서 이거 없앨 수 있는 방법이 생각이 안나네요...😭
나중에 에러 처리도 손봐야 할 것 같긴 합니다..

2024-12-03 07:40 UTC, HoeSeong123 commented on backend/src/test/java/codezap/voc/controller/VocControllerTest.java
> +    void create() throws Exception {
DisplayName 써주세요!

2024-12-03 08:56 UTC, jminkkk reviewed
제우스 수고했어요 👍
덕분에 문의하기 기능의 완성도가 더 높아지겠네요 :)

리뷰를 남기다보니 조금 많아졌는데,, 찬찬히 확인 부탁해요 ㅎㅎ

2024-12-03 08:56 UTC, jminkkk commented on backend/src/main/java/codezap/voc/config/VocConfiguration.java
> +        httpRequestFactory.setReadTimeout(properties.getReadTimeout());
👍👍👍

2024-12-03 08:56 UTC, jminkkk commented on backend/src/main/java/codezap/voc/config/VocConfiguration.java
> +        var httpRequestFactory = new SimpleClientHttpRequestFactory();
제우스 이 PR과 조금 다른 이야기일수도 있긴 한데요! var 변수에 대해 다같이 컨벤션을 논의해보면 좋을 것 같아요. 

어떤 변수는 타입 추론이고 어떤 변수는 객체 지정이면 같은 프로젝트 내에서 조금 일관성이 깨질 수도 있을 것 같아요 🥲
추가로 이에 대한 다른 분들 의견도 궁금해요!

2024-12-03 08:56 UTC, jminkkk commented on backend/src/main/java/codezap/voc/controller/VocController.java
> +    @ResponseStatus(HttpStatus.CREATED)
저도 켬미 의견에 동의합니다 👍

2024-12-03 08:56 UTC, jminkkk commented on backend/src/main/java/codezap/voc/dto/VocRequest.java
> +        @Email(regexp = "[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$", message = "올바른 형식의 이메일 주소여야 합니다.") // Regex from RFC 5322
👀 숨은 주석 발견!

2024-12-03 08:56 UTC, jminkkk commented on backend/src/main/java/codezap/voc/dto/VocRequest.java
> +        @Email(regexp = "[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$", message = "올바른 형식의 이메일 주소여야 합니다.") // Regex from RFC 5322
이메일도 Nullable 하면 명시적으로 작성해보면 어떨까요??

2024-12-03 08:56 UTC, jminkkk commented on backend/src/test/java/codezap/voc/controller/VocControllerTest.java
> +    private CredentialManager credentialManager;
클래스 내부에서 @MockBean을 별도로 지정하면 테스트 시에 사용되는 어플리케이션 컨텍스트 캐싱이 불가능해요! 
(속도 저하로 이어질 수 있어요)
기존 MockMvcTest를 재사용해보면 어떨까요?

2024-12-03 08:56 UTC, jminkkk commented on backend/src/test/java/codezap/voc/controller/VocControllerTest.java
> +                .andDo(print());
로컬 테스트를 위해 사용했던 것 같네용.
print 문은 제거해도 될 것 같아요 ㅎㅎ

2024-12-03 08:56 UTC, jminkkk commented on backend/src/test/java/codezap/voc/dto/VocRequestTest.java
> +        @DisplayName("문의 내용이 null인 경우 예외 발생")
이 부분도 `실패: 문의 내용이 null인 경우 예외 발생`처럼 수정해보면 어떨까요?

추가로 아래 부분들도 컨벤션 확인 부탁해요!

2024-12-03 08:56 UTC, jminkkk commented on backend/src/test/java/codezap/voc/dto/VocRequestTest.java
> +        @DisplayName("문의 내용 길이 임계값 검증: 19자 이하, 10,001글자 이상에서 예외 발생")
이 부분도 `실패: 19자 이하, 10,001글자 이상에서 예외 발생`으로 할 수 있을 것 같아요!

2024-12-03 08:56 UTC, jminkkk commented on backend/src/test/java/codezap/voc/dto/VocRequestTest.java
> +        @DisplayName("문의 내용 길이 임계값 검증: 20글자부터 10,000글자까지 정상 동작")
테스트 컨벤션에 맞게 `성공: 20글자부터 10,000글자까지 정상 동작`처럼 수정해보면 어떨까요?

2024-12-03 08:56 UTC, jminkkk commented on backend/src/main/resources/application-voc.yml
> +      read-timeout: 5s
각각 5, 5초로 설정한 이유가 궁금해요!
[google sheet api 사용량 한도 공식 문서](https://developers.google.com/sheets/api/limits?hl=ko)

sheet api 를 사용한 것이 맞다면, 다음 부분을 참고해보면 좋을 것 같아요 :)

> 하나의 API 요청 처리 시 최대 시간 제한이 있습니다. Sheets에서 180초가 넘는 시간을 처리하는 경우 요청에서 시간 초과를 반환합니다. 오류가 발생했습니다.

2024-12-07 08:51 UTC, HoeSeong123 reviewed
https://github.com/woowacourse-teams/2024-code-zap/pull/923#discussion_r1867136190
이것도 알려주세요😭😭😭

2024-12-07 11:00 UTC, jminkkk reviewed
안녕하세요 제우스~
수고하셨습니다 🔥

대부분의 리뷰가 반영되었는데요. 다음 두 부분이 의견이 작성되어 있지 않아 확인해주시면 바로 approve 할게요!

https://github.com/woowacourse-teams/2024-code-zap/pull/923#discussion_r1867257383

https://github.com/woowacourse-teams/2024-code-zap/pull/923#discussion_r1867291342

2024-12-07 11:02 UTC, zeus6768 reviewed
아뭐야 submit을 안 눌렀네요;; 죄송합니다 🙇‍♂️

한 번 더 검토하고 다시 요청할게요!

2024-12-07 11:14 UTC, zeus6768 commented on backend/src/main/java/codezap/voc/config/VocConfiguration.java
> +    }
확장과 테스트를 위해서 열어 놓았어요. 

- RestClient는 불변이고, Builder는 도메인에 따라 달라지는 설정을 커스텀해서 사용할 수 있어요. 
  - 지금은 사용되는 곳이 한 곳 뿐이지만, 이정도 유연성을 가져가는 건 괜찮다고 생각해서 이렇게 작성했어요. 
- 테스트코드에서처럼 MockMvcRestServiceServer를 사용하기 위해서는 RestClient Builder 객체가 필요해요.

2024-12-07 11:15 UTC, jminkkk commented on backend/src/main/java/codezap/voc/dto/VocRequest.java
> +        @Email(regexp = "[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$", message = "올바른 형식의 이메일 주소여야 합니다.") // Regex from RFC 5322
저는 주석보다 테스트가 효과적일 것 같아요!
제우스가 그 부분이 우려스럽다면 성공 테스트를 추가하고 `성공: RFC 5322 에 해당하는 이메일 형식` 처럼 의도를 표시해보면 어떨까요?

2024-12-07 11:43 UTC, kyum-q approved these changes
제우스 수고하셨습니다~!~!!~

2024-12-09 04:33 UTC, zangsu approved these changes

2024-12-10 06:26 UTC, zeus6768 commented on backend/src/main/java/codezap/voc/dto/VocRequest.java
> +        @Email(regexp = "[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$", message = "올바른 형식의 이메일 주소여야 합니다.") // Regex from RFC 5322
테스트코드에 작성할 생각은 못해봤네요!!

바로 적용했습니다

2024-12-10 06:26 UTC, zeus6768 commented on backend/src/main/resources/application-voc.yml
> +      read-timeout: 5s
제가 직접 수차례 테스트했을 땐, 1초 이상의 속도가 걸렸전 적은 없어요. 

몰리 말대로 일시적 부하가 있다면 응답에 문제가 있을 수 있지만, 구체적으로 어떤 값으로 정할지 모르겠어서 일단 넘어갈게요!

개인적으로는 관리자 기능을 개발하며 스프레드시트 대신 DB를 사용하도록 바뀌어야 한다고 생각해요 😁

2024-12-10 13:37 UTC, merged