해커톤 작업 내역을 리팩토링
woowacourse-teams/2024-code-zap pull request #94
Opened 2024-07-19 08:10 UTC by zangsu

## ⚡️ 관련 이슈
close #93

## 📍주요 변경 사항
1. 불필요한 도메인 삭제 
    - Member
    - Extension
    - Language
2. 커스텀 예외 추가
3. DTO 에 검증 어노테이션 추가
4. 테스트코드 작성

## 🎸기타
1. 현재 DTO 에 대한 예외 처리가 `MethodArgumentNotValidException` 에 대한 처리로 구현되어 있습니다. `CodeZapException`으로 감싸야 할지 고민입니다 🤔

2024-07-20 02:23 UTC, jminkkk requested changes
코드에서 고민의 흔적이 많이 보입니다👍 수고하셨어요! 
리뷰 확인해주시면 감사하겠습니다 🍀

> +) 추가로 변경 사항에 잡히지 않는 swagger 클래스들(ex. `SpringDocTemplateController`)도 확인해주시면 좋을 것 같아요!
이번 pr부터 검증 로직이 들어갔는데, 실패 케이스에 대해서도 문서화를 진행해주어야 프론트엔드 개발자가 예외 메시지나 포맷을 확인하고 처리를 수월하게 할 수 있습니다

2024-07-20 02:23 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +        );
```suggestion
        //  CreateTemplateRequest createdTemplate = makeTemplate("title");
        assertAll(
                () -> assertThat(foundTemplate.title()).isEqualTo(createdTemplate.title()),
                () -> assertThat(foundTemplate.snippets().size()).isEqualTo(createdTemplate.snippets.size())
        );
```

테스트가 매우 깔끔해서 읽기 좋아요! 👍
다만 Template이 핵심 도메인인만큼 해당 테스트가 커지면서 `makeTemplate()`를 훨씬 많이 재사용할 가능성이 있을 것 같아요.
`makeTemplate()`가 변경되어도 영향을 받지 않도록 수정해보면 어떨까요?!

2024-07-20 02:25 UTC, jminkkk commented on backend/src/main/java/codezap/template/controller/TemplateController.java
>          return ResponseEntity.created(URI.create("/templates" + templateService.create(createTemplateRequest))).build();
놓친 부분이 있다는 건.... 컨트롤러 테스트가 필요할 수도 있는 이유...라는 것....

2024-07-20 03:40 UTC, Jaymyong66 commented on backend/src/main/java/codezap/template/domain/Snippet.java
> +    private static final int THUMBNAIL_SNIPPET_SIZE = 10;
저번에 summary라는 단어를 아마 안쓰기로 했던거 같은데(요약보다는 단순 맨 위 10줄을 보여주는 것이라) 
그럼 사용하는 메서드명을 바꾸면 어떨까유

2024-07-20 03:52 UTC, Jaymyong66 commented on backend/src/test/resources/clear.sql
> +CREATE TABLE thumbnail_snippet
혹시 하나의 템플릿에 썸네일 스니펫이 두개 이상 생기는 경우도 발생하나요?

2024-07-20 03:57 UTC, HoeSeong123 commented on backend/src/test/resources/clear.sql
> +CREATE TABLE thumbnail_snippet
아뇨, 하나의 템플릿에는 무조건 하나의 썸네일 스니펫이 생깁니다.
썸네일 스니펫을 교체하는 경우는 지금은 없지만 (무조건 첫 번째 스니펫을 썸네일 스니펫으로 설정하기로 했기 때문) 추후에는 충분히 발생할 수 있을 것 같네요.
어떤 것 때문에 그러시나요?

2024-07-20 03:59 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/domain/Snippet.java
> +    private static final int THUMBNAIL_SNIPPET_SIZE = 10;
summary 자체를 다른 단어로 변경하는 방향으로 고민해보겠습니다.

2024-07-20 03:59 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/domain/Snippet.java
> +    private static final int THUMBNAIL_SNIPPET_SIZE = 10;
summary 자체를 다른 단어로 바꾸는 방향으로 고민해보겠습니다.

2024-07-20 04:00 UTC, Jaymyong66 commented on backend/src/test/resources/clear.sql
> +CREATE TABLE thumbnail_snippet
넘모 잘해서 배울려구요~

2024-07-20 04:01 UTC, HoeSeong123 commented on backend/src/main/java/codezap/global/serializing/DateTimeFormatConfiguration.java
> +package codezap.global.serializing;
패키지명을 명사 형태로 통일하기 위해서 serializing을 사용했는데 serialization이 더 올바른 표현이겠네요

2024-07-20 05:52 UTC, kyum-q requested changes
개발 할 때 열띤 토론을 하시던데, 그 과정이 아깝지 느껴지지 않을 정도로 코드 굿 😊 

코멘트로 제 의견을 좀 남겨놨어요 ! 확인해보시고 괜찮다고 생각하는 의견만 수용해주세요. (모두 다 수용하실 필요 없습니다 ~! )

2024-07-20 05:52 UTC, kyum-q commented on backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
> +                .body(ProblemDetail.forStatusAndDetail(HttpStatus.INTERNAL_SERVER_ERROR, exception.getMessage()));
handleCodeZapException에서는 status를 설정할 때 `ResponseEntity.status(HttpStatus.BAD_REQUEST)`을 사용하고, handleException에서는 status 설정할 때 `ResponseEntity.internalServerError()`를 사용하네요 ! 

handleCodeZapException를 `ResponseEntity.badRequest()`로 변경해서 두 메서드의 통일성이 있으면 좋을 것 같아요.

2024-07-20 05:52 UTC, kyum-q commented on backend/src/main/java/codezap/template/controller/TemplateController.java
>      @PostMapping("")
매핑 안에 넣은 값이 없을 때는 ("")가 생략 가능한 걸로 알고 있는데, 생략하지 않은 이유가 있을까요?
생략 가능을 알고 안 한 것이라면 이유가 궁금합니다 ~

2024-07-20 05:52 UTC, kyum-q commented on backend/src/main/java/codezap/template/domain/Snippet.java
>      @JoinColumn(name = "template_id", nullable = false)
null을 허용하지 않는 것을 `@ManyToOne`에서 optional 로 설정하지 않고 `@JoinColumn`에서 nullable로 설정한 이유가 있을까요?
두 방식 다 null처리를 해주지만, 저 같은 경우는 `@ManyToOne` 등 관계를 매핑핼 때 optional 로 null 처리를 해서 관계에서 해당 값이 null 일 수 없다고 명시하는 것을 더 선호해서 물어봅니다 ~

---
### (켬미가 알고 있고 좀 찾아본) 두 방식의 차이점
`@JoinColumn(nullable = false)`는 데이터베이스에서의 제약 조건을 정의하는 것. 이 속성은 데이터베이스 스키마를 생성하거나 수정할 때, 외래 키 열이 NOT NULL로 설정해준다.

`@ManyToOne(optional = false)`는 JPA의 매핑 규칙을 정의하는 것. 이 속성은 JPA의 엔티티 매핑 규칙에 따라 해당 관계가 선택적이지 않다는 것을 설정해준다. 즉, 엔티티에서 연관된 엔티티가 반드시 존재해야 한다는 의미한다.

2024-07-20 05:52 UTC, kyum-q commented on backend/src/main/java/codezap/template/domain/Snippet.java
> +                .collect(Collectors.joining(CODE_LINE_BREAK));
상수화 굿 ~!

2024-07-20 05:52 UTC, kyum-q commented on backend/src/main/java/codezap/template/domain/Template.java
>      @Column(nullable = false)
join된 컬럼에만 이름 설정을 해줬네요! 그냥 컬럼에는 이름 설정을 하지 않은 이유가 있을까요?
저 같은 경우에는 코드의 일관성, 읽기 편리함, 변수명 변경에 컬럼에 영향을 주지 않음 과 같은 이유로 컬럼이 변수 명과 동일하더라도, 이름 설정을 따로 해주는 편이라 궁금해서 물어봅니당 ~

2024-07-20 05:52 UTC, kyum-q commented on backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
> +        @NotNull(message = "스니펫 순서가 null 입니다.")
`null 입니다` 라는 문장은 너무 개발자 측면의 문장이라고 생각합니다. `입력되지 않았습니다.` 와 같은 문장은 어떤가요?

2024-07-20 05:52 UTC, kyum-q commented on backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
> +    public static FindAllTemplatesResponse from(List<ThumbnailSnippet> thumbnailSnippets) {
dto 네이밍은 `FindAllTemplatesResponse`인데 실제 안에 들어있는 변수는 `SummaryResponse`이고, `SummaryRespnse`는 `ThumbnailSnippet`의 dto 네요.
`SummaryRespnse` 명이 `ThumbnailSnippet`의 dto임을 잘 나타내는 이름으로 네이밍 된다면 좋을 것 같아요😊

> 그리고 이건 갑자기 든 생각인데, ThumbnailSnippet 보다 `ThumbnailTemplate`은 어떤가요? 
> 연속 사진에서 섬네일 사진은 대표 사진인 것처럼, 템플릿에 섬네일 ! ㅎㅎ
> 이렇게 되면 네이밍이 자연스러울 것 같아서요 
> ( `FindAllTemplatesResponse`, `ThumbnailTemplateResponse`, `ThumbnailTemplate` )

2024-07-20 05:52 UTC, kyum-q commented on backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
>      public static FindTemplateByIdResponse from(Template template, List<Snippet> snippets) {
인자를 2개 이상 받을 경우는 네이밍이 from이 아닌 of로 해주세요 😊

2024-07-20 05:52 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +@Sql(value = "/clear.sql", executionPhase = ExecutionPhase.AFTER_TEST_CLASS)
오 다른 테스트에 영향까지 생각한 sql 초기화 ~ 
very good ! 👍

2024-07-20 09:22 UTC, zeus6768 requested changes
해커톤 이후 첫 PR이네요 ㅎㅎ 짱수 초롱 정말 고생 많았어요!! 🎉

첫 코드리뷰라 재미있기도, 조심스럽기도 했네요. 

같이 얘기해봐요~

2024-07-20 09:22 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
`@SpringBootTest`는 스프링 컨테이너에 모든 빈을 로드해서 속도가 가장 느린 방법으로 알고 있어요. 

서비스의 단위테스트를 의도했다면 `@SpringBootTest`를 사용하지 않거나, `classes` 속성으로 사용할 빈만 등록하는 건 어떨까요?

2024-07-21 06:29 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
> +        @NotNull(message = "스니펫 순서가 null 입니다.")
이거는 프론트엔드와 이야기했었던 내용인데 
어차피 프론트 측에서 별도의 메세지로 다시 한 번 래핑해서 내보낸다고 해서 프론트 쪽으로 보내는 의미 정도로만 작성하였습니다!!

2024-07-22 07:51 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
> +        @NotNull(message = "스니펫 순서가 null 입니다.")
해당 부분은 공부를 조금 더 해보고 적용해야 할 것 같아 이슈로 열어놓고 추후에 추가하도록 하겠습니다.

2024-07-22 08:00 UTC, HoeSeong123 commented on backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler
메서드명과 매개변수만으로도 충분히 어떤 exception을 처리하는지 알 수 있다고 생각해서 불필요한 코드라고 판단하였습니다.

2024-07-22 08:27 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/domain/Template.java
>      @Column(nullable = false)
원래 의도는 필드 이름과 다르게 저장되는 컬럼 이름만 명시해 주고자 하는 의도였어요. 
하지만, 우리가 명시해 준 이름을 그대로 사용하는 경우 굳이 이름을 명시해 주는 것이 불필요하다고 느껴 제거해 주었습니다!

+) 변수 명이 변경이 된다면 컬럼에 영향을 주는 것이 자연스럽다고 생각해요. 영향을 주고 싶지 않을 경우 그 때 이름을 명시해 주는 것이 좋아 보이기도 하고요!

2024-07-22 08:50 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
> +    public static FindAllTemplatesResponse from(List<ThumbnailSnippet> thumbnailSnippets) {
`FindTemplateBySummaryResponse` 클래스는 명확한 네이밍을 차지 못해서 `FindAllTemplatesById`의 내부 클래스로 변경하였습니다.

2024-07-22 08:53 UTC, HoeSeong123 commented on backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
> +                .body(ProblemDetail.forStatusAndDetail(HttpStatus.INTERNAL_SERVER_ERROR, exception.getMessage()));
해당 메서드는 예기치 못한 오류가 발생했을 때를 구분하기 위해 작성하였습니다.

2024-07-22 08:54 UTC, HoeSeong123 commented on backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
> +        @NotNull(message = "스니펫 리스트가 null 입니다.")
해당 커멘트에 [답변](https://github.com/woowacourse-teams/2024-code-zap/pull/94#discussion_r1685659656) 달아두었습니다!!

2024-07-22 09:07 UTC, zangsu commented on backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
>          String content,
해당 내용은 이번 PR 이 아닌 다른 이슈 #102 로 등록하여 해결하겠습니다!

2024-07-22 09:40 UTC, HoeSeong123 commented on backend/src/test/java/codezap/template/TemplateIntegrationTest.java
> +    }
서비스에 대한 테스트를 이미 진행하였으므로, 서비스는 정상 동작한다고 가정하였습니다.
이에 따라 해당 테스트 코드에서는 응답만을 확인하고 있습니다.

2024-07-22 09:54 UTC, zangsu commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
조금 더 찾아보고 추후에 적용하도록 하겠습니다

2024-07-23 04:44 UTC, HoeSeong123 commented on backend/src/main/java/codezap/global/serializing/DateTimeFormatConfiguration.java
현재 저희가 사용하고 있는 `CreatedAt`과 `ModifiedAt`의  자료형이 `LocalDateTime`이라 `timeZone` 설정이 필요하지 않아 해당 코드는 삭제조치하였습니다.

2024-07-23 05:20 UTC, HoeSeong123 submitted a review, later dismissed

2024-07-23 05:33 UTC, kyum-q approved these changes
수고하셨습니다~ 👍

2024-07-23 05:34 UTC, jminkkk approved these changes
수고하셨습니다🔥
리뷰가 잘 반영된 것 같아 approve 할게요~!

2024-07-23 05:46 UTC, HoeSeong123 approved these changes
코드잽 파이팅~~!! ⚡

2024-07-23 05:47 UTC, jminkkk approved these changes

2024-07-23 05:47 UTC, zeus6768 commented on backend/src/test/java/codezap/template/service/TemplateServiceTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
해당 이슈 태그해주세용~!

2024-07-23 05:47 UTC, kyum-q submitted a review, later dismissed

2024-07-23 05:58 UTC, jminkkk requested changes
마지막까지 파이팅.........!

2024-07-23 05:58 UTC, jminkkk commented on backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
> +                        bindingResult.getFieldError().getDefaultMessage()));
`getFieldError()` 는 하나의 필드 에러만 가져오네요.
하나의 요청 바디에서 여러 개의 검증 오류가 난다면, 클라이언트는 여러번에 걸쳐서 에러를 해결해야 할 것 같아요.

유효하지 않은 필드가 여러 개라도 한번에 보여주는 게 어떨까요?
( `getFieldErrors()`로 수정 후 유효하지 않은 필드를 joining 해서 응답을 줄 수 있을 것 같아요. )

2024-07-23 06:00 UTC, zeus6768 submitted a review, later dismissed

2024-07-23 06:08 UTC, jminkkk approved these changes

2024-07-23 06:09 UTC, kyum-q approved these changes

2024-07-23 06:09 UTC, HoeSeong123 approved these changes
코드잽 파이팅 ⚡

2024-07-23 06:09 UTC, zeus6768 approved these changes
초롱 짱수 너무 고생 많았어요 !!!

2024-07-23 06:10 UTC, merged