Github Action Runner를 이용한 백엔드 CD 파이프라인 구축
woowacourse-teams/2024-code-zap pull request #96
Opened 2024-07-19 09:25 UTC by kyum-q

## ⚡️ 관련 이슈
close #27 

## 📍주요 변경 사항
- github actions 파일 작성
  - github action의 runner를 이용해 Deploy 작동
- develop/main 브랜치에서 동작

## 🎸기타
- 추후 develop, main 브랜치가 다르게 동작하도록 변경해야 함

2024-07-19 15:38 UTC, zangsu reviewed
간단한 질문 하나 남겼습니다!
제가 이해한 게 맞다면 다음 코멘트때 Approve 하겠습니다!

2024-07-19 15:38 UTC, zangsu commented on .github/workflows/backend_cd.yml
> +  deploy:
이 부분은 처음 보는 동작들이 좀 있네요! 최대한 이해하려고 노력해 봤는데, 다음의 순서가 맞을까요?

1. 우리 레포에서 최신 버전의 실행 파일 주소를 가져온다. 
2. 최신 버전 실행 파일을 다운로드 받는다. 
3. 배포 스크립트를 실행한다.
4. 정상적으로 서비스가 재시작 하였는지 확인한다.

2024-07-20 06:04 UTC, kyum-q commented on .github/workflows/backend_cd.yml
> +  deploy:
아직 CD 로직에 대한 문서화를 안해놔서 어려우실 수 있을 것 같아요. 근데 짱수 거의 완벽합니다 👍 
CI에 문서에 없는 부분들을 포함해서 조금 더 디테일하게, 최대한 단순하게 이야기해볼게요 !

--- 
#### 환경 설정
1. `needs: build` - 위에 build job 이 성공해야지 실행한다.
2. `runs-on: self-hosted` - action에 self-host runner 환경에서 실행한다. 
: 우리의 runner 환경은 우리 서버다. 즉, 아래 실행되는 job은 우리 서버에서 실행되는 작업이다.
(이 부분에 대해서는 나중에 자세히 문서화 해놓을 거니 이정도만 이해하셔도 되요.) 

#### jobs 진행
1. 우리 레포에 actions에 있는 artifact를 가져와 최신 저번 실행 파일 URL을 알아낸다.
(artifact는 cd 시 build job에서 제작해줍니다)
2. 최신 버전 실행 파일 URL을 통해 파일을 다운로드 받는다.
3. 배포 스크립트를 실행한다.
4. 정상적으로 서비스가 재시작 하였는지 확인한다.

2024-07-20 12:17 UTC, zangsu commented on .github/workflows/backend_cd.yml
> +  deploy:
켬미 설명 너무 감사합니다!! (문서화도 항상 감사하고요...!)
적어주신 부분은 모두 이해 되었어요! Approve 하겠습니다~~

2024-07-20 12:17 UTC, zangsu approved these changes

2024-07-21 05:57 UTC, HoeSeong123 reviewed
고생 많으셨습니다!!
짱수의 질문과 그에 대한 켬미의 답변 덕분에 흐름을 이해하는 데에는 전혀 어려움이 없었습니다.

다만, artifact의 개념에 대해 잘 이해가 되지 않는데 설명해주실 수 있나요? 조금 찾아보기는 했는데 잘 이해가 되지 않네요😅
주석에 대한 피드백도 하나 남겨두었습니다!!

2024-07-21 05:57 UTC, HoeSeong123 commented on .github/workflows/backend_cd.yml
> +          artifact_id=$(echo "$artifacts" | jq -r '.artifacts[0].id') # 가장 최근 아티팩트의 id를 가져옴
주석은 이해를 돕기 위해 일부러 남겨두신 건가요?
덕분에 편하게 이해 되기는 했지만 `develop` 브랜치에는 필요하지 않을 것 같아 보입니다!

2024-07-21 06:33 UTC, zeus6768 requested changes

2024-07-21 06:33 UTC, zeus6768 commented on .github/workflows/backend_cd.yml
> +          pgrep -f 'java -jar' || { echo "Deploy Failed" }
```suggestion
      - name: Verify Deploy Succeed
        run: |
          sleep 3
          pgrep -f 'java -jar.code-zap.*\.jar' || echo "Deploy Failed"
```

1. 10초는 다소 긴 것 같아요. 3초로 줄여도 충분하겠습니다. 
2. 아직은 서버에서 직접 jar 파일을 실행하며 테스트할 일이 많을 것 같아 pgrep 명령어의 표현식을 개선하면 좋겠어요.
3. 쉘스크립트에서 중괄호는 여러 명령어를 하나로 묶기 위해 사용합니다. 여기서는 echo 명령어만 실행되고 있으므로 중괄호가 없어도 되겠네요~

참고) #97 추후 작업하겠습니다!

2024-07-22 03:58 UTC, jminkkk submitted a review, later dismissed
켬미 수고했어요 🔥🔥🔥
리뷰 수정사항 반영이 된 것 같아서 approve 하겠습니다!

2024-07-22 03:59 UTC, kyum-q commented
여러분들 리뷰 반영했어요 ~ 
다들 다시 확인해주세요 😊

2024-07-22 04:01 UTC, HoeSeong123 submitted a review, later dismissed
고생하셨습니다!!

2024-07-22 04:02 UTC, kyum-q commented on .github/workflows/backend_cd.yml
> +          artifact_id=$(echo "$artifacts" | jq -r '.artifacts[0].id') # 가장 최근 아티팩트의 id를 가져옴
artifact는 단순하게 build 작업을 통해 만들어진 결과물이라고 생각해주시면 좋을 것 같아요 !

2024-07-22 04:07 UTC, zeus6768 approved these changes
켬미 정말 고생 많았어요~

2024-07-22 04:07 UTC, HoeSeong123 approved these changes

2024-07-22 04:07 UTC, jminkkk approved these changes

2024-07-22 04:07 UTC, zangsu approved these changes
수정사항 확인 했습니다! 
고생하셨습니다~~! ⚡

2024-07-22 04:09 UTC, merged