검색시 발생하는 500 에러 해결
woowacourse-teams/2024-code-zap pull request #963
Opened 2024-12-12 07:42 UTC by HoeSeong123

## ⚡️ 관련 이슈
close #962 

## 📍주요 변경 사항
- 검색 키워드가 특수 문자로 시작하면 500 에러가 발생합니다.
- ex) '+test', '-리스트' 등등
- 키워드에 특수 문자가 있는 경우, 특수 문자를 제거하고 검색하도록 변경하였습니다.

## 🎸기타
> 토요일 전에 운영 환경에 배포되어야 할 것 같아서 최대한 빠른 리뷰 부탁드립니다.

## 🍗 PR 첫 리뷰 마감 기한
12/13 16:00

2024-12-12 11:41 UTC, jminkkk approved these changes
초롱 짱이에요 수고했어요!! 👍👍
코멘트 하나 남겼어요! 확인 부탁해요!

2024-12-12 11:41 UTC, jminkkk commented on backend/src/main/java/codezap/template/repository/strategy/FullTextSearchSearchStrategy.java
> +                .map(keyword -> keyword.replaceAll("[^a-zA-Z0-9가-힣]", ""))
정규표현식만으로는 의미가 잘 나타나지 않아서 나중에 혼동이 올 것 같습니다...!
두 개의 문자열 중 두 번째 문자열은 비교적 쉽게 의미가 파악되지만 정규표현식은 상수로 빼는 게 나을 것 같은데 초롱 생각 궁금합니다!

2024-12-12 11:41 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +        @ValueSource(strings = {"안녕", "+안녕", "안+녕", " 안녕"})
👍👍👍👍👍

2024-12-12 13:31 UTC, zeus6768 requested changes
최고에요~!

딱 하나 개선하면 좋을 것 같아 의견 남겼어요~~

2024-12-12 13:31 UTC, zeus6768 commented on backend/src/main/java/codezap/template/repository/strategy/FullTextSearchSearchStrategy.java
> +                .map(keyword -> keyword.replaceAll("[^a-zA-Z0-9가-힣]", ""))
정규표현식은 컴파일 대상이에요. map을 실행할 때마다 정규표현식을 컴파일하므로, 성능이 떨어져요. 

다음과 같이 컴파일한 표현식을 Pattern 객체로 static 필드에 선언해놓고 사용하는 게 더 좋을 것 같아요. 

```java
private static final Pattern INVALID_CHAR_PATTERN = Pattern.compile("[^a-zA-Z0-9가-힣]");
```
```suggestion
                .map(keyword -> INVALID_CHAR_PATTERN.matcher(keyword).replaceAll(""))
```

2024-12-12 14:00 UTC, kyum-q approved these changes
초롱 첵오입니다~ 수고하셨어용~!~!

2024-12-12 14:00 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
> +        @ValueSource(strings = {"안녕", "+안녕", "안+녕", " 안녕"})
'안녕+' 도 테스트하면 좋을 것 같아요 외에 테스트 중에 하나는 특수문자를 -로 해주면 좋을 것 같아요 !

2024-12-12 15:44 UTC, HoeSeong123 reviewed
반영완료!👍

2024-12-12 23:23 UTC, zangsu approved these changes
이미 리뷰를 잘 남겨 주시고, 또 잘 반영해 주셨군요 🥹 
고생하셨습니다, 초롱!!

2024-12-13 00:38 UTC, zeus6768 approved these changes

2024-12-13 00:39 UTC, merged