태그 동시 생성 시 중복 문제 해결
woowacourse-teams/2024-code-zap pull request #978
Opened 2024-12-19 04:03 UTC by jminkkk

## ⚡️ 관련 이슈
close #960 

## 📍주요 변경 사항

4가지 방법(이슈 참고)에 대해 고민해봤는데 유니크 제약 조건과 재시도로 처리하는 게 적절하다고 판단했어요!

재시도를 처리해주는 spring retry 의존성을 추가했습니다.

문제 상황을 재연하기 위한 테스트에서 ServiceTest에 @Transactional 어노테이션으로 인해 재연이 불가능해요.

@Disable 처리를 해놓았으니 문제 상황을 확인하고 싶으신 분들은 참고 부탁해요!

## 🍗 PR 첫 리뷰 마감 기한
12/20 13:00

2024-12-19 11:59 UTC, kyum-q requested changes
몰리 수고하셨어욧 ~ 간단한 코멘트 남겨두었습니다 ~!! 확인하고 답변 달아주세용~

2024-12-19 11:59 UTC, kyum-q commented on backend/src/main/java/codezap/tag/domain/Tag.java
> +    @Column(nullable = false,unique = true, columnDefinition = "VARCHAR(255) COLLATE utf8mb4_bin")
컬럼 제약 조건이 추가되었으니 flyway 마이그레이션 파일도 만들어줘야하지 않나요?😁

2024-12-19 11:59 UTC, kyum-q commented on backend/src/main/java/codezap/global/retry/RetryConfiguration.java
> +public class RetryConfiguration {
해당 configuration 클래스는 없어도 될 것 같은데 어떻게 생각하시나요?
제가 찾아보고 실제 해당 파일 삭제하고 테스트 돌려보니 없어도 되는 것 같아요 !
그래서 따로 공통 설정하는 값이 있는 것이 없어서 사용되지 않고 있으니 없어도 될 것 같아요 !

2024-12-19 11:59 UTC, kyum-q commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +    @Retryable(retryFor = DataIntegrityViolationException.class, maxAttempts = 3)
maxAttempts를 3으로 설정한 이유가 궁금해용 ~

2024-12-19 11:59 UTC, kyum-q commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> -        void updateSourceCodesChangeModifiedAt() {
applicationService에서 소스코드만 변경되었을 때 수정시간이 변경되는지 확인하는 테스트 코드인데, 해당 테스트를 제거한 이유가 있을까요??
제가 modifiedAt 문제를 해결하면서 확인을 위해 추가해둔건데 삭제하는 이유가 궁금해서요 ~

2024-12-20 02:40 UTC, jminkkk commented on backend/src/main/java/codezap/tag/domain/Tag.java
> +    @Column(nullable = false,unique = true, columnDefinition = "VARCHAR(255) COLLATE utf8mb4_bin")
앗! 놓쳤네요 수정하겠습니다 👍

2024-12-20 05:23 UTC, jminkkk commented on backend/src/main/java/codezap/global/retry/RetryConfiguration.java
> +public class RetryConfiguration {
테스트는 통과하지만 실제 저장된 템플릿은 하나입니다! 
하나만 저장되고 다른 하나는 롤백되어 버려서 아마 성공한 것처럼 보였을 거에요!

테스트에 동시 요청이 모두 처리되었는지 확인하는 코드를 다시 커밋해놓았어요 확인 부탁해요!

2024-12-20 06:19 UTC, jminkkk commented on backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
> -        void updateSourceCodesChangeModifiedAt() {
리베이스 과정에서 충돌이 발생해서 덮혔었네요 🥲
다시 롤백했습니다!

2024-12-20 10:39 UTC, jminkkk commented on backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
> +    @Retryable(retryFor = DataIntegrityViolationException.class, maxAttempts = 3)
Spring Retry는 첫 시도 (실패한 시도)까지 포함을 해서 시도 횟수를 세게 됩니다.

<img width="553" alt="image" src="https://github.com/user-attachments/assets/a5d0aae7-48cc-47e1-b0a0-aa5a9807017b" />

즉, 한번 실패한 후 2번 더 시도를 하게 되는 것인데요!
2로 하게 되면 단 한번 더 재시도하고 반환하는 게 불안하기도 하고 기본값인 3면 충분할 것 같아서 기본값으로 유지했어요~! 
더 높게 설정하고 싶거나 다른 의견 있다면 말해주세요!

2024-12-20 10:42 UTC, kyum-q approved these changes
몰리 수고했어용~!~!~!~ 체고 ~!~!~!

2024-12-20 10:47 UTC, merged