컴포넌트 스타일 일관성 리팩토링
woowacourse-teams/2024-code-zap pull request #98
Opened 2024-07-21 14:17 UTC by vi-wolhwa

## ⚡️ 관련 이슈
close #92

## 📍주요 변경 사항
### 1. 변경 컴포넌트
- Button
- Flex
- Header
- Input
- Layout
- SelectList
- SnippetEditor
- TemplateItem
- TemplateTitleInput
- Text
### 2. 리팩토링 기준 (컨벤션)
- Emotion Styling Method
  - `css` 객체 스타일링 제거
  - Styled-component 사용
    - `Input`, `Flex`, `Button` 컴포넌트 우선 사용
- Props
  - 네이밍
    - 컴포넌트 : `Props`로 네이밍한다.
    - 스타일 : `StyleProps`로 네이밍 한다.
  - 선언/정의
    - 스타일 : 컴포넌트의 `Props`를 `Pick`으로 확장한다.
    - 스타일 : props를 옵셔널(`?`)로 선언한다.
- Default Value
  - 컴포넌트
    - Props에 기본값을 입력하지 않는다.
    - Styled-component에 전달할 스타일 속성은 기본값을 입력하지 않는다.
    ``` javascript <br>
    const Button = ({ children, onClick, type, variant, size, width, disabled }: Props) => (
    <S.Button type={type || 'button'} variant={variant} size={size} width={width} disabled={disabled} onClick={onClick}>
      {children}
    </S.Button>
    );
    ```
  - 스타일
    - CSS 기본값과 동일할 경우, 기본값을 입력하지 않는다.
    - 기본값 입력이 필요할 경우, props에 입력한다.
    ``` javascript <br>
    export const TextWrapper = styled.span<StyleProps>`
      font-size: ${({ size }) => `${size}rem`};
      font-weight: ${({ weight = 'regular' }) => weights[weight]};
      color: ${({ color = 'white' }) => color};
    `;
    ```    

## 🎸기타
### Stylelint 적용 관련 트러블슈팅 ([바로가기](https://www.notion.so/leijay/Stylelint-CSS-Order-3d76f4a10be641808576e4a36c38cb2d?pvs=4))

2024-07-22 07:01 UTC, Jaymyong66 requested changes
기본값 관련 이야기를 해봐야할 것 같아요~!
undefined로 둘지에 대해서도요!

2024-07-22 07:01 UTC, Jaymyong66 commented on frontend/src/components/SelectList/style.ts
> +  background-color: ${({ isSelected = '#FFEBBB' }) => isSelected};
요기 FFEBBB는 기본값으로 들어간 것 같아요!

2024-07-22 07:01 UTC, Jaymyong66 commented on frontend/src/components/Text/style.ts
> +  color: ${({ color = 'white' }) => color};
여기도 기본값이요!

2024-07-22 07:17 UTC, vi-wolhwa commented on frontend/src/components/Flex/style.ts
> +    'flex' | 'width' | 'height' | 'margin' | 'padding' | 'align' | 'direction' | 'wrap' | 'gap' | 'justify'
`Props`에 Style에서 사용하지 않는 prop가 있는 케이스가 있기 때문에 `Pick`를 사용했습니다.
1. Style 파일들 간의 구조적 일관성 유지
2. 컴포넌트의 prop이 추가되었을 때, `Pick`으로 리팩토링 해야 하는 문제

2024-07-22 07:24 UTC, Hain-tain reviewed
고생하셨습니다 👍👍 

+ 우리 해커톤 끝났으니까 이제 슬슬 색상과 font-size 등에 대한 토큰을 상수로 빼서 사용하는 작업을 시작해야 할 것 같아요!!

2024-07-22 07:24 UTC, Hain-tain commented on frontend/src/components/SelectList/style.ts
> +  background-color: ${({ isSelected = '#FFEBBB' }) => isSelected};
```suggestion
  background-color: ${({ isSelected }) => isSelected && '#FFEBBB' };
```

2024-07-22 07:24 UTC, Hain-tain commented on frontend/src/components/Input/Input.tsx
> +      formNoValidate={type === 'email' ? true : undefined}
```suggestion
      formNoValidate={type === 'email'}
```

2024-07-22 07:24 UTC, Hain-tain commented on frontend/src/components/SnippetEditor/SnippetEditor.tsx
> +      />
현재 input 디자인이 figma와 다른 것 같아요!! Input 컴포넌트 수준에서 디자인을 바꿀 수 있도록 확장할지, 아니면 새롭게 디자인된 input 컴포넌트를 만들지 같이 협의해봅시다! 개인적인 생각으로는 input도 버튼처럼 variant를 주는 방식으로 리펙토링 해보면 어떨까 싶어요!! 왜냐하면 input의 기능은 동일한데 스타일만 바뀌는 것이니까요..!!

2024-07-22 07:24 UTC, Hain-tain commented on frontend/src/components/Text/Text.tsx
> +  <S.TextWrapper as='h1' size='3.2' weight={weight} color={color}>
as 라는 문법(?)을 처음 보는데 굉장히 유용하고 신기하군요  👍👍

2024-07-22 07:24 UTC, vi-wolhwa commented on frontend/src/components/Button/style.ts
> +  ${({ size = 'medium' }) => sizes[size]};
`size = `medium`은 size prop을 전달받지 않았을 때 기본값을 지정한 것입니다.

`size`가 `undefined` 일 경우 : `medium`
`size`가 `small` | `medium` 일 경우 : `small` | `medium`

2024-07-22 07:27 UTC, vi-wolhwa commented on frontend/src/components/Header/Header.tsx
> +          width='40rem'
`max-width`를 추가했던 이유는 화면이 작아질 때, 검색창의 길이를 줄이기 위해서입니다.

코드를 확인하던 중 실수로 현재 속성이 적용되지 않고 누락이 되어있었습니다. 따라서 기존 동작을 유지하는 방향으로 리팩토링 하였습니다.

2024-07-22 07:34 UTC, vi-wolhwa commented on frontend/src/components/Input/Input.tsx
> +      formNoValidate={type === 'email' ? true : undefined}
``` javascript
formNoValidate={type === 'email'}
```

2024-07-22 07:35 UTC, vi-wolhwa commented on frontend/src/components/SelectList/style.ts
> +  background-color: ${({ isSelected = '#FFEBBB' }) => isSelected};
``` javascript
  background-color: ${({ isSelected }) => isSelected && '#FFEBBB' };
```

2024-07-22 07:36 UTC, vi-wolhwa commented on frontend/src/components/SnippetEditor/SnippetEditor.tsx
> +      />
기존 코드로 롤백 하였습니다!

2024-07-22 08:31 UTC, vi-wolhwa commented on frontend/src/components/Button/Button.tsx
> +  <S.Button type={type || 'button'} variant={variant} size={size} width={width} disabled={disabled} onClick={onClick}>
논의 결과
1. 컴포넌트에서 'default value' 설정
2. Props에서 불필요한 Optional(`?`) 삼가
(ex. `size`, `variant`와 같은 필수적인 prop)

2024-07-22 08:47 UTC, vi-wolhwa commented on frontend/src/components/Flex/style.ts
> +    'flex' | 'width' | 'height' | 'margin' | 'padding' | 'align' | 'direction' | 'wrap' | 'gap' | 'justify'
컴포넌트의 `Props`를 Import 해서 스타일 인터페이스 선언 없이 사용하기

2024-07-24 04:46 UTC, Jaymyong66 approved these changes

2024-07-24 04:51 UTC, Hain-tain approved these changes

2024-07-24 04:51 UTC, merged