카테고리 순서 변경
woowacourse-teams/2024-code-zap pull request #988
Opened 2024-12-23 10:26 UTC by HoeSeong123

## ⚡️ 관련 이슈
close #이슈번호

## 📍주요 변경 사항
> 주요 변경 사항에 대해 작성해주세요.

## 🎸기타
> 고려해야 하는 내용을 작성해 주세요.

## 🍗 PR 첫 리뷰 마감 기한
00/00 00:00

2024-12-26 11:55 UTC, zeus6768 requested changes
코드 넘 깔끔해졌네요 ⚡⚡⚡

버그 발견해서 RC 남겨요!!

2024-12-26 11:55 UTC, zeus6768 commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +    }
<img width="800" alt="Screenshot 2024-12-26 at 8 29 41 PM" src="https://github.com/user-attachments/assets/08253cde-d981-4d2f-a128-20fd734219ae" />

로직이 잘못된 것 같아요. ordinal + 1이 count와 일치해야 할 것 같아요~

해당 내용으로 테스트코드 추가하면 좋겠네용

2024-12-26 11:55 UTC, zeus6768 commented on backend/src/main/java/codezap/category/service/CategoryService.java
코드가 너무 길어서 검증 로직을 CategoryValidationService로 분리하면 어떨까 제안해요. 

```java
@Service
@RequiredArgsConstructor
public class CategoryService {

    private final CategoryRepository categoryRepository;
    private final CategoryValidationService validationService;

    @Transactional
    public CreateCategoryResponse create(Member member, CreateCategoryRequest request) {
        validationService.validateDuplicatedCategory(request.name(), member);
        validationService.validateOrdinal(member, request);

        Category category = categoryRepository.save(createCategory(member, request));
        return CreateCategoryResponse.from(category);
    }

    @Transactional(readOnly = true)
    public FindAllCategoriesResponse findAllByMemberId(Long memberId) {
        return FindAllCategoriesResponse.from(categoryRepository.findAllByMemberIdOrderById(memberId));
    }

    @Transactional
    public void updateCategories(Member member, UpdateAllCategoriesRequest request) {
        validationService.validateDuplicateNameRequest(request);
        validationService.validateOrdinals(request);
        validationService.validateIds(request);

        createCategories(member, request);
        updateCategories(request.updateCategories(), member);
        deleteCategories(request.deleteCategoryIds(), member);

        validationService.validateCategoriesCount(member, request);
    }

    private void createCategories(Member member, UpdateAllCategoriesRequest request) {
        categoryRepository.saveAll(request.createCategories().stream()
                .map(createRequest -> new Category(createRequest.name(), member, createRequest.ordinal()))
                .toList());
    }

    private void updateCategories(List<UpdateCategoryRequest> updates, Member member) {
        updates.forEach(update -> {
            Category category = categoryRepository.fetchById(update.id());
            category.validateAuthorization(member);
            validationService.validateDefaultCategory(category);
            category.update(update.name(), update.ordinal());
        });
    }

    private void deleteCategories(List<Long> ids, Member member) {
        ids.forEach(id -> {
            Category category = categoryRepository.fetchById(id);
            category.validateAuthorization(member);
            validationService.validateDefaultCategory(category);
            validationService.validateHasTemplate(id);
            categoryRepository.deleteById(id);
        });
    }
}
```

```java
package codezap.category.service;

import java.util.HashSet;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.springframework.stereotype.Service;

import codezap.category.domain.Category;
import codezap.category.dto.request.CreateCategoryRequest;
import codezap.category.dto.request.UpdateAllCategoriesRequest;
import codezap.category.dto.request.UpdateCategoryRequest;
import codezap.category.repository.CategoryRepository;
import codezap.global.exception.CodeZapException;
import codezap.global.exception.ErrorCode;
import codezap.member.domain.Member;
import codezap.template.repository.TemplateRepository;
import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class CategoryValidationService {

    private final CategoryRepository categoryRepository;
    private final TemplateRepository templateRepository;

    public void validateDuplicatedCategory(String categoryName, Member member) {
        if (categoryRepository.existsByNameAndMember(categoryName, member)) {
            throw new CodeZapException(ErrorCode.DUPLICATE_CATEGORY, "이름이 " + categoryName + "인 카테고리가 이미 존재합니다.");
        }
    }

    public void validateDefaultCategory(Category category) {
        if (category.isDefault()) {
            throw new CodeZapException(ErrorCode.DEFAULT_CATEGORY, "기본 카테고리는 수정 및 삭제할 수 없습니다.");
        }
    }

    public void validateHasTemplate(Long id) {
        if (templateRepository.existsByCategoryId(id)) {
            throw new CodeZapException(ErrorCode.CATEGORY_HAS_TEMPLATES, "템플릿이 존재하는 카테고리는 삭제할 수 없습니다.");
        }
    }

    public void validateDuplicateNameRequest(UpdateAllCategoriesRequest request) {
        List<String> allNames = Stream.concat(
                request.createCategories().stream().map(CreateCategoryRequest::name),
                request.updateCategories().stream().map(UpdateCategoryRequest::name)
        ).toList();

        if (hasDuplicates(allNames)) {
            throw new CodeZapException(ErrorCode.INVALID_REQUEST, "요청에 중복된 카테고리 이름이 존재합니다.");
        }
    }

    public void validateOrdinal(Member member, CreateCategoryRequest request) {
        long ordinal = request.ordinal();
        long count = categoryRepository.countByMember(member);
        if (ordinal != count) {
            throw new CodeZapException(ErrorCode.INVALID_REQUEST, "카테고리 순서가 잘못되었습니다.");
        }
    }

    public void validateOrdinals(UpdateAllCategoriesRequest request) {
        List<Long> allOrdinals = Stream.concat(
                request.createCategories().stream().map(CreateCategoryRequest::ordinal),
                request.updateCategories().stream().map(UpdateCategoryRequest::ordinal)
        ).sorted().toList();

        if (!isSequential(allOrdinals)) {
            throw new CodeZapException(ErrorCode.INVALID_REQUEST, "카테고리 순서가 연속적이지 않습니다.");
        }
    }

    public void validateIds(UpdateAllCategoriesRequest request) {
        List<Long> allIds = Stream.concat(
                request.updateCategories().stream().map(UpdateCategoryRequest::id),
                request.deleteCategoryIds().stream()
        ).toList();

        if (hasDuplicates(allIds)) {
            throw new CodeZapException(ErrorCode.INVALID_REQUEST, "요청에 중복된 id가 존재합니다.");
        }
    }

    public void validateCategoriesCount(Member member, UpdateAllCategoriesRequest request) {
        if (request.updateCategories().size() + request.createCategories().size()
                != categoryRepository.countByMember(member) - 1) {
            throw new CodeZapException(ErrorCode.INVALID_REQUEST, "카테고리의 개수가 일치하지 않습니다.");
        }
    }

    private boolean hasDuplicates(List<?> items) {
        return items.size() != new HashSet<>(items).size();
    }

    private boolean isSequential(List<Long> ordinals) {
        return ordinals.stream()
                .distinct()
                .sorted()
                .collect(Collectors.toList())
                .equals(ordinals);
    }
}
```

다른 분들 의견도 궁금하네용 동의한다면 따봉을, 다른 의견이 있다면 코멘트 부탁해요~!

2024-12-26 11:55 UTC, zeus6768 commented on backend/src/main/resources/db/migration/V11__add_category_ordinal.sql
> +ALTER TABLE category ADD COLUMN ordinal BIGINT NOT NULL;
(member_id, ordinal) 합성 필드에 unique 조건 걸어볼까요??

```suggestion
ALTER TABLE category ADD COLUMN ordinal BIGINT NOT NULL;
ALTER TABLE category ADD CONSTRAINT member_ordinal_unique UNIQUE (member_id, ordinal);
```

2024-12-26 11:55 UTC, zeus6768 commented on backend/src/main/java/codezap/category/domain/Category.java
>      }
`@AllArgsConstructor` 생성자 체이닝 제안해요~

```suggestion
    public Category(String name, Member member, long ordinal) {
        this(null, member, name, false, ordinal);
    }
```

2024-12-26 13:51 UTC, kyum-q requested changes
초롱 수고했어요~ 최대한 꼼꼼하게 리뷰했습니다~ 확인 부탁드려요~!

2024-12-26 13:51 UTC, kyum-q commented on backend/src/main/java/codezap/category/dto/request/UpdateAllCategoriesRequest.java
> +public record UpdateAllCategoriesRequest(
(⚡어필의 차원에서 zap을 사용합니다 ㅎㅎ )

해당 dto에서 fail fast를 위해 소스 코드 request처럼 SourceCodesOrdinalValidator를 이용해서 dto에서도 순서 검증하는 건 어떨까요?

현재 해당 로직이 템플릿 수정 로직과 매우 유사하다고 생각합니다. 그래서 현재 SourceCodesOrdinalValidator의 이름을 OrdinalValidator로 변경하여 소스코드에서만 사용하지 않고 이렇게 순서 검증이 필요한 곳에서 재사용하면 좋을 것 같아요 ~! 

이렇게 한다면 ValidatedSourceCodesOrdinalRequest의 
`@SourceCodesOrdinal(message = "소스 코드 순서가 잘못되었습니다.", groups = SourceCodeOrdinalGroup.class)`
이 메시지를 `순서가 잘못되었습니다.` 로 어디서든 사용될 수 있게 변경한다면 더 재사용하는데 좋을 것 같아요~

이에 대해 어떻게 생각하시나요?

> 만약 변경에 동의하시다면 지금 당장 클래스 이름은 변경 안하면 좋을 것 같아요 ,,! 해당 클래스를 #991 에서 사용하고 있어서 추후 둘 다 머지되고 이름 변경하면 좋을 것 같아요~

2024-12-26 13:51 UTC, kyum-q commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +        ).sorted().toList();
제가 위에 말한대로 ValidatedSourceCodesOrdinalRequest을 사용한다면 해당 코드를 request에 extractSourceCodesOrdinal() 메서드로 두고 호출해서 사용할 수 있을 것 같아요~

그래서 dto에서 1차 검증으로 fast fail의 장점을 잡고, 내부에서는 안정성을 위해 한 번 더 체크하는 장점을 잡을 때 하나의 메서드를 사용하면 추후 리펙터링 시에도 좋을 것 같아요~

2024-12-26 13:51 UTC, kyum-q commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +    private void createCategories(Member member, UpdateAllCategoriesRequest request) {
전달 인자를 UpdateAllCategoriesRequest가 아닌 List<CreateCategoryRequest> 로 넘기면 더 좋을 것 같아요. 사용하는 데이터는 CreateCategoryRequest 뿐이니까요

2024-12-26 13:51 UTC, kyum-q commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +            throw new CodeZapException(ErrorCode.INVALID_REQUEST, "요청에 중복된 카테고리 이름이 존재합니다.");
swagger에는 `"이름이 %s 인 카테고리가 이미 존재합니다."`로 에러메시지로 되어있네요~ 둘 중 하나를 변경해 통일성 있게 해주세요~

2024-12-26 13:51 UTC, kyum-q commented on backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
> +            @ErrorCase(description = "카테고리의 순서가 잘못된 경우", exampleMessage = "템플릿 순서가 중복됩니다.")
애플리케이션 예외 메시지와 동일하게 
```suggestion
            @ErrorCase(description = "카테고리의 순서가 잘못된 경우", exampleMessage = "카테고리 순서가 잘못되었습니다.")
```

로 변경해주세요~!

2024-12-26 23:12 UTC, zangsu commented on backend/src/main/java/codezap/category/dto/request/UpdateAllCategoriesRequest.java
> +public record UpdateAllCategoriesRequest(
이미 동일한 기능을 하는 `Validator`가 존재하니 좋은 의견이네요~~
소스코드와 카테고리의 동작이 언제까지 동일할지 모르니 기존의 클래스를 완전 재사용하는 것이 조금은 조심스럽기도 하지만, 나중에 동작이 달라져야 할 때 상속을 통한 분리를 고려해 봐도 좋을 것 같고요~~

2024-12-26 23:25 UTC, zangsu commented on backend/src/main/java/codezap/category/service/CategoryService.java
네이밍을 단순하게 `CategoryValidator`로 지어도 좋을 것 같긴 한데, `XXXRepository` 들의 의존성을 가지고 있기도 하네요.
`CategoryValidationService`도 좋을 것 같기도 하구요~~

2024-12-27 01:51 UTC, jminkkk commented on backend/src/main/java/codezap/category/service/CategoryService.java
음 validateDuplicateNameRequest, validateOrdinal, validateOrdinals, validateIds, validateCategoriesCount 등 레포지토리를 호출하지 않는 검증들은 일급 컬렉션을 활용해서 도메인의 책임으로 주는 건 어떨까 싶은데............. 어떻게 분리하면 좋을지 고민되네요..........

2024-12-27 02:43 UTC, zangsu approved these changes
에궁, 리뷰가 늦었습니다 ㅠㅠ
제우스와 켬미가 이미 너무 잘 봐주어서 달리 추가할 코멘트는 없습니다!

2024-12-27 03:18 UTC, jminkkk approved these changes
롱초 와우 수고하셨어요 👍 엣지 케이스나 테스트가 진짜 만만치 않았겠네요...!

로직이 복잡해지면서 service의 private 메서드가 많아져버렸네요 🥲
도메인 책임으로 넘길 수 있는 방법에 대해 저도 고민해볼게요 !
너무 고생하셨습니다!

2024-12-27 03:18 UTC, jminkkk commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +        }
List의 forEach 쓰면 어떨까요~? 한줄로 가독성이 좋아질 것 같아요!

2024-12-27 03:18 UTC, jminkkk commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +            throw new CodeZapException(ErrorCode.INVALID_REQUEST, "카테고리의 개수가 일치하지 않습니다.");
+) 카테고리 전체 (수정되지 않는 카테고리)도 보내주어야 한다는 게 전달되면 좋을 것 같네요!
그렇지 않으면 여기서 예외가 많이 터질 것 같슴다

2024-12-27 04:15 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +    }
치명적인 오류였네요.
기본 카테고리인 `카테고리 없음`의 순서를 0으로 고정하기로 했습니다!!

2024-12-27 12:15 UTC, HoeSeong123 reviewed
피드백 반영 완료하였습니다.
좀 많이 변경되었는데 아래의 부분을 중점적으로 확인해주시면 감사드리겠습니당
- 검증 로직 책임 분리 (https://github.com/woowacourse-teams/2024-code-zap/pull/988#discussion_r1898477039)
- 중복된 이름 검증 (https://github.com/woowacourse-teams/2024-code-zap/pull/988#discussion_r1898271871)
- 유니크 제약 조건 (https://github.com/woowacourse-teams/2024-code-zap/pull/988#discussion_r1898293752)

2024-12-27 12:15 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/service/CategoryService.java
저도 몰리 의견대로 도메인의 책임으로 주는 것이 좋다고 생각했습니다.
repository를 사용하지 않으면서 dto를 검증하는 로직은 커스텀 어노테이션을 통해 컨트롤러 계층에서 검증되도록 변경하였습니다.
도메인에서 진행할 수 있는 검증은 도메인 쪽으로 분리하였고, 나머지는 그대로 두었습니다.

더 좋은 의견 있으면 공유해주세요!!

2024-12-27 19:39 UTC, kyum-q reviewed
초롱 리뷰 반영 완전 최고애요~! 
정말 대단해~!!!
답변 달아준거에 추가적으로 제 의견 더 달아두었습니다~ 확인 부탁드려요 😁

2024-12-27 19:39 UTC, kyum-q commented on backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
> +    @Operation(summary = "카테고리 생성, 수정, 삭제", description = "해당하는 식별자의 카테고리를 생성, 수정, 삭제할 수 있습니다.")
사소하지만 설명에 "해당하는 식별자의 "는 제거해면 좋을 것 같아요~ path variable로 식별자를 받는다면 더 적절하겠지만 현재는 아니니 해당 문구를 제거해도 좋지 않을까합니다~

2024-12-27 19:39 UTC, kyum-q commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +            throw new CodeZapException(ErrorCode.INVALID_REQUEST, "요청에 중복된 카테고리 이름이 존재합니다.");
수정 시에는 데이터베이스 매번 접근하지 않는 현재 방식이 좋은 것 같네요~ swagger에만 추가했다면 현재 코드 너무 좋아요~!

2024-12-27 19:39 UTC, kyum-q commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +        ).sorted().toList();
> 제가 이해한 바로는 위 코드를 dto에 두고 service에서도 해당 코드를 불러서 재사용하자는 것 같은데 맞나요??
> 만약 맞다면 똑같은 검증 로직을 dto와 service에서 두 번 실행하자는 얘기인가요?

네 맞습니다 ~!

이번에 disabled 테스트를 수정하면서 템플릿 순서 검증을 dto에서만 해서 서비스를 호출할 때 dto를 거치지 않고 테스트하면 순서가 보증되지 않음을 알 수 있었어요.

그래서 dto검증을 믿어야할지, 중복 검증이라도 한 번 더 검증할지 고민해봤습니다.

그래서 저는 결론적으로 해당 로직은 데이터베이스 접근이 없고 복잡하지 않은 로직이니 서비스 단에서 한 번 더 중복 체크하는 것이 안정적인 서비스가 될 거라고 판단했습니다!
왜냐하면 결국 해당 메서드는 public으로 열려 있고 또 사용될 때 외부에서 순서 검증 하겠지 하고 믿는다면 휴먼 에러로 문제가 발생할 가능성이 생길 것 같다고 판단했기 때문입니다.

>[stack overflows](https://stackoverflow.com/questions/42280355/spring-rest-api-validation-should-be-in-dto-or-in-entity)를 보면 
검증 위치에 대한 질문중 가장 많은 추천을 받았던 답변에서는 ‘We should always strive to perform validation at multiple stages of any application.’ 라는 의견도  있습니다~!

2024-12-28 01:11 UTC, zeus6768 commented on backend/src/main/java/codezap/category/service/CategoryService.java
저는 도메인에서 커스텀 예외(CodeZapException)를 던지는 로직이 틀렸다고 생각하는 입장이에요. 

도메인이 다른 계층에 의존하지 않아야 한다는 원리에 어긋난다고 생각하기 때문인데요. 

예를 들면 초롱이 만든 카테고리 도메인의 `validate...` 메서드들이 클라이언트에게 반환되는 상태코드와 에러메시지를 알고 있는 것처럼요. 에러코드 또는 예외 클래스가 변경되면 도메인에 변경이 전파될 수 있어요. 

그래서 템플릿 도메인의 `matchMember` 메서드나 회원 도메인의 `matchPassword` 메서드처럼 boolean을 반환하는 메서드를 만들고 예외를 던지는 로직은 서비스 레이어에 있어야 한다고 생각해요. 

예외를 바로 던지고 싶다면 커스텀 예외가 아니라 IllegalStateException과 같은 자바 기본 예외를 던져야 해요. 

아니면 몰리 말처럼 검증을 담당하는 도메인 객체가 따로 있는 것도 좋아요. 

개인적인 의견이니 반영은 자유롭게 해줘도 괜찮아요~

2024-12-28 01:11 UTC, zeus6768 commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +    }
개인적으론 이렇게 작성하는 게 나은 것 같아 제안해요!!

재사용되지도 않는 메서드를 선언하기 위해 클래스의 라인 수가 길어진다고 생각해요. 

```suggestion
    @Transactional
    public CreateCategoryResponse create(Member member, CreateCategoryRequest request) {
        validateDuplicatedCategory(request.name(), member);
        validateOrdinal(member, request);
        Category category = new Category(request.name(), member, request.ordinal());
        Category saved = categoryRepository.save(category);
        return CreateCategoryResponse.from(saved);
    }
```

2024-12-28 01:11 UTC, zeus6768 commented on backend/src/main/java/codezap/global/validation/Ordinal.java
👍

2024-12-28 05:11 UTC, HoeSeong123 reviewed
반영 완료!!

## 변경사항
- dto에서 검증한 로직을 서비스 계층에서 다시 한 번 검증
- validationService 분리
- 도메인에서 예외처리 X

2024-12-28 05:11 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/service/CategoryService.java
>저는 도메인에서 커스텀 예외(CodeZapException)를 던지는 로직이 틀렸다고 생각하는 입장이에요.
도메인이 다른 계층에 의존하지 않아야 한다는 원리에 어긋난다고 생각하기 때문인데요.

동의합니다!!
제우스 의견에 따라 도메인에서는 boolean을 반환하는 메서드만 만들었고 예외를 던지는 로직은 서비스에서 진행하였습니다.
또한 켬미 의견에 따라 dto에서 진행한 검증 로직을 서비스에서 다시 한 번 검증하였는데, 그로 인해 서비스 클래스가 너무 뚱뚱해져서 맨처음 제우스 의견대로 validationService 클래스를 분리하였습니다!

2024-12-28 05:12 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/service/CategoryService.java
> +        ).sorted().toList();
동의합니다!!
dto에서 진행한 검증을 서비스에서 다시 한 번 검증하도록 수정하였습니다.
이에 따라 테스트 코드도 추가하였습니다!

2024-12-28 05:23 UTC, jminkkk commented on backend/src/main/java/codezap/category/service/CategoryService.java
음 커스텀 예외를 어디 계층으로 볼 것이냐 부터 시작일 것 같은데요. 예외조차 도메인으로 볼 수 있지 않을까요?
우리 서비스가 지금 도메인을 도메인 답게 사용하고 있는 것 같지는 않아서, 도메인의 의존 관계의 의미가 크게 느껴지지 않는 것 같아요.

---

이건 논의가 조금 길어질 것 같기도 한데요 🥲
일단 제우스 의견대로 분리하고, 더 이야기해봐도 좋을 것 같아요.

+) 우리와 조금 예외처리 방식이 다르긴 하지만 [리뷰미 팀 코드](https://github.com/woowacourse-teams/2024-review-me/tree/develop/backend/src/main/java/reviewme/review/domain/exception)를 참고해보아도 좋을 것 같아요.

2024-12-28 05:27 UTC, kyum-q approved these changes
초롱 완전 빨라빨라 체고에요~!!

2024-12-28 06:13 UTC, jminkkk approved these changes
롱초 수고했어요 😀
최고입니다!!!!!!!!!

도메인 책임에 대해 리뷰를 하나 남겼지만, 논의는 아무래도 전에 초롱이 얘기했던 테이블 분리와 함께 대면 회의 때 논의해보면 좋을 것 같네요 😅
수고했어요 🔥

2024-12-30 08:32 UTC, HoeSeong123 reviewed
리뷰 반영하였습니다~~~

2024-12-30 08:32 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/service/CategoryValidationService.java
> +    }
순서, id 중복, 이름 중복에 대한 검증을 다음과 같이 진행했습니다.
일급 컬렉션 쪽에서는 `IllegalArgumentException`을 던지고 서비스 계층에서 이를 잡아 `CodeZapException`으로 던지도록 하였습니다.

2024-12-30 08:32 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/service/CategoryValidationService.java
> +    }
카테고리명 중복 에러 메세지를 다음과 같이 통합하였습니다.

2024-12-30 08:32 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/repository/CategoryJpaRepository.java
> +
`@Modifying`을 사용하여 삭제, 수정 쿼리에 flush를 하도록 수정하였습니다.
이는 데이터베이스에 변경 사항을 전송할 뿐, 트랜잭션이 커밋되지 않으면 해당 변경 사항은 최종적으로 반영되지 않으므로 같은 트랜잭션 내에서 실패할 경우 자동으로 롤백이 됩니다.

2024-12-30 09:18 UTC, jminkkk reviewed
롱초 뚝딱 바로! 멋져요 👍👍👍
도메인 관련 리뷰 남겼어요! 
확인 부탁해요!

2024-12-30 09:18 UTC, jminkkk commented on backend/src/main/java/codezap/category/service/CategoryValidationService.java
> +    }
음 GlobalExceptionHandler 말고 서비스 계층에서 처리한 이유가 있을까요??
GlobalExceptionHandler에서 처리하면 어떨까요??
try-catch가 서비스에 있는 게 어색하게 느껴지네요...!

2024-12-30 09:18 UTC, jminkkk commented on backend/src/main/java/codezap/category/domain/Ids.java
> +
생성 시 즉시 검증되지 않고 public 메서드로 외부에서 호출하게 한 이유가 궁금해요!

생성자에서 처리하지 않는다면 외부에서 따로 검증 메서드를 호출해야 하는데, 휴먼 에러로 이 검증을 호출하지 않아버릴 수 있을 것 같아요 🤔 또 도메인 규칙을 지키지 않는 도메인 객체가 생성되어 남게 될 수도 있겠네요!

이것에 대해 어떻게 생각하는지 궁금해요!

2024-12-30 09:59 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/service/CategoryValidationService.java
> +    }
저도 그렇게 하려고 했는데 그러면 도메인에서 던지는 모든 예외는 같은 에러 코드를 가지게 되더라고요.
사실 뭐 request dto에서 발생하는 오류니까 `INVALID_REQUEST`로 통일해도 문제는 없을 것 같은데 어떤게 더 괜찮나요?
기존에 중복된 이름에 대해서는 `DUPLICATE_CATEGORY`로 던지고 있어서 이렇게 하기는 했습니다.

2024-12-30 10:08 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/domain/Ids.java
> +
```java
public void validateOrdinals(UpdateAllCategoriesRequest request) {
    try {
        Ordinals ordinals = new Ordinals(request.extractOrdinal());
    } catch (IllegalArgumentException e) {
        throw new CodeZapException(ErrorCode.INVALID_REQUEST, e.getMessage());
    }
}


public void validateIds(UpdateAllCategoriesRequest request) {
    try {
        Ids ids = new Ids(request.extractIds());
    } catch (IllegalArgumentException e) {
        throw new CodeZapException(ErrorCode.DUPLICATE_ID, e.getMessage());
    }
}

public void validateNames(UpdateAllCategoriesRequest request) {
    try {
        Names names = new Names(request.extractNames());
    } catch (IllegalArgumentException e) {
        throw new CodeZapException(ErrorCode.DUPLICATE_CATEGORY, e.getMessage());
    }
}
```

코드가 이런 느낌이 돼서 뭔가뭔가 어색하더라고요..ㅋㅋ
근데 몰리 말대로 도메인 규칙을 지키지 않는 객체가 생성될 수 있는 문제가 생기긴 하겠네요.
다른 분들 의견만 더 들어보고 수정해보겠습니다!

2024-12-30 13:35 UTC, zeus6768 requested changes
`@Modifying`을 활용해서 결국 문제를 해결했네요 멋져요 👍👍👍

도메인에서의 검증에 대해 열심히 생각하고 코멘트 작성했어요. 

논의를 해야 한다고 생각해서 한 번 더 RC 남길게요!! 🙇‍♂️

2024-12-30 13:35 UTC, zeus6768 commented on backend/src/main/java/codezap/category/domain/Ids.java
> +
그런데... 코드 리뷰를 하며 곰곰이 생각해보니 저는 ids라는 도메인을 도메인으로 바라보는 게 맞지 않은 것 같아요. 

우리가 검증을 하는 이유는 생성, 수정, 삭제라는 기능이 실행되기 위한 입력이 정상적인지 확인하기 위해서에요. 
우리가 "요청을 받는 방식"을 정책적으로 결정함에 따라 생겨난 요구사항이에요. 
그 과정에서 사용되는 ID라는 속성은 RDBMS와 JPA에 의존하기 때문에 생겨났을 뿐이고, 카테고리라는 도메인과 무관해요. 

본 클래스는 컬렉션에서의 중복 검증 로직일 뿐이에요. 
로직이 도메인의 특성에서 비롯되지 않았어요. 
"카테고리" 라는 도메인 영역과 무관해요. 
카테고리가 아닌 다른 도메인에서도 컬렉션의 중복 검증 로직은 얼마든지 이루어질 수 있어요. 
실제로 SourceCodeService에서도 동일한 검증 로직을 수행하고 있죠. 
그런 의미에서 본 ID 중복 검증 클래스가 하는 일은 JPA Entity의 ID의 컬렉션을 이용한 서비스 로직으로 간주해야 한다고 생각해요. 
SourceCodeService에서 같은 로직을 사용하고 있으니, global 패키지의 util 로 분리해도 되겠군요. 

Ordinals, Names 클래스도 같은 의견이에요. 
두 클래스는 서비스 레이어에서 DTO를 사용하는 방식 때문에 만들어졌을 뿐이고, 다른 도메인 객체와 상호작용하지 않아요. 
Ordinals, Names가 도메인 영역에서 의미를 갖고 다른 도메인 객체와 상호작용이 있다면 도메인으로 볼 수 있겠지만, 그렇지 않으므로 categoryValidationService로 옮겨져야 한다고 생각해요. 

저는 몰리가 일급컬렉션을 이야기했을때, Categories를 만드는 것을 생각했어요. 
그렇게되면 Categories 객체가 생성될 때 각 원소의 ordinal과 name 필드의 중복을 검사할 수 있죠. 
다만 중복 검증 로직은 여전히 util로 분리할 여지가 있다고 생각하고, Categories 클래스를 만든다면 생성자에서 util 클래스의 정적 메서드를 호출해서 검증하는 게 좋을 것 같아요. 

핵심은 검증이라고 해서 다 같은 검증이 아니라는 거에요. 도메인의 검증과, 서비스의 검증을 구분하자는 이야기를 하고 싶었어요. 예를 들어 Default 카테고리가 있다는 정책은 도메인 영역으로 봐도 좋다고 생각해요. 카테고리를 수정할 수 있다는 것도 도메인 영역이에요. 그래서 카테고리를 수정할 때, Default 카테고리를 수정하려 할 경우 도메인 객체에서 예외를 발생시켜도 된다고 생각해요. 그래서 위 Category 클래스에 같은 의도로 의견을 남겼답니다. 

너무 길게 써서 죄송합니다... 😭
그러나 제 생각을 가능한 그대로 전달하는 게 서로에게 더 도움이 된다고 생각했어요. 
혹시 제가 모르는 게 있거나, 다른 의견이 있다면 얼마든지 부탁해요!!

2024-12-30 13:35 UTC, zeus6768 commented on backend/src/main/java/codezap/category/domain/Category.java
>      }
기본 카테고리의 이름이나 ordinal은 수정되면 안 된다고 생각해요.

드디어 여기서 도메인으로서의 검증을 할 수 있을 것 같네요. 

아래의 검증 로직이 update 실행 전에 호출되는 건 어떤가요?

메서드로 분리하는 것도 좋다고 생각해요. 

```suggestion
    public void update(String name, int ordinal) {
        if (isDefault) {
            throw new IllegalStateException("기본 카테고리는 수정할 수 없습니다.")
        }
        this.name = name;
        this.ordinal = ordinal;
    }
```

2025-01-04 02:40 UTC, HoeSeong123 commented on backend/src/main/java/codezap/category/domain/Category.java
>      }
카테고리 update를 변경감지가 아닌 update 쿼리를 직접 사용하도록 변경하였으므로 해당 코드는 삭제하였습니다!

2025-01-05 09:38 UTC, zeus6768 approved these changes

2025-01-07 14:21 UTC, merged