인기 태그 목록 조회
woowacourse-teams/2024-code-zap pull request #997
Opened 2024-12-28 04:13 UTC by jminkkk

## ⚡️ 관련 이슈
close #900

## 📍주요 변경 사항
인기 태그 목록 API를 구현했습니다.

기존 요구사항은 다음과 같았어요. 

- 7일 동안 생성된 템플릿 목록 중에서 가장 많이 연결된 태그를 조회한다. 태그는 5개씩 조회한다.
- 7일 동안의 태그가 5개 이하인 경우 기간은 연장될 수 있다.

설계를 고민했을 때 기간 연장에 대한 요구사항이 구체적이지 않아서 [이슈에 고민한 구체 방안](https://github.com/woowacourse-teams/2024-code-zap/issues/900#issuecomment-2563343636)을 적어 두었어요.

태그가 지정된 사이즈만큼 될때까지만 기간을 늘리는 로직으로 구현이 하였으니 다른 좋은 의견 있다면 부탁해요!

## 🎸기타
### 1. 기본값 변경
view 단이 변경될 것 같지만, 지금은 이미지가 있음에도 5개가 넘어가요.
따라서 5개면 너무 적을 것 같아서 기본값을 10개로 했어요.

### 2. 스케줄링과 캐싱 적용
현재 API 호출 시점을 기준으로 7일간 많이 생성된 템플릿 태그 개수를 계산하여 로직을 구현해요.
따라서 월요일 23:59분에 조회했을 때와 화요일 00:00 시에 조회했을 경우, 결과가 달라요.

이 PR이 머지된 후, 조회하는 기간을 고정해두고(월 ~ 일) 캐싱을 적용할 생각입니다!

기획 당시에 바로 캐싱 적용을 논의했었는데, 그것보다는 없을 때와 비교해보는 것이 의미있을 것 같아요
혹시 이것도 다른 좋은 의견이 있다면 편하게 말해주세요!

### 3. DatabaseListener 관련 TestExecutionListenr 충돌
TagServiceTest에서 기준 기간에 생성된 템플릿 태그가 너무 적을 경우, 위에 구체화한 정책에 따라 기간을 늘리는 것에 대한 테스트가 있어요.
이에 대한 테스트를 위해 clock mocking과 더미데이터를 고민했고, sql 파일이 더 빠르게 지정할 수 있어서 해당 방식을 선택했어요.

그런데 문제가 하나 있었어서 공유해요~!
@Sql은 내부적으로 SqlScriptsTestExecutionListener에 의해 실행되어요.
우리 ServiceTest에서 사용하는 DB 격리용 DatabaseListener가 AbstractTestExecutionListener를 상속받아 AbstractTestExecutionListener에 의해 실행되는 것처럼 말이죠!

그런데 두 TestExecutionListener가 동시에 실행될 경우, 커스텀으로 등록한 DatabaseListener는 기본 Listener가 실행된 후에 실행되어요.
따라서 SqlScriptsTestExecutionListener가 실행된 후 DatabaseListener가 실행되기 때문에 더미데이터가 넣어졌다가 다시 격리를 위해 truncate 되어버려요.

따라서 DatabaseListener의 우선순위를 낮추기 위해 Listener의 순서를 반환하는 메서드를 재정의했어요.
SqlScriptsTestExecutionListener의 우선순위가 5000이기 때문에 SqlScriptsTestExecutionListener보다 하나 더 높은 4999로 지정했어요.
<img width="402" alt="image" src="https://github.com/user-attachments/assets/b493acaf-0d68-4356-9424-80a61fd1237f" />

---

이렇게 순서를 재정의하게 되면, 흐름은 다음과 같아요.

1. 두TestExecutionListener가 충돌
2. 커스텀 리스너에 충돌 설정 (mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS)에 의해 AnnotationAwareOrderComparator가 동작
<img width="882" alt="image" src="https://github.com/user-attachments/assets/c469d99b-e977-40b0-a8f4-6deafbe60261" />
<img width="669" alt="image" src="https://github.com/user-attachments/assets/44a34089-2329-4ecd-9668-8f7edda1b1ad" />

3. @Order 기준으로 우선순위가 높은 Listner부터 실행
4. 4999인 DatabaseListener 실행 후, 5000인 SqlScriptsTestExecutionListener 실행

혹시 이해가 안되거나 더 나은 처리 방식이 있다면 이 부분도 말해주세요~!

## 🍗 PR 첫 리뷰 마감 기한
12/29 15:00

2024-12-29 02:50 UTC, kyum-q requested changes
몰리 수고했어요~
정책 상 헷갈리는 게 있어서 리뷰 남겨뒀습니다 확인해주세요~!

> DatabaseListener 관련 TestExecutionListenr 충돌

은 어렵네요..! 좀 더 공부해보겠지만, 현재로서는 몰리의 해결 방안이 최선인 것 같아요~!

2024-12-29 02:50 UTC, kyum-q commented on backend/src/main/java/codezap/tag/service/TagService.java
> +        return tagRepository.findMostUsedTagsByRecentTemplates(size);
### 1번 : 내가 이해한 몰리 의도

이슈를 읽어보면 '최근 10일 간 인기 태그 조회 시 10개 이하이면 태그가 지정된 사이즈만큼 될때까지만 기간을 늘린다.' 라고 이해했습니다.

예를 들어 
1일 전 ~ 10일 전 : 태그1 1개, 태그2 2개, 태그3 3개, 태그4 3개, 태그5 3개, 태그6 3개, 태그7 3개, 태그8 3개
11일 전 : 태그9 3개,  태그10 3개
12일 전 : 태그11 100개
일 때 10개가 11일에 채워지니 12일 거는 확인하지 않고 **태그1부터 태그10까지를 인기 태그**로 하는걸로 이해했는데 맞을까요??

### 2번 : 실제 코드

그런데 해당 코드를 레포지토리 단까지 분석하면 정책이 '최근 10일 간 인기 태그 조회 시 10개 이하이면 **전체 인기 순위에서 10개를 뽑는다.** '인 것같아요. 

예를 들어 
1일 전 ~ 10일 전 : 태그1 1개, 태그2 2개, 태그3 3개, 태그4 3개, 태그5 3개, 태그6 3개, 태그7 3개, 태그8 3개
11일 전 : 태그9 3개,  태그10 3개
12일 전 : 태그11 100개
일 때 최근 인기 10개니 태그 1이 제외되고 **태그2부터 태그 11까지를 인기 태그**로 하는 것 같아요.

> orderBy의 첫번째 조건이 개수니 사용 개수를 먼저 줄세우고 동일한 개수 내에서 시간을 줄세워 10개만 뽑으니 가장 작은 태그 1이 제외


---

제가 궁금한건 몰리가 의도한게 1번방식이 맞는지, 아니면 제가 잘못 이해한 건지 궁금합니다.

그리고 제가 잘못 이해한 거라면, 해당 api가 개수에 따라 어쩔때는 최근 인기순이고 어쩔 땐 전체 인기순인거는 맞지 않다고 생각합니다.
그래서 만약 개수가 부족하다면 1번 방식으로 가거나, 부족한 대로 전달하는게 맞지 않을까 싶습니다.

2024-12-29 07:33 UTC, zeus6768 reviewed
고생했어요 몰리~~ 코드가 넘 깔끔해요

다만 간단히 논의하고 싶은 내용이 있어요. 

인기 태그를 조회한다는 도메인 용어에서, 인기를 `top`이라고 할지 `popular`라고 할지 명확히 정하면 좋겠다는 생각이 들었어요. 

컨트롤러에서는 top이라고 칭하는데, 서비스와 그 이하 계층에서는 popular라고 칭하니 이해하는데 시간이 조금 더 걸렸거든요. 

몰리의 생각이 궁금해요~!

2024-12-29 07:33 UTC, zeus6768 commented on backend/src/main/java/codezap/tag/controller/TagController.java
> +    public ResponseEntity<FindAllTagsResponse> getTopTags(@RequestParam(defaultValue = "10") int size) {
정책적인 의미를 갖는 값이라고 생각하는데, "10"을 상수로 선언하는 건 어떤가요?? 

`DEFAULT_TOP_TAG_COUNT` 또는 `DEFAULT_POPULAR_TAG_COUNT` 제안해요~~

2024-12-29 07:33 UTC, zeus6768 commented on backend/src/main/java/codezap/tag/service/TagService.java
> +        return tagRepository.findMostUsedTagsByRecentTemplates(size);
와 켬미 진짜 똑똑꼼꼼하네요 따봉 두개 드리고 싶은데 안돼서 코멘트 남깁니다

2024-12-29 07:33 UTC, zeus6768 commented on backend/src/test/java/codezap/global/DatabaseCleaner.java
> +public class DatabaseCleaner implements Ordered, TestExecutionListener {
👍 🔥

2024-12-29 07:33 UTC, zeus6768 commented on backend/src/main/java/codezap/tag/service/TagService.java
> +        List<Tag> tags = tagRepository.findMostUsedTagsWithinDateRange(size, startDate.minusDays(7));
7도 같은 의미에서 상수 어떤가요~!

`DEFAULT_POPULAR_DATE_RANGE` 라는 이름 제안해요~~

2024-12-29 09:21 UTC, HoeSeong123 requested changes
몰리 체거!!!!!👍

2024-12-29 09:21 UTC, HoeSeong123 commented on backend/src/main/java/codezap/tag/controller/TagController.java
> +    public ResponseEntity<FindAllTagsResponse> getTopTags(@RequestParam(defaultValue = "10") int size) {
10개를 requestParam으로 받는 이유가 있나요?
해당 메서드가 10개 말고 다른 숫자로 재사용 될 일이 있는 건가 싶어서요.

2024-12-29 09:21 UTC, HoeSeong123 commented on backend/src/main/java/codezap/tag/service/TagService.java
> +        return tagRepository.findMostUsedTagsByRecentTemplates(size);
역시 꼼꼼켬미👍
orderBy 절에서 count와 createdAt의 순서가 바뀌어야 할 것 같네요

2024-12-30 07:02 UTC, jminkkk commented on backend/src/main/java/codezap/tag/service/TagService.java
> +        return tagRepository.findMostUsedTagsByRecentTemplates(size);
이야 ~~~~~~~~~~ 김켬미 최고에요 👍👍👍

2024-12-30 07:20 UTC, jminkkk commented
@kyum-q DatabaseListener 관련 TestExecutionListenr 충돌

> DatabaseListener 관련 TestExecutionListenr 충돌은 어렵네요..! 좀 더 공부해보겠지만, 

[TestExecutionListenr 간의 충돌 문제에 대해 알아보아요](https://github.com/woowacourse-teams/2024-code-zap/wiki/TestExecutionListenr-%EA%B0%84%EC%9D%98-%EC%B6%A9%EB%8F%8C-%EB%AC%B8%EC%A0%9C%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%95%84%EC%9A%94) 

켬미 발생했던 문제에 대해 더 자세하게 문서화했어요~! 참고하길 바래요 😀

2024-12-30 07:22 UTC, jminkkk commented on backend/src/main/java/codezap/tag/controller/TagController.java
> +    public ResponseEntity<FindAllTagsResponse> getTopTags(@RequestParam(defaultValue = "10") int size) {
현재 인기 태그 관련 디자인이 나오지 않아서, 태그 데이터가 10개보다 더 필요할 수도 있을 것이라고 생각했어요!

처음 논의되었던 개수는 5개였는데, 이미지가 안들어가면 적을 것 같아서 10개로 늘린 것이기도 하구요!

2024-12-30 07:27 UTC, jminkkk commented
> 고생했어요 몰리~~ 코드가 넘 깔끔해요 👍
> 
> 다만 간단히 논의하고 싶은 내용이 있어요.
> 
> 인기 태그를 조회한다는 도메인 용어에서, 인기를 `top`, `popular`, `mostUsed` 중에 명확히 정하면 좋겠다는 생각이 들었어요.
> 
> 컨트롤러에서는 top이라고 칭하는데, 서비스에서는 popular, 레포지토리에서는 mostUsed라고 칭하니 이해하는데 시간이 조금 더 걸렸거든요.
> 
> 몰리의 생각이 궁금해요~!

top, popular는 확실히 통일이 되어야할 것 같네요 😅 고마워요 우스~

레포지토리 레벨에서 mostUsed를 사용한 것은 구현 세부사항을 정확히 반영하기 위함이었어요.
다만 서비스나 컨트롤러에서는 사용자 관점의 비즈니스 용어인 "인기 태그"를 사용함으로써 API를 사용하는 클라이언트 입장에서 기능을 직관적으로 이해할 수 있고, 나중에 인기도 측정 방식이 변경되더라도(예: 좋아요 기준 등) API 이름을 바꿀 필요가 없어요.

인기에 대한 정책이 내부적으로는 mostUsed이지만, 이는 변경될 가능성이 높다고 생각해요. 예를 들면 좋아요 순으로 인기 태그를 정할 수도 있구요. 때문에 컨트롤러에서 mostUsed라는 내부 정책을 알 필요는 없다고 생각했어요!

2024-12-30 08:01 UTC, zeus6768 approved these changes

2024-12-30 08:13 UTC, HoeSeong123 commented on backend/src/main/java/codezap/tag/controller/TagController.java
> +    public ResponseEntity<FindAllTagsResponse> getTopTags(@RequestParam(defaultValue = "10") int size) {
앗 아뇨 제가 하고싶었던 말은 개수를 requestParam으로 받아야 하나 싶어서요.
10개든 5개든 내부적으로 논의만 된다고 하면 서비스나 레포지터리 계층에서 정해진 숫자만큼 가져오면 될 것 같아요. url로 따로 요청받지 않아도요!!
만약 어떤 곳에서는 5개만 가져오고 다른 곳에서는 10개를 가져온다면 requestParam으로 받아서 개수를 조절하는 것이 적절한 것 같지만, 그게 아니라 항상 10개 또는 5개를 가져오는 거라면 컨트롤러 단에서 size를 몰라도 될 것 같아서요!!

2024-12-30 08:17 UTC, jminkkk commented on backend/src/main/java/codezap/tag/controller/TagController.java
> +    public ResponseEntity<FindAllTagsResponse> getTopTags(@RequestParam(defaultValue = "10") int size) {
엇 저의 목적은 결국 뷰에 의해 개수가 변경되더라도 서버 코드는 변경되지 않았으면 해서 였어요!
음 고정 시키는 게 나을까요?

2024-12-30 08:46 UTC, kyum-q commented on backend/src/main/java/codezap/tag/controller/TagController.java
> +    public ResponseEntity<FindAllTagsResponse> getTopTags(@RequestParam(defaultValue = "10") int size) {
저는 외부에서 사이즈를 받는 현재 로직이 좋다고 생각해요~ 숨겨야하는 정보도 아니고, 유동적으로 데이터의 개수를 조절할 수 있으니 더 좋은 것 같아요~

2024-12-30 08:47 UTC, kyum-q approved these changes
몰리 문서 체고애요 완전 이해되버림 당신 천재~

2024-12-30 09:44 UTC, HoeSeong123 commented on backend/src/main/java/codezap/tag/controller/TagController.java
> +    public ResponseEntity<FindAllTagsResponse> getTopTags(@RequestParam(defaultValue = "10") int size) {
확인해보니 템플릿도 외부에서 사이즈를 받아오네요
이대로 가도 될 거 같습니다!

2024-12-30 12:26 UTC, HoeSeong123 approved these changes
문서 확인했습니다!!
문서화 정말 잘하시네요...
최곱니다 몰리👍

2025-01-02 04:13 UTC, merged